* 书中所征书集及作者名目：
  1. 柳如是：东山酬和集、河东君尺牍、湖上草、戊寅草、鸳鸯楼词
  2. 汪汝谦：春星堂集、春星堂诗集（又名《草堂诗》）
  3. 吴伟业：梅村家藏稿、绥寇纪略
  4. 李商隐：李义山诗集
  5. 邓汉仪：天下名家诗观·初集·一二
  6. 王士禛：池北偶谈、衍波词
  7. 钱谦益：牧斋有学集、牧斋初学集·一六·丙舍[^1]诗集、牧斋尺牍、列朝诗集（编选）、投笔集
  8. 靳荣藩：吴诗集览
  9. 黄宗羲：南雷诗历、海外恸哭记、南雷文定后集
  10. 陈子龙：陈忠裕全集（王昶辑）
  11. 王昶：国朝词综、青浦诗传
  12. 宋徵璧：含真堂诗稿
  13. 徐釚：续本事诗
  14. 朱鹤龄：杜诗辑注、李义山诗集笺注、愚庵小集
  15. 归庄：恒轩集
  16. 潘柽章：松陵文献
  17. 程嘉燧：耦耕堂存诗稿、松圆浪淘集
  18. 李雯：仿佛楼诗稿、蓼斋集（门人石维昆辑刊）
  19. 陶弘景：真诰
  20. 钱曾：牧斋诗集注（初学集、有学集）、读书敏求记
  21. 王应奎：海虞诗苑、柳南续笔
  22. 沈雄、江尚质：古今词话
  23. 袁景辂：松陵诗征
  24. 沈虬：河东君传
  25. 葛昌楣：蘼芜纪闻
  26. 仲廷机、仲沈洙、仲周霈、仲虎腾等：盛湖志、盛湖志补
  27. 郑澍若：虞初续志
  28. 周灿：泽畔吟
  29. 谢三宾：一笑堂集、嘉定四君集
  30. 顾苓：河东君传、塔影园集
  31. 王沄：虞山柳枝词、三世苦节传、辋川诗钞
  32. 全祖望：鲒埼亭外集
  33. 杜濬：变雅堂文集
  34. 杨钟羲：雪桥诗话续集
  35. 罗振玉：殷礼在斯堂丛书、贞松老人外集
  36. 范锴：华笑庼杂笔・一 所引 顾苓 之 《河东君传》
  37. 缪荃孙：秦淮广记、云自在龛笔记
  38. 李桓：耆献类征初编
  39. 钱孙爱：河东君殉家难事实
  40. 钱肇鳌：质直谈耳
  41. 陈盟：崇祯内阁行略
  42. 曹溶：崇祯五十宰相传（初稿）
  43. 谈迁：枣林杂俎合集
  44. 钮琇：觚賸
  45. 陶谷：清異錄
  46. 李清：三垣笔记
  47. 陈继儒：陈眉公集、晚香堂小品、年谱（子陈梦莲撰）
  48. 翁同龢：瓶庐诗稿
  49. 徐孚远：钓璜堂集、钓璜堂存稿
  50. 查继佐：国寿录
  51. 钱肃润：南忠记
  52. 邹祗谟：丽农词
  53. 董以宁：蓉渡词
  54. 顾贞观、成德同（仝）：今词初集
  55. 蔡澄（练江）：鸡窗丛话
  56. 施绍莘：花影集
  57. 黎美周、張山來：瑶台片玉
  58. 陈作霖：金陵通传
  59. 葛万里：牧斋先生年谱
  60. 周容：春酒堂诗话、春酒堂文存
  61. 王士禄：宫闱氏籍艺文考略 所引 神释堂诗话
  62. 徐沁：明画录
  63. 俞正燮：癸巳存稿
  64. 徐康：前尘梦影录
  65. 郑方坤：本朝名家诗钞小传
  66. 徐乃昌：小檀栾室汇刻闺秀词
  67. 闵麟嗣：黄山志
  68. 蒋逸雪：张溥年谱
  69. 钱文选：诵芬堂文稿
  70. 徐树敏、钱岳：众香词
  71. 周铭：林下词选
  72. 金鹤翀：钱牧斋先生年谱
  73. 闵尔昌：碑传集补
  74. 宋琬：安雅堂未刻稿
  75. 陈乃乾、陈洙：徐闇公先生年谱
  76. 汤漱玉：玉台画史
  77. 陈子龙、徐孚远、宋徵璧等：皇明经世文编（方岳贡、张国维、张溥、许誉清等序）
  78. 龚鼎孳：定山堂集
  79. 黄道周：黄漳浦集（附 庄起俦 撰 漳浦先生年谱）
  80. 阮阅：诗话总龟后集
  81. 余怀：板桥杂记
  82. 王秀琴：历代名媛书简
  83. 陈文述：西泠闺咏、秣陵集
  84. 沈德潜：西湖志纂
  85. 丁丙、丁申：武林掌故丛编
  86. 周亮工：赖古堂尺牍新钞
  87. 翁方纲：苏诗补注
  88. 冒襄：影梅庵忆语
  89. 邹斯漪（清初）：诗媛十名家集
  90. 邹弢：三借庐笔谈
  91. 杨绍和：楹书隅录初编
  92. 胡震亨：读书目录
  93. 陈维崧：妇人集
  94. 严元照：蕙櫋杂记
  95. 顾张思：寓疁杂咏
  96. 温睿临：南疆逸史
  97. 郏伦逵：虞山画志
  98. 单学傅：海虞诗话
  99. 冯舒：虞山妖乱志
  100. 瞿九思：万历武功录
  101. 张潮：虞初新志
  102. 叶廷琯：徐元叹先生残稿
  103. 许浩基：郑延平年谱（郑成功）
  104. 徐鼒：小腆纪传
  105. 文秉：烈皇小识
  106. 屈大均：皇明四朝成仁录
  107. 梁章钜：浪迹丛谈
  108. 侯方域：壮悔堂文集
  109. 邵长蘅：侯方域魏禧传
  110. 严正矩：芝麓传（龚鼎孳传）
  111. 夏燮：明通鉴
  112. 顾公燮：消夏闲记选存
  113. 陆次云：圆圆传
  114. 张岱：石匮书后集
  115. 龚鼎孳：定山堂诗集
  116. 杨文骢：洵美堂诗集
  117. 李日华：紫桃轩杂缀
  118. 阮葵生：茶余客话
  119. 孙原湘：天真阁集
  120. 董潮：东皋杂钞
  121. 吴应箕：留都见闻录
  122. 徐复祚：花当阁丛谈
  123. 史惇：恸余杂记
  124. 夏完淳：续幸存录
  125. 林时对：荷插丛谈
  126. 徐树丕：识小录
  127. 邓之诚：清诗纪事初编
  128. 蒋良骐：东华录
  129. 査继佐：鲁春秋
  130. 祝纯嘏：孤忠后录
  131. 赵宗建：旧山楼书目
  132. 叶绍袁：启桢记闻录
  133. 计六奇：明季南略
  134. 龚明之：中吴纪闻
  135. 李棪：東林黨籍考
  136. 金堡：遍行堂集
  137. 杭世骏：道古堂集
  138. 痛史：国变难臣钞（佚名）、嘉定县乙酉纪事（朱九初，字子素）、甲申朝事小纪（21）、侯峒曾年谱
  139. 阙名：牧斋遗事（虞山丁氏钞藏）、南翔镇志、嘉定县志、松江府志、嘉善县志、苏州府志、杭州府志
  140. 民国六年：名人笔记汇海·莼乡赘笔
  141. 民国二十一年：钱牧斋先生年谱（金鹤冲【翀】・编）
* 书中涉及的一些诗词
1. 河中之水歌 •萧衍〔南北朝〕
   #+begin_verse
   河中之水向东流，洛阳女儿名莫愁。
   莫愁十三能织绮，十四采桑南陌头。
   十五嫁为卢家妇，十六生儿字阿侯。
   卢家兰室桂为梁，中有郁金苏合香。
   头上金钗十二行，足下丝履五文章。
   珊瑚挂镜烂生光，平头奴子擎履箱。
   人生富贵何所望，恨不嫁与东家王。
   #+end_verse
   河东君之名当来自此诗。
2. 碧城三首（其二）•李商隐
   #+begin_verse
   对影闻声已可怜，玉池荷叶正田田。
   不逢萧史休回首，莫见洪崖又拍肩。
   紫凤放娇衔楚佩，赤鳞狂舞拨湘弦。
   鄂君怅望舟中夜，绣被焚香独自眠。
   #+end_verse
   影怜之名当来自此诗。
* 一些引用书籍的简介
1. *《皇明经世文编》* 所提及之名流：予辈志识固陋，鲜所取衷，幸高贤大良,一时云会，若李宝翁先生、李载翁先生、王依翁先生、吴雪翁先生，（寅恪案：李宝翁即李瑞和。嘉庆修《松江府志·四二名宦传·三·李瑞和传》略云：“李瑞和，字宝弓，漳浦人。崇祯七年进士。授松江推官。在郡七年,征拜监察御史。”王依翁疑为王佐圣。《松江府志·三六·职官表》“明教职”栏载：“崇祯十年。王佐圣。教谕。长洲人。举人。”同治修《苏州府志·八七·人物·一四·明长洲县·王佐圣传》略云：“王佐圣，字克仲。举万历壬子乡试。授青浦教谕。崇祯十四年选遵义知县。并可参《启祯野乘一集·九王遵义（佐圣）传》。又，李宝翁即李宝弓，李载翁即李载阳，王依翁即王依日，吴雪翁即吴雪因。均见原书所列“鉴定名公姓氏”。）皆具良史之才，宦游吾土，士绅咸奉规范。此编出入共禀鉴裁。遭逢之盛，良为侈矣。许霞翁（誉卿）、徐勿斋（汧）、马素修（士奇）、张西铭（溥）、张受先（采）、黄仲霖（澍）、吴志衍（继善）、夏彝仲（允彝）、吴坦公（培昌）、张讱叟（元始）、吴来之（昌时）、朱闻玄（永祐）、宛平金伯玉（铉）、王敬哉(崇简）、崔道母（子忠）、王大含（谷），桐城方密之（以智）、孙克咸（临），莱阳宋澄岚（继澄），侯官陈道掌（元纶）、陈克理（兆相），金沙周介生（钟），丹阳荆实君（廷实），槜李钱孚于（嘉徵）、钱彦林（栴）、钱雍诵（泮）、黄复仲（子锡）、陆芳洲（上澜）、朱子庄（茂曝），归安唐子仪（起凤），虎林严子岸（渡）、张幼青（埁），茂苑杨维斗（廷枢）、许孟宏（元溥）、姚瑞初（宗典）、姚文初(宗昌），玉峰王与游（志庆）,吴江周安期（逢年）、吴日生（易），疁水侯雍瞻（岐曾）、傅令融（凝之），娄东王子彦（瑞国）、吴纯祜（国杰）、张无近（王治），维扬郑超宗（元勋），海虞顾麟士（梦麟），彭城万年少（寿祺），皆系良友素知。琼瑶之赠，遥睇临风。二酉之藏，倾厢倒箧矣。四方兰谱，若杨子常（彝）、杨龙友（文骢），则分教吾土，乐与晨夕。集始于戊寅仲春，成于成寅仲冬，寒暑未周，而披览亿万，审别精详，远近叹咤，以为神速。良由徐子、陈子博览多通，纵横文雅，首用五官，都由一目。选辑之功，十居其七。予质钝才弱，追随逸步，自嗤蹇拙，以二子右萦左拂，奔命不遑，间有选辑，十居其二。若溯厥始事，则周勒卣（立勋）、李舒章（雯）、彭燕又（宾）、何悫人（刚）、徐圣期（风彩）、盛邻汝（翼进）及家伯氏子建（存标）、家季辕文（徵舆），咸共商酌。适李子久滞京邸，周子壮游梁苑，彭子栖迟邗上，何子寄迹鸳水，徐子、盛子则各操月旦，伯氏家季则潜心论述，曾无接谈之暇，未假专日之工。若友人吴绳如（嘉胤），唐允季（允谐），李存我（待问），张子美（安茂），朱早服（积），蔡季直（枞），单质生（恂），郁子衡(汝持），沈临秋（泓），陆子玄（庆曾），朱宗远（灏），董士开（云申），郁选士（继垣），张子服（宽），张子退（密），钱子璧（瑴），李素心（愫），徐惠朗（桓鉴），邵霏玉（梅芬），徐武静（致远），李原涣（是楫），华芳乘（玉芳），咸资讨论。卷首总目则友人谢提月（廷桢）一人所辑。
2. *《林下词选》* 是清代康熙年间吴江文人周铭编纂的女性词作总集，为中国现存首部女性词选专集。全书共十四卷（含补遗一卷），收录宋、元、明、清四朝女性词人作品，选源包括《填词集艳》等未刻秘本，并参考《女史》《花庵词选》等文献。书中保留词人小传、词评及校勘记录，对李清照、朱淑真词作异文进行标注，编者还对不合音律字句作精审标注。该选本采用“以人系词”体例，体现“鄙意为之”的编选特色，其编纂延续明末清初女性文学繁荣背景，对后世选集产生影响。铭字勒山，松江人。是集题曰《林下》，盖取世说所载谢道韫事也。其书采取女子之作，自宋、元、明以及国朝，编次颇为无绪。末卷以《减字木兰花词》，题为南齐苏小小。亦沿田艺蘅之误，而不能正也。
3. *《众香词》* 是由清代**徐树敏**与**钱岳**共同编纂的综合性女性词选，成书于清康熙二十八年至三十年（1689-1691 年）。全书以儒家"六艺"（礼、乐、射、御、书、数）为分集标准，收录明末清初 382 位女性词人的 1493 首作品，涵盖显宦妻女、士族闺秀、歌妓婢妾等不同阶层。其独创的伦理身份编次体系，将编纂者群体扩展至王士禛、曹寅等 46 位文人，形成独特的文献编纂网络。
4. *《龙城录》* 旧题唐代柳宗元谪居柳州时所作，宋代起学者多质疑其伪托，清代四库馆臣从文风与记事年代推断或为宋人仿作。该书属轶事小说集，分二卷四十三则，收录中唐时期帝王官吏、文人士子的奇闻异事，内容糅合历史人物与超现实情节。全书以简练笔法记载朝野传说，如唐明皇梦游广寒宫衍生《霓裳羽衣曲》、赵师雄罗浮山遇梅花仙等故事，借神鬼奇谈隐现现实境遇。部分条目涉及诗文创作，如韩愈之父受托为曹植作序、裴武公焚化鬼诗等，暗含对文字力量的哲思。书中频繁提及韩愈且叙事视角独特，虽文风与柳宗元其他作品差异显著，仍为作者身份争议留下探讨空间。
5. *《真诰》* ，南朝梁陶弘景在茅山（句曲山）隐居期间编，为道教上清派要典， 凡七卷。「真诰」意为「真人口授之诰」，「真人」是道教对神仙人物的尊称，「诰」是上对下的一种诫勉。《真诰》系东晋杨羲、许谧、许翽等人的"通灵"记录。在陶弘景前，顾欢曾加以搜集整理，编成《真迹》一书。陶弘景勤加搜访，并加注解，编之《真诰》。书中内容庞杂，介绍了道教上清派的历史、传记和方术等，对道教其他派别也有所涉及。《真诰》认为「道者混然，是生元气。元气成，然后有太极。太极则天地之父母，道之奥也」。《真诰》重视《抱朴子》的金丹和守一，但认为「若得《大洞真经》者，复不须金丹之道」。《真诰》奉上清法为"上道"，认为高出旧天师道的"太清家"。崇尚诵经、存神、守一、斋戒。书中「上清真人」，"为老君之师"，反映出上清派信仰特徵有异于旧天师道。此书描述佛有如神仙，反映佛教初入中国时人们对佛教的观念。《真诰》也是精彩的文学作品，文字典雅，人物形象生动，描写了许多女仙下凡和凡人恋爱的故事。女仙教导凡夫俗子修炼，同她们一起过神仙生活。《隋书·经籍志》未见著录《真诰》。《三洞珠囊》多引其文。
6. *《盛泽志》* ：盛泽有修志的传统。明末清初，盛泽的诗书簪缨之家仲氏开始致力于《盛湖志》的编纂。**仲沈洙**是盛泽的鸿儒，他步卜梦熊后尘，着手修志，“以所见为经，所闻为纬，凡里中耆老备历咨询，务得其真。”（乾隆《盛湖志·序》）终于在清顺治十年（1653 年）脱稿，但因财力不足，未能刊行。至康熙年间，仲沈洙之孙**仲栻**、**仲枢**受父之命对《盛湖志》予以增纂。仲氏昆仲都是饱学之士，博闻多识，诗文俱佳。至乾隆中，仲枢的胞侄**仲周霈**又增补了内容，并于乾隆三十五年（1770 年）将《盛湖志》（2卷）刻本行世。这本经历了仲氏 4 代人、100 余年努力的第一本盛泽地方志，为后世保存了许多珍贵的历史资料。又过了 100 年，到了同治年间（1862—1874 年）。仲周霈的玄孙**仲廷机**在祖辈所著的旧志基础上，广泛收集资料，并参考府志、县志及其它史料，编纂成内容更为详实、体例更为完备的新《盛湖志》。同治末年廷机亡故后，他的儿子**仲虎腾**又广泛采集光绪年间的掌故，续成了 4 卷，名为《盛湖志补》，使历史记述延伸至光绪二十六年（1900 年）。但是虎腾未及校录就谢世了，于是接力棒又交到其子**仲冠雄**手中。冠雄将《盛湖志补》重加校录后，竭力张罗刻印出版其祖、父两代以毕生心血著成的《盛湖志》。然而事出意外，志书付印前夕，杭州琵琶巷书铺因火灾波及，雕镂书版全部被焚，后幸得旧嘉兴县参议陶葆廉、南浔书商周庆云资助，于 1920 年依据仅存的底稿重新雕版，至 1924 年正式刊出。仲廷机所纂《盛湖志》为 14 卷本，加卷首、卷末各 1 卷，共 16 卷，又附仲虎腾编纂的《盛湖志补》4 卷，形成 20 卷 8 册版本的方志。仲氏家族自清初仲沈洙撰志稿起，到仲冠雄努力完成最后出版工作，前后达 280 年。期间，经仲氏七代人的持续不懈，勉力笔耕，修成《盛湖志》3 种，对桑梓贡献甚巨，其道义责任、韧性毅力令后人钦敬。难怪秀水陶葆廉称颂说“盛泽二百余年来，修志者皆出仲氏”。
7. *《历代名媛书简》* 是王秀琴编纂的一部历代女性书信总集，由商务印书馆于 1941 年出版。该书是清末民初女性尺牍总集编撰潮流中的一部。书中收录了包括女性寄给外人的书信在内的作品。其中关涉为母者“课子诲女”的家训书信，展现了清代知识家庭母亲理性严苛而又温情慈爱、固守传统而又灵活变通的多面形象。该书所录文献虽部分真伪有待考辨，但具有独特的史料价值。
8. *《武林掌故丛编》* 是清代藏书家丁丙与其兄丁申在保护文澜阁《四库全书》后主持编纂的大型地方文献丛书。全书共收录 622 卷古籍文献，涵盖吴越至明清时期杭州地区的方志、笔记、诗文等官私典籍，采用影印方式保留古籍原貌，其编纂沿袭胡凤丹《金华丛书》传统，收录晚清所藏孤本、善本 [。该丛书已知最早版本为 1967 年超星电子图书出版的 26 卷本，丛书于清光绪九年（1883）由钱塘丁氏嘉惠堂刊刻，共 26 集 208 册 ，后世有广陵书社 2008 年精装全集版和杭州文献集成系列影印版等版本。其编纂体例按专题分类，收录的《西湖月观纪》《文澜阁志》等文献，被广泛用作《梦粱录》等古籍校勘的参考底本，并曾纠正《知不足斋丛书》本的多处讹误 。孙峻曾帮助丁丙编撰此书 ，直到 21 世纪，《杭州文献集成》、《西湖文献集成》等丛书仍以其为底本 。
9. *《天禄琳琅书目》* 为清代官修善本目录，乾隆九年（1744 年）设于乾清宫昭仁殿，乾隆四十年（1775 年）于敏中等纂前编 10 卷著录 429 部，嘉庆二年（1797 年）彭元瑞续编后编 20 卷收 664 部，合计宋元明善本 1093 部。书目按版本年代分类，详录序跋及藏书印，采用锦函、褐绨分级装帧，钤印“乾隆御览之宝”“天禄琳琅”等皇家玺印。嘉庆二年乾清宫火灾致前编书焚毁。现存后编书 604 部，主要藏于台北故宫博物院（321 部）、国家图书馆（279 部）及辽宁省图书馆（35 部）。国家图书馆 2013 年启动修复项目，历时 8 年修复 279 部 300 余册，含元大德本《汉书》、明成化本《资治通鉴纲目》等孤本。
10. *《孤忠后录》* 是由明末清初祝纯嘏撰写的中国史类著作。该书主要记述清顺治三年（1645）江阴贡生黄毓祺孤身起兵抗清，被捕后死于南京狱中的历史事件。 书中披露黄毓祺起兵事件涉及多方关联，如钱谦益曾派遣柳如是至海上犒师等细节。该书基于民国时期标点整理版本呈现记述内容，为研究清初政治史提供了相关事件的第一手史料。
* 一些常识
1. *建州女真* ，明代女真族三大部之一，明代女真分为建州、海西、野人三部。建州女真主要分布于今牡丹江、绥芬河及长白山一带。
2. *尹邢避面* ，《史记·外戚世家》：“尹夫人与邢夫人同时并幸，有诏不得相见。尹夫人自请武帝，愿望见邢夫人，帝许之。即令他夫人饰，从御者数十人，为邢夫人来前。尹夫人前见之，曰：‘此非邢夫人身也。'帝曰：“何以言之？'对曰：‘视其身貌形状，不足以当人主矣。'于是帝乃诏使邢夫人衣故衣，独身来前。尹夫人望见之，曰：‘此真是也。'于是乃低头俛而泣，自痛其不如也。谚曰：‘美女入室，恶女之仇。'”指因嫉妒而互相回避。
3. *御李* ：东汉李膺有贤名，士大夫被他接见的，身价大大提高，被称作登龙门。荀爽去拜访他，并为他驾御车马，回家后对人说：“今日乃得御李君矣！”见《后汉书·李膺传》。后因以“御李”谓得以亲近贤者。
4. *玄素* ：玄女和素女。传说她们以房中术授黄帝。见《云笈七签》卷一百《轩辕本纪》。晋葛洪《抱朴子·微旨》：“知玄素之术者，则曰唯房中之术，可以度世矣。”《云笈七签》卷九九：“不才吴子，知命任真，志尚玄素，心乐清贫。”
5. *枚卜* ：一一占卜。古代以占卜法选官，因以指选用官员。《书·大禹谟》：“枚卜功臣，惟吉之从。”孔传：“枚谓历卜之而从其吉。”明代专指选大臣为大学士，入内阁主事。《明史·杨涟传》：“国家最重无如枚卜。忠贤一手握定……岂真欲门生宰相乎？”
6. *涂月* ：农历十二月的别称。《尔雅·释天》：“十二月爲涂。”俞樾《群经平议·尔雅二》：“十一月爲辜，十二月爲涂。辜之言故，涂之言除也。一歲至此將除去故舊而更新矣，是以十一月謂之故，十二月謂之除也。”
7. *阳月* ：农历十月的别称。汉董仲舒《雨雹对》：“十月，陰雖用事，而陰不孤立。此月純陰，疑於無陽，故謂之陽月。”
8. *三眠* ：指柽柳(即人柳)的柔弱枝条在风中时时伏倒。《三辅故事》：“漢苑中有柳狀如人形，號曰人柳，一日三眠三起。”故柽柳又称三眠柳。
9. *羽陵蠹* ：古地名。《穆天子传》卷五：“仲秋甲戌，天子東游，次于雀梁，□蠧書于羽陵。”郭璞注：“謂暴書中蠹蟲，因云蠹書也。”后以“羽陵”为贮藏古代秘籍之处。南朝陈徐陵《〈玉台新咏〉序》：“辟惡生香，聊防羽陵之蠹。”隋江总《皇太子太学讲碑》：“紫臺秘典，緑帙奇文，羽陵蠹迹，嵩山落簡；外史所掌，廣内所司，靡不飾以鉛槧，彫以緗素。”宋文莹《玉壶清话》卷三：“上曰：‘蟫有何義？’奏曰：‘臣聞出羽陵蠹書，曰白魚蟲也。’”
10. *诺皋* ：唐段成式《酉阳杂俎》有篇名《诺皋》、《支诺皋》，专记怪力乱神之事。后借指神怪小说。清钱谦益《赵灵均墓志铭》：“﹝靈均﹞閒託于《虞初》、《諾臯》以耗磨光景，陶陶款款如也。”
11. *条脱* ：古代臂饰。呈螺旋形，上下两头左右可活动，以便紧松。一副两个。南朝梁陶弘景《真诰·运象·绿萼华诗》：“贈詩一篇並致火澣布手巾一枚、金玉條脱各一枚。條脱似指環而大，異常精好。”唐李商隐《李夫人歌》：“蠻丝繫條脱，妍眼和香屑。”
12. *薛灵芸* ，东晋王嘉志怪小说《拾遗记》中的虚构人物，魏文帝曹丕的宫人，别名 *薛夜来* 。因精于刺绣技艺，被宫中称为针神，其缝制衣物皆为文帝专属。 薛灵芸出身常山郡贫寒之家，十七岁被郡守谷习选献入宫，离别父母时以玉唾壶盛泪凝成血红色，形成‘红泪’典故。魏文帝以华贵车驾相迎，赐名‘夜来’。外国曾进献火珠龙鸾钗， 文帝怜惜其弱不禁风而未让其佩戴 。其缝纫时无需灯火的特技确立‘ *针神* ’称号，因面触水晶屏风形成‘晓霞妆’，与莫琼树等并称魏宫四美。曹丕临终前遗命遣散后宫，薛灵芸得以返回故乡。 后世文学作品中‘红泪’意象多源于此典故，清代《红楼真梦》曾将其与林黛玉类比。清代诗歌中亦有对薛灵芸的吟咏，其‘晓霞妆’在现代美妆文章中仍被提及。 其形象通过《拾遗记》等古籍传播，成为古代著名美人典型。
13. *割臂盟公* ： 原指春秋战国时鲁庄公与孟任割破胳臂，订下婚约。后泛指用割破手臂立誓宁约（指男女秘订婚约）。《左传·庄公三十二年》：“初，公筑台，临党氏，见孟任，从之。閟。而以夫人言，许之，割臂盟公。生子般焉。”
14. *便给* ：灵巧敏捷。《续资治通鉴·元顺帝至正二十六年》：“夫质朴者多迂缓，狡猾者多便给。便给者虽善办事，或伤于急促，不能无损于民。”《明史·魏允贞传》：“每遇科道员缺，率择才性便给、工谄媚、善逢迎者授之。”
15. *屈戍* 即 *屈戌* ：门窗、屏风、橱柜等的环纽、搭扣。唐李商隐《骄儿》诗：“凝走弄香奩，拔脱金屈戌。”戌，一本作“戍”。 明陶宗仪《辍耕录·屈戌》：“今人家窗户設鉸具，或鐵或銅，名曰環紐，即古金鋪之遺意，北方謂之屈戌，其稱甚古。”
16. *狐埋狐搰* ： 搰：挖掘。狐性多疑，刚把东西埋下，又把挖出来看看。比喻疑虑过多，不能成事。出处《国语·吴语》：“狐埋之，而狐搰之，是以无成功。”
17. *俞跗* 即 *俞跗* ：汉刘向《说苑·辨物》：“俞柎之爲毉也，搦腦髓，束盲莫，炊灼九竅而定經絡，死人復爲生。”俞跗，传说为黄帝时良医。 《鹖冠子·世贤》：“卓襄王問龐煖曰：‘夫君人者亦爲其國乎？’龐煖曰：‘王獨不聞俞跗之爲醫乎？已成必治，鬼神避之。’”
18. *牙签* ：系在书卷上作为标识，以便翻检的牙骨等制成的签牌。唐韩愈《送诸葛觉往随州读书》诗：“邺侯家多书，插架三万轴；一一悬牙签，新若手未触。”宋苏轼《书轩》诗：“雨昏石砚寒云色，风动牙签乱叶声。” 亦指书籍。宋陆游《冬夜读书示子聿》诗：“绝胜锁向朱门里，整整牙签饱蠹鱼。”
19. *玉检* ：玉牒书的封箧。《汉书·武帝纪》“登封泰山”颜师古注引三国魏孟康曰：“玉者功成治定，告成功于天……刻石纪号，有金策石函，金泥玉检之封焉。” 唐李商隐《赠华阳宋真人兼寄清都刘先生》诗：“玉检赐书迷凤篆，金华归驾冷龙鳞。”《说文·木部》“检，书署也”清段玉裁注：“玉牒检者，玉牒之玉函也，所谓玉检也。”桂馥义证：“《六书故》：检状如封匧。” 亦借指玉牒文。唐刘禹锡《平齐行》之二：“侍臣燕公秉文笔，玉检告天无愧词。”
20. *橐饘* ：亦作“槖饘”。指衣食。《左传·僖公二十八年》：“﹝晉﹞執衛侯，歸之于京師，寘諸深室。甯子職納橐饘焉。” 杜预注：“甯俞以君在幽隘，故親以衣食爲己職。橐，衣囊；饘，糜也。”
21. *致仕* ：辞去官职。《公羊传·宣公元年》：“退而致仕。”何休注：“致仕，還禄位於君。”《北史·韦孝宽传》：“孝寬每以年迫懸車，屢請致仕。” 致仕的条件，主要是年老或有病。始于周代，有大夫七十致仕的规定。汉代官吏致仕后，有经济上、政治上的待遇，其高低视皇帝恩宠程度而定。宋代规定，凡文武朝官、内职，因年老求退休者，享有增秩或加恩其子孙的优惠待遇。
22. *设帨* ：古礼，女子出生，挂佩巾于房门右。《礼记·内则》：“子生，男子设弧于门左，女子设帨于门右。”郑玄注：“帨，事人之佩巾也。”帨，《广韵》舒芮切。后用以指女子生辰。明李开先《哭幼女招弟》诗：“设帨旧居秋草满，埋香新冢暮云横。”
23. *词林* ：翰林院的别称。明洪武时建翰林院，额曰“词林”，故名。
24. *牛腰* ：牛的腰部。喻诗文数量之大。唐李白《醉后赠王历阳》诗：“书秃千兔笔，诗裁两牛腰。”王琦注：“言其卷大如牛腰也。”
* 一些政治事件
1. *黄毓祺案* ：顺治五年（永历二年，1648 年），钱谦益再次因反清被逮入监狱。起因是该年四月，清朝凤阳巡抚陈之龙在通州擒获了反清志士黄毓祺，搜出了黄的总督官印以及一些“悖逆诗词”，并上奏称钱谦益曾留宿并资助黄毓祺。 五月，钱谦益被清廷两江总督马国柱逮往南京，但人身相对自由。后来马国柱以“谦益、毓祺素非相识”将此案了结。钱谦益直到次年（顺治六年，永历二年，1649 年）春天以后方得以离开南京。这一次引发了江南遗民的极大同情，纷纷前来慰问，并与 /林古度/ 、 /盛集陶/ 、 /顾梦游/ 、 /濮仲谦/ 、 /金渐皋/ 、 /冯文昌/ 等名士交游唱和，当时“名纸填门，诗卷堆案，长干传为盛事”。就此钱谦益被江南的遗民文化圈所接纳，并完成了入清之后的心态转换——从出儒入佛、誓断笔墨到反清复明、投笔报国。钱谦益感慨说，从这时开始，自己才敢公开地以遗民、义士自居。
2. *大悲案* 是南明的一起政治案件，南渡三案之一（又称为南都三案，是指南明弘光政权年间的三大案件，林时对称之为《南都三大疑案》。这三件大案都与“皇族身份的辨别”有关，背后与“明末党争”有极大的关联。而弘光帝处理得极差，导致失去民心，瓦解了时人对南明的向心力。）。比丘释大悲，俗家姓朱，徽州人，跟潞王朱常淓相识。1644 年 12 月大悲来到南京水西门外，自称是明朝亲王，崇祯时封为齐王，又改封定王。他声称“潞王恩施百姓，人人服之，该与他作正位”。弘光帝原本对潞王有所猜忌，怀疑大悲是来为潞王刺探情报，便将他投入监狱，又传谕戍政赵之龙、锦衣掌堂冯可宗与蔡忠“三堂会审”，严加刑讯，大悲在供词中提到钱谦益，于是阮大铖开了一份黑名单，共有一百四十三人，牵涉有史可法、高弘图、姜曰广、张慎言、刘宗周、祁彪佳等东林党和复社的成员，要大悲招供，大悲抵死不从。马士英亦不愿牵涉过广，遂将大悲绑赴西市问斩，此事不了了之。
3. *童妃案* 是南明时期的政治案件，是南渡三案之一。1645 年（弘光元年）初，一位童氏女子逃至南京，自称为福王朱由崧之元配正妃，越其杰和广昌伯刘良佐深信不疑，一面奏报，一面派人护送来南京。朱由崧立即否认，宣布童氏为假冒。三月初一日，童氏送抵南京，朱由崧拒不召见，交付锦衣卫监候，令都督冯可宗审讯。童氏自述“年三十六岁。十七岁入宫，册封为曹内监。时有东宫黄氏，西宫李氏。李生子玉哥，寇乱不知所在。氏于崇祯十四年生一子，曰金哥，啮臂为记，今在宁家庄”。朱由崧则怒斥曰：“朕元妃黄氏，先帝时册封，不幸早世；继妃李氏，又死于难。朕即位之初，即追封后号，诏示海内，卿为大臣，岂不知之？童氏冒诈朕妃，朕初为郡王，何东西二宫之有？且称是邵陵王宫人，尚未悉真伪？”冯可宗因此被撤，改由屈尚忠审理，对童氏严刑拷打，不久童氏死于狱中，哗然一时。朱由崧的辩白是符合实际情况的，按明朝典制，亲郡王立妃由朝廷派员行册封礼，并无东西二宫。《明熹宗实录》载，天启二年十月传制遣“工科给事中魏大中、行人司行人李昌龄封福府德昌王由崧并妃黄氏”。有推测童氏可能是一周王府或邵陵王的宫女，崇祯十四年（1641 年）洛阳被李自成军攻破时逃到尉氏县，与福王同居过并怀孕生子，福王南下后失散。但就案件本身而言，无论童氏是诈骗，是误会，还是战乱之中与朱由崧有过一夜情后想要当上皇后，有一点可以肯定，她只有可能是外妇，绝不是朱由崧的王妃，且此案也不应成为政局的焦点。童妃案一如大悲案、南都太子案，背后有政治角力的介入，可能是马士英与复社之间的权力斗争，一般以为复社名士皆骨鲠正直之人，其实不然，热衷名利的人也混迹其间，成为一复杂的团体，处处充满门户之见。
4. *南都太子案* ，又称崇祯太子案，是南明弘光元年（清顺治二年，1645 年）的在南都金陵发生的一宗案件，为南渡三案之一。弘光元年二月，鸿胪寺少卿高梦箕秘奏：崇祯帝太子朱慈烺出现在浙江。三月初一，弘光帝朱由崧令太监李继周往浙江一探究竟，并将他带回安置在太平门内的兴善寺。朱由崧又派二名太监辨识，二名公公见到太子，抱头恸哭，解下衣衫为储君御寒，随即如实飞报弘光帝。朱由崧大怒：“真假未辩，何得便尔”，将二名太监灭口，又杀李继周。原总督京营太监卢九德也来探视，觉得太子是假，前太子讲官王铎则一口咬定太子是假。此时文武百官纷纷赶赴兴善寺，“踊跃趋谒”。弘光元年三月二日，弘光帝正式举行对质，以辨别太子真伪。太子讲官刘正宗与这位自称太子者互相进行了多次问答，结果太子在讲学的细节上一无所知。甚至还对刘正宗发怒，声称：“你要说假的便是假的好了。”马士英也举出了此人身份的多处疑点：在性格上，真太子比较忠厚，而自称太子者则机变百出；崇祯帝之女寄养于周奎家且尚健在，但自称太子者则称她死去；种种迹象都不能使人信服。最后在马士英的建议下找来另一名讲官方拱乾来辨认太子。三月九日，方拱乾面见太子后当即斥责太子为伪装。但之后太子向他问安时，却又退到人群之中，掩面不答。朱由崧只得将太子交付锦衣卫冯可宗处看管。太子遭收狱，掀起轩然大波，“南京士民”皆“哗然不平”。江防督抚袁继咸、宁南伯左良玉、广昌伯刘良佐等大臣上疏抗争。左良玉甚至起兵东下，声称“清君侧”，但左不久病逝。据《明史》、《罪惟录》所载，认定这位太子是伪装的。阉党杨维垣声称此人乃状貌酷似太子的高阳人王之明，王之明是驸马王昺之侄孙，故也了解一些宫廷之事。弘光灭亡后，南京百姓将这位太子从监狱中释放出来，并抓住之前认定太子是伪装的王铎，王铎解释说否定太子是马士英的意思，他只是按意思办事罢了。而多铎进入南京后也对这位太子十分尊重。最终这位疑似太子者与弘光帝一起在北京被处决。
5. *函可案* ，发生于顺治四年（1647 年）的清朝第一起文字狱。顺治四年（1647 年）丁亥四月，一位法号函可的和尚，原是明朝礼部尚书韩日缵的长子，因藏有“逆书”《再变记》而遭到满洲大将巴山、张大猷等逮捕，被擒送军前，函可身上有洪承畴的印牌，牵涉到洪承畴，“拷掠至数百，绝而复苏者屡，但曰某一人自为，夹木再折，血淋没趾无二语，观者皆惊顾咋指，叹为有道。”。顺治五年（1648 年），多尔衮考虑到稳定江南局势，不想再生事端，对函可从轻发落，流放到沈阳。
* 年份对比
** 崇祯朝
|------------+------+--------|
| 崇祯元年   | 1628 | **戊辰** |
| 崇祯二年   | 1629 | **己巳** |
| 崇祯三年   | 1630 | **庚午** |
| 崇祯四年   | 1631 | **辛未** |
| 崇祯五年   | 1632 | **壬申** |
| 崇祯六年   | 1633 | **癸酉** |
| 崇祯七年   | 1634 | **甲戌** |
| 崇祯八年   | 1635 | **乙亥** |
| 崇祯九年   | 1636 | **丙子** |
| 崇祯十年   | 1637 | **丁丑** |
| 崇祯十一年 | 1638 | **戊寅** |
| 崇祯十二年 | 1639 | **己卯** |
| 崇祯十三年 | 1640 | **庚辰** |
| 崇祯十四年 | 1641 | **辛巳** |
| 崇祯十五年 | 1642 | **壬午** |
| 崇祯十六年 | 1643 | **癸未** |
| 崇祯十七年 | 1644 | **甲申** |
|------------+------+--------|
** 顺治朝
|------------+------+--------+------------------------------------------|
| 顺治元年   | 1644 | **甲申** | *南明*                                     |
| 顺治二年   | 1645 | **乙酉** | 安宗朱由崧【福王政权】（弘光、隆武元年） |
| 顺治三年   | 1646 | **丙戌** | 绍宗朱聿键【唐王政权】（隆武二年）       |
| 顺治四年   | 1647 | **丁亥** | 文宗朱聿𨮁（绍武、永历元年）             |
| 顺治五年   | 1648 | **戊子** | 昭宗朱由榔【桂王政权】（永历二年）       |
| 顺治六年   | 1649 | **己丑** |                                          |
| 顺治七年   | 1650 | **庚寅** |                                          |
| 顺治八年   | 1651 | **辛卯** |                                          |
| 顺治九年   | 1652 | **壬辰** |                                          |
| 顺治十年   | 1653 | **癸巳** |                                          |
| 顺治十一年 | 1654 | **甲午** |                                          |
| 顺治十二年 | 1655 | **乙未** |                                          |
| 顺治十三年 | 1656 | **丙申** |                                          |
| 顺治十四年 | 1657 | **丁酉** |                                          |
| 顺治十五年 | 1658 | **戊戌** |                                          |
| 顺治十六年 | 1659 | **己亥** |                                          |
| 顺治十七年 | 1660 | **庚子** |                                          |
| 顺治十八年 | 1661 | **辛丑** |                                          |
| 顺治十八年 | 1662 | **壬寅** | 永历十六年（南明灭、台郑续用）           |
|------------+------+--------+------------------------------------------|
** 康熙朝
|----------+------+--------+--------|
| 康熙元年 | 1662 | **壬寅** |        |
| 康熙二年 | 1663 | **癸卯** |        |
| 康熙三年 | 1664 | **甲辰** | 牧斋卒 |
| 康熙四年 | 1665 | **乙巳** |        |
| 康熙五年 | 1666 | **丙午** |        |
| 康熙六年 | 1667 | **丁未** |        |
| 康熙七年 | 1668 | **戊申** |        |
| 康熙八年 | 1669 | **己酉** |        |
| 康熙九年 | 1670 | **庚戌** |        |
| 康熙十年 | 1671 | **辛亥** |        |
|----------+------+--------+--------|
* 人物简介
** 暂无详细资料者
1. 李孟芳：毛晋之舅氏。与牧斋关系密切。
2. 柴紫芳（清？），有《庐峰旅记》。
3. 孙永祚，字子长，尝为牧斋之《东山酬和集》作《东山酬和赋》，载于集前，见之于同治修《苏州府志・一百》
4. 沈璜，字璧甫，事迹见之于《列朝事迹・丁・一三・下・小传》，尝为牧斋志《东山酬和集》作序。
5. 祝纯嘏，字芸堂。
6. 徐季白，牧斋有《题徐季白诗卷后》一文。
7. 陳璧，字昆良、崑良，号雪峰道人。生于明萬曆三十三年(1605)，崇祯末年尝三上书论事，不报，归隐。
8. 佟怀东，佟佳氏族人，牧斋友。
** 女
1. *徐佛* ，原名寿羽，字云翾，小字阿佛。明代歌姬，能琴，工诗，善画兰，声名极著。嘉兴人，后迁居盛泽。幼时随母迁居盛泽归家院。徐佛为归家院院主，心地善良，多才多艺，操琴写诗，善画兰花。名妓徐佛能琴，工诗，善画兰，声名极著。柳如是尝拜她为师。她收养并悉心调教柳如是，使其粗通文墨，才艺大长，很快在归家院挂头牌。崇祯八年秋，柳如是曾别陈子龙于松江，重返盛泽镇徐佛家。四方名流扁舟过访，无不倡酬。徐佛后来独立门户。徐佛常与当湖、武原诸人游，但她心厌秾华。曾有一士跟她有约，竟未果，她因而作《怨诗》五首。其一云：“锦簟孤栖灯炧青，董笼斜倚漏三更。西风欲破人愁寂，吹入芭蕉作雨声。”此诗最为选家所赏。徐佛后嫁**周金甫**（周灿之弟），周金甫爱她妩媚，称呼她为欢喜佛。周金甫死后，她削发入空门。在斜桥之北，旧名北书房，绮疏曲栏，歌姬并集，徐佛与梁道钊、张轻云、宋如姬等歌姬都是以翰墨闻名。道钊淹通典籍，墨妙二王。轻云诗词笔札，并擅其长。如姬聪慧，姿色冠于一时。每当花晨月夕，诸姬鼓琴吹箫,吟诗作字以为乐。又皆殉节御侮，不负所主，奇女子也。
2. *柳如是* （1618 年—1664 年），本名杨爱，或做杨影怜，后改名柳隐，字如是。浙江嘉兴人，明末歌妓。因读宋朝辛弃疾《贺新郎》中：“我见青山多妩媚，料青山见我应如是”，故自号“如是”；又称“河东君”、“蘼芜君”，书画双绝，才气过人，为“秦淮八艳”之首。柳如是生于明朝万历四十六年（1618 年），被辗转贩卖，真实姓氏也无从得知。幼年时，为江南名伎徐佛收养。柳如是并不迷醉其中。沈虬《河东君传》说她：“知书善诗律，分题步韵，倾刻立就；使事谐对，老宿不如。”柳如是与李待问、宋征舆、陈子龙等都发展过一段恋情，但迫于礼教所阻。尤其是与陈子龙的一段情愫，双方情切意笃，长居松江南楼，赋诗作对，互相唱和。可惜南楼唱和的美景不长，陈子龙原配张氏带人闹上南楼。柳如是不甘受辱，悲切而毅然地离去。虽然如此，陈子龙对于柳如是仍不死心，根据陈寅恪先生的推证，陈子龙后来还是为柳如是的流闻心碎三次。
3. *王微* （1600 年－1647 年），字修微，号草衣道人，明末扬州人，歌妓、诗人。早年因丧父流落风尘，以诗文才情闻名江南，与**柳如是**、**李因**并称明末女性文艺三大家，并与李宜之、钱谦益、黄宗羲等文人交游，获誉“美人学士”。七岁沦落为歌妓后，常携书参与江南文人雅集，结交汪然明、董其昌等名士。1620 年前后游历江楚山川，登武当天柱峰，访陈继儒、施子野等隐士。1623 年首嫁抗清名士茅元仪，后因情感变故离开，转嫁东林党人许誉卿，1644 年正式成婚。明末战乱中助夫抗清，临终前劝许誉卿剃发避祸，后许氏遂出家为僧。著有《樾馆诗集》《远游草》《期山草》《名山记》等，诗风清丽，融竟陵派特色，钱谦益赞其“清文丽句，秀出西泠”。
   1) /许誉卿/ ，生卒年不详，字公实，号霞城，南直隶松江府华亭县（今上海市松江区）人，明朝末年官员。 万历四十四年（1616 年）进士，授金华推官。天启三年（1623 年），召为吏部给事中，抗疏极论魏忠贤大逆不道，又上疏营救赵南星、高攀龙等名臣，削秩归。崇祯年间，起官复任，主张罢免阉党余孽房壮丽、安伸、杨维垣等人，不久被薛国观冠以“东林党结党乱政”的罪名致仕。崇祯七年（1634 年），起任故官，历任工科都给事中。崇祯八年（1635 年），弹劾阁臣温体仁、王应熊等人玩忽职守，后因为谢升所污蔑，被勒令致仕。福王立，起用许誉卿为光禄卿，没有赴任。 明亡后，许誉卿剃发为僧，很久以后才去世。
4. *杨宛* ：（？—1644），字宛叔，一作宛若，明末金陵（今南京）歌妓。工诗词、娴南曲，兼善书画，尤以草书见称，著有《钟山献》四卷及《续集》《再续》各一卷，为晚明唯一留下词集（《石民诔词》）的妓女词人。万历四十年（1612 年）入茅元仪家为妾，与王微情同姐妹，后因茅氏厚待杨宛致王微出走。崇祯年间茅元仪去世后随田弘遇赴京，甲申之变时携田氏女南逃至金陵，藏匿山村期间因护田女抗拒盗贼遇害。其草书得董其昌赞誉，《静志居诗话》评其书法“瘦硬见资媚”，《玉台画史》称其绘兰石“清妍饶韵”。
   1) /茅元仪/ （1594 年－1640 年），字止生，号石民，又署东海波臣、梦阁主人、半石址山公，浙江归安（今浙江省湖州市）人。明末时期官员、文学家。茅坤之孙，茅国缙之子。茅元仪家学深厚，喜读史书，雄杰异常，少时有仗义疏财、匡济黎民之志。又喜谈兵，熟知军务。于万历四十七年（1619 年）辑成《武备志》，天启元年（1621 年）刻竣。此后充任军中赞画，随大学士孙承宗督师辽东，以军功荐为翰林院待诏。孙承宗因受魏忠贤排挤解职，茅元仪遂遭牵连被削籍。崇祯元年（1628 年），茅元仪向新帝朱由检进呈《武备志》，并进言兵事，未被起用。翌年，后金军逼近京师，孙承宗再次督师御敌，茅元仪被任为副总兵，署大将军印，督理觉华岛水师，不久被解职。后因辽东兵哗变牵连，充军福建。其壮心不已，请兵勤王，仍遭阻止。悲愤之下，纵酒而卒，年仅四十七岁。茅元仪交游广阔，引竟陵派钟惺、谭元春等为同道，文武兼长，著述宏富。历时 15 年辑成的《武备志》，为中国古代一部字数最多的百科全书式综合性兵书，对后世影响较为深远。此外，诗文、杂记亦有大量存世。有《平巢事迹考》《西峰淡话》《西玄青鸟记》《暇老斋杂记》《青油史漫》《三戌丛谭》《嘉靖大政类编》等 60 余种。中年自编《石民四十集》《石民未出集》。
5. *黄媛介* （1620 年或 1621 年－1669 年），字皆令，浙江秀水（今嘉兴市）人，明代女诗人、画家。出身儒士家庭，姊 *黄媛贞* 为 /朱茂时/ 妾，与夫 /杨世功/ 困于明清易代战乱，鬻书画、设闺塾为生，辗转江南，与吴伟业、钱谦益、柳如是等交游，现存《南华馆古文诗集》《离隐词》残篇，楷书扇面藏于天渡楼。
   1) *黄媛贞* （1606—1675），字皆德，浙江秀水（今嘉兴）人，明代女诗人黄媛介之姐，姊妹均有才名。黄鼎妹，贵阳知府朱茂时侧室。著有《云卧斋诗稿》《黄皆德诗草》，其诗被朱彝尊评为"冰雪净聪明" [ 。黄媛贞早年嫁 /朱茂时/ 为妾，崇祯十三年（1640）随夫赴贵阳知府任所，后定居嘉兴放鹤洲别业。现存诗作涵盖 1627 至 1667 年间创作，包含《贵阳廨中》《秋窗阅史》《题美人图》等篇目，内容多咏物、节令及亲友唱和。诗作《留别徐娘》《寄赠吴中赵夫人二首》记录其闺阁诗友交往，部分作品入选《名媛诗纬初编》  。浙江图书馆藏清抄本《云卧斋诗稿》为海内外孤本，2018 年《黄媛贞黄媛介合集》首次系统整理其诗文，附录朱茂时《琐记》及家族谱牒资料。
   2) /朱茂时/ (明)，字子葵，号葵石。秀水 (今嘉兴)人。为工部治河于张秋，擢知贵阳。战擒叛酋，年 89 卒。
6. *林雪* ：明末清初时期的歌伎、著名的名妓画家，字天素，福建建宁人，生卒年不详。董其昌、陈继儒、李流芳、曹学佺、陈文述等人对她颇为青睐。她曾在杭州生活过一段时间，交游皆名人高士，后来还乡。 林天素因在家乡受到豪绅的迫害而离开福建，先流浪到苏州，后来辗转到了杭州。林天素旅居西湖时，经济拮据，曾假冒陈继儒之名作画售卖，被陈继儒识破后，陈继儒在其画上签名，两人由此结缘。  林天素后离开福建，先到苏州玄墓，后来到了杭州西溪，依附汪汝谦，寄住在西溪的“随喜庵”。汪汝谦极爱林天素，汪氏《梦草》、《闽游诗纪》几乎围绕林天素而作；在《武夷游记》中，更见林天素的情意浓浓。林天素与杨云友是好友，杨云友死后，离开杭州。杨云友死后，林天素感到孤寂无伴，后又因社会上的豪强所迫，无奈地离开了杭州。万历四十八年（1620 年）冬天回到了福建建宁。但据陈寅恪《柳如是别传》，天启元年辛酉（1621），林天素游西湖，不久即归闽。1620 年冬，实际已经是 1621 年。根据林天素为柳如是作的序《柳如是尺牍小引》，林天素约 1621 年游西湖，又十年，林天素回到福建三山老家，又十年（约 1641 年）汪汝谦请杨云友。林天素回忆当年和杨云友、柳如是的关系，评价柳如是“艳过六朝，情深班蔡”。崇祯 14 年（1641），汪汝谦（汪然明）前往福建，专为寻访林天素，在建溪得到了林天素深情款待，但林天素没有跟随其回去。次年 5 月汪汝谦归。林天素的结局正史无记载，一说其晚年遁入空门；另有一说称其最终在战乱中被辱而死。
7. *杨云友* ：名成岫，又名慧林，号云道人，别号林下风。钱塘人，明末女画家、词人。人称“诗，书，画三绝噪于西泠”，“书法二王”，《明画录》、《无声诗史》等有记载。她没有文集留存，流传下来的词仅有三阙。她的画受到董其昌、陈继儒、柳如是等人的重视。 李渔后来把她牵强附会写在《意中缘》里，又经后人误传，写成小传。
8. *张宛仙* ：又号香隐，汪然明称其“香隐校书”。事迹简介暂无。陈寅恪认为她或为钱牧斋诗中所指之“惠香”，又称此惠香或为柳如是之妹（非亲妹），即 *杨绛子* 。
9. *葛嫩娘* （？—1646 年），字蕊芳，金陵人。早年为将门之后，其父因抗清殉国，家破人亡，葛嫩沦落秦淮为歌妓，“指奸辨贤，抱香自重”。孙临为葛嫩娘赎身，娶为侧室。清初孙临参加抗清活动，唐王时任监军副使。一日过太湖，孙临因事登岸，将葛嫩娘留在舟中， 忽有清兵至，舟上明军力战死。清兵见葛嫩娘貌甚美，欲逞兽欲，葛嫩娘咬舌自尽，鲜血喷向清军，跳湖殉难死。孙临亦就义。
10. *薛素素* （约 1575 年-约 1652 年 ），字素卿，又字润卿，号雪素 ，小字润娘。 吴(今江苏苏州)人，寓南京；一作嘉兴(今属浙江)人。 明代歌妓 、女画家、棋手。她工小诗，能书，作黄庭小楷。尤工兰竹，不笔迅捷，兼擅白描大士、花卉、草虫、各具意态，工刺绣。又驰马、走索、射弹尤为拿手好戏，被誉为“十能”才女。 薛素素还是明代唯一有史料可查的女棋手。在董其昌的指点下，薛素素画山水兰竹，都能落笔而就，且无不意态入神；后又兼擅白描大士、花卉、草虫。成年后，她的诗、书、画都挤入了名流。 薛素素曾被李征蛮纳为宠妾，后其画像传入酉阳，被彭宣慰设计骗至当地，因拒婚被羁押十余年才放归。回到南京后，薛素素重为歌妓 。后得江南名士沈德符赎身，嫁其为妾。 数年后又离开沈家，改嫁苏州富商袁微之为妾。晚年长斋礼佛。
11. *宋惠湘* ，明末金陵歌女，秦淮名妓 *卞玉京* 义女，长于烹饪。清军入关时被镶黄旗官兵掳掠北上，途经河南卫辉府汲县潞王城，于驿壁题绝句四首后殉节。其诗借曹操赎蔡文姬典故自喻，末句“厢黄旗下赎文姝”直述身世，跋文言“被难而来，野居露宿”并冀望获救未果。十四岁遭逢战乱北迁途中，宋惠湘所作四首绝句以“薄命红颜马上来”等句记录个人遭遇，诗风沉郁，清初文人余怀《板桥杂记》完整收录其诗及题壁经过，陈维崧《妇人集》记载时首句“薄命红颜”另有版本作“绝代红颜”。其事迹与诗作在清初广泛流传，朝鲜文人朴趾源于乾隆年间亦引用其诗句。
12. *董小宛* ，名白，字小宛，又字青莲， 别号青莲女史， 有“针神曲圣”之称， 南直隶苏州（今江苏苏州）人。 董小宛是明末歌妓 、昆曲艺人、 清初女诗人， 亦是明末“秦淮八艳”之一（余怀的《板桥杂记》分别写了 *顾横波* 、 *董小宛* 、 *卞玉京* 、 *李香君* 、 *寇白门* 、 *马湘兰* 六人。后人又加入 *柳如是* 、 *陈圆圆* 而称为秦淮八艳。台湾郑经生在《董小宛之谜》一文中则将马湘兰换成 *郑妥娘* 。王德恒、陈予一合著的《顺治与鄂妃》一书变动较大，它加上了 *李十娘* 、 *龚之路* 、 *黄艳秋* 三人，去掉了马湘兰、寇白门、卞玉京。）， 并位列于中国古代十大名厨之一。董小宛出身苏绣世家，少女时家道中落，成为歌妓。  她唯对明复社四公子之一的冒辟疆一见倾心，于是立志相嫁，克服种种困难，终于嫁与冒辟疆为妾，入冒府为“如夫人”。 董小宛能诗善画，酷爱苏州山水，迁居半塘，筑竹篱茅舍吟诗弹琴，后又游历黄山、西湖、太湖。因躲避清军，冒辟疆全家财产被洗劫一空，贫困如洗，董小宛仍不离不弃，想尽办法勉力支撑家计。 冒辟疆一心研究学问，董小宛日夜为其查阅资料、抄写文稿，自己也着手《奁艳》的编纂。由于日夜劳累，竟积劳成疾，一病不起，于 1651 年病逝。董小宛名冠秦淮，才艺双绝 ，主要作品有《仕女图》《秋园雅兴》《仿六如居士笔意》等， 15 岁时所画的《彩蝶图》，现收藏在无锡市博物馆，上有董小宛题词，并有二方图章印记，还有近人评价很高的题诗。 董小宛不但有诗书画传世，而且还有董肴、董糖等制作工艺流传至今。与冒辟疆结合后，两人情投意合，矢志不渝为世人所称道。
13. *卞玉京* （约 1623 年—1665 年），又名 *卞赛* ，字云装，后自号“玉京道人”，习称玉京。明代歌妓，与马湘兰、顾横波、李香君、董小宛、寇白门、柳如是、陈圆圆同称“秦淮八艳”。有妹曰敏，归申维久，亦宰相孙也。卞赛诗琴书画无所不能，尤擅小楷，还通文史。她的绘画艺技娴熟，落笔如行云，“一落笔尽十余纸”。喜画风枝袅娜，尤善画兰，作有《题扇送志衍入蜀》。顺治十年，卞玉京为一位年已古稀的好心肠的良医郑保御所收留，他为她另筑别室并悉心照拂。卞玉京在吴梅村这里找不到生命的归宿，历经湖海风涛，勘破红尘俗世，便以修道作为躲避时代的急风烈雨的避难所，以空门作为自己伤痕累累的心灵的栖息地。她持戒极严，钱谦益与邓汉仪闻之，前往求一面而不可得。卞玉京虽然皈依空寂，但她善良而重情，为了感激佛门俗家弟子郑保御的悉心照料，让她有一个焚香诵经的安宁晚年，她曾刺舌血以三年时间为其抄写一部《法华经》。卞赛后来隐居无锡惠山，十余年后病逝，葬于惠山柢陀庵锦树林。康熙七年（1668 年）九月，年届六十的吴梅村踏着萧萧落叶，前往无锡拜谒卞玉京墓，献上了他们这一段刻骨铭心的爱情绝唱：《过锦树林玉京道人墓并序》。
14. *李香君*  （1624 年—1654 年），又名李姬或李香，蘇州人，明代歌妓，秦淮八艷之一，孔尚任《桃花扇》中的女主角。现南京秦淮景区建有李香君故居纪念馆。 明天启四年（1624），生于苏州阊门枫桥吴宅，有兄妹三人。父亲原为一位朝廷武官，因成为东林党员，被魏忠贤诬陷治罪，吴家自此败落。崇祯四年（1631），随养母歌妓李贞丽改吴姓为李。自幼与人学习艺家诸艺，音律诗词、丝竹琵琶，尤擅南曲，歌声甜润，深得四方游士追慕。因李贞丽仗义豪爽且知风雅，因此媚香楼善结正直侠义之士。崇祯十二年（1639），结识复社领袖侯方域，与之交往，并为妾室。阮大铖得知方域经济拮据，暗送妆奁，以拉拢侯方域，结交复社。香君识破阮大铖的圈套，坚决退还妆奁。崇祯十七年（1644），三月京师沦陷，五月福王朱由崧即位南京，起用阮大铖，趁机陷害侯方域，迫使其投奔史可法，自侯去后，结束了媚香楼的生活。弘光元年、清顺治二年（1645），四月清兵攻下扬州，五月南京沦陷，弘光帝被部将劫持献给了清军。南京城破时，李香君随着一些宫人趁夜逃出，市街烽烟一片，清兵到处烧杀抢掠，难民四处逃窜。李香君在南京受尽苦难，后躲进栖霞山葆真庵，与昔日秦淮姐妹卞玉京相伴为尼。秋八月侯方域在栖霞山寻到李香君。经过商议，二人携手渡江北上，前往老家归德(今商丘)，住在翡翠楼上。因歌妓出身，为公公歧视，赶到侯氏庄园（今李姬园）居住。顺治十一年（1654），郁郁而亡，侯方域为香君立一石碑，上书“李香君之墓”五个大字，下有“卿含恨而死，夫惭愧终生”的小字。
15. *顾横波* （1619 年—1664 年），原名顾媚，字眉生，别字后生，号横波，后改姓徐，号善财君，又号智珠、梅生，时称横波夫人，上元（今江苏南京）人。明末清初歌妓、昆曲艺人 、画家、诗人，“秦淮八艳”之一。 顾横波原为秦淮歌妓，后为龚鼎孳宠妾。清末有人将顾横波刻于《秦淮八艳图咏》。顾横波交游甚广，家有眉楼（因此又称为眉楼），几乎每日设宴，酬唱应答，极富文采。顾横波利用自己的地位保护过不少反清诗人。后来，龚鼎孳称她为“亚妻”，被朝廷封为一品夫人。1664 年，病死于北京。顾横波精通音律，善能诗词，著有诗集《柳花阁集》，其还善画山水，尤以画兰为名。
16. *陈圆圆* （1623 年～1689 年 ，一说 1695 年），原姓邢，名沅，字圆圆，又字畹芳、畹芬。年幼时父母双亡，由姨妈收养，姨夫姓陈，故改姓陈，居苏州桃花坞。明代歌妓、吴中名伶，精通琴棋书画，是“秦淮八艳”之一。有画作《陈圆圆墨竹图》真迹传世，笔墨精妙，画如其人秀美，罕见而珍贵。崇祯末年被田畹所掳，后被转送吴三桂为妾。相传李自成攻破北京后，手下刘宗敏掳走陈圆圆，吴三桂遂引清军入关。
17. *汤漱玉* （1795 年—1855 年），清代女画家。字德媛，钱塘（今浙江杭州）人。汪远孙妻。汤漱玉好读书，精通经史、诗文，能画梅兰等花卉，罕为外人作。善书法，师法米芾、米友仁父子。家藏书甚富，精究目录。其夫汪远孙，为其书《玉台画史》作别录一卷。《玉台画史》是其选历代能画妇女辑录的画史，价值极高。
18. *汪菊孙* ，字静芳，钱塘人。乾隆甲寅举人刑部主事諴女，远孙姊，光禄寺署正金文炳室。有《停琴伫月轩诗钞》。闺秀汪端亦研究史学，兼及声韵，是为菊孙之从姑。 菊孙自幼请业焉，故其诗亦取法青邱（高启）。卒后，魏滋伯广文评选其稿付刊。［《两浙糟轩续录》］孺人有二贤子，曰城，字杏楼；曰善字访叔；皆能诗善画。娶小米中翰女，即孺人侄女，亦能诗。
19. *许楚姬* （朝鲜文:허초희，1563 年—1589 年 3 月 19 日），一名许孝玉，字景樊，号兰雪轩，兰雪斋。本贯阳川许氏，朝鲜王朝中期女性诗人，作家，画家。遗作诗调是 200-300 余数，她亦是朝鲜作家许筠的姐姐。著作有《兰雪轩集》等。
** 男
1. /钱谦益/ （1582 年 10 月 22 日—1664 年 6 月 17 日），字受之，初号尚湖，又号牧斋，晚号绛云楼主人、蒙叟、东涧老人，又因其住址而称虞山、因其职位而称宗伯，直隶常熟县（今江苏省苏州市常熟市）人，万历三十八年探花。作为明末清初时期文学领域的集大成者，钱谦益引领文坛长达五十年之久。在政治上钱被视为东林党或复社人士。明朝时四次出仕，官至礼部尚书。后在南京降清，任礼部侍郎五个月，有“贰臣”之目。辞官后投入反清复明运动，为遗民义士接纳，更成为联络东南与西南抗清复明势力的总枢纽。后钱谦益的诗文被乾隆帝下诏禁毁。 陈寅恪认为其是“复国之英雄”，“应恕其前此失节之愆，而嘉其后来赎罪之意，始可称为平心之论”，并称钱与其妻柳如是的诗文足以“表彰我民族独立之精神，自由之思想”。有子名孙爱。
2. /钱曾/ （1629 年—1701 年），字遵王，号也是翁，又号贯花道人、述古主人，南直隶苏州府常熟县虞山人，明末清初藏书家。崇祯二年（1629 年）八月二十五日出生。钱曾是钱谦益族曾孙，钱岱曾孙，钱时俊孙，钱裔肃第三子。自幼随父整理图书，顺治十八年（1661 年）因江南奏销案被革去生员。
3. /陆贻典/ （1617 年—？），一名陆典。字敕先，号觐庵。藏书家。少从钱谦益学诗，与冯班友好，冯班称他“今之端士”“下语多惊人”“咏情欲以喻札义”，是虞山诗派重要人物。《藏书纪事诗》称其为“新城令君之才子，汲古季子之妇翁。东涧老人之高足，其友则大冯小冯。”三次校勘《乐府诗集》。康熙二十三年（1683 年），尚在人世。毛扆是他的女婿，二人常一起校书。
4. /冯班/ （1602 年—1671 年），字定远，号钝吟老人，直隶苏州府常熟县人，明末清初诗人。冯复京次子。生于万历三十年（1602 年）。早年为诸生，从钱谦益学诗，与兄 /冯舒/ 齐名，人称“海虞二冯”。明亡后不仕，常就座中痛哭，自署曰“二痴”。冯班是虞山诗派的重要人物，钱谦益称冯班之诗“沉酣六代，出入于义山（李商隐）、牧之（杜牧）、庭筠（温庭筠）之间”，论诗讲究“无一字无来处”，反对严羽《沧浪诗话》的妙悟说，其《钝吟杂录》卷五《严氏纠谬》专驳严羽说。钱陆灿对冯班提出“以妖冶为温柔，堆砌为敦厚”的批评。吴乔推崇贺裳、冯班，称贺裳《载酒园诗话》、冯班《钝吟杂录》与自己的《围炉诗话》为“谈诗三绝”，书中多引贺裳、冯班之语。康熙十年（1671 年）卒。赵执信尝谒其墓，以“私淑门人”刺，焚于冢前。
5. /吴殳/ （1610 年—1694 年），又名乔，字修龄，太仓常熟人，明末清初诗人、史学家、武术家。 吴殳少年时，正值明朝内忧外患之际，他考虑到在这时代若倘得能考取功名，得到朝廷所用，必然会参与平定内乱或抵抗外敌的工作。因此，他经常与同乡的少年一起驰马游历，又研读《孙子兵法》、《纪效新书》等军事著作。曾从朱熊占学习峨嵋枪法。崇祯六年（1633 年），石电（号敬岩）受聘至娄（即今江苏刘河镇），寓居于当地的“报本寺”，负责练兵的工作。吴殳得到消息后，便约了同乡的少年夏君宣、夏玉如、陆世仪（号桴亭）三人，一同向石电拜师，在其门下学习枪法，前后学习了三年。崇祯八年（1635），石电战死，而三人枪法中辍。同年春末，吴殳于湖上遇项元池，学得双刀法。又客游燕中，得郑世子所著的《乐书》。崇祯十一年（1638 年），考取秀才。崇祯十七年，李自成攻入北京，吴三桂引清兵入关。革代之后，吴殳心如死灰。顺治十八年（1661 年），秋，著成《乐书》；冬，写成〈石敬岩枪法记〉。康熙元年（1662 年），吴殳接受盛辛五聘到鹿城，担任他儿子的老师。自此吴殳与盛辛五的好友朱熊占谈论枪法，使当年所学顿复旧观。八月十日，写〈单刀图说自序〉。中秋，著成《峨嵋枪法》。冬初，从朱熊占手上得到程真如的《峨嵋枪法》。康熙十六年（1678 年），八月，编成《手臂录》。秋，写〈梦绿堂枪法序〉。康熙十六年（1680 年），自果亭徐公复得郑世子《乐书》。夏，编成《难光录》。康熙十九年（1681 年），冬，著《围炉诗话》。康熙二十五年（1687 年），夏，编成《无隐录》。康熙三十三年（1695 年），吴殳卒，享年八十五岁。著作有《手臂录》、《围炉诗话》、《西昆发微》、《难光录》、《怀陵流寇始终录》（由戴笠始于顺治年间编纂，戴笠死后遗稿由其门生潘耒所得，后由吴殳删节成书。全书叙述了明末民变的全过程，是研究明末民变的重要史书。）、〈剑诀〉及〈后剑诀〉（剑术方面的重要文献，对后代中国剑术发展有重要影响。）。
6. /冯舒/ （1593 年-1649 年），字己苍，号默庵，别号癸巳老人，自号孱守居士。江苏常熟人，冯复京之子，冯班之兄。中国明末清初学者、著名藏书家、刻书家、 诗人。 冯舒年幼承父教诲，笃志读书，肆力于古学，含茹经史，穿穴百家。30 岁时，即谢去诸生，与弟冯班笃志于诗，吴中有“二冯”之称。明末复社领袖张溥爱慕其才而招之，因社名犯其父偏讳，不往。崇祯年间（1628 年-1644 年），冯舒因钱谦益下狱牵连被逮。冯舒入清后，顺治六年（1649 年），以议论赋役之事触忤县令，被借口以其《怀旧集》语涉讥谤，下狱而死。 冯舒家多藏宋元善本，手自校勘，评定次第。又建小阁，设两厨，各题一铭，以宝藏之。他尤精于诗，诗风近于李商隐。著有《默庵遗稿》10 卷，编有《怀旧集》2 卷、《历代诗纪》100 卷，又有《诗纪匡谬》1 卷、《校订玉台新咏》10 卷，别撰《虞山妖乱志》2 卷。
7. /沈雄/ （生卒年不详），字偶僧，江苏吴江人，清顺治年间在世，清代词人。工于词作，著有《柳塘词》，并辑录《古今词话》，后者辑录宋元至明清词人词作及词论，系统划分词学门类，保存部分失传文献。曾从元明文献中整理宫词史料，节选朱有墩《兰雪轩词》、张昱《辇下曲》等故实，创作《清平乐·宫词》十首，聚焦元代宫廷生活细节。其编纂的《古今词话》收录本人词论，涉及词体源流、创作技法等范畴，引述冯子骏、吴彦高等人轶事及词作背景，体例对后世词学理论框架有参考意义。该书被收录于《词话丛编》，在清代词学界广泛引用，成为考察宋词传承的重要文献。沈雄在《古今词话·凡例》自署“戊辰新秋吴江沈雄识于金阊之宝翰楼”，“戊辰”为康熙二十七年（1688 年），据此可推断沈雄大约出生于万历晚期，至少活到了康熙二十七年之后。沈雄曾参与校阅吴江沈氏家族重要曲学传人沈自晋的《南词新谱》，在清初江南词坛交游广泛，与曹溶、钱谦益、龚鼎孳、王士禛、陈维崧、曹尔堪、江尚质等文坛领袖及知名词人有词学交流与互动。
8. /袁景辂/ （1724 年—1767 年），字质中，号朴村。清朝吴江人。雍正二年甲辰（1724 年）出生。乾隆五年（1740 年）追随沈德潜学诗。中年弃举业。乾隆二十九年（1764 年）与王元文、袁益之、顾汝敬、顾我鲁、陈毓升、陈毓咸等人创立竹溪诗社。乾隆三十二年丁亥（1767 年），去世，年仅四十四。尝辑《松陵诗征》。著有《小桐庐诗稿》。
9. /汪汝谦/ （1577 年—1655 年），字然明，又号松溪道人，明末清初徽商、文人和书画收藏家。陈寅恪认为他是“钱、柳因缘之介绍人也。”著有《春星堂集》、《不系园集》等。
   1) /汪鹤孙/ ，字雯远，钱塘人，为汪汝谦之从子（集中称其大父）。康熙癸丑进士，改庶吉士。有《延芬堂集》。
   2) /汪继昌/ ，或称征五先生，号悔岸。然明先生次子。顺治（五年）子经魁。（六年）己丑成进士。历仕广西左江道、湖广江防兵备按察司副使。
10. /张溥/ （1602 年—1641 年），字乾度，后改字天如，号侯在，改号西铭，直隶太仓州（属今江苏太仓市）人。明代文学家、学者，复社领导人。张溥幼时常受屈辱，15 岁父亡后，奉母别居西郊，肆力苦学，读书“七录七焚”以强记忆，因颜其室曰“七录斋”。天启四年（1624 年），与张采、杨廷枢、杨彝、顾梦麟、朱隗、吴昌时等十一人共创“应社”，以治五经、研讨制义为务。天启六年（1626 年），魏忠贤逮周顺昌，激苏州民变，颜佩韦、杨念如等五人被杀，张溥因作《五人墓碑记》以记之。崇祯元年（1628 年），以恩贡入太学，结“燕台社”，又与杨伯祥结“江北应社”。崇祯二年（1629 年），于吴江开尹山大会，合十七家文社为一，以“兴复古学，将使异日者务为有用”为宗旨，称“复社”，共推张溥为首领。次年，乡试夺经魁，中试，并于南京首举“复社”社集，称“国门广业社”。崇祯四年（1631 年），入京，中进士，选翰林院庶吉士。在京二年，后以葬亲乞假归。崇祯六年（1633 年），再主盟“复社”士子虎丘之会，次年，复于南京社集。崇祯十四年（1641 年）五月初八，卒。 张溥在文学方面，推崇前后七子的理论，主张复古，又以“务为有用”相号召；张溥也是明末的散文家，善诗词，一生著作颇丰，辑有《汉魏六朝百三名家集》，对后世较有影响。另著有《七录斋集》等。
11. /吴昌时/ （1594 年—1643 年），字来之，号竹亭，又号鸳湖主人，苏州府吴江县籍浙江嘉兴县人。明末政治人物。天启四年（1624 年），与郡中名士张采、杨廷枢、杨彝、顾梦麟、朱隗等十一人组织复社。崇祯三年（1630 年）庚午科应天乡试第七十四名举人。崇祯七年（1634 年）中甲戌科三甲第三名进士，工部观政后，本年六月授行人司行人，十二年升礼部祠祭司主事，十三年升精膳司员外郎，养病回籍。十五年补仪制司郎中，十六年升吏部文选司郎中。崇祯十年（1637 年）薛国观因收受吴昌时的赂金，事发被弹劾免职，最终自尽死。昌时后依附周延儒，崇祯十四年（1641 年）二月，经张溥、吴昌时的竭力策划，周延儒任相，昌时为文选郎中。昌时与董廷献狼狈为奸，把持朝政。最后吴昌时用药毒害张溥，“以一剂送入九泉”。亲家徐汧见昌时结怨太多，料定必定遭祸。祁彪佳首劾吴昌时紊制弄权，随意将御史外调。御史蒋拱宸弹劾吴昌时赃私巨万，牵连周延儒，给事中曹良直亦劾周延儒十大罪，朝廷遂削周延儒之职，遣锦衣卫逮其入京受审。昌时百般辩解，称“祖宗之制，交结内侍者斩，法极森严，臣不才，安敢犯此？”崇祯帝亲自审问吴昌时，命用刑打断了吴的小腿，阁臣蒋德璟、魏藻德奏道：“殿陛之间无用刑之例，伏乞将昌时付法司究问。”崇祯帝怒批：“此辈奸党，神通彻天，若离此三尺地，谁敢据法从公勘问者！”二阁臣奏道：“殿陛用刑，实三百年来未有之事！”崇祯帝说：“吴昌时这厮，亦三百年未有之人。”二臣哑口无言。崇祯十六年（1643 年）冬十一月，吴昌时被斩首示众。方以智撰《哀吴江》诗悼之。
12. /吴鉏/ （1618 年—1679 年），本名吴祖锡，字稽田、佩远，嘉兴府嘉兴县人，明朝、南明政治人物。吴鉏的父亲是文选郎中吴昌时，因罪被杀；他在崇祯十五年（1642 年）的乡试中副榜，抱志气，又希望为父亲雪耻。中原混乱，他打算在浙西勤王，浙东属于许都；许都败亡，厌恶者陷害他，惟徐石麒支持他而作罢。不久，北京、南京相继沦陷，他散尽家产结交豪侠之士，取回父亲在嘉兴郡库的籍官钱四万，故交陈洪范得知他的意志，对他向天发誓说自己是不得已投降清朝，因此他把因四万两交付给对方；很快陈洪范薙发，他大感失望，改名吴鉏跟随陈子龙、徐孚远谋求复兴国家。陈子龙命他到杭州侦察，遭仇人捆绑送往南京，很快逃出与妻弟徐枋往来灵岩山和支硎山。他前往绍兴，监国鲁王授与他职方郎中，绍兴失陷后到滇京，永历帝亦授与同样职务，不久加入张煌言军队。永历十五年（1661 年）清兵入缅，张煌言遣派吴鉏带着帛书到郧阳山中，游说夔东十三家在湖广出兵支援缅甸；但当时十三家已衰微无法出兵，不久张煌言军队也解散，他北走中原绕道南归，经过枋涧上草堂不回家，在胶山、大竹山居住。每逢崇祯帝死忌，他动辄哭到呕血；永历三十一年（1677 年）他迎接周王府的镇国将军朱丽中入山，打算奉他监国，唯因为自己生病并未成事。两年后（1679 年）的崇祯帝死忌他呕血而死，葬在胶东，虚岁六十二。
13. /张煌言/ （1620 年—1664 年），字玄箸，号苍水，小字阿云。浙江宁波府鄞县（今属浙江省宁波市海曙区）人。抗清名将，南明兵部尚书，文学家。后被清兵所俘，殉国。乾隆年间，清廷追谥忠烈。后永历朝覆亡，郑成功入台后亦无力回师闽南；张煌言只得纠集民间各反对力量，继续于浙东沿海一带进行抗清行动。及至永历十七年（1662 年），鲁王朱以海病死于金门，张煌言终于认为复明无望，将军队解散，躲避至浙江象山附近的小岛隐居，之后仍为清军侦知。。清人利用降清旧部乔装成僧人，乘其随从籴米之时，劫船入岛执之。张煌言被捕后，神色自若，拒绝清廷的招降，在省城杭州被处斩决，临刑前，赋《绝命诗》一首：“我年适五九，偏逢九月七。大厦已不支，成仁万事毕。”“坐而受刃”，同死者还有其客罗纶、杨冠玉等人。其妻与长子押解至镇江处斩。著有《张苍水集》《奇零草》《北征录》《探微吟》等。
14. /张名振/ （1601-1655），字侯服，南直隶应天府江宁县人。一说山西人，南京锦衣卫籍。 原任台州石浦游击，封富平将军。弘光元年（1645 年），安宗被俘，招集义师，共图恢复。与张煌言等拥立鲁王监国于绍兴。后奉监国鲁王之令从福建金门回到舟山。鲁监国二年（1647 年），获悉苏松士绅起义，统战船进至崇明，覆舟兵败。清军进逼，迎监国鲁王居舟山。舟山失陷，又奉鲁王依郑成功。其后与张煌言多次攻崇明、镇江，进窥金陵，力图恢复。永历八年（1654 年），随延平武王朱成功收复舟山，死于军中。
15. /张采/ （1596 年 12 月 8 日—1648 年 9 月 16 日），字受先，初号来章，晚号南郭，南直隶苏州府太仓州（今江苏省苏州市太仓市）人。明末官员。  崇祯元年（1628 年），张采进士登科，授江西临川知县。崇祯三年（1630 年）秋，张采病归。崇祯六年（1633 年），张采作《军储说》，建言太仓州以军储代漕兑，但被讦未行。张采与张溥同参与创建应社，治经分主《礼记》。后应社等江南文社统合为复社，又同被奉为盟主。崇祯十四年（1641 年），复社被诬结党乱政，张采应诏具疏据实辩诬。同年，太仓旱蝗饥疫，张采佐赈施粥活万余人。次年，纂成《太仓州志》，并为兵备道程峋谋划平定农民起义。张采晩事理学，以程朱为宗。崇祯十七年（1644 年），福王朱由崧即位，张采为礼部仪制司主事。弘光元年（1645 年），升员外郎，以奉使乞归。被豪猾报复几死，避难流寓。永历二年（1648 年），卒于昆山，终年五十三岁，私谥“贞毅先生”。 张采与张溥为生死至交，以名节相砥砺，以尊经复古倡天下，并称娄东二张。生前评阅《宋名臣言行录》，编辑两汉三国两晋及南朝宋齐文皆行世，南朝梁陈至隋文成书未行。著有《知畏堂文存》《知畏堂诗存》等。
16. /吴伟业/ （1609 年 6 月 21 日—1672 年 1 月 23 日），字骏公，号梅村，又号灌隱人、大雲居士、鹿樵生，室名飼鶴軒、鹿樵溪舍，祖籍直隶苏州府昆山县（今江苏省昆山市），祖父始迁居太仓州（今江苏省苏州市太仓市），明末清初诗人、政治人物，长于七言歌行，初学“长庆体”，后自成新吟，后人称之为“梅村体”。与钱谦益、龚鼎孳并称为“江左三大家”。
17. /靳荣藩/ （?—?），一说靳容藩，字价人、介人，号绿溪，山西黎城县人，清朝政治人物，同进士出身。乾隆十三年（1748 年）戊辰科进士，授河南新蔡县知县，升直隶蔚州、遵化州知州，创立文蔚书院，晋大名府知府。著有《潞郡旧闻》。
18. /宋征璧/ （1602 年—1672 年），宋懋澄堂侄，宋存标之弟，原名存楠，字尚木，又字让木，号幽谷朽生，别署歇浦村农，邬桥张塘村人，直隶松江府华亭县人，明末清初人物。天启七年（1627 年）丁卯科顺天乡试第一百七名举人，崇祯十六年（1643 年）癸未科三甲第五名进士，吏部观政，本年授中书舍人，经筵展书。与陈子龙等交往深厚。明亡后与从弟宋征舆降清，授秘书院撰文中书舍人，迁礼部郎中，出为潮州府知府。著有《抱真堂诗稿》八卷，另有词集《三秋词》。
19. /宋征舆/ （1618 年—1667 年），又名宋徵舆，字直方，一字辕文，明末清初词人，与陈子龙、李雯并称“云间三子”。邬桥张塘村人。生于明神宗万历四十六年，卒于清圣祖康熙六年，年五十岁。顺治四年（公元一六四七年）进士，官至都察院左副都御史。徵舆为诸生时，与陈子龙、李雯等倡几社，以古学相砥砺，故所作以博瞻见长。有《林屋文稿》十六卷，诗稿十四卷（含《海闾香词》等），在《四库总目》中传于世。另有《广平杂记》《琐闻录》等。
20. /周道登/ （？—1632 年），字文邦，又字先岸、文岸，号念西，南直隶苏州府吴江县（今属江苏）人。民籍。晚明政治人物。周道登为万历二十五年（1597 年）丁酉科顺天乡试第十三名举人，联捷二十六年（1598 年）戊戌科进士。改庶吉士，二十八年授编修，次年丁忧归。三十四年补原职，三十七年养病，四十年升国子监司业，升右谕德，四十一年管理诰敕撰文，升右庶子，四十三年升左庶子，掌左春坊堂印，四十四年迁少詹事。泰昌元年（1620 年）升礼部左侍郎，天启二年（1622 年）补经筵日讲官，养病。五年被革职为民。崇祯继位，七年丁卯（1627 年）十二月起升礼部尚书兼东阁大学士，出任辅臣，颇有所争执。崇祯初年，周道登与李标等同入阁。因奏对鄙浅，被传为笑柄，一次崇祯问他“宰相须用读书人，当作何解”，结果他一时答不出来，呆了半晌才说“容臣等到阁中查明回奏”；崇祯颇不悦，又微笑问：“近来诸臣奏内多有‘情面’二字，何谓情面？”结果还是答不上来，竟把情面二字颠倒，曰：“情面者面情之谓也”。崇祯二年（1629 年）御史田时震等先后交劾之，后罢去，闲居乡里。道登生性好色，家中妻妾成群，仍以无嗣为由，到处寻花问柳。又买下/柳如是**。崇祯五年（1632 年）卒。《明史》第一百三十九卷有传。
21. /李雯/ （1607 年—1647 年），字舒章，上海松江府华亭县人，明末清初词人。父李逢申，万历进士，官工部郎中。李雯出生于万历三十五年（1607 年），读书刻苦，诸生。早年为复社主盟，与陈子龙、宋征舆并称“云间三子”，和彭宾、夏允彝、周立勋、徐孚远等人以诗文唱和。李雯曾对柳如是用情极深。崇祯十七年（1644 年），李自成破北京，李逢申罹难。李雯在京邸，痛哭不绝，得棺木收殓。不久，清军入京城，经龚鼎孳等推荐，荐授宏文院撰文、中书舍人。相传多尔衮的《致史相国书》劝降书，出自于李雯手笔。顺治四年（1647 年）南归葬父，是年十二月冬还抵北京，不久病死。著有《云间三子新诗合稿》等等。
22. /程嘉燧/ （1565 年—1643 年），字孟阳，号松圆老人、偈庵，直隶休宁（今属安徽）人，明朝画家。程衍寿之子。初寓武林（今杭州），善绘事，擅画山水，师法黄公望、倪瓒，是新安画派的先驱，吴梅村评定为“画中九友”之一。家贫，以诗画应酬于文人。后徙居直隶嘉定（今属上海市嘉定区），晚年皈依佛门，释名海能。晚居虞山（今江苏常熟）之拂水庄。与唐时升、娄坚、李流芳合称“嘉定四先生”。崇祯时，钱谦益罢归，筑耦耕堂，曾邀嘉燧读书其中，二人日夕酬唱，共同推举宋诗。崇祯十四年（1641 年），回到休宁，崇祯十四年（1643 年）卒于新安，年七十九。
23. /陈子龙/ （1608 年—1647 年），字卧子，号轶符，晚号大樽，明末政治人物、诗人，直隶松江府华亭县（今上海市松江区）人，青浦县籍。陈子龙由祖母抚养长大，天启三年（1623 年）十六岁参加童子试。崇祯元年（1628）与湖广宝庆府邵阳县知县张轨端之女结婚。崇祯三年（1630 年）中式庚午科应天乡试举人，崇祯十年（1637 年）登丁丑科进士，刑部观政，出任广东惠州府推官，十三年补浙江绍兴府推官。十五年浙江同考，十六年入计，吏部举廉卓天下第一，十七年二月升吏部文选司主事，三月行取兵科给事中。福王于南京即位，复官南京兵科给事中，巡视京营。上防守要策，请召还前吏部尚书郑三俊，朝廷不听，隔年二月，以奉养父母为由离开朝廷。后出家，法名信衷。屡次起兵抗清，后联络太湖反清武装，图谋起事，最终兵败逃亡。夏之旭自杀后，陈子龙到密友侯岐曾的仆人刘驯家里躲避，又逃至其婿昆山顾天逵兄弟处。不久在吴县潭山顾天逵祖墓被操江都御史陈锦所逮捕，永历元年（清顺治四年，1647 年）6月 15 日夜间，在登船前往江宁的途中穿过跨塘桥时，陈子龙挣断镣铐，投河自杀死，被割下首级，抛尸河中。陈子龙的学生们捞其遗体，将其安葬于陈氏坟地。乾隆间追谥忠裕。
24. /朱鹤龄/ （1606 年—1683 年），字长孺，号愚庵，江苏吴江人，明末清初学者。明末诸生，明亡后隐居家乡，专心著述，与顾炎武、钱谦益、吴伟业、万斯同、徐乾学等有往来。著有《毛诗通义》。四库馆臣评：“其凡例九条及考定郑氏诗谱皆具有条理。惟鹤龄学问淹洽，往往嗜博好奇，爱不能割，故引据繁富而伤于芜杂者有之，亦所谓武库之兵，利钝互陈者也。要其大致则彬彬矣。”著有《愚菴小集》，四库全书版本。
25. /徐乾学/ （1631 年 11 月 24 日—1694 年 9 月 6 日 ），字原一、幼慧，号健庵 、玉峰先生，清代大臣、学者、藏书家。清江南（明朝为南直隶）昆山人，明末清初大儒顾炎武外甥，与弟徐元文、徐秉义皆官贵文名，人称“昆山三徐”。康熙九年（1670 年）庚戌一甲进士第三名（探花），授编修。康熙十一年（1672 年），任顺天乡试副主考官，因选人不当，降级调用。后升左赞善，充日讲起居注官。母丧归家，著《读礼通考》120 卷，丧满任《明史》总裁官，升侍讲学士。康熙二十四年（1685 年）廷试第一，入南书房，教习皇子，升内阁学士，任《清会典》、《大清一统志》副总裁，教习庶吉士。康熙二十六年（1687 年），升左都御史、刑部尚书。 与高士奇、王鸿绪等互相标榜。 其家人门客子侄亦受贿营私，横行乡里，因而屡遭劾奏。然罢官之后，康熙帝仍命将书局自随。 著有《读礼通考》《通志堂经解》《传是楼书目》《澹园集》等。家有藏书楼“传是楼”，乃中国藏书史上著名的藏书楼，藏书甚富，辑有《传是楼书目》。
26. /黄宗羲/ （1610 年 9 月 24 日—1695 年 8 月 12 日），字太冲，号梨洲，世称南雷先生或梨洲先生，浙江绍兴府余姚县（今浙江省余姚市）人。明末清初经学家、史学家、思想家、地理学家、天文历算学家、教育家。黄宗羲与顾炎武、王夫之并称“明末三大思想家”（或“明末三先生”）；与弟黄宗炎、黄宗会号称“浙东三黄”；与顾炎武、方以智、王夫之、朱舜水并称为“明末五大师”。
27. /黄宗炎/ （1616 年—1686 年），字晦木，一字立谿，号鹧鸪，浙江余姚（今浙江省余姚市）人，明末清初学者。黄宗炎是黄尊素次子，母姚氏，兄黄宗羲。曾师从刘宗周。崇祯九年（1636 年），黄宗炎与黄宗羲、三弟黄宗会到杭州应考乡试，时人称为“浙东三黄”。崇祯十二年，黄宗炎秋试不中，与黄宗会约定闭关读尽天下书才出世。顺治二年（1645 年），黄氏兄弟在家乡起兵抗清，惟最终失败。黄宗炎“于象纬、律吕、小学、轨革、壬循之学均有钻研，兼长于诗”，主张“理象合一”，注重“践履”。《清史稿》有传。著作有《周易象辞》二十一卷、《周易寻门余论》一卷、《图学辩惑》一卷等。
28. /彭宾/ （？—？），字燕又，一字穆如，松江枫泾人，明末清初时文人。是复社、几社成员。早年在松江教书为生，明崇祯二年（1629 年）太仓人张溥创立复社，崇祯三年庚午举人，彭宾首批入社。明崇祯二年（1629 年）夏允彝、周立勋、彭宾、徐孚远、陈子龙、杜麟征等六人，在松江成立“几社”，社名的含义：“绝学有再兴之几，而得知几其神之义也”，称为“几社六子”。著有《几社六子诗》、《几社壬申文选》等诗文集。
29. /徐釚/ （1635 年—1708 年），南直隶苏州府吴江县（今江苏省吴江县）人，明清政治人物。又称楓江漁父、虹亭、電發、鞠莊。徐釚于崇祯八年（1635 年）十二月初四出生，早年以计东为师，读书于南州草堂。后入宋实颖门下。少年成名，失意于科考。康熙七年（1668 年），好友程康庄任芜湖郡司马，招徐釚入幕。十一年，徐釚应计东之邀遂至北京，与朱尔迈、冯溥、周在浚、宋思玉、周纶、王鸿绪、汪懋麟、纪映锺等有唱酬。龚鼎孳于临殁谓梁清标曰：“负才子如徐君，可使之不成名耶？”康熙十七年（1678 年），朝廷诏博学鸿儒，梁清标荐举徐釚，康熙十八年（1679 年），登博学鸿词科，授翰林院检讨，参修《明史》，著俞大猷、戚继光、刘显、马芳诸大将军传，行文缜密，“一时推大作手”。康熙二十一年（1682 年），因病告假归里，二十五年（1686 年），入京补官翰林院检讨，因与同官争修改史稿而被外放，康熙二十六年（1687 年）辞归。康熙四十二年（1703 年），帝南巡至吴江，徐釚偕在籍诸臣接驾。康熙四十八年（1709 年）十月二十一日，卒。另著有《南州草堂集》、《南州草堂续集》、《词苑丛谈》、《南洲草堂词话》、《枫江渔父图咏》等。
30. /毛晋/ （1599 年—1659 年），原名凤苞，字子九，后改名晋，字子晋，号潜在、隐湖，别号汲古阁主人，室名绿君亭、汲古阁，南直隶苏州府常熟县人，居于昆承湖七星桥（亦名曹家滨），明末清初藏书家，以其汲古阁刻书留名于世。生于万历二十七年（1599 年）正月初五日。早年师从钱谦益，十三岁为诸生，二十六岁选为博士弟子员，此后会试失意。家藏图书八万四千余册，多为宋、元刻本，筑建汲古阁、目耕楼收藏。曾校刻《十三经》、《十七史》、《津逮秘书》、《六十种曲》等书，流布甚广，居历代私家刻书者之首。尤嗜好抄录罕见秘籍，缮写精良，后人称为“毛钞”。编著甚多，有《毛诗陆疏广要》、《苏米志林》、《海虞古今文苑》、《毛诗名物考》、《明诗纪事》、《隐湖题跋》等。
31. /潘柽章/ （1626 年—1663 年），字圣木，号力田，直隶苏州府吴江县平望人，清朝历史学家。潘志伊曾孙。十五岁补县庠生，是周道登之姻戚，与吴炎、朱鹤龄友好。明亡后，隐居故里，用功读书，尤精于史学，早年曾与吴炎加入“惊隐诗社”，与顾炎武等订交。康熙二年（1663 年）二月，浙江南浔庄廷鑨明史案发，与吴炎同被逮捕，明史稿被焚，同年六月二人在杭州府弼教坊被凌迟处死。妻沈氏流放至广宁，中途流产，沈氏服药自杀。顾炎武撰《书吴潘二子事》纪念潘柽章与吴炎。“惊隐诗社”随潘柽章、吴炎二人的逝世而没落。著有《国史考异》、《松陵文献》等。殁后《松陵文献》多有散佚，残稿由其弟潘耒再编成。
32. /潘耒/ （1646 年—1708 年），原名栋吴，字次耕，号稼堂，晚号止止居士，江南苏州府吴江县平望人，清朝政治人物、经学家、文学家。潘志伊曾孙。潘柽章之弟。自小过目成诵，师事徐枋、顾炎武、王锡阐、吴炎等，为顾炎武唯一及门弟子，博通经史、历算、音学。康熙十八年（1679 年）举博学鸿儒科，授翰林院检讨，参与纂修《明史》，主纂《食货志》六卷，充日讲起居注官，以浮躁降调。三十四年（1695 年）在福建建阳县刻成《日知录》三十二卷本行世。晚年崇信佛学，好山水，历游名胜，为文记之。四十二年（1703 年）康熙帝南巡后，起复原职，坚辞不受，四十七年（1708 年）卒于家。著有《类音》、《遂初堂诗集》、《遂初堂文集》、《遂初堂别集》等。名篇有〈游南雁荡记〉、〈火焰峰〉、〈天柱峰僧饷黄独〉、〈仙居诸山游记〉等。
33. /姚士粦/ （1559 年—1644 年），字叔祥。嘉兴海盐人。明朝政治人物。嘉靖三十八年（1559 年）出生。寓居秀水。十三岁为孤儿，二十岁仍不识字，作画为生，在德清时，教谕姜孩曰见他资质不凡，亲自授以句读，才开始识字。三年学成。万历十六年乡试不第。后与胡震亨同学，同郡沈思孝出抚陕西，召其入幕。思孝被调抚河南，士粦不复求仕。又与胡应麟、俞安期、曹学佺等常有问学往来。万历二十五年，入南京国子监，助冯梦祯校刻南北诸史。搜罗秦汉以来的遗文，助沈士龙、胡震亨撰《秘册汇函》，遇火板毁，后残板并入《津逮秘书》。万历三十九年，随屠乔孙等辑刻《十六国春秋》。顺治二年（1644 年），因兵祸饿死。另有《蒙吉堂集》、《莲花幕记》、《陆氏易解》一卷、《干宝易注》一卷、《见只编》三卷等。
34. **葛昌楣**（1886—1964），字咏莪，号荫梧、雍吾，别署韬华，浙江平湖人。清末民初诗人，南社社员，工书法、篆刻，擅长鉴藏。室名传朴堂、弢华馆等，著有《蘼芜纪闻》《橅六朝碑碣》等作品。其祖父葛金烺为清末词人，室名传朴堂、爱日吟庐，著有《竹樊山庄词》《传朴堂诗稿》。堂弟葛昌楹精篆刻，为西泠印社早期社员，辑有《传朴堂藏印菁华》《吴赵印存》等印谱，室名亦承袭传朴堂。
35. **沈虬**，江苏吴江人，字次雪，或称次云，号双庭，一号茧村。以岁贡知钱塘县，后调嘉善罢归。虬工书，初学文征明，既学董其昌，皆能乱真，盛行于时。其子沈天宝，字竹西，康熙四十四年(1705)举人，亦以能诗善书名。(《苏州府志》）
36. **周灿**，明末清初江苏吴江地区的文人，字光甫，号阁昭，崇祯四年（1631 年）考中进士。其诗作《盛泽》中'水乡成一市，罗绮走中原'被后世文学创作引用。通过地域背景及作品风格分析，学者认为周灿除政治身份外，还具有文学与绘画才能，晚年以诗、画自娱，并著有《盛泽》。当前学界对其生平活动的记载较少，但诗文作品为研究江南地域文化提供了重要素材。
37. **顾苓**（1609—1682），字云美、员美，号浊斋居士、荆蛮、塔影园客，明末清初江苏苏州人，篆刻家、书法家。明亡后隐居虎丘山麓塔影园，以“文氏弥甥”自居，拒绝仕清。顾苓承袭文彭篆刻技法，为清初吴门派代表印人。工隶书，取法《夏承碑》，精研汉碑著《汉碑目》，提出篆刻“白文转折处须有意，非方非圆，天然成趣”的理论。其篆刻风格圆劲静穆，作品《塔影园集》传世，入周亮工《印人传》。清初与遗民交游于塔影园。
38. /谢三宾/ （1593-1672），字象三，号塞翁，浙江鄞县（今宁波）人。明天启五年进士，历任嘉定知县、监察御史、太仆寺卿，师从钱谦益。工山水画，与董其昌、李流芳等名家探讨画理，作品“迥异恒境”。著有《一笑堂诗集》，收录诗作近千首。崇祯五年巡按山东期间平定登莱叛乱，战后侵吞财物致富。丁忧归乡后与抗清势力对立，清军南下时两度降清，告密宁波义军致抗清失败，并参与镇压南明势力。曾编纂《嘉定四先生集》（指明末**程嘉燧**、**唐时升**、**李流芳**、**娄坚**四位文人，活跃于万历至崇祯年间，以诗文书画著称），任嘉定知县时疏浚吴淞江改善灌溉。与名妓柳如是有情感纠葛，后收购钱谦益藏书。其子殉明死节，三孙以祖父降清为耻。
    1) 子于宣，字宣子。
39. /马元调/ （？～1645），字巽甫，又字简堂，明嘉定（今上海嘉定）人，诸生，为明末嘉定文派重要成员。 师从 /娄坚/ ，精经史典章，长于古籍校勘，著有《简堂集》，曾刊刻元稹、白居易文集及《梦溪笔谈》等善本。凡邑境兵防、水利及藏书事务多有建言，清兵破嘉定时与黄淳耀等殉难。少时得《容斋随笔》，借诸家藏本校订千余字，于崇祯三年重刻该书。万历崇祯年间，曾参与龚氏园会文唱和。其刊刻《梦溪笔谈》在崇祯四年。晚年寓居僧舍整理旧籍，刻书时亲自主持校勘。1645 年清军攻城，城陷后死节，与守城诸生共赴国难。
40. /黄淳耀/ （1605 年-1645 年），初名金耀，字蕴生，一字松崖，号陶庵，又号水镜居士，或称为“忠节”。南直隶苏州府嘉定（今属上海）人。中国明代文学家、官员。 黄淳耀 17 岁时补博士弟子员。明崇祯二年（1629 年），入复社。崇祯六年（1633 年），为侯峒曾所聘，教授诸子。崇祯十一年（1638 年），黄淳耀参与讨伐阮大铖。3年后，在常熟参加临社。崇祯十五年（1642 年），在家乡成立直言社，并中乡举。崇祯十六年（1643 年），中进士，未授官而归，家居研习经籍。弘光元年（1645 年），清兵南下，嘉定士绅举义兵数千人，推侯峒曾与黄淳耀为首，据城抵御。城陷，黄淳耀与弟渊耀自缢于城西僧舍。 黄淳耀弱冠即有志圣贤之学，晚而充养和粹，造诣益深，名著乡里。其文宗归有光，诗学太白，卓然名家。著有《知过录》《自监录》《吾师录》《陶庵集》等。
41. /王沄/ ，江南华亭人，字胜时，或作胜持。陈子龙抗清败死，其眷属贫不能给，子龙门下均不顾，沄常周恤之。有《瓠园集》、《辋川诗钞》等。
42. /瞿式耜/ （1590 年—1650 年），字起田，号稼轩、耘野，又号伯略，汉族，南直隶苏州府常熟县人，明末诗人、官员。瞿式耜早年拜钱谦益为师，1616 年中进士，后授江西永丰知县，颇有政绩。1623 年丁父忧返里，与西洋教士艾儒略（Jules Aleni）往还，后受洗入教，取名多默（Thomas），曾为艾氏所著性学觕述作序。1628 年，擢户科给事中，屡疏劾斥掌权佞臣，皇帝多采其言。后遭温体仁、周延儒等排挤陷害，与其师钱谦益同贬削，继而罢归常熟。式耜在乡颇治园林，以诗酒自遣，集大儒隽语为《媿林漫录》十卷。1644 年李自成攻克北京，福王在南京建立政权，瞿式耜出任应天府丞，旋擢为右佥都御史，巡抚广西。1645 年夏，瞿式耜抵梧州，时南京已破，鲁王监国于绍兴，唐王亦称号于福建，靖江王亦于稍后监国于桂林，瞿式耜以为当立者应为永明王由榔，故与丁魁楚等合力擒靖江王，亦不入闽就唐王封职。第二年，唐王殉国，朱由榔立于肇庆，瞿式耜进吏部右侍郎。后清兵破赣州，瞿式耜留肇庆。明年，改元永历，清兵陷肇庆，乃走梧州，旋护帝至桂林，升任兵部尚书。瞿式耜曾自澳门借得葡兵三百人、重炮数门，故一时收复失地甚多，桂林亦因之而久守，后封临桂伯。1650 年，南明朝臣互诋，粮饷匮乏，清兵自全州进，桂林大乱，城中无一兵，瞿式耜独不去，与总督张同敞相对饮酒，日赋诗唱和，得百余首。后从容就逮，孔有德劝降不屈。又于囚中作临难表疏，与张同敞同在桂林风洞山仙鹤岭下英勇就义。
43. **顾景星**(1621 年～1687 年)， 明末清初文学家。字赤方。号黄公，别号玉山居士。蕲州（今属湖北蕲春县蕲州镇）人。明末贡生，南明弘光朝时考授推官。入清后屡征不仕。康熙己未(1679 年)荐举博学鸿词，称病不就。顾景星经历丰富，一生坎坷，他虽府试院试皆获第一，且严父 指教，博学广记，加之深厚的文化积淀浸润，前程应是不可限量的。他完全可以辅佐朝政，治国安邦；但他坚定地选择了一心著书立说的事业中，成为了当时最负盛名的文学家之一。生平著述宏丰，共有 430 卷之多。其中《来耕集》和《南渡集》75 卷编入《四库全书》；《黄公说字》100 余卷中有 47 卷编入《四库全书》。《白茅堂集》包括乐府民歌、诗赋、策论、志论、奏疏、史论、传记、序文、铭诔、杂著等共 46 卷。
44. **杨钟羲**(1865—1940)清末藏书家。姓尼堪氏，原名钟庆，戊戌政变后改为钟羲，冠姓杨，字子勤，圣遗、芷晴，号留垞、梓励，又号雪桥、雪樵等。先隶满洲正黄旗，乾隆间改为汉军正黄旗，世居辽阳。光绪十一年(1885 年)举人，十五年进士，授翰林院庶吉士，散馆授编修。二十三年任国史馆协修和会典馆图画处协修。二十九年任湖北乡试内监试官。后历任襄阳、淮安、江宁知府。辛亥革命后，蛰居上海，以遗出任湖北襄阳、安陆知府，江苏江宁、淮安知府。辛亥革命后，留寓上海，以清遗老自居，寄情文史，不问世事，为刘翰怡编校图书数年，后又供职伪廷，卒后伪谥“文敬”。
45. **范锴**（1765~1844），清代藏书家、文学家。原名范音，字声山，号白舫，别号苕溪渔隐、苕溪渔叟、苕溪老渔。浙江乌程（今吴兴）南浔镇人。例贡生。有隽才，工诗词，好游历。性淡泊孤傲，无意于仕途，而寓意于盐策，往来于淮扬楚蜀之间达 30 年之久。范锴青年时期常在南浔藏书家刘桐处阅览典籍。旅居汉口经营盐业多年，撰有《汉口丛谈》六卷，该书记述汉口历史与发展，史料详实，被视为第一部系统叙述汉口城市兴衰的史书。其著述颇丰，刊刻有《苕溪渔隐诗稿》，著有《浔溪纪事诗》《蜀产吟》《汉口丛谈》《痴人说梦》《揽茞山房漫记》《花笑庼杂笔》《声山杂著》《吴兴藏书录》《浔溪渔唱》《苕溪渔隐词》《幽华诗略》等，辑有《吴兴志续编》《吴兴山墟名》《吴兴记》《吴兴入东记》等，后多汇刻为《范白舫所刊书》及《范声山杂著》。所著《痴人说梦》为嘉庆二十二年（1817 年）刊本，是早期重要的《红楼梦》研究专著，内含《槐史编年》《胶东余牒》《鉴中人影》《镌石订疑》四种，编制了《红楼梦》年谱、人物谱、贾氏宗族谱牒，进行了版本校勘，并绘制贾府及大观园图，在红学史上具有重要地位。中岁以后往来楚、蜀经营盐业，晚岁寓居扬州。
46. **缪荃孙**（1844.9.20—1919.12.22），字炎之，又字筱珊，晚号艺风老人，江苏江阴申港镇缪家村人。中国近代藏书家、校勘家、教育家、目录学家、史学家、方志学家、金石家。我国文化教育科技界尊称他为中国近代图书馆的鼻祖。清光绪年间进士。缪荃孙幼承家学，11 岁修毕五经。17 岁时太平军进江阴，侍继母避兵淮安，丽正书院肄业，习文字学、训诂学和音韵学。21 岁举家迁居成都，习文史，考订文字。23 岁应四川乡试中举。1876 年会试中进士，授翰林院编修。此后事编撰校勘十余年。1912 年后移居上海，继续从事目录学研究。缪荃孙与陈三立等文人交往。2019 年 12 月 22 日，在北京国家图书馆举行缪荃孙逝世 100 周年纪念活动。家乡江阴申港镇设有缪荃孙图书馆。
47. /曹溶/ （1613—1685 年），字秋岳，一字洁躬，亦作鉴躬，号倦圃、鉏菜翁，浙江秀水（今嘉兴）人。明崇祯十年进士，官御史。 尝劾辅臣谢升，又熊开元参周延儒遭廷杖，曹溶疏白其冤。清顺治元年清兵入北京后，仕清任顺天学政，为清王朝献策，疏陈定官制，定屯田、盐法、钱法规制，禁兵丁将马践食田禾等，皆被采纳实施。又就有关科举、荐举隐逸、访旌殉节者等问题向朝廷建议。三年二月充会试监考官，三月迁升为太仆寺少卿。不久，被发现在学政任上所举贡生中有明代受世袭职和中武举者，降两级调用。接着又因选拔贡生超额被革职回籍。十一年官复原职，迁左通政。次年三月擢左副都御史，旋擢户部右侍郎，接着又授广东布政使。十三年，以举动轻浮，降一级改任山西阳和道。康熙三年裁缺归里。十三年，三藩举兵，阁臣以边才荐，随征福建。十七年诏举博学鸿词，大学士李霨等荐曹溶，未试。十九年，学士徐元文荐曹溶佐修《明史》，未赴。曹溶长于经济，未竟其用，乃独肆力于文章。家富藏书，朱彝尊纂《词综》，即多从其家藏宋人遗集中录出。其故宅在金陀坊，筑有园林倦圃，周之恒绘《倦圃图》，朱彝尊为之记，园有“山泉鱼鸟蔬果花药”诸胜，共 20 景。曹溶工诗词，其诗源本杜甫苍老之气，一洗妩柔之调，与龚鼎孳齐名，世称“龚曹”。填词规摹两宋，无明人之弊，浙西词风为之一变，朱彝尊受曹溶影响颇深，少时曾从曹溶游。著有《静惕堂诗词集》等。又精于小简，有《静惕堂尺牍》 4 卷，时称江东独步。
48. /谈迁/ （1594 年-1658 年 1 月 14 日），史学家，原名以训，字仲木、孺木，号射父，浙江海宁（今浙江海宁西南）人。明亡后改名迁，字孺木，号观若，自称“江左遗民”。 终生不仕，以佣书、作幕僚为生。谈迁博鉴群书，善诸子百家，精研历史，创作了史书《国榷》。他的作品还有《枣林杂俎》《北游录》《枣林集》。谈迁立志编撰一部翔实可信的明史，从明天启元年（1621）开始，历时 20 余年，前后“六易其稿，汇至百卷”，完成一部编年体明史，共 500 万字，取名《国榷》。顺治四年（1647），《国榷》手稿被窃。发愤重写，经 4 年努力，矢志不挠，终于完成新稿。顺治十年（1653），携稿随人北上，在北京两年半，走访明代故臣搜集明代遗闻，并实地考察历史遗迹，加以补充、修订。书成后，署名“江左遗民”，以寄托亡国之痛。顺治十四年，去山西平阳祭奠先师张慎言，病逝于旅舍。《国榷》以《明实录》为本，参阅诸家史书，考证订补，取材广博，选择谨严，为研究明史的重要著作。他与张岱、查继佐、万斯同合称为“浙东四大史家”。
49. **查继佐**（1601 年 8 月 1 日－1676 年 3 月 4 日），初名继佑，入清更名省，或隐名为左尹。初字三秀，后字不省、友三。号非人氏、伊璜、敬修、与斋、舆斋、东山钓史。学者称东山先生。浙江海宁人。明末清初史学家、文学家。查继佐出身于书香门第，自幼勤奋读书，稍长后善于诗文，声名鹊起，20 岁起在私塾任教。崇祯六年（1633 年），中试为举人。大明北都沦陷后，参加抗清斗争，曾任鲁监国的兵部职方主事。抗清失败后返回故里隐居，后又讲学于杭州敬修堂。康熙十五年（1676 年），去世。查继佐一生勤于著书，其著作有六七十种之多，其中史学著作占有重要位置，《罪惟录》一书尤为重要，是一部纪传体明史巨著。他还撰写了多部南明史著作，如纲目体史书《鲁春秋》，专记鲁王监国始末，兼及福王、唐王、桂王政权史事；传记体史书《国寿录》，记载明末浙江地区抗清的史事；《东山国语》，记载南明抗清殉节诸人传略，分区编排，以地系人。其与张岱、谈迁、万斯同合称为“浙东四大史家”。
50. **钮琇**（？-1704 年），字玉樵，吴江（今属江苏苏州）人。中国清代文学家、学者、官员。钮琇幼年师事吴南邨、吴愧庵，受《尚书》《左传》及制艺。于康熙十一年（1672 年），拔贡生，由教习考授知县。康熙十六年（1677 年），官河南项城县。因父母相继去世，于康熙二十四年（1685 年），扶亲柩南归。丁忧后，除陕西白水县知县，后改任广东高明县知县。康熙四十三年（1704 年），钮琇卒于任所。钮琇性喜诗文著述，公务之暇，不废笔墨。词翰斐然，文情轩举。诸体杂文，四六骈体，无不擅长。其诗多纪事之作，不乏佳作，著有《秋雨叹和杜少陵韵》《泣柳词》。其对于传奇演义等通俗文学也有所涉猎，在文学方面最大的贡献，就是撰写了笔记小说《觚剩》。此外，还著有《临野堂诗集》十三卷、《文集》十卷等。
51. /陈继儒/ （1558 年—1639 年），字仲醇，号眉公、也作麋公，又号白石山樵。松江府华亭县（今上海市松江区）人。明代文学家、书法家及画家。陈继儒自幼聪颖，为同郡大学士徐阶器重。参加三次乡试，可惜都不成功。二十九岁时，焚弃儒生衣冠，隐居昆山之阳（山南），筑室东佘山，杜门著述。黄道周给崇祯帝上疏提到：“志向高雅，博学多通，不如继儒”。陈继儒是文人兼书商，外界署名“陈继儒”的作品约有上千种之多，其中真假难辩，陈继儒本人亦颇为苦恼。如《小窗幽记》是本奇书，署“云间陈继儒眉公手辑”，但作者是陆绍珩。善绘画、书法，“远近竞相购写，征请诗文者无虚日。”作画善写水墨梅花，“即其制创，无不堪垂后世也。”画山水“涉笔草草，苍老秀逸，不落吴下画师恬俗魔境。”书法则师法苏轼、米芾，凡苏轼字帖、断简，必极力搜采，手自摹刻之，曰晚香堂帖。与同郡董其昌齐名，董其昌云：“眉公胸中素具一丘壑，虽草草泼墨，而一种苍老之气岂落吴下画师恬俗魔境。”。著有《眉公全集》、《晚香堂小品》等。子陈梦莲与门人吴震元、许经等编订《陈眉公集》。
52. /许经/ （约公元 1628 年前后在世），字令则，松江华亭人，明代诗人。生卒年不详，活跃于明毅宗崇祯初年前后，师从陈继儒。现存诗作四篇，包括《奉和牧翁催妆词四首・其二》《奉和牧翁催妆词四首・其三》《奉和牧翁催妆词四首・其四》及一首未命名诗作。许经曾与陈继儒之子陈梦莲、门人吴震元等人商议编订《陈眉公先生全集》，原计划分四刻百余卷，后因条件所限仅刊行《陈眉公先生全集》六十卷附《年谱》一卷。
53. /李待问/ ，字存我，又字存吾，明万历二十一年(公元 1603 年)出生于松江府华亭县竹冈李家角(今属上海市奉贤区西渡街道灯塔村)。明崇祯十六年(公元 1643 年)进士，授中书舍人。李待问书法笔力遒劲，字体秀逸，行书可与董其吕媲美。松江博物馆藏有手迹行书诗轴。著有《玉裕迸存稿》。清顺治二年(公元 1645 年)，李待问与沈犹龙、陈子龙、夏允彝等松江文人义士起兵抗清，防守东门，城破被俘。临行前，劝告松江百姓剃发更装，免“嘉定三屠”之惨剧，清将敬佩其凛然大义，终未开杀戒。乾隆四十一年间追谥为“忠节”。
54. /徐孚远/ （1599 年-1665 年），字闇公，晚号复斋，南直隶松江府华亭县（今上海市松江区）人，明朝内阁首辅徐阶之弟徐陟的曾孙。中国明末清初诗人。徐孚远于 1642 年，中举人。明亡前，主要在松江地区活动，以科举应试和学术研究为主。1645 年，清兵南下，徐孚远与家人等参加松江保卫战，城破，长子徐世威战死，徐孚远与妻子航海入闽，奔赴唐王，被任命为大兴司礼。1646 年，徐孚远以兵科给事中随张肯堂水师沿海北上。同年八月，隆武帝殉国，鲁王监国，赐徐孚远一品服，充行人司。同年十一月，徐孚远与陈子龙、夏完淳一起，策反清松江提督吴胜兆。1649 年，迁国子监祭酒、左佥都御史。1651 年，清军破舟山，与张名振等护送鲁王到厦门。1653 年，作为监军，参加张名振、张煌言北伐。1657 年，受鲁王和郑成功委派，取道安南，觐见永历帝。1660 年，徐孚远助郑经留守厦门。1662 年，随郑经入台，居于彰化，一面从事农耕，养家糊口，一面与在台遗民多有唱和，有组建“海外几社”之说。1663 年至 1664 年间，往来于闽、广的铜山、饶平之间，逃避清廷追捕。1665 年，徐孚远去世。徐孚远与陈子龙、夏允彝、彭宾等创立几社，先后编著有《壬申文选》《史记测议》《几社会义》《皇明经世文编》等。徐孚远注重诗歌的社会功用。其诗歌主要见于《钓璜堂存稿》20 卷。另有《交行摘稿》《南海摘草》两书收录徐孚远在安南、广东时期作品，惜原本佚。徐孚远尤擅长以悲壮之语抒发情感，诗风豪迈苍凉，部分作品有诗史之美。弟致远，字武静。
55. /王应奎/ ，字东溆，号柳南，诸生，生于康熙二十二年（1683），约卒于乾隆二十四、五年（1759—1760）间，年近八十岁。许廷录在《王东溆诗集序》中称：“其平昔研讨典籍，探索经史，挹其华而摛其实”。工书法，初学颜真卿。亦善於山水画，不落近人窠臼。著作除了《柳南随笔》、《续笔》外，还有《柳南诗文钞》、《海虞诗苑》十八卷。《海虞诗苑》既展现了虞山诗人群体形象，具有突出的地域特色，是一部地域诗歌文学史，同时在诗人及作品的编选上，也体现了王应奎本人的诗学观念。
56. /钱肃润/ （1619-1699），字礎日、号季霖，是明末清初江南地区具有代表性的遗民学者，以著述讲学、结社交游等方式坚守政治气节。其编纂的《南忠纪》等史籍记载南明抗清事迹，被后世视为研究明清易代的重要史料。作为惊隐诗社成员，他与顾炎武、归庄等遗民群体保持密切交往，通过诗文活动维系汉文化传统。明亡后拒绝仕清，因坚持穿戴明代衣冠遭清廷杖责致残，自号"跛足生"并隐居民间讲学。所著《南忠纪》等人物传记，系统记录了江南士人拒斥城市、保持气节的文化现象，成为研究明清士人精神世界的重要文献。
57. /邹祗谟/ （1627 年—1670 年），字訏士，号程村，武进人（今属江苏）。顺治戊戌进士。清初词坛上的重要词家，有《远志斋集》。又有《丽农词》二卷，与王士禛《衍波词》、彭孙遹《延露词》并称“三名家词”。
58. **董以宁**（1629-1669），字文友，清代初期江南武进（今江苏武进）人。性豪迈慷慨，喜交游，重然诺。明末为诸生，与邹祗谟齐名，时称“邹董”；又与陈维崧、黄永等并称“毗陵四子”或“兰陵四才子”。同里结国仪社，委以启札，魏裔介虽未谋面，亦为之倾倒。其诗文词皆工，晚年专研历法、乐律、经学及方舆之学，多所发明，著述有《正谊堂诗集》《董文友全集》及词集《蓉渡词》。《蓉渡词》含艳情、悼亡、咏史等题材，其中“艳体词”引发学界争议，《满江红·乙巳述哀》十二首被视作词史补白之作。诗词创作涉及闺怨、咏物等主题，代表作《闺怨》中“留得当时临别泪”等句体现婉约词风。作为“毗陵四家”成员，主张古文创作应“神明变化于古人之法则”，参与编纂《文统》选本。
59. **黄周星**（1611 年—1680 年），本姓周，名星，字九烟、景明、景虞，号圃庵、而庵、笑苍道人、汰沃主人，明末清初湖广湘潭（今湖南）人，生于上元（今江苏南京），戏曲作家、戏曲理论家。幼年因生母遭正室妒忌被遗弃，由商人周逢泰收养，就读于南京国子监。崇祯十三年（1640 年）中进士，授户部主事。明亡后携妻隐居吴越，以教书为生，康熙十九年（1680 年）拒应博学鸿儒试自尽。黄周星作有传奇《人天乐》与杂剧《试官述怀》《异花报》（后二者已佚），其中《人天乐》融入宗教元素及故国之思。戏曲论著《制曲枝语》提出‘少引圣籍，多发天然’‘雅俗共赏’等主张。工诗文，通音律，著有《夏为堂集》《廋词》，曾校订《西游证道书》。
60. **殳丹生**，明末清初人士，初名京，字彤宝，号山夫，浙江桐庐人。工诗、画，其诗作风格雄快。初居吴地（苏州）专诸塔右，后徙嘉兴盛泽三年，复为避水患迁居嘉善蒋湖之西园亦三年。晚年无家，徜徉五湖以终。作有《同臞庵过寒山寺》等诗。其妻陆观莲，字少君，号雨鬘道人，嘉善人。殳丹生室。有《蒋湖寓园草》。有女殳默，字斋季，清初女诗人，浙江嘉善人，生而奇慧，九岁能诗，刺绣刀尺，无不入妙。习小楷，摹画李公麟白描大士，爱管夫人画竹一幅，与同卧起。父爱远游，与母居，年十六未字。母死三日，默亦卒。所爱管夫人画竹并文石子十许枚，凡零香断墨残绘剩绣，其父悉纳之棺。著《闺隐集》。
61. /陈文述/ （1771 年—1843 年），初名文杰，字云伯，号颐道居士，钱塘（今浙江杭州）人。嘉庆年间举人，历任全椒、昭文等地知县，著有《碧城诗馆诗钞》《颐道堂集》等。其诗学吴伟业、钱谦益，博雅绮丽，与杨芳灿并称“杨陈”。陈文述十八岁入县学，嘉庆元年乡试以《仿宋画院制团扇》诗受阮元赏识，得“陈团扇”雅号。嘉庆五年中恩科举人。三试进士不第，留京期间与杨芳灿交游密切。
62. /夏允彝/ （1596 年-1645 年），字彝仲，号瑗公，松江府华亭（治今上海松江）人，夏完淳之父，明末抗清大臣。夏允彝幼好学，善文辞。万历四十六年（1618 年），中举人，和同郡陈子龙、徐孚远等组建“几社”。崇祯十年（1637 年），夏允彝中进士，任福建长乐知县。他能体恤民间疾苦，革除弊俗，惩办豪猾，尤善决疑狱，他县有疑案而不能断，上司都命夏允彝去审理，闽中称为“神明”。后因母丧，回家守制。崇祯十七年（1644 年），李自成攻陷北京，崇祯帝自缢。夏允彝募义兵，欲从海上赴京勤王，旋闻清军入京，作罢。后欲与史可法兴复，闻福王已在南京即帝位，遂还。擢为吏部主事，疏请“终制”，未赴任。弘光元年（1645 年），夏允彝与陈子龙、徐孚远等在松江起兵抗清，自任随军参赞。后闻松江府城被清兵攻占，又闻侯峒曾、黄淳耀等领导嘉定人民起义失败而殉国，以及吴志葵的水军在黄浦被清军全歼的消息，夏允彝从容自投松塘而死。夏允彝文学造诣和民族气节，和陈子龙齐名，世称“陈、夏”。著作有《夏文忠公集》《私制策》。编注有《春秋四传合论》《禹贡合注》《几社六君子诗》。
63. /夏完淳/ （1631 年 10 月 4 日—1647 年 10 月 16 日），乳名端哥，原名复，字存古，号小隐，又号灵首。诗人、明朝抗清将领。祖籍浙江会稽，生于南直隶松江府（今上海市松江区）。夏完淳为抗清烈士夏允彝之子，师从陈子龙。自幼聪慧，有神童之誉，“五岁知五经，七岁能诗文”，十四岁随父夏允彝抗清。夏允彝兵败自杀后，夏完淳和陈子龙继续抗清，鲁王监国封为中书舍人，参谋太湖吴昜军事，吴昜失败后，仍为抗清而奔走。顺治四年（1647 年）兵败被俘，该年九月十九日不屈而死，年十七岁。殉国前有《狱中上母书》。身后留有妻子钱秦篆（钱彦林之女，钱熙、钱默之妹）和女儿以及遗腹子，出世后夭折，家绝嗣。夏允彝、夏完淳父子合葬墓今存于上海市松江区小昆山镇荡湾村华夏公墓旁。著有《南冠草》、《续幸存录》、《玉樊堂集》、《内史集》等，其中夏完淳向嫡母与生母诀别的《狱中上母书》被选为台湾的高中国文教科书，亦被收录至华东师大出版社的《大学语文》教科书中。 夏完淳所写的《别云间》也被选入中国大陆九年级语文书中。
64. /施绍莘/ （1588-约 1630），字子野，号峰泖浪仙，华亭（今上海松江）人，明代晚期代表性词曲家。出身官宦世家，为宋代华亭县令施退翁十二世孙， 屡试不第后放浪声色，寄情山水创作。其创作兼擅词与散曲，尤以套曲成就最为突出，《秋水庵花影集》现存套曲 86 套，数量居明人之首，被吴梅评为"明代散曲一代之殿"。作品融合词曲文体特征，在明代词体"曲化"与散曲"雅化"的互动中具有典型意义。
65. **王昶**（1725 年 1 月 6 日—1806 年 7 月 22 日），字德甫，号述庵，又号兰泉。江苏青浦朱家角（今属上海）人，清代文学家、金石学家。出身书香门第，父王士毅辑有《百世师录》以教子弟。王昶于乾隆十九年（1754 年）中进士，乾隆二十二年（1757 年）召试第一，授内阁中书，入直军机处。期间六次随乾隆帝出巡，四次扈从木兰围猎，并任科举同考官五次。乾隆三十二年（1767 年）涉两淮盐引案被夺职，次年应云贵总督阿桂之邀佐征缅军事，起草招降檄文。乾隆三十六年（1771 年）随温福征讨大小金川，九年军旅生涯中加军功十三级。乾隆四十一年（1776 年）平定金川后升任鸿胪寺卿，赏戴花翎，历任江西按察使、陕西按察使、云南布政使，官至刑部右侍郎。乾隆五十九年（1794 年）获准致仕，归里后主讲娄东、敷文等书院。嘉庆元年（1796 年）赴千叟宴，嘉庆十一年（1806 年）病逝。王昶辑《明词综》《国朝词综》确立浙西词派地位，编纂《湖海诗传》《湖海文传》保存大量文献。所著《金石萃编》160 卷收录商周至宋辽金石拓本 1500 余种，开创金石文献与史籍互证体例。藏书楼"熟南书库"藏书五万卷，编《熟南书库目录》6 卷。诗文合集《春融堂集》收录作品 2700 余首，融合格调派与浙派风格。晚年修纂《青浦县志》《太仓州志》，提出"采录寡则几于陋"的方志理论。
66. /冯文昌/ ，清初藏书家。字研祥，一字文元。浙江嘉兴人，后移居钱塘（今杭州）。诸生。尝学于钱谦益。 家藏书甚富。祖父冯梦桢藏有王羲之《快雪时晴贴》真迹归他收藏后，遂将其藏书楼命名为“快雪堂”，该楼于杭州西湖孤山之侧。他还因藏有宋椠本《金石录》十卷本，该书因十分珍贵，他极为珍爱，被当做镇堂之宝而加以珍藏。还篆刻一专门印章为“金石录十卷人家。”长笺短札，帖尾书头，每每用之。然而，他的藏书并没有固守永久，不久逐渐被流散，《金石录》十卷本相继被江立、鲍廷博、阮元、赵魏、汪諴、韩泰华、甘福、潘祖荫、潘景郑等著名藏家收藏，均被当做镇楼之宝加以递藏，且各藏书家均刻有“金石录十卷人家”藏书章。
    1) /冯梦桢/ ，出生于 1548 年，卒于 1605 年，明学者、藏书家。字开之。秀水（今浙江嘉兴）人。万历五年（1577 年）进士，官编修、迁国子祭酒，因伤于流言蜚语辞官而归。富收藏，精品甚多，尤以名画、书帖较多，但书籍不加校勘。因收藏有书圣王羲之的“快雪时晴帖”斋名“快雪堂”。与学者沈懋学、屠隆等人以文章相尚。曾刻书数种，刻有《大唐新语》、《陶靖节集注》、《先秦诸子合编》等。其主刻的南监本，在收藏界颇为知名。所撰《窦生传》，叙窦绳祖与李爱姑悲欢离合的传奇故事，在明代文学中有一定影响。著有《快雪堂集》64 卷、《快雪堂漫录》1 卷及《历代贡举志》等。著有《快雪堂集》64 卷、《快雪堂漫录》1 卷及《历代贡举志》等。子 /冯鹓雏/ ，字云将，科举不得志，身世颇困顿，与汪然明交好。
    2) /冯延年/ ，字千秋。明国子监祭酒秀水梦祯孙。梦祯娶武林沈氏，爱西湖之胜，筑快雪堂于湖上。延年因入籍钱塘。中崇祯十二年副贡，入太学。归隐秋月庵。
67. **范骧**（1608 年—1675 年），字文白，号默庵。海宁人。明朝贡生，善书法。家贫，著述不辍。清初举贤良方正，坚辞不就。顺治十八年因庄廷鑨明史案被逮捕，后与查继佐、陆圻等三人因提早自首，得免于祸，最后无罪开释。卒年六十八。门人私谥清献先生。著有《点庵集》、《昭代尺牍小传》。
68. **周容**（1619—1692），字鄮山，一字茂三，又作茂山，号躄堂；明末清初鄞县（今浙江宁波）人。周容世代居住在七里垫村，出身书香门第。他是明代诸生，负才名，有侠气。周容在明朝灭亡后，一度在东钱湖畔的青雷寺剃度为僧，后为尽孝道而返俗归隐。他曾受知于御史徐殿臣，代其为质受刑，致使两脚已躄，因而自号“躄翁”。顺治十四年（1657 年）秋，周容在故里建“春酒堂”以奉养父母。康熙十七年（1678 年），同乡史大成招其入京。次年，清廷开设博学鸿词科，召周容应试，他力辞不就，后病卒于京城客栈，享年 61 岁。周容于诗文书画用工皆勤，时人谓之“画胜于文，诗胜于画，书胜于诗”。著有《春涵堂集》（一作《春酒堂遗书》）。其《小港渡者》（又名《渡者之言》）、《芋老人传》等作品被收录于一些中小学教科书。《清画家诗史》《国朝画征录》等载有他的事迹。
69. **黄道周**（1585 年 3 月 9 日—1646 年 4 月 20 日），汉族，字幼玄，一作幼平或幼元，又字螭若、螭平，号石斋，世人尊称石斋先生。为明末学者、书画家、文学家、民族英雄。福建漳州府漳浦县（今福建省东山县铜陵镇）人， 祖籍福建莆田，其曾祖从莆田迁徙至漳州。天启二年（1622 年）进士，改庶吉士，深得考官袁可立赏识。历官翰林院修撰、詹事府少詹事。南明隆武（1645 年-1646 年）时，任吏部尚书兼兵部尚书、武英殿大学士（首辅）。因抗清失败被俘。顺治三年（隆武二年，1646 年）壮烈殉国，享年 62 岁。隆武帝赐谥“忠烈”，追赠文明伯。清乾隆四十一年（1776 年）追谥“忠端”。与刘宗周并称“二周”。黄道周通天文、理数诸书。工书善画，诗文、隶草皆自成一家，先后讲学于浙江大涤、漳浦明诚堂、漳州紫阳、龙溪邺业等书院，培养了大批有学问有气节的人。陈子龙会试中式，实出于石斋之门。
70. /刘宗周/ （1578 年-1645 年），字起东，别号念台，浙江绍兴府山阴（今浙江绍兴）人，世称蕺山先生。明末理学家、 儒学大师、抗清名臣。 刘宗周于万历二十九年（1601 年）中进士。天启（1621 年-1627 年）年间，官至礼部主事，右通政，因疏劾魏忠贤、客氏，被削籍归。崇祯（1628 年-1644 年）年间，初起为顺天府尹，累官左都御史，又以论救姜埰、熊开元，遭革职。福王监国时，再起原官，又因痛陈时政，劾马士英、阮大铖等，辞官归里。杭州失守后，绝食而亡。 刘宗周其学以诚意为主，慎独为功，清修等行，不愧衾影，学者称念台先生，又称蕺山先生。黄宗羲、陈确等皆出其门。与黄道周皆以善易称于明末。其说易长于理，且多由心得，不尽墨守程《传》、朱《义》。惟其根据旧说删《说卦》《序卦》《杂卦》三传，以及移置经文次第，著有《周易古文钞》二卷、《读易图记》一卷、《易衍》等，今皆见存。其他著作甚富，有《圣学宗要》《学言》《人谱》《人谱类记》《论语学案》《道统录》《阳明传信录》《人社约言》及《刘子全书》《遗编》等。
71. /刘履丁/ ，字渔仲，或称大行，明代福建漳浦人。刘履丁与黄道周（号石斋）为畏友，其书法、绘画造诣精深，《漳州府志》《广印人传》载其艺事。岁丙子， /刘履丁/ 与金沙 /张公亮/ 、 /吕霖生/ 、盐官 /陈则梁/ 、雉皋 /冒辟疆/ 盟于眉楼。见屈大均《皇明四朝成仁录·七·嘉兴起义诸臣传》。
72. /陈则梁/ （？—？），名梁，字则梁，初名昌应，字梦张，号浣公、仑者、梁父，晚号散木子，浙江盐官（今浙江省嘉兴市海宁市盐官镇）人，明末文人。晚年葬于海盐县开济乡海月庵，自题墓铭“生无愧怍，去无牵缠”。陈则梁十八岁皈依莲池大师，法名广籍，后赴长安上书未果。崇祯九年（1636 年）与冒襄、张明弼等人在眉楼结盟，撰写“牲盟不如臂盟，臂盟不如神盟”盟文  。曾致信名妓顾眉劝其脱离风尘，促成其择主而嫁 。著有《苋园诗》因而人称苋园公，另有《仑者菑》《浣笔池藏稿》，其文以奇崛著称，时人评其“人奇文奇，举体皆奇”，魏学伊称其“口能剧谈”“博览半雄，而好深湛之思”。
73. /徐树敏/ ，字玉山、号师鲁，江苏省苏州府昆山县（今江苏省昆山县）人，清朝政治人物、进士出身。徐乾学之子，徐元文、徐秉义之侄。《清代名人传略》记载：“徐树敏，字师鲁，号玉山，1703 年进士。1711 年-1719 年任河南安阳县令。”《苏州府志》记载：“徐树敏，清人，康熙二十六年丁卯科举人，四十二年，癸未进士。”康熙二十六年，乡试中举。康熙四十二年，登进士，授江南嘉定知县。康熙五十年，任河南安阳县知县。康熙五十九年，任户部郎中。有兄徐炯、徐树谷，弟徐树屏、徐骏。徐树敏和**钱岳**连同 90 多名士编写了词集《众香词》。
74. /万寿祺/ （1603 年－1652 年），明末清初文学家、书画家，祖籍江西南昌，生于江苏徐州，入清后改名慧寿，字年少、介若、内景，别号明志道人、寿道人、寿若、若若，世称年少先生。崇祯三年（1630 年）与陈子龙同为乡试举人，后困于春闱十六年，参与复社活动。弘光元年（1645 年）于苏州起兵抗清，兵败后隐居江淮。顺治三年（1646 年）出家为僧，于淮安山子湖畔建隰西草堂，晚年以书画篆刻为生，著有《隰西草堂诗集》《沙门慧寿印谱》等，书画代表作有《秋江别思图》《松石图》《山水图》等。万寿祺擅楷书、行书，书风融合王羲之与颜真卿，绘画师法倪瓒，兼工白描。精研六书，主张印章应重篆法笔意，推崇汉印自然风格，著有《印说》批判明末印坛流弊。常与顾炎武、阎尔梅等遗民交游，晚年移居清江浦南村耕读自给，顺治九年卒于隰西草堂。
75. **李延罡**（？～1722），原名彦贞，字我生，一字期叔，后改延罡，字辰山，别号西园老人。明末清初上海人，医学家。出身官宦世家，早年参与桂林抗清活动。明亡后出家为道，晚年居平湖佑圣宫。精研医术，著有《药品化义》《脉诀汇辨》等医书。行医不避远途，诊金多用于购书，藏书达三十架环置榻边。另撰《放鹇亭集》《南吴旧话录》等诗文杂记，日常仅携一瓢一笠一琴一砚。
76. /李流芳/ （1575—1629），字长蘅，号檀园、慎娱居士，祖籍安徽歙县，后居苏州嘉定（今属上海）。万历三十四年举人，明代诗人、书画家、篆刻家，与程嘉燧、唐时升、娄坚并称“嘉定四先生”，著有《檀园集》《西湖卧游图题跋》等。李流芳早年致力于科举，万历三十四年（1606）中举后屡试不第，天启二年（1622）因会试受阻弃仕返乡，建檀园隐居。其诗文主张抒发性灵，风格自然平易；书法取法苏轼，笔致瘦劲；山水画融合宋元技法，注重写生，代表作《吴中十景图》以实地风景入画。篆刻师承文彭流派，刻作见于《中国闲章艺术集锦》。晚年与董其昌等人合称“画中九友”，崇祯二年（1629）病逝于檀园。所建檀园后毁于清初战乱，2011 年在南翔老街重建开放。伯兄**李元芳**，字茂初，诸生。子**李杭之**，字僧筏。诗文书画有父风，性放旷，放浪山水间，乙酉死难。
77. /李宜之/ （1575-1656 前），字缁仲，名芳子，明代画家，嘉定（今属上海）人，李流芳之侄。世居南翔，家有漪园，乱后寓居候氏东园，以寓园名其集。其画承家法，曾参与刊定吴伟业《秣陵春》传奇，该作于顺治十年（1653）秋前后刊刻。竹刻家朱稚征曾为其私家园林古猗园擘画设计。崇祯十七年（1645 年）六月，嘉定奴仆起义期间，李宜之因滞留南京幸免于难，其家族因拒交奴仆身契遭灭门，全家遇害于南翔猗园南厅，该事件致南厅得名“难厅”。清世祖曾询问寓园主人姓名，吴伟业以李宜之对，而彼时李宜之已去世。生平事迹见于清光绪六年《嘉定县志》卷十九。尝作《哭修微》绝句百首。
78. /李杭之/ （？—1644）字僧筏，明代诗人李流芳之子，祖籍歙县。其书画承袭家学精髓，山水画取法黄公望，以苍劲松秀的笔法与萧疏静穆的意境著称。安徽博物院藏有其 1640 年所作《溪山访友图》，画作融合枯笔淡墨技法与黄公望画意，题款及印章保存完整。明末嘉定诸生张鸿磐曾以"小李风流继阿翁，萧疏笔墨见心胸"评述其艺术造诣。
79. /张鸿磐/ ，字子石，嘉定人。崇祯朝诸生。
80. /唐时升/ （1551 年-1636 年），字叔达，号灌园叟。嘉定（今属上海）人。中国明代文学家。唐时升幼年丧父，常在叔父唐叔训身边从学，以异才名，博览群书，精研六经，尤得王世贞常识。其有强烈的经世济民之志，早年曾赴乡试，屡蹶于时，未到 30 岁便弃举子业，安居乡里，读书汲古。晚年闭门止酒，味庄周、列御寇之微言，常与娄坚、程嘉燧布衣杖屦，外出游玩，三人谈诗论文，不染尘俗，被称为“练川三老”。崇祯九年（1636 年），无疾而终。唐时升与里人娄坚、程嘉燧、李流芳并称“嘉定四先生”，受归有光遗风之沾溉，被视为归有光所开创的“嘉定文派”的有力接续者。其诗最为人所称道的乃咏物七言律诗，以《咏雁字二十四首》与《和沈石田先生咏落花》诸篇为最。前者语言通俗，形象生动，善于捕捉稍纵即逝的情趣，不拘于模拟而自然工整，后者感情真挚细腻，颇为动人。其著有《三易集》20 卷。
81. /娄坚/ （1554 年-1631 年），字子柔，一字歇庵。其曾祖由长洲迁至江东（今上海市浦东新区高桥镇）又迁至嘉定城内。 中国明代诗文作家，书法家。 娄坚为隆庆、万历年间贡生，幼年好学，早从归有光游，为乡里所重，推为大师，与 /唐时升/ 、 /程嘉燧/ 并称“练川三老”。万历三十二年（1604 年），嘉定马元调从娄坚学文，四明谢宾山为知县时尝将唐时升、程嘉燧、李流芳及娄坚诗刻之，曰《嘉定四先生集》。娄坚卒于崇祯四年（1631 年）。 娄坚著有《吴歈小草》10 卷、《学古绪言》25 卷。在各体诗的创作中，较善于古体。其古体诗能刊落浮嚣，直率地抒发自己的情愫，生发自己的议论，清雅和畅。 能文，深受唐宋派的影响著有《长庆集序》《缑山先生集序》等，运笔虽欠劲健，但有迂纡畅达的特点。
82. **汪明际**（？—？），字无际，号雷庵，一字雪庵，明代嘉定人。早年孤苦力学，以孝侍母闻名，博涉经史，尤精《周易》。万历戊午（1618 年）中举人。初授寿昌教谕，后历国子监学录、都察院司务、工部营缮司主事，晋员外郎，督修京仓。后以疾告归，因同官接管误工被杖死。汪明际在嘉定建有名园垫巾楼，该楼为其所辟，位于辅文山后，积谷仓前，成为程嘉燧、宋珏等辈觞咏之所。其山水画作笔意苍凉萧散而风格秀逸，友人郑胤骥曾为《茸游册》题诗，赞其诗作“幽响清磔磔”“下笔妙言语”，画作能摭取胸中丘壑。该册记录其湖山游历之胜情，反映文人交游与艺术创作活动。著有《遨仙阁集》《陶斋佚稿》《羲经翼》《性理会通》等文集。
83. **宋珏**（1576—1632），字比玉，号荔支子、浪道人、国子仙，福建莆田人，明代诗人、书画家。国子监生，工书画篆刻，山水画师法米芾、黄公望、吴镇，用笔苍老秀逸，不拘于法，兼善画松，篆刻开创"莆田派"，以八分书入印突破传统。早年游历金陵、吴越，结交顾梦游、谭元春等文人，创作以摹仿写生为主，绘有《山楼对雨图》。晚年寓居南京，山水画转向写意风格，代表作品《松阴晓霭图》《亭皋落木图》藏于北京故宫博物院。其隶书取法汉碑，刻有蔡襄《荔枝谱》《古香斋帖》。崇祯五年（1632）卒于南京，归葬莆田梅陇山麓。
84. **孙致弥**（1642—1709），原名翔（或做翽 hui4），字恺似，又字松坪，孙元化之孙。八都人（今属高桥地区）。家贫好学，才情藻逸，尤长于诗。清康熙十七年（1678 年）游都门，遂以国学监生假二品服，为朝鲜副使，购藏书，辑其国人诗为《采风集》。是年，中顺天乡试。二十七年（1688 年）成进士，选庶吉士。以蠲漕议，几狱。阅十年复职，四十一年（1702 年），典试山西，授编修。寻充《佩文韵府》总裁，历官至翰林院侍读学士。其纂修勤且久，考核详慎，书垂成而卒，年 68。致弥慷慨乐易，好奖掖后进。书法逼似董其昌，诗词跌宕流逸，与陆元辅、赵俞、张云章、张大受、张鹏翀称六君子。累官至侍读学士。致弥工于诗，兼善书法。稿巳散佚，张鹏翀得其写本，选为祆左堂集六卷，续集三卷，及词四卷，（均清史列传）刊行于世。
85. /李成栋/ （？-1649 年 4 月 6 日（永历三年二月乙卯）），字廷桢，号虎子，宁夏人，陕西宁夏卫军籍，明末清初将领。 李成栋少时跟随李自成部下高杰为盗，号“李诃子”，后随高杰归附明朝，累官总兵，驻守徐州。弘光元年（1645 年），清朝豫亲王多铎和张存仁征江南，李成栋率所部剃发投降清朝，并跟随清军攻打浙江、福建、广东，制造嘉定三屠，擒杀南明绍武帝朱聿鐭，杀害抗清大臣陈子壮、张家玉（与陈邦彦并称“岭南三忠”）。顺治四年（1647 年），授广东提督，加左都督衔。顺治五年（1648 年）正月，李成栋与清朝两广总督佟养甲不合，聚众反清归明，封惠国公。顺治六年（1649 年），李成栋出兵江西，兵败坠水而死。
86. **邓汉仪**（1617—1689），字孝威，号旧山，原籍吴县洞庭之绮里，清初诗人、诗歌评论家。他早年为明末诸生，加入复社。顺治元年（1644）为避祸迁居泰州，从此绝意仕进。康熙十八年（1679）举博学鸿词，因年老授中书舍人归籍。迁居泰州后以吟咏为事，成为当地诗坛领袖，交游广泛。他倾注毕生精力编选《诗观》，这部诗歌总集共三集四十一卷，选评了 1824 人的 15000 余首诗，阮元称其“与太仓吴梅村主盟风雅者数十年”。
87. /归庄/ （1613 年 8 月 29 日－1673 年 10 月 1 日），字尔礼，又字玄恭，号恒轩，苏州府昆山县（今属江苏）人。明末清初书画家、文学家，明代散文家归有光曾孙，书画篆刻家归昌世季子。早年与顾炎武并称“归奇顾怪”，参与复社活动。清顺治二年（1645 年）参加昆山抗清起义，兵败后削发为僧，自号归藏、鏖鏊钜山人等。晚年隐居乡里，以卖书画为生，拒仕清廷。归庄崇祯十三年（1640 年）辞官不就，弘光元年（1645 年）率众参与昆山抗清，城破后被指名搜捕，亡命他乡，后潜返乡里削发为僧。顺治九年（1652 年）北上淮阴联络抗清势力，后返乡安葬家族遗骨并筑庐守墓。康熙十二年（1673 年）编刻《归有光全集》期间病逝。其诗文多抒反清复明之志，《万古愁》曲以抨击时政著称，书法狂草与墨竹作品被《桐阴论画》列为神品，传世著作有《归玄恭文钞》《玄弓》《恒轩》等。曾作《历代遗民录序》区分遗民与逸民，强调“忠于先朝而耻仕新朝”的立场。
88. **郑澍若**，字醒愚，别号玉缠人，福建闽县玉田（今长乐市玉田镇）人，清代文学家**郑方坤**之孙，郑天箓（一作郑天鋂）之子，秀才，著有《虞初续志》十二卷。主要活动于乾隆、嘉庆年间。《虞初续志》为郑澍若所编短篇小说集，成书于嘉庆七年（1802 年），承接张潮《虞初新志》体例，收录真人真事为主的奇异故事。该书第十二卷《郭猫儿》一文，详细记述了口技艺人郭猫儿表演杀猪场景的全过程，通过鸡鸣、饲猪、宰杀、售卖等声效的精准摹写，展现其口技之精妙。该篇与张潮所编《虞初新志》相似，采用小品文笔调描述超常技艺，具有鲜明的情节特征。
89. **杜濬**（1611～1687），又作“杜浚” ，明末清初诗人。原名绍先，字于皇，号茶村，又号西止，晚号半翁。湖北黄冈人。明崇祯时太学生。明亡后，不出仕，避乱流转于南京、扬州，居南京达四十年，刻意为诗，诗多寓兴亡之感。年七十七，卒于扬州。著有《变雅堂集》。
90. **罗振玉**（1866 年 8 月 8 日—1940 年 5 月 14 日），初名宝钰（振钰），字式如、叔蕴、叔言，号雪堂，晚号贞松老人、松翁，亦号刖存。祖籍浙江省上虞县永丰乡，出生于江苏淮安，中国近代考古学家、古文字学家、金石学家、敦煌学家、目录学家、校勘学家、农学家、教育家、汉奸。“甲骨四堂”之一。罗振玉于清末奉召入京，任学部二等谘议官，后补参事官，兼京师大学堂农科监督。宣统三年（1911 年）辛亥革命爆发，与王国维等避居日本，从事学术研究。民国十三年（1924 年）奉溥仪之召，入值南书房。九·一八事变后，参与策划成立伪满洲国，并任多种伪职。民国二十九年（1940 年）5月 14 日，罗振玉在旅顺逝世，终年 74 岁。罗振玉对中国的科学、文化、学术颇有贡献，他参与开拓中国的现代农学、保存内阁大库明清档案、从事甲骨文字的研究与传播、整理敦煌文卷、开展汉晋木简的考究、倡导古明器研究。书法善篆、隶、楷、行，是创以甲骨文入书者之一。所作小行楷题跋精严工稳。曾搜集和整理甲骨，铜器、简牍、明器、佚书等考古资料，均有专集刊行。他以学术的眼光发现挖掘中国传统文献，并以科学的方法进行整理，刊布流传，其功大焉。罗振玉一生著作达 189 种，校刊书籍 642 种。编著有《殷墟书契》《敦煌石室遗书》《鸣沙石室佚书》《敦煌古写本周易王注校勘记》《鸣沙石室古籍丛残》等。
91. **李桓**（1827 年-1892 年），字叔虎，号黻堂，一号辅堂，湖南湘阴（今汨罗）人。李星沅第三子。作品有：《国朝耆献类征》七百二十卷，《闺媛类征》十二卷。《宝韦斋类稿》，含《奏疏》四卷，《官书》二十四卷，《尺牍》四十八卷，《甲癸梦痕记》六卷补遗二卷，《明论》四卷；《诗录》二卷；《文录》三卷；《宾退纪谈》七卷。《浙游百卅律》一卷，《影言》一卷，《悼亡小草》一卷，《海南军次秋兴二十四首》一卷，《两髯提倡集》一卷。《汪莼家传》一卷。《海粟楼书目》。
92. **章有谟**字载谋，生于湖南永州，当时章旷已卒数月，故章有谟为遗腹子。其母吴氏，将其抚养成人。章有谟回故乡华亭后，隐居于佘山，勤于学问，却不愿出仕为官。曾寓居张泽姻亲蒋氏宅，与蒋麟等唱和，著有《礼说》《景船斋杂记》二卷。其子章继绪，字重光，又字绍庭，康熙五十六年(1717)中举人，雍正五年(1727)中进士，历任山东章丘、栖霞、利津知县，官声甚佳。在利津任上时，建义学七所，并仿松江府学教授陆在新的方法，设引年会，凡诸生年六十以上者，每年给银六两，七十倍之，八十又倍之，其敬老崇教如此。
93. **钱孙爱**（字孺饴），清代江苏常熟人，钱谦益之子，著有《钱氏家变录》。顺治四年（1647 年丁亥岁），钱谦益因案被捕押解金陵，钱孙爱因年幼无力营救。钱谦益在狱中写下“恸哭临江无孝子”诗句，钱孙爱担忧此句引发非议，遂托人请求修改原诗，最终刻本将“孝子”改为“壮子”。
94. **钱肇鳌**（字尧光，号钝夫），嘉定钱氏人，诸生，卒年七十。他是一位善于文章、好聚异书的学者，晚年致力于研究易理，手著有《大成集》八卷，尚未完成即去世。此外，他著有《质直谈耳》，钱大昕为之作序，称其为“吾弟”。
95. **钱大昕**（1728 年 2 月 16 日－1804 年 11 月 2 日），字晓征，又字及之，号辛楣，晚年自署竹汀居士，江苏太仓州嘉定县望仙桥河东宅（今属上海市嘉定区外冈镇）人。清代史学家、文学家、教育家，乾嘉学派代表人物。被誉为“中国十八世纪最为渊博和专精的学术大师”。钱大昕早年以诗赋闻名江南。乾隆十六年（1751 年），因向乾隆帝献赋被提督学政庄有恭选为一等。后在召试中被评为一等，特赐举人，授内阁中书学习行走。乾隆十九年（1754 年）三月，中进士，经御试后改翰林院庶吉士。其后历任翰林院编修、右春坊右赞善、武英殿纂修官、功臣馆纂修官、詹事府少詹事，提督广东学政。期间还出任过会试同考官及山东、湖南、浙江、河南等地乡试考官。乾隆四十年（1775 年），因父丧归里，从此引疾不仕。归田三十年，潜心著述课徒，历主钟山、娄东、紫阳书院讲席，出其门下之士多至二千余人。嘉庆九年（1804 年），于苏州紫阳书院逝世，享年七十七岁。钱大昕是 18 世纪中国渊博和专精的学术大师，其学以“实事求是”为宗旨，其治学范围广博精深，在史学、经学、小学、算学、校勘学及金石学等学术领域，均有建树和创见。有《十驾斋养新录》，后世以之与顾炎武《日知录》并称。一生著述甚富，后世辑为《潜研堂丛书》刊行。
96. **陈盟**（1584—1661），字无盟，号雪滩、雪斋、雪公，四川富顺人。万历四十年（1612）壬子科举人，万历四十五年（1617）任新安教谕，天启壬戌（1622）进士。选翰林庶吉士，历官翰林院检讨、国子监司业、经筵讲读、吏部左侍郎。金陵变后为僧，名德藏，号雪公。工书，黄道周称其类赵文敏（赵孟頫，谥文敏）。以文学风雅名于时，著有《三朝纪略》《雪斋诗集》。
97. **陶谷**（902 年-970 年），本姓唐，字秀实，邠州新平（今陕西彬州市）人，北宋大臣。陶谷在后晋时为知制诰。天福九年（944 年），加仓部郎中。后以言忤兖帅安审信坐责授太常少卿，嗣拜中书舍人。契丹主北归，威胁陶谷从行，陶谷逃匿，遂归后汉为给事中。后周时先为右散骑常侍，世宗即位累迁户部侍郎、兵部侍郎。显德六年（959 年），加吏部侍郎。入宋后先转礼部尚书，依前翰林承旨。后加刑部、户部尚书。开宝三年（970 年），陶谷卒。陶谷强记嗜学，博通经史，善隶书，喜蓄法书名画。精通礼制，主持制定南郊祭天制度。然因其奔竞务进，多忌好名，被宋太祖所鄙视，始终未得重用。《宋史》有传。《宋史·艺文志》著录《陶谷集》十卷，今未见。《补五代史艺文志》《四库全书总目》著录《清异录》，传为陶谷所作。
98. **李清**（1602 年－1683 年），字心水，号映碧，南直隶扬州府兴化县（今江苏省泰州市兴化市）人。天启年间中举，明崇祯四年（1631 年）进士，授宁波府推官，历任刑科、吏科、工科给事中，南明弘光时官至大理寺左寺丞。早年任宁波府推官期间多平反冤案，判词注重证据梳理与法理阐述。崇祯十一年任刑科给事中时奏请追谥前朝忠谏之臣，后因忤旨降职。弘光政权期间屡陈抗清方略未果。清军南下后隐居兴化枣园三十八年，拒绝清廷征召。晚年潜心著述，撰有《南渡录》《三垣笔记》《折狱新语》等史学及司法文献，记录明代司法制度与南明史事。每逢崇祯帝忌日必行哭祭，终未仕清。
99. **翁同龢**（1830 年 5 月 19 日—1904 年 7 月 4 日），字声甫，一字均斋，号叔平，又号瓶生，晚号松禅老人，江苏常熟人。中国近代史上著名的政治家、书法家、收藏家。翁同龢是体仁阁大学士翁心存之子。咸丰六年（1856 年）状元及第。此后历仕咸丰、同治、光绪三朝，历任翰林院修撰、陕西学政、文渊阁校理、翰林院赞善、詹事府右赞善、右春坊右中允、右春坊右庶子、太仆寺卿、内阁学士、署理刑部右侍郎、户部右侍郎、都察院左都御史、刑部尚书、工部尚书、户部尚书、协办大学士等职，其中任户部尚书最久，达十余年。在此期间，他曾充当同治帝和光绪帝的师傅，并两入军机处，参与内政外交的决策。他尤其在甲午战争中坚决主战，被视为“帝党”的代表、晚清清流派中“后清流”的领袖。甲午战败后，他主张变法图强，并于光绪二十四年（1898 年）起草“定国是诏”，拉开百日维新的序幕。但不久即被勒令开缺回籍，百日维新失败后被革职编管，永不叙用。光绪三十年（1904 年），翁同龢去世于常熟虞山，享年七十五岁。宣统元年（1909 年）开复原官，中华民国三年（1914 年）由逊帝溥仪赐谥号“文恭”。翁同龢擅长诗文和书画，尤其在书法上有很高的造诣，清代杨守敬在《学书迩言》中说：“同龢，同治、光绪间，推为天下第一，询不诬也。”遗著有《翁文恭公日记》《瓶庐诗稿》等，被今人整理为《翁同龢集》。
100. **方岳贡**（1597 年—1644 年），字四长，号禹修，湖广谷城人。明朝末年大臣。方岳贡于明天启二年（1622 年）中进士，授户部主事，进郎中。历典仓库，督永平粮储。崇祯元年（1628 年），出为松江知府，筑防海堤有功。后累迁户、兵二部尚书兼文渊阁大学士，总督漕运、屯田、练兵诸务。李自成攻陷京师后，方岳贡自缢而死。著有《古文国纬集》等。
101. /蔡澄/ （？—1645 年），字嗣清，福建漳州府龙溪县人，明朝、南明政治人物。蔡澄是万历四十年（1612 年）的举人，到天启五年（1625 年）成进士，其时魏忠贤得势，他不愿意依附，同时自己的双亲年老，于是提出试任南京官职，方便给假省亲，是明朝第一位于南京选任实习的进士。崇祯初年，蔡澄补任职方主事，迁员外郎，外任肃州佥事。当地边防紧急，军事文书传递迅速。他就重视斥候，核查军籍，多方防御，有事攻守同时进行，多次打胜仗，转任湖广参议。杨嗣昌因为夺情被黄道周与何楷弹劾，在剿灭楚地寇匪时获赐尚方剑；得知蔡澄是黄道周同乡，又是何楷姻亲，因此很是怨恨他，令人窥视他的错误，但多年无所获。陈睿谟看重他的才能，让他带兵平定苗族叛乱，改官广西副使。巡按李仲熊是蔡澄门下士，得知北京危急，向各部队征召入朝支援，蔡澄提供粮饷资助。不久北京被攻陷，李仲熊离开，他日益孤立。弘光帝即位，调任蔡澄到岭东，擢任参政，隆武初年在任内去世。（案：貌似非«鸡窗丛话»之蔡澄，此澄字练江，清人。）
102. /陈作霖/ （1837－1920），字雨生，号伯雨，晚号可园，江苏南京人。 清末举人，历任崇文经塾教习、奎光书院山长（校长）、上江两县学堂堂长，为南京地方史志学家、著作家、藏书家。陈作霖出身科举世家，光绪元年（1875）中举后专注教育及史志编纂。同治十三年（1874）参与纂修《上江两县志》，提出“修志乘以耸民听”的史志理念。编纂《金陵通纪》《金陵通传》收录金陵人物三千余，与甘元焕合编《国朝金陵文征》《金陵诗续征》《金陵琐志五种》等地方文献集。晚年主持《江苏通志稿》编纂，完成《江苏兵事纪略》《古迹志》等篇目。其藏书楼“冶麓山房”藏三千余卷文献，编纂《上元江宁乡土合志》系统记录南京风土人情。故居可园现存于南京安品街。
103. **葛万里**（字翊甫，号梦航）出身昆山望族，其家族与徐乾学家族有姻亲关系。此外，葛万里著述不止于此，其《葛万里杂著》十二种十九卷（清初刻本）包含《明人同姓名录》、《梦航杂缀》、《牧翁先生年谱》等多种著作。昆山葛氏家族勤于著述，葛万里与葛芝是家族中著述最为出色者之一。《别号录》在宋代徐光溥《自号录》基础上扩展，钱曾《读书敏求记》记载的孙道明抄本为重要参照。编纂时正值别号文化鼎盛的康熙年间，葛氏提出"别号盛于南宋，滥于明"的论断被四库提要采纳。
104. **范骧**(1608～1675)，清初书法家，字文白，号默庵，海宁人，以品格高洁闻名。清朝建立后，地方上推举他为贤良方正，坚辞不就。有《点庵集》《昭代尺牍小传》问世。
105. **王士禄**（1626 年-1673 年），字子底，一字伯受，号西樵山人，山东新城（今桓台）人。清初官员、诗人。王士禄于清顺治九年（1652 年），中进士，选莱州府教授，迁国子监助教，官至吏部员外郎。康熙二年（1663 年），充任河南乡试主考官。第二年，磨勘时遭非议而入狱。历时半年才得以昭雪，被免官归乡。数年后，以原官起用。不久，又被罢免。康熙十二年（1673 年），因母亲去世，王士禄哀伤过度而死。王士禄年少时即能文，尤工诗，曾以诗法教授弟士祜、士禛，兄弟三人并驰名诗坛，号为“三王”。士禄的诗十之八九是山水纪游、登临怀古和酬答友人之作，很少反映社会现实的篇章，在艺术上宗法孟浩然。著有《表余堂诗存》2 卷、《十笏草堂诗选》9 卷、《辛甲集》7 卷、《上浮集》2 卷、《炊闻词》2 卷。此外，还著有《读史蒙拾》《然脂集例》等。
106. **徐沁**，字野公，号委羽山人，会稽(今浙江省绍兴市)人。活动于明末清初。著有《明画录》、《谢皋羽年谱》等。
107. **张廷棫**，字子薪，兵部郎楙族子。工诗文，与**李孝廉流芳**、**程山人嘉燧**为友。族孙**崇儒**，字鲁生，筑招隐亭，名流多过从觞咏，风致可想见云。
108. **俞正燮**（1775 年 10 月 1 日－1840 年 5 月 13 日），字理初，安徽黟县人，清代学者。道光元年（1821 年）中举人，三次会试未第，以佣书校勘为业，参与编修《大清会典》《黟县志》《两湖通志》等二十余种官私典籍。治学涉猎经史、天文、舆地，代表作为《癸巳类稿》、《癸巳存稿》，其中《节妇说》《贞女说》质疑传统贞节观，主张恢复先秦儒家女性礼制地位。俞正燮二十余岁谒孙星衍时撰《左丘明子孙姓氏论》成名，曾校正杨芳《六壬书》、校订《读史方舆纪要》，协助编纂《续行水金鉴》等近二十种著述但多不署名。早年家贫，佣书为生，足迹遍及南北，曾为张井、林则徐等官员编校书籍。晚年主讲江宁惜阴书院，藏书七万卷于四养斋，卒时家无余财。其考据学成果涵盖边疆史地、赋税制度等领域，主张男女平权思想。
109. /侯峒曾/ （1591～1645） 字豫瞻，一字广成，居诸翟（今属上海县）。明天启五年（1625）进士，授南部武选主事。后改南方文选主事，迁浙江右参政，分守嘉兴、湖州两府。侯峒曾为人耿直，有才干。吏部尚书郑三俊推举天下官吏贤能者五人为监司，他是其中之一。任南部武选主事时，与**徐石麒**、**陈洪谧**被誉为“南部三清”。清乾隆年间追谥为“忠节”。有《侯忠节公全集》。侯峒曾好诗文，能书法，曾任浙江参政。万历四十六年（1618 年），侯峒曾中举人，天启五年（1625 年），中进士，除南兵部武选司主事，未到任，丁父忧归。崇祯七年（1634 年），以兵部尚书张凤翼荐，补职方郎中，辞不就，改南吏部文选司主事，历稽勋司郎中。崇祯十一年（1638 年），侯峒曾出为江西右参议，提督学政。崇祯十六年（1643 年），迁浙江右参政，分守嘉湖道，寻召为顺天府丞，未赴而值甲申鼎革。福王时起为左通政，旋不满于时局累卵之际众官倾轧，辞官归里。清兵南下。明弘光元年（1645 年），侯峒曾散尽家财，聚义兵数千据嘉定城御清兵，至七月初四城被攻陷，侯峒曾偕二子赴水，气未绝而被清兵引出杀害，终年五十五岁。子侯元瀞为其撰《年谱》。
110. /郑三俊/ （1574 年 3 月 14 日－1656 年 7 月 31 日），字用章、伯良、中一，号玄岳，晚号巢云、隐庵，南直池州府建德县（今安徽省池州市东至县）人（故亦称建德公），明朝末年官员。  万历二十六年（1598 年）进士，授元氏县知县。累迁南京礼部郎中、归德府知府、福建提学副使。天启初，召为光禄寺少卿，陈中官侵冒事。魏忠贤乱政，三俊疏斥阉党祸国，语侵内阁。擢左佥都御史，疏陈兵食大计，抗疏救吏部郎徐大相。杨涟劾忠贤，三俊亦上疏极论，寻引疾去，竟褫职闲住。崇祯初，起南京户部尚书兼掌吏部，主持京察尽汰阉党遗孽。南粮积逋数百万，三俊力祛宿弊，士得宿饱。芜湖等三关司官贪黩，悉劾罢。移吏部，京察斥 78 人，朝野服公。流寇扰江北，数陈防御策，疏救侍郎陈子壮。擢刑部尚书，清理积狱，奏定决囚期限，释诖误诸臣。以拟侯恂、工部案轻典触帝怒，下狱。徐石麒等力救，得释候讯。十五年（1642 年），复故官，代李日宣为吏部尚书。值考选，帝欲亲擢夤缘者，三俊力谏："考选乃部院职，天子不得专。"忤旨。举李邦华、刘宗周自代，荐黄道周、史可法等。救姜埰、熊开元等诸直臣，奏罢不职司官，起用废斥贤士。惟徇周延儒请，调吴昌时掌文选，违制遭劾。与昌时黜言官十人，舆论哗然，遂引咎乞归。京师陷，家居十余年卒。 郑三俊为人端严清亮，正色立朝，抗魏阉、力救直臣，掌铨选则荐贤任能；虽起用吴昌时一事颇受争议，终白璧微瑕。后人辑有《巢云老人焚余集》。
111. /徐石麒/ （1577 年—1645 年），初名文治，字宝摩，号虞求，浙江嘉兴人。天启二年（1622 年）进士，授工部营缮司主事，因得罪魏忠贤，被削籍。崇祯三年（1630 年）恢复原职，官至刑部尚书，因忤崇祯帝意，落职闲住。南明弘光政权建立，召拜右都御史，改吏部尚书，为马士英等所扼，郁郁不得志，乞归。清兵下江南，嘉兴城陷，自缢死。隆武帝时，赠少傅、文渊阁大学士，谥“忠襄”。鲁王监国时，赠太师。
112. **徐康**（1814—约 1888），字子晋，号窳叟，江苏苏州人，晚清学者、藏书家。工诗、画、篆、隶、刻印，精于鉴别书、画、金石。少为诸生，曾作幕僚，交游颇广。著有《前尘梦影录》，记录所见文房珍品；另著《神明镜诗》等。光绪年间与吴昌硕探讨金石。批注《聊斋志异》，完成于光绪十二年(1886 年)。
113. **沈宏祖**，字彦深，高才博学。崇祯壬午奉文改兑漕米，申茎芳等赴阙上书，疏出宏祖手。尝佐有司赈荒，民得实惠。（《嘉定县志》）
114. /周延儒/ （1589 年/1593 年—1644 年 1 月 17 日），字玉绳，号挹斋，南直隶常州府宜兴县（今江苏省宜兴市，秦汉时称阳羡）人。明朝末年大臣，崇祯年间的内阁首辅之一。周延儒自幼聪颖，万历四十一年（1613 年）连中会元、状元，历任翰林院修撰、右中允、左庶子、少詹事、正詹、礼部右侍郎等职。他善于迎合崇祯帝旨意，于崇祯二年（1629 年）十二月以礼部尚书兼东阁大学士，进入内阁。翌年二月加太子太保衔，改任文渊阁大学士，九月升任内阁首辅，加少保衔，进武英殿大学士。崇祯五年（1632 年）二月加少傅兼太子太傅，改吏部尚书，进建极殿大学士。期间与同僚温体仁倾轧，崇祯六年（1633 年）六月因被言官陈赞化揭露曾私下称崇祯帝为“羲皇上人”而辞职。崇祯十四年（1641 年）九月再任内阁首辅，翌年七月进少师，升为中极殿大学士。他复出后，推翻温体仁主政时的弊政，笼络人心，并重新获得崇祯帝的信任。但同时也倚靠吴昌时、董廷献等亲信，结交内侍，收受贿赂，加剧了朝政的腐败。崇祯十五年（1642 年）冬，清军第六次入塞大掠，翌年四月，周延儒自请督师堵截撤退的清军，但他不仅没有认真堵截，还不断谎报军情。五月还朝后，崇祯帝欲加封他为太师，但其督师期间的行径随即由锦衣卫都督骆养性等密告于崇祯帝，因而被勒令致仕回乡。不久，雷縯祚、郝䌹、蒋拱宸等揭发其招权纳贿、结交内侍，触怒崇祯帝，周延儒被再召至京师，于崇祯十六年十二月（1644 年 1 月）赐死。清修《明史》将他列入“奸臣传”。
115. **徐乃昌**（1869-1943），字积余，号随庵老人，安徽南陵人，中国近代藏书家、学者。出身官宦世家，伯父徐文达曾任两淮盐运使，堂兄徐乃光为驻美外交官。光绪十九年（1893 年）中举，历任淮安知府、江南盐巡道，光绪二十八年（1902 年）赴日考察学务，归国后总办江南高等学堂，1905 年督办三江师范学堂（南京大学前身）。清亡后潜心藏书与古籍校刊，建有积学斋藏书楼，藏宋元刊本 10 余种，刊刻《积学斋丛书》《随庵丛书》等 560 余卷典籍，其夫人马韵芬曾影写丁氏八千卷楼藏元刻本《阳春白雪》，书后附刻黄丕烈三跋。民国三年（1914 年）主编《南陵县志》，首创金石志四卷，参与编修《安徽通志》《上海通志》，晚年主持《安徽丛书》。1934 年南陵大旱期间四出募捐，从安南购米赈济灾民。其藏书多存于安徽、南京等地图书馆，其中《玉台新咏》校刊本现存于图书馆，现存《徐乃昌日记》及近千封往来书札为研究史料。藏书印有“积学斋镇库”“南陵徐乃昌审定善本”“十万琳琅阁珍藏”等。
116. /黄丕烈/ （1763—1825），字绍武，一字承之，号荛圃，绍圃，又号复翁、佞宋主人、秋清居士、知非子、抱守主人、求古居士、宋廛一翁、陶陶轩主人、学山海居主人、秋清逸叟、半恕道人、黄氏仲子、民山山民、龟巢老人、复见心翁、长梧子、书魔、独树逸翁等。江苏苏州人，清代藏书家、目录学家。有藏书室士礼居、百宋一廛、陶陶室等。年少读书，务求精纯，所作文章，必以六经为根柢。19 岁时补学官弟子，乾隆五十三年（1788 年）中举，后屡应会试不果，遂无意科场。嘉庆六年（1801 年）擢为直隶知县，不愿就职，援引旧例任户部主事，不久弃官归里，杜门著述、校书。平生博学多闻，惟好收聚典籍。其藏书之丰富，为当时东南巨擘，且多精本、善本，尤重宋版；长于校勘。 黄丕烈从二十多岁开始藏书，一直到他去世，共收藏了大约二百多部宋版书和上千种元、明刻本及大量的旧抄本、旧刻本。 是清代“赏鉴派”藏书家的代表人物。
117. /朱承爵/ （1480—1527），字子儋，号舜城漫士，江阴（今属江苏）人，明代藏书家、刻书家。祖籍江西婺源，科举失利后潜心典籍收藏与校勘，藏书楼名“行素斋”“集瑞斋”“存余堂”，蓄藏宋元古籍、书画逾千件，以“悬金购书”著称，曾以爱妾换取宋刻《汉书》  。所藏《春秋集注》《唐女郎鱼玄机诗》等珍本后归曹寅、黄丕烈等递藏，部分今存国家图书馆。主持刊刻《浣花集》《樊川诗集》《黄太史精华录》等唐宋文集，注重版本考校，世称善本  。藏书钤“存余堂印”等鉴印，编著有《存余堂诗话》，提出“意境融彻”诗论观点，现存版本涉及《学海类编》等系统   。其鉴藏活动与江南文化关联密切，藏印、题跋及古籍流转脉络为研究明代藏书史提供了重要实证。
118. **闵麟嗣**，（公元 1628～1704 年），字宾连，号橄庵，徽州岩寺镇人（今安徽歙县）。著名明末清初学者、旅行家，以编纂《黄山志定本》著称。闵麟嗣生于歙县文人世家，主要活动于康熙年间。其代表作《黄山志定本》历经七年编纂，于康熙十八年（1679 年）撰成，康熙二十五年（1686 年）增补。该书分形胜、建置、山产、人物志、灵异、艺文、诗赋等七类，是存世黄山志书中最为完备、流传最广、影响最大的一部旧志。闵麟嗣采用实地勘察与文献考据结合的方法，首次系统整理黄山文献史料，考证黄山七十二峰位置，并完整保存了徐霞客“登黄山天下无山”的著名评价。他还著有《庐山集》《古国都今郡县合考》等地理文献，其中《黄山松石谱》新增棋枰松、困龙松等品种命名体系。《黄山志定本》成为后世研究黄山的重要依据，构建了黄山文化传承谱系。
119. **朱治憪**（？—？），字子暇，明末清初人物，曾受命总督两广。在广州失陷、桂王（永历帝）出奔时，他被任命负责防守肇庆。此外，根据相关记录，他亦有诗作《春星堂诗集》流传。
120. **蒋逸雪**（1902-1985），江苏建湖人。又名连城，文史研究专家。家道孤贫，笃志励学，学有所成。应聘执教于江苏省立第九中学，旋又至国史馆任编审，主要致力于经学、文学、小学研究。1956 年来扬州师范学院中文系任教，历任讲师、副教授、古代文学硕导，退评教授。著有《国学概论》、《张天如先生年谱》、《刘鹗年谱》、《南谷类稿》等，《南谷类稿》曾获江苏省哲学社会科学优秀成果奖。
121. **钱文选**（1874~1957），普名灿，字士青，自号诵芬堂主人，是五代十国吴越王钱镠三十二世孙。4岁丧父，16 岁丧母。光绪二十四年（1898 年）入安徽省立求是学堂，光绪二十九年（1903 年）被选送京师大学堂师范馆学习。光绪三十四年（1908 年）完成学业后，以七品京官任用。宣统元年（1909 年）任学部留学生襄校监视官，二年改任驻英留学生监督。在英期间，兼任伦敦万国人种大会和海牙万国修身大会的中国代表。他青年时代就具有富国强邦的志向，主张学习西方先进科技。曾向清政府提出中国发展飞机的倡议，并于宣统二年（1910 年）亲送厉汝燕进布里司厂学习飞机驾驶，培养了中国的第一个飞行员。民国 26 年（1937 年），钱文选任杭州红十字会会长，兼任浙江救济难民委员会常委。抗战爆发后，杭州沦陷前夕，他避居上海。日军多次威胁他回杭州任职，他严词拒绝。他也是个著书颇丰的作家，著有《美国制盐新法》、《钱氏家乘》、《钱武肃王功德史》、《诵芬堂文稿》、《英制纲要》等。钱文选一生谨奉家训，以行善为荣为乐。不仅在外做了很多贡献，还不忘回报他的家乡父老。民国十八年（1929 年），他捐资 600 元在家乡双溪上架起一座大木桥；又出资修筑广德至溧阳的松岭古道，解决了当时山北人民的运输困难，人们在山顶刻石铭记；民国九年（1920 年）又在松岭古道山脚下捐资千元创办士青小学，凡家乡贫困儿童免费入学，此后每年开支的数百元费用全由钱文选供给。1957 年病逝。
122. **吴绮**（1619 年-1694 年），字薗次（园次），一字丰南，号绮园、听翁，江苏江都（今江苏扬州）人，中国清代文学家，词人。顺治十一年（1654 年）拔贡生，荐授弘文院中书舍人，升兵部主事、武选司员外郎。康熙五年（1666 年）任湖州知府，任内惩治豪强、整顿吏治，因"多风力、尚风节、饶风雅"被称"三风太守"，三年后罢官未再出仕。其骈文与陈维崧齐名，代表作有《上龚大宗伯书》《董少君哀辞序》等。词作以《醉花间》"把酒祝东风，种出双红豆"闻名，获"红豆词人"雅号，陈廷焯评其词为"词中小品"；长调《岳坟次武穆原韵》等意境高远。诗作尤擅七古与律诗，宗尚李商隐、杜牧之风，文辞富艳而风调悠扬。著有《林蕙堂全集》《岭南风物记》，传奇《忠愍记》等三种已佚。晚年寓居扬州，自号"听翁"。
123. **闵尔昌**（1872—1948），初名真，字葆之，号黄山，晚号复翁，江苏江都（今扬州）人，秀才出身。历任袁世凯幕僚、北洋政府总统府秘书、内史监成员，1927 年辞任后任北京辅仁大学讲师。精研碑传之学，与袁克文等人结诗社，与方地山为好友、与董玉书结为儿女亲家。闵尔昌长期从事文史研究，参与编纂《清儒学案》，所编《碑传集补》历时十年，收录 810 余人传记，新增《使臣》《畴人》等类目。著有《雷塘词》，题写《勺湖款春图册》并作《登州府中学堂碑记》。抗日战争期间拒绝外出，保存武昌起义时期袁世凯与清廷往来函电。弟子卞孝萱继承其碑传拓片及信札文献。
124. /宋琬/ （1614 年-1673 年），清初著名诗人，清八大诗家之一，字玉叔，号荔裳，汉族，山东莱阳人。生于明万历四十二年（1614 年），清顺治四年（1647 年）进士，曾任户部河南司主事、吏部稽勋司主事、陇西右道佥事、左参政，康熙十一年（1672 年），授通议大夫四川按察使司按察使；翌年，进京述职，适逢吴三桂兵变，家属遇难，忧愤成疾，病死京都，时年 59 岁。宋琬的诗入杜、韩之室，与施闰章齐名，有“南施北宋”之说，又与严沆、施闰章、丁澎等合称为“燕台七子”。著有《安雅堂集》《二乡亭词》。
125. /施闰章/ （1618 年—1683 年），字尚白，一字屺云，号愚山，又号蠖斋，晚号矩斋。江南宁国府宣城县（今安徽省宣城市）人。明清官员、诗人。生于明神宗万历四十六年（1618 年），十八岁，考中秀才。早年游学于复社名士沈寿民及周镐门下。顺治六年（1649 年）进士，授刑部主事，官山东学政、江西布政司参议、分守湖西道。康熙六年（1667），归里。康熙十八年，召博学宏词，仅列二等第四名，充《明史》纂修官。康熙二十二年，任翰林院侍读。康熙二十二年（1683 年）卒。 施闰章与宋琬齐名，号“南施北宋”，又与严沆、丁澎等合称为“燕台七子”，其诗风“温柔敦厚，一唱三叹，有风人之旨”。张裕钊在《国朝三家诗钞》中，将郑珍和施闰章、姚鼐并列为清代三代诗人。蒲松龄在著作《聊斋志异》卷十《胭脂》一文中大加赞扬作他考官的施闰章。著有《学余堂文集》二十八卷、《学余堂诗集》五十卷、《学余堂外集》二卷等。
126. /黄毓祺/ （1579 年－1649 年），字介子、介之、介祉，号大愚，明末常州府江阴县（今江苏江阴）人。天启年间贡生，崇祯二年（1629 年）加入复社，主张革除阉党残余。崇祯年间曾与缪尊素等人成立“江上九子社” 。清顺治二年（1645 年）参与江阴抗清守城，与参将张宿、徽商程璧歃血同盟，任军政参谋。城破前潜出城外谋求援兵 ，后潜居通州湖荡桥。次年于舟山起兵再抗清，失败后逃至泰州一寺庙被捕  。囚于南京监狱，因不肯屈服而死（一说病死于狱中，死后被戮尸）  。被捕后曾因所作诗句被告发，在狱中坚贞不屈，作诗自比苏武明志，且未攀咬曾资助其抗清的钱谦益。遗著《大愚老人集》（或称《古杏堂集》）存世，收录其诗歌作品。民国十年（1921 年），江阴地方人士于黄梅禅院内为其设立专祠祭祀。
127. /邓大临/ ，字起西，号丹邱。明末清初江苏常熟人。孝廉出身。师事江阴黄介子繁祺。顺治二年（1645 年）江阴城陷，崇明事败，黄介子被捕入狱而死，死后戳其尸骨。大临于锋刃中赎其师首级，棺殓送归。时人称有有汉杨匡之风。后遍走江湖，欲得奇才剑客而友之，卒无报遇。顺治十八年（1661 年）访黄梨洲于双瀑院，后至武林，居玉皇山。张雪崖、顾石宾皆其道侣也。黄宗羲称大临之在玄门苦身持力，无异于全真教有死之心、无生之气，以其悲天悯人之故也。事迹详载于黄宗羲《南雷文定后集》中《邓起西墓志铭》。
128. /汪远孙/ ，（1789—1835）清代官吏、学者。字久也，号小米，又号借闲漫士，浙江钱塘人。生于清高宗乾隆五十四年，卒于宣宗道光十五年，年四十七岁。 （补疑年录作生于乾隆五十九年，卒于宣宗道光十六年，年四十三岁。此从清史列传）幼聪颖。十岁，侍祖父受经。嘉庆二十一年（1816）举人，官内阁中书。丁外艰，闻讣，疾归里。遂绝意进取，终居乡里，结社吟诗，文雅风流，冠冕全郡。惟肆力于著书、刻书、藏书。先世藏书之所曰“振绮堂”，插架夙多善本。他读尽家中所藏之书，又多方搜求，于家中建“水北楼”、“借闲小筑”藏书楼，临濒西湖，逢春秋佳日，焚香曝书。其家藏书自汪宪开始，历经**汪曰璐**、**汪汝瑮**、**汪諴**至远孙，“振绮堂”藏书，冠于浙右。龚自珍曾赋《杂诗》咏“振绮堂”藏书，有“振绮堂中万卷书，乾嘉九野有谁如”之句。编纂《振绮堂书目》、《借闲小筑藏书目录》。家有水北楼，著述之暇，与同里文人学士结“东轩吟社”，优游畅吟；时更登山临水，寄其旷逸之怀，乃自号“借闲漫士”。濒西湖春秋佳日，焚香读书以为常。暇与里中耆彦结东轩诗社。四方文士至，则觞咏楼中。喜刻书，先后刊刻有《咸淳志》、《临安志》、《辽史拾遗》、《东城杂记》，《左通补释》等。著《诗考补遗》，《汉书地理志校勘记》，《借闲生诗词》、《国语考异发正》、《三家诗考证》、《世本集证》等。远孙著有《清尊集》、《借闲生诗》三卷，词一卷，及《三家诗考证》、《世本集证》、《汉书地理志校勘记》等，均《清史列传》并传于世。
129. /陈乃乾/ （1896 年 9 月—1971 年 2 月），浙江海宁人，文献学家、编辑出版家，清代藏书家陈鳣（仲鱼）后裔。后任职于徐乃昌积学斋。 代表作品有《清代学术丛书》《周秦诸子斠注十种》《重订曲苑》《室名别号索引》《清代碑传文通检》。1916 年起任上海进步书店编辑，参与编印事务。1926 年任大东书局编辑、发行所长，兼任持志学院、国民大学教授。1930 年代在开明书店辑印《清名家词》，协调测海楼藏书收购案。1956 年调任北京古籍出版社，后转入中华书局，主持《永乐大典》《汉唐地理书钞》等古籍影印项目，参与点校《三国志》《旧唐书》。藏书积至万卷，建有慎初堂、共读楼，编有《共读楼藏年谱目录》等。
130. /周立勋/ （1597-1639），字勒卣，明末奉贤泰日湾人，周茂源之侄。自幼聪颖，与陈子龙、夏允彝等并称“云间五才子”，亦为“云间七子”之一。 崇祯二年（1629 年）与杜麟征、夏允彝、徐孚远、彭宾、陈子龙创立几社，合称“几社六子”（一说“云间六子”），年岁仅次于朱灏，受松江太守方岳贡器重。周立勋以太学生身份屡试不第，长期滞留南京国子监（南雍）。几社成立后，同人每月于夏允彝的花园浜、陆树德的南园、彭宾的春藻堂、周茂源的素园高会雅集，诗酒唱和，砥砺著述。其诗歌如《折杨柳歌》《再过淀山湖》《惜捐》《田家诗》等成一时传诵，文章《易论》亦被称道。崇祯十二年（1639 年）周立勋再次就试金陵，不幸客死他乡，时在明朝灭亡之前。陈子龙出钱葬之，并作《哭周勒卣》诗八章以悼念。   所作诗文多散佚，后由玄孙周京搜集整理为《符胜堂集》。其部分作品见于《几社壬申合稿》，该合集作者共十一人，周立勋位列其中。
131. /杜麟征/ （1607 年—1645 年），字仁趾，松江青浦县人，晚明官员、学者。几社六子之一。天启元年（1612 年），杜麟征中式辛酉科应天乡试举人，崇祯四年（1631 年）登辛未科进士。礼部观政，授刑部江西司主事，五年调兵部职方司，掌管章奏。丁忧去职。十年（1637 年）升职方司郎中，为尚书熊明遇所重，后丁母忧归乡，卒年三十九岁，着有《浣花遗稿》。崇祯二年（1629 年）与夏允彝、周立勋、彭宾、徐孚远、陈子龙等六人，在松江成立「几社」，社名的含义：“绝学有再兴之几，而得知几其神之义也”，称为“几社六子”。
132. /熊明遇/ （1579 年 8 月 8 日－1649 年 7 月 18 日），字良孺，一字子良，号坛石，江西南昌府进贤县（今江西省南昌市南昌县）人，明末清初政治家、科学家。  熊明遇弱冠中万历二十九年（1601 年）进士，授长兴县知县，有美政仁声。四十三年（1615 年）升兵科给事中，弹劾不避权贵，进“八忧五渐三无”疏极谏，外调福宁兵备佥事，升宁夏分守参议。天启元年（1621 年）回朝，累擢提督操江南京右佥都御史，借地震上“五不安”疏切谏，帝不省。齐庶人朱睿爁谋逆，计捕之，又设标兵，缮防务。章允儒唆傅櫆劾左光斗、魏大中，熊明遇与之，后以不附阉党，借汪文言案削籍，戍平溪卫，阉党败回籍。崇祯元年（1628 年）升兵部右侍郎，四年（1631 年）六月由左侍郎、南京刑部尚书累迁兵部尚书，仍主抚。监军宦官议设标兵，力阻之。吴桥兵变，熊明遇用职方郎余大成议招抚； 事败，仍一意孤行，李九成、孔有德假意议和，至炮毙、诱捕巡抚徐从治、谢琏，交章劾罢。十五年（1642 年）起南京兵部尚书，与李邦华檄止左良玉水军东下，议改工部，引疾归。明绍宗时，起户部尚书兼右都御史，因病辞，不久去世，私谥“文直”。熊明遇向传教士学习西方科学，推崇其天文历算之长，认为可补中国不足，主张"格物致知"探究万物规律，将格致之学视为《大学》治国平天下的关键，但坚持宇宙有"无始无终"的主宰者；所著《则草》传授方以智等，订补为《格致草》。另有《绿雪楼集》等，子熊人霖辑有《文直行书》。
133. /杜登春/ （？—？），字九高，号让水，一号姜翁。明朝几社领袖。几社创始人杜麟征之子。给事中张王治之婿。顺治八年（1651 年）拔贡，与夏完淳等组成“西南得朋会”，继承畿社。杜登春着有《社事始末》，说明当年几社创立的宗旨为“几者，绝学有再兴之几，而得知几其神之义也”，“昌明泾阳之学，振兴东林之绪。”。有《童心犯难集》。
134. **陆庆曾**，字子玄，一作文孙（见诸《复社姓名录》），明朝礼部尚书陆树声之孙。陆庆曾少时家资丰厚，精研医术，曾为李振邺治愈疾病。顺治十四年（1657 年）参加丁酉顺天科场考试时卷入科场舞弊案，初判斩立决后改流尚阳堡。流放期间因家境贫困，陆庆曾以行医维持生计。当时尚阳堡自然环境恶劣且医疗资源匮乏，陆庆曾在此地提供医疗服务。
135. **张国维**（1595 年 6 月 5 日－1646 年 8 月 9 日），字其四，号玉笥，晚号止庵，浙江金华府东阳县（今浙江省金华市东阳市）人，明末抗清名臣、水利专家。  张国维中天启二年（1622 年）进士，授番禺县知县，治绩有闻。崇祯元年（1628 年），擢刑科给事中，陈时政五事。历任礼科都给事中，太常寺少卿，崇祯七年（1634 年）升任右佥都御史，巡抚江南十府。任内大力兴修水利，疏浚河道，主持修建繁昌、太湖两县城池。崇祯十四年（1641 年）夏，升兵部右侍郎，监督四镇兵护漕，剿灭李青山起义。崇祯十五年（1642 年）九月，接任陈新甲为兵部尚书。崇祯十六年（1643 年），张国维因总督赵光抃螺山兵败被弹劾入狱。崇祯帝念其治河功释之，复原官兼右佥都御史，命往江南、浙江练兵筹饷。离京十日，京师陷。弘光政权建立，任兵部尚书，协理戎政，因受马士英等人排挤，辞归。弘光元年（1645 年），南京、杭州陷落，张国维支持鲁王朱以海监国，以方国安、王之仁的部队作为屏障，率军收复富阳、於潜等地，沿江修筑木城要塞，联合诸义军欲长期抗清。鲁监国元年（1646 年），因军饷断绝，众部溃散，鲁王败退台州后出海，张国维退守东阳县。清军到达，作赴义词三章，投园池殉节。乾隆朝赐谥“忠敏”。  张国维为人宽惠，得士大夫心，所辖百姓遇灾时能为民请命；抚吴六年，抵御起义军南下，使江南免遭战火；总理河道期间，疏通漕河、护理漕运，保证朝廷漕粮的供给。著有《抚吴疏草》《吴中水利全书》等，后人辑有《张忠敏公遗集》。
136. /马士英/ （1596.5.9~1646），字瑶草，一字冲然，贵州贵阳府人。明末大臣。 万历四十七年（1619 年）进士，授南京户部主事。天启时，迁郎中，历知严州、河南、大同三府。1632 年，累官右佥都御史，巡抚宣府。因擅取公帑行贿，坐遣戌，流寓南京。1642 年复起，任兵部右侍郎兼右佥都御史，总督庐州、凤阳等地军务。1644 年，拥兵立福王于南京，进东阁大学士兼兵部尚书，与高弘图、史可法并命。史可法出镇，督师淮、扬。 马士英的权力因为挟傀儡福王以令群臣的谋略被巩固和加强了，但也加速了新建立的南明朝廷的覆灭。1645 年，清兵连破南京、杭州，马士英往投唐王，不纳。乃入方国安军中，国安败，又欲投唐王，亦被拒。 后马士英被俘，被清帝判处死刑。
137. /阮大铖/ （1586 年—1646 年），字集之，号圆海、石巢、百子山樵。怀宁（今属安徽）人。中国明末清初戏曲作家， 明朝末年大臣。 万历四十四年（1616 年），阮大铖中进士。天启时官给事中，依附魏忠贤。崇祯元年（1628 年），起为光禄卿。魏党败，以附逆罪罢斥为民，乃匿居南京，力求起用，受阻于东林党和复社。明亡后，与马士英迎立福王朱由崧（弘光帝），弘光时官至兵部尚书、右副都御史。对东林、复社诸人罗织罪名，进行报复。南京破后降清，随清军攻仙霞关时死于道途。纵观大铖一生的官宦生涯只有大约二年左右的时间。然而大铖却是着实有文采，而且结交广泛，在放意归田的一段时间里，如史可法、文震孟、张岱、范景文等一批名士，皆曾是大铖游宴倡和的人。这在阮大铖的《和箫集》和《咏怀堂诗》之中，都收有大量唱和之作。 阮大铖作传奇 9 种，现存《春灯谜》《燕子笺》《双金榜》和《牟尼合》，世称“石巢四种”。《忠孝环》《桃花笑》《井中盟》《狮子赚》《赐恩环》未见传本。阮大铖剧作的艺术风格内容空泛，思想平庸，格调不高，但曲词工丽，文采绚烂，情节热闹，善用误会法铺叙，加以作者精通舞台艺术，所以在旧时舞台上颇为流行。
138. /刘孔炤/ ，字复旸，青田人。诚意伯刘基子孙，刘荩臣子。《南明史》中评价：“倾侧机辨，遇事风生“。崇祯年领南京右府提督操江兼巡江防。弘光时，与马士英、阮大铖善，国破，坚持抗清，最后出航不知所终。天启三年袭封诚意伯。孔炤祖父尚忠和继配夫人胡氏生子莱臣，而他的父亲荩臣是婢女生的，刘尚忠死后，爵位应该由莱臣继承，因为莱臣年纪小，被刘荩臣继承，刘荩臣死后，又被刘孔炤继承。后来将叔叔刘莱臣和祖母胡氏先后杀害。崇祯朝，多次与东林人发生冲突。为了得到操江官职，他参劾侯恂，献媚于温体仁，又攻击倪元璐去职，终于如愿以偿，十一年，领南京右府提督操江兼巡江防。1644 年，三月李自成攻入北京，崇祯帝自尽，南京成为新朝廷所在。刘孔炤作为勋贵与操江提督成为重臣，马士英联结军镇武臣拥立福王朱由崧即位，刘孔炤也是其中一员。弘光时，刘孔炤与马士英、阮大铖相善，他是马士英入相的重要推力，并在此期间积极参与朝廷权利的争夺。1645 年，清军南下，很快破镇江逼近南京，刘孔炤走太平（当涂）。弘光帝逃至太平，孔炤闭门不纳，最后在芜湖被清军抓获。刘孔炤带领残兵数千人乘船顺流东去，最后入海。在唐、鲁争立中刘孔炤在监国鲁王一边，驻兵处州，后屯兵温州，内讧又一次发生，清军继续南下，隆武政权覆亡，复入海。清顺治十年（永历七年），三月，张名振入长江，刘孔炤偕其子永锡率众依之，一起攻破京口，截长江，驻崇明，随后又收复舟山。清顺治十三年，清军攻入舟山，刘孔炤子刘永锡偕英义伯阮骏迎战死，死时，年十七。刘孔炤最后入海不知所终。
139. /龚鼎孳/ （1615 年—1673 年），字孝升，号芝麓，合肥（今安徽合肥）人，明末清初官员、诗人、文学家。明思宗崇祯七年（1634 年）进士，官兵科给事中。李自成起义军攻入京城后，授直指使，巡视北城。后清兵攻占北京，龚鼎孳迎降而授礼科给事中，升太常寺少卿、左都御史。龚鼎孳为刑部尚书时，对志士遗民陷于囹圄者，尤多矜恤，轻财重义，常倾囊以恤穷交，故在当时亦享盛名。康熙十二年九月十二日（1673 年 10 月 12 日）病卒。龚鼎孳与钱谦益、吴伟业齐名，称“江左三大家”。以其文学创作和活动，不仅在清初诗歌史上留下了浓墨重彩的一笔，且对康熙前期诗坛格局的形成亦有过重要的推波助澜之功。其著有《龚端毅公文集》27 卷、《龚端毅公奏疏》8 卷、《浠川政谱》1 卷等。
140. /严正矩/ ： （1610-1681）字方公，号絜庵，明成化丁未进士，祯正德庚辰进士志廸之裔孙也。幼颖异，九岁能文，二十食饩。崇祯丙子举于乡，癸未成进士，未仕。（清）国初授嘉禾司理，尝作《龚鼎孳传》。
141. /阮阅/ （生卒年不详），原名美成，字闳休，号散翁、松菊道人，舒城（今属安徽）人。中国宋代词人。阮阅于神宗元丰八年（1085），举进士。曾任钱塘幕官，后以户部郎官知巢县。徽宗宣和二年（1120 年），知郴州，作七绝《郴江百咏》，有宣和六年（1124 年）自序。高宗建炎元年（1127 年），知袁州，初至时以讼牒繁，书“依本分”三字，印榜四城墙壁，又榜西厅曰“无讼堂”。后致仕，即居袁州（今江西宜春）。阮阅喜吟咏，长于绝句，时号“阮绝句”。又“能为长短句，见称于世。”其著有《诗话总龟》《郴江百咏》《阮户部词》。《全宋词》辑存其词 6 首。
142. **张涟**（1587 年－1671 年），字南垣，松江华亭（今上海）人，明末清初造园艺术家。后迁居嘉兴，因技艺卓著被《嘉兴县志》《清史稿》等方志史籍载录，吴伟业、黄宗羲等名家为其作传。其叠山技法突破传统高架叠缀模式，主张土石相间、因形布置，通过短垣密竹遮蔽边界，营造"奇峰绝巘"的视觉延伸效果。张涟少时习画，融合倪瓒、黄公望山水笔法于园林营造，活动江南五十余年  。代表作品有松江横云山庄、太仓乐郊园、常熟拂水山庄及上海豫园黄石大假山。晚年主持北京皇家园林修造，康熙特赐肩舆出入畅春园  。次子张然继承其艺供奉内廷，参与瀛台、静明园等工程，形成"山子张"流派。张熊等子侄延续技艺，家族传承达百余年。
143. **孙临**，（1611-1646），字克咸，更字武公，谥节愍，室名、别号飞将军，或称孙三。少司马晋季弟。少读书任侠，与里中方密之、周农父、钱饮光齐名。所为歌诗、古文、词，流传大江南北。崇祯末，流贼蹂楚豫，阑入蕲黄，英寥间皆为战场，皖当其冲。先生渡江走金陵，益散家财，结纳奇材剑客，与云间陈大樽、夏瑗公、徐复庵三君厚善。大樽赠先生诗曰“孙郎磊落天下才”云云,著其事也。
144. /余怀/ （1616 年—约 1696 年），字澹心，号曼翁、鬘持老人，福建莆田人，长期寓居南京，明末清初文学家。别号广霞山人、壶山外史等，著有《板桥杂记》《味外轩稿》《玉琴斋词》等。余怀终生未应试入仕，明亡前家境优渥，寄情声色。清军攻占南京后流亡浙中，晚年隐居苏州。其诗与杜濬、白梦鼐齐名，时称"余杜白"，前期诗风轻俊流美，多写闲情逸趣；后期转为悲凉雅健，代表作《咏怀古迹》三十首以南京胜迹寄托兴亡之感。笔记《板桥杂记》三卷记述明末金陵风月，通过盛衰对照抒写沧桑之叹。著作涉及诗词、文史、戏曲、茶艺等领域，尚有《甲申集》《东山谈苑》《三吴游览志》等存世。
145. /林云凤/ ，字若抚，长洲人。若抚当钟、谭焰张之日，守正不回，诗篇极其繁富，惜知者寥寥，困阨终老，相如遗草，已不可问矣。
146. /董其昌/ （1555 年 2 月 10 日—1636 年 10 月 26 日），字玄宰，号思白、香光居士，松江华亭（今上海市）人。明朝后期大臣、书画家。万历十七年（1589 年），考中进士，授翰林院编修。一度担任皇长子朱常洛的讲官。历任湖广提学副使、福建提学副使、河南参政，因病辞职。泰昌元年（1620 年），明光宗朱常洛继位，授太常少卿、国子司业，参修《明神宗实录》。天启五年（1625 年），出任南京礼部尚书，因事辞官。崇祯五年（1632 年）任太子詹事。崇祯七年（1634 年）回归乡里。崇祯九年（1636 年）去世，谥号“文敏”。 董其昌擅于山水画，师法于董源、巨然、黄公望、倪瓒，笔致清秀中和，恬静疏旷；用墨明洁隽朗，温敦淡荡；青绿设色，古朴典雅。以佛家禅宗喻画，倡“南北宗”论，为“华亭画派”杰出代表，兼有“颜骨赵姿”之美。存世作品有《岩居图》《秋兴八景图》《昼锦堂图》《白居易琵琶行》《草书诗册》《烟江叠嶂图跋》等。广东省博物馆收藏了董其昌绘画 16 件。画作及画论对明末清初的画坛影响甚大。书法出入晋唐，自成一格。作品《戏鸿堂帖》（刻帖）。颇能诗文，著有《画禅室随笔》《容台文集》等。
147. /袁思亮/ ：（1879-1939），字伯夔、一字伯揆，号蘉庵、莽安，别署袁伯子，湖南湘潭人，民国藏书家、学者。袁树勋之子。光绪二十九年(1903)举人，后绝意科举。民国初年曾任北洋政府工商部秘书、国务院秘书、印铸局局长等职。 袁世凯复辟时弃官归，隐居上海，终日以著述、购书为事。所藏宋元古籍甚多，曾以重金购得宋本《韩昌黎集》等，世称宋本集部第一。其藏书后因宅第失火，部分古籍被焚损，如《注东坡先生诗》残存卷册后被称为“焦尾本”。 与陈三立交好，陈三立的一些应酬文字由袁思亮代笔。曾为松坡图书馆筹办员。藏书处曰“雪松书屋”、“刚伐邕斋”等。著有《蘉庵文集》、《蘉庵词集》、《蘉庵诗集》等。
148. /周亮工/ （1612 年-1672 年），原名亮，谱名为圻，字元亮，又字伯安（又作百安、白安），号栎园，别号减斋、陶庵、栎下生、太白学人、偶遂堂主人等。祥符（今河南开封）人。中国清代官员、文学家、篆刻家、书画鉴藏家。明崇祯十二年（1639 年）中举，次年成进士，官山东潍县知县，迁浙江道监察御史。入清后，任两淮盐法道、淮扬海防道兵备参政、福建按察使、福建布政使、都察院左副都御史、户部右侍郎等。后屡次被劾论死，又遇赦。康熙二年（1663 年），起为青州海防道，后擢江南江安督粮道，曾代理安徽布政使。康熙八年（1669 年），被劾去职，不久病死。周亮工博学多通，治学广泛，以经史旁及小学、地理、天文、音韵、书法、绘画、医药等多方面。周亮工文论思想比较通达，兼收并蓄，颇有创见。他批评文坛上“为周秦者若不许更为汉魏，为六朝者不许人更为唐宋”的取法前人、求同排异的不良现象，反对泥守“一帜一色”，提倡“树千万五色帜”。周亮工嗜绘画、书法、篆刻，善鉴赏，爱收藏，其文集中多题跋、引语、书后一类文字，如《题胡元润画册》《题徐青藤花卉手卷后》等文，对文物考古、版本改订多有参考价值。周亮工亦工诗，“论诗每以切题、自道性情为主，而所得矜奇，渐老渐熟似李杜”，反对专讲格调气色，主张作诗有真我，有真意，力矫晚明不良诗风。周亮工撰有《赖古堂集》24 卷，《闽小纪》4 卷，《全潍纪录》1 卷，《字触》6 卷，《印人传》3 卷，《读画录》4 卷等。
     1) /周亮节/ ，（1622-1670）文炜次子,亮工弟，又称靖公。
149. /刘同升/ （1587 年-1646 年），字晋卿，又字孝则，江西吉水人。生于明神宗万历十五年（1587 年），卒于明绍宗隆武元年十二月（1646 年 1 月）。明朝崇祯十年（1637 年）丁丑科状元。授翰林院修撰。因抨击朝廷用人不当，谪福建按察司主事。又以体弱病多，告假归里。明亡后与杨廷麟收复吉安、临江，加封詹事兼兵部侍郎卒于赣州。著有《锦麟诗集》《明名臣传》等。其父 *刘应秋* 探花出身，与大剧作家汤显祖是同年进士，两人曾同朝为官，意气相投，久而久之两人结成了儿女亲家，汤显祖把小女儿詹秀许给了探花之子刘同升。
150. /翁方纲/ （1733 年－1818 年），字正三，一字忠叙，号覃溪，晚号苏斋，顺天大兴（今北京）人，清代书法家、文学家、金石学家。乾隆十七年（1752 年）进士，历任编修、内阁学士，曾参与纂修《四库全书》，并任广东、江西、山东学政。其书法与刘墉、梁同书、王文治齐名，尤擅隶书，以法度严谨著称。翁方纲精于金石考据，著有《两汉金石记》《粤东金石略》《苏米斋兰亭考》等，藏书楼“宝苏斋”因藏苏轼《嵩阳帖》得名，每年举办“祭苏会”延续至民国。论诗倡“肌理说”，主张以考据入诗，著有《复初斋诗文集》《小石帆亭著录》《石洲诗话》。其学术著作涵盖经史、书画、诗论，其中《四库全书》编纂期间广搜金石拓本，奠定清代金石学研究基础。
151. /洪承畴/ （1593 年 10 月 16 日—1665 年 4 月 3 日），字彦演，号亨九，福建泉州南安英都（今英都镇良山村霞美）人。明末清初政治、军事人物。洪承畴于万历四十四年（1616 年）进士。崇祯初，累迁至延绥巡抚、陕西三边总督，镇压陕西农民军。旋晋兵部尚书，总督河南、山西、陕西、湖广等处军务，曾击败高迎祥、李自成部。崇祯十二年（1639 年）调任蓟辽总督。崇祯十四年（1641 年）统兵十三万出山海关，救援锦州，在松锦之战中为清军所败。次年被俘于松山，遂降清，隶镶黄旗包衣牛录（后入镶黄旗汉军）。顺治元年（1644 年），任秘书院大学士。次年，南下总督军务，招抚江南诸省。顺治十年（1653 年），奉命经略湖广、广东、广西、云南、贵州五省，赐“经略大学士”印，驻扎长沙，主持进攻南明永历政权。顺治十五年（1658 年），授武英殿大学士。次年，以目疾请解任回京。顺治十八年（1661 年）致仕，予三等阿达哈哈番世职。康熙四年（1665 年），洪承畴去世，康熙帝追赠他为少师，赐谥号“文襄”。洪承畴是明清之际一个有重大争议的历史人物。有观点认为，他为清朝统一中国出谋划策，参与清朝中央佐理机务，在招抚江南、避免江南百姓生灵涂炭方面，起了重要的作用。 也有观点认为，洪承畴在大是大非面前总是经不起考验，挺不起脊梁，是一个可悲可叹的人物。
152. /冒襄/ （1611 年—1693 年），字辟疆，号巢民，一号朴庵，又号朴巢，江苏如皋人。 明朝副使冒起宗之子， 明末清初文学家，明末四公子之一（ *陈贞慧* （1604–1656）、 *方以智* （1611–1671）、 *冒襄* （1611–1693）、 *侯方域* （1618–1655），分籍宜兴、桐城、如皋、商丘。）冒襄幼年随祖父在任所读书，14 岁就刊刻诗集《香俪园偶存》，被比作初唐的王勃。在 1627-1642 年间，冒襄 6 次去南京乡试，6次落第，深感怀才不遇。1636 年，与张明弼结盟，参加复社，同陈贞慧、方以智、侯方域过从甚密，人称“四公子”。清兵入关后，冒襄回归故里隐居， 他隐居后名气更大。清朝督抚和御史均因其才能推举他，他都借口父亲年迈而推辞。康熙年间，有人又以山林隐逸及博学鸿词举荐冒襄，他也不去。康熙三十二年（1693 年），冒襄去世，享年八十三岁。 冒襄能诗善文，博学多才，一生著作繁富，有品茶、古玩、植花等科学杂著。传世的有《先世前征录》《朴巢诗文集》《岕茶汇抄》《水绘园诗文集》《影梅庵忆语》《寒碧孤吟》和《六十年师友诗文同人集》等。其中《影梅庵忆语》洋洋四千言，回忆了冒襄和秦淮名姬董小宛缠绵悱恻的爱情生活，是中国忆语体文字的鼻祖。除了在文学方面有较高的成就，冒襄一生还有一个杰作——水绘园。水绘园是其淡出仕途之后主持改建和扩建的园林，是他和董小宛曾经的栖隐之所。这里一度成为明末清初中国东南的文化活动中心。此园林的设计，别具匠心，达到园林艺术的新境界，是中国徽派园林的孤本代表。
153. /陈贞慧/ （1604 年-1656 年），字定生，南直隶常州府宜兴县（今江苏省宜兴市）人。中国明末清初散文家。 明末诸生，后中乡试副榜第二人。父陈于廷，东林党人，官左都御史。陈贞慧是复社成员，文章风采，著名于时，与冒襄、侯方域、方以智，合称“四公子”。曾与吴应箕、顾杲共议声讨阮大铖，由吴应箕起草《留都防乱檄》，揭帖于南京，为阮大铖所恨。南明弘光朝，受阮大铖迫害，曾一度入狱。入清不仕，隐居家乡，10 余年不入城市。陈贞慧的文章婉丽闲雅，兼擅骈、散两体。记载掌故及纪念明末“清流”和殉难人士的作品，多寄托故国之思。又《痛史》及《中国内乱外祸历史从书》第一辑，收录《过江七事》一种，专记弘光朝的史事，题为陈氏之作。著有《雪岑集》《皇明语林》《山阳录》《书事七则》《秋园杂佩》等，后三者收入《太仓先哲遗书》，合称《陈定生先生遗书三种》。
154. /吴应箕/ （1594 年 10 月 24 日—1645 年 12 月 2 日），字次尾，号楼山，南直隶池州府贵池县大演（今安徽省池州市石台县大演乡）高田人，复社领袖，诗人、学者。万历二十二年九月十一日(10 月 24 日)出生于石台县大演乡永福村高田组。性豪放，“性喜声，使娱乐，不肯一日郁郁作穷悴状。”崇祯十二年（1639 年）和陈贞慧起笔《留都防乱公揭》，历数阮大铖罪行。八试不第，崇祯十五年（1642 年）中乡试副榜。工书法，草书初学黄庭坚，后宗米芾、颜真卿。好与忠贞志士交往。弘光元年（1645 年）闰六月在家乡起兵抗清，与徽州金声等义兵相呼应，一度收复皖南大部。唐王授以池州推官之职，纪监军事。十月，在贵池县泥湾山口阻击清兵，兵败灌口，退至回山，于压气培（今乌鸦培，在大演乡新龙村境内）为清兵俘获，押送府城，十月十七日行至山口施松林，清兵恐引起骚动，就义于池州城外石灰冲，清兵割首而去，《池州府志》载“头入郭门如生，三日不变”。侯方域挽词：“面冷而苍，髯怒以张；言如风发，气夺电光”。清道光二十九年（1849 年）山口二秀才施士端、施士谦感其忠烈，在殉难地捐立碑石，以志纪念。吴应箕诗歌坚实质朴，激昂豪放，著有《两朝剥复录》、《国朝记事本末》、《留都见闻录》、《楼山堂集》等等。
155. /方以智/ （1611 年—1671 年 11 月 9 日），字密之，号曼公，浮山愚者，又号鹿起，别号龙眠愚者，出家后改名大智，字无可，别号弘智，人称药地和尚，方孔炤之子。南直隶安庆府桐城。明代思想家、哲学家、科学家。方以智一生正当明清交替之际，时局动荡，政权更迭。使得他个人的际遇也十分坎坷。早期，由于仰仗祖上的余荫，尚能过着“衣纨縠，饰驺骑，鸣笳叠吹，闲雅甚都”的富贵文人的生活。中期自明朝灭亡后，从北京逃返南京，又经浙江、福建辗转到两广，从三十四岁到四十二岁，艰苦的十几年流亡在他的思想上打下了深刻的烙印。顺治九年（1652 年）北归。康熙十年（1671 年）冬，方以智为粤事牵连被捕，解往广东，途经江西万安惶恐滩头。十月七日（11 月 8 日），方以智因疽发卒于舟中，时年六十一岁。方以智为“明末四公子”之一，家学渊源，博采众长，主张中西合璧，儒、释、道三教归一。他对于经学、哲学、文字和音韵学、医药学、物理学都有深入研究，并写有专著。他总结汉唐宋明以来易学的发展，讨论了一系列哲学问题，从象数之学的角度，在易学史上建立起一套本体论的体系。但由于以河洛之学和先天易学解说《周易》经传，又将象数之学推向了极端，遭到义理学派和考据学派的抨击，引发了否定图书之学的思潮。其一生著述 400 余万言，多有散佚，存世作品数十种，内容所及文、史、哲、地、医药、物理。
156. /方孔炤/ （1590——1655），字潜夫，号仁植，安徽桐城凤仪里（今桐城市区北大街）人，明末大臣、易学家，方以智之父。明神宗万历四十四年（1616 年）进士，授嘉定州知州，累官至湖广巡抚，在镇压明末农民起义的过程中八战八捷，立下赫赫战功。著有《周易时论》 。
157. /张缙彦/ （1599 年 11 月 1 日－1670 年 11 月 26 日），字濂源，号坦公，别号大隐，河南卫辉府新乡县（今河南省新乡市新乡县）人。明末清初官员。张缙彦中崇祯四年（1631 年）进士，授陕西清涧县知县，调三原县，守城有功，朝议称之。入京任户部主事，对策称意钦授翰林院简讨，以知兵升兵部都给事中，丁父忧归。夺情起用超擢兵部尚书，接任冯元飚。十七年（1644 年），京师陷落，归顺大顺政权，未几逃归，沿路招兵，弘光帝授河南总督。睢州之变，张缙彦逃亡英霍山区担任联寨抗清盟主，知事不可为，通过前长官洪承畴暗中通款投靠清朝。久之，顺治十年（1653 年）始上任山东右布政使，历任浙江左布政使、工部右侍郎，期间卷入党争，被魏裔介等人多次弹劾，降补徽宁道佥事。十七年（1660 年），张缙彦因与前明官员方拱乾、刘正宗等人交往过密，被顺治帝借文字狱之名流放至宁古塔。徙外方十年，“曳杖携樽，寻山问水，搜奇揽胜”，于康熙九年（1670 年）去世，享年七十二岁。张缙彦聪颖敏捷，读书必求根底，广集经典，人称经司；同时多才多艺，精绘画、善雕刻，尤工诗文，著作颇多，有《新乡县志》《庸南俭约序》《啸风亭》等。所著述的《宁古塔山水记》为黑龙江省第一部山水志，《域外集》还汇集了历代有关中俄边界的史事。
158. /王铎/ （1592—1652 年），字觉斯（之），号十樵、嵩樵、痴庵、痴仙道人、烟潭渔叟，平阳府洪洞县（今山西省洪洞县）人 ，诞生于河南省孟津县  ，明末清初大臣、书画家，王本仁的儿子。天启二年（1622 年），考中进士，入选庶吉士，历任太子左谕德、太子右庶子、太子詹事、南京礼部尚书。弘光政权建立，出任东阁大学士。顺治元年（1644 年），跟随钱谦益投降清朝，授礼部尚书、弘文院学士、太子少保。顺治九年（1652 年），病逝，享年六十一岁，安葬于河南巩义县洛河边，谥号文安。善于书法，与董其昌齐名，有“南董北王”之称。正如李志敏评价：“王铎的草书纵逸，放而不流，纵横郁勃，骨气深厚”。 书法作品有《拟山园帖》和《琅华馆帖》等。绘画作品有《雪景竹石图》等。
159. /薛所蕴/ （1600－1667），字子展，号行屋，河南孟州人。崇祯元年进士，贰臣。累官至国子监司业。福王时，以曾附李自成，定入从贼案。复降清，授原官，累官礼部左侍郎。为高尔俨所劾，乞休归。工诗文，有《椁庵集》、《澹友轩集》等。
160. /刘正宗/ (1594～1661)，字可宗，号宪石，赐号中轩，明末清初大臣，世称“刘阁老”，山东安丘城里人。生于书香门第，1625 年（天启五年）县岁试第一，1627 年（天启七年）8月乡试中举。1628 年（崇祯元年）3月中进士，历任真定府司理、翰林院编修、东宫讲读官、侍讲、礼部会试副主考。1644 年（清顺治元年）为暂避战乱，携眷南下金陵。翌年 5 月清兵破金陵后，携眷回归安丘故里。
161. /李维桢/ （1547-1626），字本宁，湖北京山人。晚明大臣、著名文学家，文坛领军人物。隆庆二年（1568 年），举进士，由庶吉士授编修。万历朝，参修《穆宗实录》，进修撰。出为陕西右参议，迁提学副使，又任浙江、山西按察使，布政使（省最高行政官员），河西兵备督理。他在京外做官，宦海浮沉近三十年。天启初年（公元 1621）以布政使之职居家赋闲。天启初年，为南京太仆卿，旋改太常卿。四年，太常卿董其昌复荐，召为礼部右侍郎，后进南京礼部尚书（从一品）。天启六年，卒于家，年八十。崇祯继位，赠太子太保。李维桢秉性乐观豁达，交际广泛。文章恢宏恣肆，极有才气，每天都有人前往请教。他的诗歌各体兼备，尤擅七言古诗、律诗、绝句，风格多样，可见雄浑壮阔、沧桑悲凉、清远明丽、轻松戏谑等各种诗风。撰写的碑文、题辞几乎遍及海内。明万历时期，以李维桢为代表的湖北作家群体以强有力的现实存在，闪现出璀璨的光芒，证实了“惟楚有材”的价值与魅力。《明史》卷二百八十八《列传第一百七十六·文苑四》为李维桢立有传记。
     1) /李维柱/ ，维桢之弟，别名本石。
162. /屠隆/ （1543 年-1605 年），字长卿，又字纬真，号赤水，晚号鸿苞居士，别署一衲道人、蓬莱仙客、娑罗主人等，浙江鄞县（今宁波）人，后迁居汤家山（今江西省抚州市），中国明代传奇作家、戏曲家。 屠隆于明万历五年（1577 年）中进士，授颍上（今属安徽）县令，后调任青浦（今属上海）县令。任青浦县令时遇水灾，率众修筑江堤防洪，次年奏请调整县境区划，离任时当地士民数百人送别至太仓州。  万历十一年（1583 年），擢升礼部仪制司主事，次年因刑部主事俞显卿诬告其“淫纵”遭罢免（实际因拒绝徐阶笼络遭忌恨）。  后纵情诗酒，蓄养家班并亲自指导排演戏曲，率领戏班在江浙巡演《昙花记》。  屠隆是“后五子”代表，既继承前后七子复古理论，又受公安派影响反对拟古，提出“性灵”说，主张唐诗胜在“托兴深”“生于性情”，批评宋诗“不入品裁”。著有诗文集《由拳集》《白榆集》《栖真馆集》，杂著《鸿苞集》《考槃余事》，清言小品《娑罗馆清言》等。创作《昙花记》《彩毫记》《修文记》传奇三种（合称《凤仪阁乐府》），主张戏曲创作“不用隐僻学问，艰深字眼”，其中《彩毫记》以李白为主人公，《昙花记》成书于万历二十六年（1598 年）并以佛理入戏。晚年与汤显祖两次在遂昌会面研讨文艺创作。
163. /孙慎行/ （1565 年～1636 年）字闻斯，号淇澳，又号玄晏子 。江苏武进人。明朝开国功臣燕山忠愍侯、全宁侯之后。外祖父是明代著名文学家、军事学家唐顺之。家族及外祖父的事迹对他影响很深，所以他自幼即勤奋好学，在万历二十三年（1595）殿试中摘得“探花”（第三名）的桂冠。天启初，拜为礼部尚书，为追论大学士方从哲进荐“红丸”罪案，为当朝权贵所忌，于天启二年（1622 年）托病辞官。后阉党作《三朝要典》翻“红丸案”，指责孙慎行为罪魁，流放宁夏，适逢魏忠贤失势才幸以免谪。崇祯元年，命以故宫办理詹事府，力辞不就。崇祯八年（1635）荐召入阁，但未及上任即逝世，享年七十二岁，被追赠太子太保、谥“文介”。他著有《中庸慎独义》、《史左编》等十四种，三百二十多卷。因其操行峻洁，被明廷尊为十大贤臣之一。明万历二十三年（1595 年）朱之蕃榜进士第三人。授翰林院编修。累官至礼部侍郎。韩敬科场事发，孙慎行主张罢黜韩敬，遭到韩敬同党的攻击。辞官。熹宗继位，召回孙慎行，拜为礼部尚书。“红丸”事起，孙慎行上疏无效，遂以病辞官。魏忠贤组织纂修《三朝要典》，在“红丸”之案中，将孙慎行定为罪魁祸首。熹宗下诏将其革职，遣戍宁夏，还未起行，崇祯帝继位，才得赦免，命以原官协理詹事府事，孙慎行力辞不就。享年 74 岁。著有《困思抄》、《玄晏斋集》等。
164. /孙承宗/ （1563 年—1638 年），字稚绳，号恺阳，保定高阳（今属河北）人。中国明末大臣、民族英雄。万历三十二年（1604 年），孙承宗考中进士，授翰林院编修，又升中允，历任谕德、洗马。明熹宗天启元年（1621 年），以左庶子充日讲官，进少詹事。天启二年（1622 年），拜兵部尚书兼东阁大学士，自请督师山海关外。汰逃将，肃军纪，在关外四年，前后收复大城九，堡四十五，练兵十一万，拓地四百里，开屯田五千顷，岁入十五万。天启五年（1625 年），因柳河之役失败，受魏忠贤党排挤而求归。崇祯二年（1629 年），在己巳之变中复职，于通州、山海关抵御后金，复永平等四城，因功加太傅，辞不受。崇祯四年（1631 年），再出关整饬松山、锦州军务。同年冬，明军在大凌河之战中失败后，他因主张修大凌河城“召衅辱国丧师”而免官闲住。 崇祯十一年（1638 年），率家人守高阳城抗清，城破被俘，自缢而死。南明弘光时，赠太师，谥文忠（清谥忠定）。孙承宗整顿山海关防务，打造了关宁锦防线，在此后的 20 余年间，从努尔哈赤到皇太极都未能打破这道壁垒森严、布防严密的军事防线。较长的一段时期内，山海关关门宁静，狼烟不举，基本稳定了京师东大门和辽西走廊的军事形势。其著作有《高阳集》《督师全书》等。
165. /萧士玮/ （约 1585-约 1651），一名溟，又名敏，字伯玉，号三莪，江西泰和县城西人。 曾任行人司行人。明末清初文学家。 萧士玮自幼聪颖，读书一目十行，师从曾大奇、葛寅亮等名师。登进士后任行人司行人，负责外交礼仪、诏书传达、邦交册封等事务。天启年间，权臣魏忠贤索要其宅院，萧士玮严词拒绝。他在泰和柳溪营建春浮园，规模宏大，有柳溪、公安亭等十四景，享誉全国。天启六年（1626 年），魏忠贤毁天下书院，萧士玮倡迎僧居书院，将书院复为寺；崇祯年间又与王艺山将寺复为书院。 萧士玮传世文集有《春浮园集》6 卷、《起信论解》1 卷，另有《南归目录》《日涉录》《萧斋日记》等日记体文集，其著述被乾隆朝列为被毁书目。
166. /艾南英/ （1583 年 12 月 30 日——1646 年 9 月 19 日），字千子，号天佣子，抚州府东乡县 （今江西省抚州市东乡区）人。明朝末年散文家、文学评论家。 天启年间中举人，策文讥刺权宦魏忠贤，罚停考三科。因深恶科场八股文章腐烂低劣，与临川人章世纯、罗万藻、陈际泰等力矫其弊，以兴斯文为任，刻印四人文章，世人翕然赞同，人称临川四才子，或江右四家。清军南下，江西郡县尽失。入闽见南明唐王朱聿键，授监察御史。隆武二年，病卒。著作今存《禹贡图注》、《天佣子集》。
167. /邹弢/ （1850—1931），字翰飞，号酒丐、瘦鹤词人、潇湘馆侍者，亦称司香旧尉，江苏无锡人。晚清报人、小说家。 曾任《苏报》主编。邹弢早年科举不第，曾设馆教书。 约 1880 年赴上海，此后开始报人生涯，先后任职于《申报》《益闻录》《苏报》《格致益闻汇报》等报馆。1900 年入天主教。1905 年起在上海启明女塾任国文教员。1912 年，与友人创建诗文团体希社，并被推举为社长。1923 年 9 月，与俞凤宾联合撰写《日本天灾之急宜筹赈》一文。1927 年，被荐举为泰伯市图书馆馆长。1928 年，在乡办报《泰伯市报》任总编。1931 年去世。幼年作客，历馆姑苏，几及十年，与俞达为患难交。居沪上亦甚久。 尝写妓女苏韵兰事，为《断肠碑》（一名《海上尘天影》）六十回；《中国通俗小说书目》又有《三借庐丛稿》及《三借庐笔谈》十二卷，《浇愁集》八卷，《诗学速成指南》二卷，并行于世。曾任《苏报》主编，晚年在上海启明女学任教。
168. /李衷纯/ （1564—1639），字广霞，号元白、玄白，浙江秀水（今浙江嘉兴）人，为“梅溪李氏” /李芳/ 的从子、 /李良年/ 的伯曾祖父。 万历四十年（1612）中顺天乡试，四十七年（1619）出任如皋县令。在如皋教民纺织、兴修水利、倡导花木栽培。后历任南京工部主事、兵部员外郎、邵武知府，官至两淮盐运使。在邵武清厘关税收归公用，任运使时整顿盐政。退休后家无余财。著有《激楚斋诗集》，诗作入选《明诗综》。屠隆与李衷纯有五次集中交往，屠隆曾寓李衷纯尺牍两通。 李衷纯与钱谦益关系密切，钱谦益为他撰墓志铭。 湖州人茅维引李衷纯为知己，万历己亥（1599）写信邀他赴秋社；常州人、国子监学正蒋绍煃也将李衷纯引为“踯躅红尘”的同伴，赠《秋山图》及诗。
169. 李良年（1635 年－1694 年），原名法远，又名兆潢，字武曾，号秋锦，浙江秀水（今嘉兴）人。明末清初诗人，与兄李绳远、弟李符合称“三李”，与朱彝尊并称“朱李”，为浙西词派代表人物。早年与朱彝尊、王翃、周筼、缪泳、沈进等结诗课，康熙十七年（1678 年）应试博学鸿儒科落第，后受徐乾学聘修《一统志》。著有《秋锦山房集》二十二卷、《清史列传》及《浙西六家词》辑录其词作。李良年少时家道中落，以教授为生。康熙十年（1671 年）应贵州巡抚曹申吉邀入幕，诗作《贵阳山中杂兴》《水车行》等得江山之助 [。后辗转凤阳、福州为幕僚，五十一岁归乡筑“秋锦山房”隐居  。其诗持格律严谨，词兼取吴文英、张炎之长，谭献评《暗香·绿萼梅》“白石故以幽胜”；古文尤擅议论，得长洲汪琬推重。擅长尺牍，与曹溶齐名，世称“曹李”。
170. /杨绍和/ ，清著名藏书家、目录学家。字彦合，又字念微，号协卿、筠岩。聊城县城里(今属聊城市东昌府区) 人。杨以增次子，海源阁第二代主人。杨绍和在目录学方面也颇有造诣。他在对海源阁阁藏进行整理后，于 1869 年(同治八年)写出了《楹书隅录初编》5 卷，又于 1871 年(同治十年)撰《楹书隅录续编》4 卷，对所录之书考核异同，检校得失，详记各书的名家题跋，间附己意，并记其行式、印章及收藏经过等，使海内人士得以了解海源阁藏书之梗概。时人谓：“杨氏以藏书为世业，宋椠元抄集诸家之大成，故藏书之富，鉴别之审，海内推先生第一。”1875 年卒于官。著《仪晋观堂诗抄》，民国初，杨承训汇刻有《聊城杨氏三代诗文集》。
171. /胡震亨/ （1569 年-1645 年），原字君鬯，后改字孝辕，自号赤城山人，晚号遯叟。浙江海盐武原镇人。明代文学家、藏书家。先世业儒，藏书万卷。震亨才识通达敏捷，为诸生即怀济世之志。明万历二十五年（1597 年）中举，后为合肥知县。在任 5 年，大兴水利，改革官粮运输，颇多善政。崇祯末年，荐补为定州知州，擢兵部职方司员外郎。乞归居家。一生嗜书如命，日夕不倦研读，凡秘册僻本、旧典佚事、错差模糊不可卒读者，亦均研读补正，时人称之为博物君子。近人张元济称其为“吾邑第一读书种子”。胡震亨一生著述宏富，当时海虞毛氏汲古阁所刻诸书，也大多为胡震亨所编定。胡氏以毕生精力编撰而成的巨卷《唐音统签》，奠定了他在明代研究唐诗诸学者中的巨擘地位，后代学者给以很高的评价。该书以天干为纪，共分 10 签，甲至壬签辑录唐诗，间加评论；《癸签》33 卷则是胡震亨研究唐诗心得的结晶，体大思精，内容广博。《唐音统签》为清修《全唐诗》蓝本，原本及抄补之足本现藏北京故宫博物院；《癸签》则于建国后单独出版。
172. /朱彝尊/ （1629 年—1709 年），字锡鬯，号竹垞、金风亭长、 醧舫、 小长芦钓师，浙江秀水（今浙江省嘉兴市）人。清代文学家、 词人、学者、藏书家。 朱彝尊早年为布衣时，专注于古学，博览群书，客游南北，专事搜剔金石录。 顺治七年（1650 年），赴嘉兴南湖十郡大社。顺治十三年（1656 年），接受广东高要知县杨雍建的礼聘，选录《岭南诗选》。此后，漫游于江浙、陕西、山东、京师各地，佐幕为生。康熙十八年（1679 年），参加博学鸿词科考试，授翰林院检讨，参修《明史》。康熙二十年（1681 年），出典江南乡试 ，入直南书房。康熙二十三年（1683 年），私携仆入内廷抄书，受劾降职。 康熙三十一年（1692 年），辞官回乡，专事著述。康熙四十八年（1709 年），朱彝尊逝世，时年八十一岁。朱彝尊博赡渊雅，学术贡献遍及经学、史地学、文学以及目录学等各领域，所撰《经义考》，是中国古代第一部经学专科目录。 在诗、文、词的创作以及理论上更是成就卓著，深刻影响后世。其诗以才藻魄力称盛，当时与王士禛齐名，称“南朱北王”， 为浙派诗开山祖师，与查慎行同为浙派初期两大家，其词讲求醇雅，力挽明词颓风，与陈维崧合称“朱陈”，曾合刊《朱陈村词》，并开创浙西词派，在清代词坛居于领袖位置， 著有《经义考》《日下旧闻》《明诗综》等。
173. /张明弼/ （1584-1652）明文学家、学者。字公亮，号琴张子，金坛人。崇祯六年(1633)举人。十年进士。授广东揭阳县令。政绩卓著，秩满，被谗谪为浙江按察司照磨，群议不平，始调台州推官。年逾，擢户部陕西司主事，愤马士英、阮大铖当国，不赴。早年师从曹大章，古文诗赋名重一时。与冒襄等五人义结金兰，为复社重要成员。天启六年(1626)因作《獝狂国记》，隐指魏忠贤，几乎获祸。其《避风岩记》为散文名篇。著作除以上外，还有《兔角诠》、《萤芝集》、《萤芝全集》、《萤芝新集》、《榕城集》、《雾吐(唾)集》、《杜单集》、《蕉书》等。
174. /祁彪佳/ （1603 年 1 月 3 日－1645 年 7 月 28 日），字虎子，一字幼文，又字宏吉，号世培，别号远山堂主人，浙江山阴人，明末散文家、戏曲家。祁彪佳少年早发，聪慧过人。十六岁中院试第一，补博士弟子员第一名。万历四十六年（1618 年），不足十七岁中浙江乡试第六十八名举人。天启二年（1622 年），不足二十一岁即中三甲进士。然而仕途坎坷，一生三起三落。天启三年（1623 年）任福建兴化府推官，崇祯四年（1631 年）任福建道御史，崇祯六年（1633 年）任苏松巡按御史，崇祯十五年（1642 年）掌河南道，崇祯十七年（1644 年）任右佥都御史巡抚苏松，他力图挽救南明危局，为人所梗，心灰意冷辞官回到杭州。弘光元年（顺治二年、1645 年）六月底，清廷欲招祁彪佳为官。祁彪佳不为所动，于弘光元年闰六月六日（1645 年 7 月 28 日）自沉湖中，以死明其志。隆武帝赠少傅兼太子太傅兵部尚书，谥忠敏。祁彪佳著有《远山堂剧品曲品》《远山堂诗集》《祁忠敏公日记》等。《剧品》收杂剧剧目 242 种，是明代著录名人杂剧的惟一专书。《曲品》收传奇剧目 467 种。其中有明清同类著述中未见著录的戏曲曲目 295 种。两部曲目增录了许多重要戏曲作家的作品，并改订了以前曲目的错误。
     1) *商景兰* （1605 年—1676 年），字媚生，浙江会稽（今绍兴）人，明末清初女诗人，能书善画。明兵部尚书 *商周祚* 长女，抗清名臣祁彪佳妻，与其妹 /商景徽/ 俱以诗名。万历四十八年（1620 年）嫁祁彪佳，夫妻琴瑟和鸣二十五载，时人誉作“金童玉女”。顺治二年（1645 年）祁彪佳殉国后，商景兰主持家事，教导子女理孙、班孙及三女德渊、德琼、德宦，与儿媳张德蕙、朱德蓉等组建家庭诗社，常于梅市登临赋诗，形成“葡萄之树，芍药之花，题咏几遍”之盛况，开清代闺阁联吟风气。晚年历经子女夭亡、家道中落等变故，仍坚持文学创作，著有《锦囊集》，收录诗词百余首。其诗作多抒故国之思与丧夫之痛，如《悼亡》诗中“公自成千古，吾犹恋一生”句广为传诵。朱彝尊称其家族文学活动“望若十二瑶台”，陈维崧评其为“当世题目贤媛之冠”。
175. /毛奇龄/ （1623 年－1716 年），原名毛甡，字大可，一字于一，又字齐于，别号河右，又号西河，又有僧弥、僧开、初晴、秋晴、晚晴、春庄、春迟诸号。浙江萧山（今属杭州）人。中国清代学者、诗人、文学家。  毛奇龄少年颖悟，明末躲避战火，于县城南山中筑土室读书。康熙十八年（1679 年），以廪监生荐举博学鸿辞科试，列二等，授翰林院检讨，充《明史》馆纂修官。康熙二十四年（1685 年），充会试同考官。不久乞假归，得痹疾。康熙三十八年（1699 年），圣祖南巡，毛奇龄迎驾于嘉兴，以《乐本解说》进，谕旨奖劳。康熙五十五年（1716 年），毛奇龄卒于家中。 毛奇龄论诗以“涵蕴”为尚。诗学唐人，但能自成一格。作词拘守传统，有香艳之气。而骈文、散文则纵横恣肆。尤长经学，并以此傲睨当世。作《四书改错》，抨击朱熹《四书集注》，喜标新立异。毛奇龄一生著述宏富，有《西河合集》400 余卷，《西河诗话》《西河词话》《放偷记》《买家记》等。
176. /叶襄/ ，字圣野，长洲人事迹见同治修《苏州府志・八八》、《明诗综・七七》、陈田《明诗纪事・二二》。与牧斋亦有来往。
177. /陈田/ （1850 年－1922 年），字松山（一作崧山），号黔灵山樵，贵州贵筑（今贵阳）人。清同治八年（1869 年）乡试第一名，光绪十二年（1886 年）进士，选翰林院庶吉士，授编修，历任江南道监察御史、吏科给事中等职。光绪年间，陈田与莫庭芝、黎汝谦共同辑编《黔诗纪略后编》30 卷，收录清代贵州 421 位诗人诗作 2289 首，独力完成《黔诗纪略补》三卷，并编纂《明诗纪事》二百卷。任给事中期间连奏弹劾奕劻、袁世凯揽权纳贿。宣统三年（1911 年）辞官寓居北京，清亡后忧愤而终。著有《周渔璜年谱》《听涛斋诗集》等。
178. /张文峙/ ，原名张可仕，原字文寺，后改为文峙，后又改字紫淀。明末清初时期人物，家住钟山之阳（今南京紫金山一带）。他曾与冒辟疆、王士禛等文人交往。 学识渊博，“贯穿经史，辨核掌故”，曾编纂《南枢志》一百七十卷、《明布衣诗》一百卷。与归安茅元仪善，茅死，有姬杨宛，以才色称，戚畹田弘遇欲得之，以千金寿文寺，求喻意，文寺绝弗与通。范文贞公礼为上客，公殉国，文寺设位雨花台，为文哭之。崇祯末，集子史成句为四言诗一卷，讽切时事，号《击磬集》。弟可度，字罽筏，好佞佛，一食清斋，逌然终日。
179. /杨基/ （1326～1378）元末明初诗人。字孟载，号眉庵。原籍嘉州（今四川乐山），大父仕江左，遂家吴中（今江苏苏州），“吴中四杰”之一（苏州诗人高启、杨基、张羽、徐贲）。元末，曾入张士诚幕府，为丞相府记室，后辞去。明初为荥阳知县，累官至山西按察使，后被谗夺官，罚服劳役。死于工所。杨基诗风清俊纤巧，其中五言律诗《岳阳楼》境界开阔，时人称杨基为“五言射雕手”。少时曾著《论鉴》十万余言。又于杨维桢席上赋《铁笛》诗，当时维桢已成名流，对杨基倍加称赏：“吾意诗境荒矣，今当让子一头地。”杨基与高启、张羽、徐贲为诗友，时人称为“吴中四杰”。
180. /完颜麟庆/ （1791－1846），清代官员、学者。字伯余，别字振祥，号见亭，满洲镶黄旗人。嘉庆十四年进士。道光间官江南河道总督十年，蓄清刷黄，筑坝建闸，后以河决革职，旋再起，官四品京堂。麟庆生平涉历之事，各为记，记必有图，称《鸿雪因缘记》，又有《黄运河口古今图说》《河工器具图说》《凝香室集》。
181. /沈德潜/ （1673 年 12 月 24 日—1769 年 10 月 6 日），字碻（què）士，号归愚，江苏苏州府长洲（今江苏苏州）人。清代大臣、诗人、学者。 康熙三十三年（1694 年），被录为长洲县庠生，此后四十年间屡试不第。乾隆元年（1736 年），荐举博学鸿词科。乾隆四年（1739 年），以六十七岁高龄得中进士，授翰林院编修。乾隆帝喜其诗才，称其“江南老名士”。历任侍读、内阁学士、上书房行走。乾隆十四年（1749 年），以原品致仕。乾隆二十二年（1757 年），加礼部尚书衔。乾隆三十年（1765 年），封光禄大夫、太子太傅。乾隆三十四年（1769 年），沈德潜病逝，年九十七，赠太子太师，祀贤良祠，谥文悫（què）。乾隆四十三年（1778 年），因卷入徐述夔案，沈德潜遭罢祠夺官。沈德潜所作的诗大都平正典雅，为台阁体诗人的典型。其论诗主格调，古体宗汉魏，近体尊盛唐。在诗的内容上，主张“诗之为道，可以理性情、善伦物、感鬼神、设教邦国、应对诸侯”。反对专以嘲风雪，弄花草为事。在诗的风格上，强调要“温柔敦厚”“怨而不怒”“一归于中正和平”。他的诗虽也有反映民间疾苦的篇章，但很多颂圣赞德的作品，削弱了诗歌讥刺时弊、抨击黑暗的社会作用。他的诗论比“神韵派”更有利于封建统治。他根据自己论诗的宗旨编选的《古诗源》《唐诗别裁》《明诗别裁》《国朝诗别裁集》等，在辨析源流、指陈得失、对古典诗歌的借鉴与流传方面曾起过一定作用。
182. /沈德符/ （1578 年—1642 年），字景倩，又字虎臣、景伯，浙江秀水（今浙江嘉兴）人，明代文学家。沈德符的祖父、父亲都是科举出身，曾任职监司词林。沈德符自幼生长于北京，曾在国子监读书。据说他聪敏好学，每天都要读一寸厚的书籍。他精通音律，熟谙掌故。万历四十六年（1618 年）中举人，后在会试落第。沈德符所撰《万历野获编》，多记万历以前的朝章国故，并保存了一些有关戏曲小说的资料。除《野获编》外，他的著作还有《清权堂集》《敝帚轩剩语》三卷、《顾曲杂言》一卷、《飞凫语略》一卷，《秦玺始末》一卷。
183. /严元照/ （1773—1817），字元能（一作修能），一字久能（一作九能），号悔庵，又号蕙櫋，浙江归安（今湖州）人。生于清高宗乾隆三十八年，卒于仁宗嘉庆二十二年，年四十五岁。清藏书家、版本目录学家、文学家。字修能，一字久能，号悔庵居士。浙江归安人。贡生。工于诗词古文，又熟于小学，精治目录版本学。平生聚书数万卷，分别贮于“芳淑堂”“柯家山馆”“画扇斋”内，多宋椠元本。于苏州钱景开处购得毛氏汲古阁旧藏宋本《分门纂类唐歌诗》1 种，喜不自胜，遂作咏诗 1 首。撰藏书题跋甚多，所著《悔庵学文》8 卷，所录书跋，多为其他藏书家所未具。所作跋语，以考核精审知名。近代藏书家潘景郑曾想将他所写的书跋，编为一册付梓，惜未完成。藏书印有“石溪严氏”“芳淑堂藏书”“侍儿香修”等。姬妾张秋月，字香修，一字幼怜，亦能藏书，有一藏书印文为“张氏秋月字香修一字幼怜”“余独好修以为常”。晚年藏书流散后，部分归入丁丙“八千卷楼”，部分归于陆心源“皕宋楼”。著有《尔雅匡名》《悔庵文抄》《诗抄抄》《娱亲雅言》《柯家山馆词》等。
184. /顾张思/ （？—？），字怀祖，号雪亭，或称为纯恩（？），清代江苏太仓人，学者、诗人。主要生活于乾隆、嘉庆年间，著有《土风录》18 卷、《谈书录》18 卷等。  顾张思为成志之子，早年考取诸生，承袭家学，博览群书。其《土风录》按时令、民俗、日用等类别编排，收录千余条吴地俗语并考据源流，如"茶食""裁缝""茶船"等条目，记录了清代乾嘉时期江浙地区风俗与日常用语。该书国内现存嘉庆三年刊本，被日本学者长泽规矩也编入《明清俗语辞书集成》，上海古籍出版社亦有整理出版。顾张思自述写作历程存于《读书录自序》。
185. /徐锡胤/ ，字尔从，崇祯末年时期袭爵永康侯，无子。爵除。其妻朱氏，成国公 /朱纯臣/ 女也。夫殁，楼居十余年，不履地。城陷，捧庙主自焚死。
186. /何云/ ，明末藏书家。字士龙，苏州府常熟县人。著有《疏影词》等。好藏书，多善本，能古文词，尤熟唐史。凡唐人诗有关时事者，历历指出如目睹。钱谦益爱其才，邀请他担任钱氏家塾教师。崇祯丁丑（1637）钱谦益被讦下狱，何云亦称愿一同“慷慨誓死，草索相从”。后跟随瞿式耜至闽、粤各地。流离 10 余年，复归故园。冯班称其“何云有文，钱牧翁重之。”钱谦益有《送何士龙南归兼简卢紫房一百十韵》，可见钱谦益与何云的关系非同一般。
187. /温睿临/ ，字邻翼/令贻，号哂园，为浙江乌程人，康熙四十四年举人，清代南明史研究领域开创性史家。其代表作《南疆逸史》以纪传体系统记载南明四朝史事， 首创“纪略”体例规避清廷忌讳，完整保留南明政权年号纪年。该书采摭 40 余种私家史料，与徐鼒《小腆纪年》构成互补，被杨凤苞称为‘简而有法’的南明信史。作为温体仁族孙，温睿临与《明史》修纂者万斯同交谊深厚，在清初私家修史浪潮中填补了官方史书对南明记载的缺失。其著作现存 56 卷足本被南京图书馆收藏，1959 年中华书局版本为学界通行本。
188. /郏伦逵/ （?—?），字蘭坡，号铁兰道人，江苏常熟人。清代画家。生卒年不詳，生平亦不詳。擅长山水、墨兰。著有《白雪山房集》、《兰坡外集》，並編纂论画著作《虞山画志》。
189. /苏先/ ，字子后，号墨庄。少时作《新柳诗》，钱宗伯爱之。工画仕女，为时推重。子后为程孟阳写《仙游图》，题云：“撇开尘俗上青霄，绛续仙人拍手招。踏破洞天三十六，月明鹤背一枝箫。” 才横气豪，即诗可见。
190. /单学傅/ （1778 年—1837 年），字师白，号钓翁，常熟钓渚渡人，清代诗人、诗评家。嘉庆五年（1800）庠生，府试第一，少称神童，师从吴蔚光，馆其家十余年，后客游河南开封，与姚椿、洪崎孙唱和，卒于旅舍 。著有《钓渚诗选》《海虞诗话》等，门人姚锡田于道光十七年（1837）作《钓渚师遗像赞》以追念 。单学傅承冯班、王应奎诗论，工近体诗，具晚唐风味，强调诗歌须“写真事、抒真情” 。所编《海虞诗话》收录清初至道光年间常熟诗人近 400 位，略宦达而重隐逸，突破前人选诗惯例，对女性诗人成就予以肯定，意在阐幽而作 。其诗作《溪上》《漫兴》等以清丽意象展现晚唐风格。
191. /冯元飏/ （1586 年—1644 年），字尔赓，又字元冲、元仲、言仲，号留仙，浙江宁波府慈谿县（今慈城）人，明朝政治人物，进士出身。万历四十六年（1618 年）戊午科浙江乡试举人，崇祯元年（1628 年）登戊辰科进士，授工部都水司主事，不久上疏告归还乡。但很快就起任为礼部主事，进员外郎，迁苏松兵备参议。后迁福建提学副使。当朝大臣同族之子弟在乡里横行，冯元飏将其绳之于法，得罪廷臣，因而谪山东盐运司判官。崇祯十一年（1638 年）辽东告急，山东守备紧急，因而摄济宁兵备事。崇祯十四年（1641 年）迁天津兵备副使。同年十月，擢右佥都御史、任天津巡抚，兼督辽饷。崇祯十五年（1642 年）因军功荫一子为锦衣卫。当时其弟 /冯元飚/ 已任兵部尚书，掌朝廷中枢。冯元飏以年老上疏辞职告归，但崇祯帝多有挽留，待之甚厚。与弟冯元飚并称“二冯”。不久京师城陷，冯元飏从海路撤退，回到家乡。崇祯十七年（1644 年）九月秋，卒。
192. /冯元飚/ ，（1598 年 6 月 22 日－1644 年 10 月 10 日），字尔弢，号邺仙，浙江宁波府慈谿县（今浙江省宁波市江北区慈城镇）人，明朝末年兵部尚书。  冯元飚出身慈城望族，天启二年（1622 年）中进士，丁父忧归，服阙补揭阳县知县，平流寇、兴文教，崇祯四年（1631 年）召为户科给事中，民立生祠纪之。在谏垣敢言，反对宦官监军，劾首辅周延儒等人，又为翰林姚希孟等谪臣辩护，帝不从，告假归。八年（1635 年）入朝，屡劾首辅温体仁、次辅王应熊等敷衍塞责、欺上瞒下， 后又为受首辅张至发排挤的黄道周辩护，多为帝采纳。十一年（1638 年）升太常寺少卿，自请外放为南京太仆寺卿以避当权，升南京通政使，十四年（1641 年）入朝为兵部右侍郎，升左侍郎。冯元飚多智略，尚权谲，转与首辅周延儒交好，献策欲助其党羽兼通谱冯铨入阁。陈新甲入狱，冯元飚代理兵部。崇祯帝西苑论兵，冯元飚奏对称意，拟擢兵部尚书，以病辞，乃用张国维。十六年（1643 年）五月张国维入狱，冯元飚代之。时清军、流寇南北夹击，冯元飚无计可施，加之身染重病，八月即以病辞，仍舆疾口画，十月末始归。十七年（1644 年）甲申之变，冯元飚闻之不再服药，至九月去世，晚兄冯元飏十日卒，年仅 46 岁。  冯元飚自幼气弱形羸，立骨见衣表，为官期间多次突发晕厥，晚年更两足枯萎，无力下床。然颇能料事，孙传庭治兵关中，力主不可轻易出战，帝不听，传庭果败；后推李邦华、史可法自代，帝亦不从，用误国之张缙彦以至城陷 。有《冯太保文集》五卷传世 。
193. /李邦华/ （1574 年～1644 年 4 月 25 日），字孟闇，一字懋明，江西吉水盘谷镇谷村人，明末大臣。李邦华受业于同里邹元标， 万历三十二年（1604 年）中进士。授泾县知县，有异政，授监察御史。以敢言闻名。天启时，以右佥都御史巡抚天津。军府新立，庶务草创，极力振饬，津门军遂为诸镇冠。崇祯初，任兵部侍郎，锐意改革，戎政大饬，不久罢职。后起为左都御史。李自成入京师，自缢于信国祠。赠太保、吏部尚书，谥忠文。清朝谥忠肃。
194. /汪珂玉/ （1587－?）字玉水，号乐卿，自号乐闲外史，秀水（今浙江嘉兴）人。颜所居曰莲登草堂、韵石阁、青人巢。崇祯（一六二八－一六四四）中官山东盐运使制官。其父爱荆，与项元汴交好，筑“凝霞阁”以贮书、画，收藏富甲一时。他又广为搜罗，别置“莲登草堂”、“韵石阁”等。并就其所藏及闻见所及，撰《珊瑚网》，崇祯间成书，收录并评记所见书画之得失。崇祯十六年（一六四三）成书。朱彝尊称其堪与清河书画舫、真迹日录并驾。亦工诗，万历四十七年（一六一九）与魏仲雪、沈止伯于北山草堂结诗社。著作有《珊瑚网》、《画继》、《画据》、《画法跋》、《四部总录艺术编》等。
195. /温体仁/ （1574 年 1 月 1 日—1638 年 8 月 11 日），字长卿，号员峤、园峤，浙江乌程县（今湖州市）南浔辑里村人，明朝政治人物，进士出身。崇祯年间担任内阁首辅。崇祯朝阁员五十人，唯温体仁最久。崇祯十年免职。卒谥文忠。     温体仁与礼部侍郎周延儒两人在崇祯帝朱由检即位之初选择阁辅时，以钱谦益收贿名义打击钱谦益，并且全力打击钱谦益同党，而被不爱党争的朱由检信任，崇祯元年（1628 年）便与周延儒入阁并出任礼部尚书东阁大学士。而后来温体仁又排挤周延儒，并出任阁辅。温体仁善于利用朱由检的个性而当政八年，并得到朱的恩礼优渥，而且也以为温体仁是个不组党羽的孤立之士；但是“同官非病免物故，即以他事去”（同僚或者因病亡离职，或者被其他原因免职），引发朝臣的不满与批评；崇祯十年（1637 年）刘宗周等人上奏指出温体仁的十二大罪，而最后司礼监太监曹化淳向朱告密，指称温体仁自有党羽，朱大惊说“体仁有党”，最后免除温体仁的阁辅之职。崇祯十年（1637 年）六月，一日温体仁正在吃饭。忽有太监传旨，令削去温体仁官职。崇祯十一年（1638 年）温体仁病故乌程家中。《明史》有传。温体仁死后，崇祯帝赠为太傅，谥文忠。福王朱由崧即位于南京后便削其谥号，弘光元年（1645 年）三月又恢复了温体仁的谥号。
196. /薛国观/ （1582 年—1641 年），字家相，号宾廷，陕西韩城县人。明朝政治人物，万历末进士。崇祯间官至内阁首辅，建议皇亲国戚捐款以救国难，后因牵扯收贿案，被崇祯帝赐死，自经身亡。崇祯十年（1637 年）温体仁致仕，国观入阁成为宰辅，崇祯十二年二月刘宇亮罢官，国观进为首辅。崇祯十三年六月（1640 年）给事中袁恺上疏，揭发薛国观受贿，国观下狱，并牵连傅永淳、蔡奕琛等十一人。薛国观奏辩：“袁恺诬劾，出礼部主事吴昌时之意。”崇祯不听。最后锦衣卫左都督郭承昊前去宣布赐死，薛国观临死前说“吴昌时杀我”。薛国观是嘉靖首辅夏言被赐死之后，再次被赐死的首辅。国观死后，其同党为其辩护，鸣怨叫屈。
197. /杨嗣昌/ （1588 年—1641 年），字子微，号文弱，湖广常德卫（今湖南常德）人，祖籍直隶建平（今安徽郎溪）。明末政治、军事人物。出身门阀，祖父杨时芳乃武陵名士，父亲杨鹤以督军著世，嗣昌为人雅好文艺，博闻强记、有辩才、文笔，与名流袁宏道、袁中道、锺惺等来往。亦喜军事，设“四正六隅”之策以灭流寇，一度颇有成效，后流寇复起，李自成烹杀福王朱常洵，张献忠焚杀襄王朱翊铭，嗣昌忧悸以病卒，追赠太子太保。葬桃源金厂溪。
198. /项煜/ （1598 年—1645 年），字仲昭，号水心，直隶苏州府吴县人，明末政治人物。天启五年（1625 年）乙丑科进士。依附魏忠贤。选庶吉士，历官翰林院检讨。崇祯二年（1629 年）清军入塞，项煜就此弹劾兵部尚书王洽，引世宗斩丁汝夔旧例，主张严惩。崇祯帝遂决心将王洽下狱拟斩，王洽瘐死。崇祯十年（1637 年），项煜任东宫讲官，教授太子朱慈烺读书。又弹劾内阁首辅张志发把持考选，被崇祯帝逐出。官至詹事府少詹事兼翰林院侍读。崇祯十七年（1644 年），李自成破北京，项煜投降。大顺大学士黎志升原为项煜甲戌科所取进士，欲推荐其任高官。然而，项煜仅得授太常寺丞，十分沮丧。奉命祭祀泰山，驿驰至山东，变装南逃。项煜家为苏州巨富。五月，当地诸生声讨从贼乡官，项煜及大理寺正钱位坤、通政司参议宋学显、礼部员外郎汤有庆家皆被吴中士民给焚烧劫掠。福王在南京即位，项煜盛装参加朝贺，诸臣称怪。十二月，刑部尚书解学龙治从贼之狱，上六等定罪名单，项煜拟为“三等应绞拟赎者”。弘光元年（1645 年），清军破南京。六月，项煜逃亡浙东，至慈谿冯元飏家。当地有人以其为贼臣，投入桥下溺死。
199. /徐汧/ （？—1645 年），字九一，号勿斋，南直隶苏州府长洲县人，明朝、南明政治人物。少时孤贫，与同里杨廷枢相友善。复社同仁周顺昌被捕，徐汧以妻子的簪珥二十金赠之， 周顺昌叹曰：“国家养士三百年，如徐生，真岁寒松柏也”。徐汧雅好交游，蓄声伎，王稼是其家优。天启七年（1627 年）举丁卯科应天乡试，崇祯元年（1628 年）联捷戊辰科进士，改翰林院庶吉士，授检讨，迁右春坊右谕德、右庶子，升侍读学士，充经筵讲官。南明时，官至少詹事，上陈时政七事。后被安远侯柳祚昌弹劾。清顺治二年、 南明弘光元年（1645 年），南京、苏州、常熟相继被清军攻占，徐汧慨然叹息，告诫其子徐枋说：“吾不可以不死，若长为农夫以没世可也”。说完整理衣冠，北向稽首，投虎丘新塘桥下死。 郡人赴哭者数千人，有一蓝衫老人随之死。谥文靖，清朝改谥忠节。
200. /杨廷枢/ （1595 年-1647 年），字维斗，号复庵，学者称皋里先生，南直隶苏州府长洲（今江苏苏州）人。明末抗清官员、学者。 杨廷枢幼承家学，深于治经。天启四年（1624 年），与杨彝、张溥等十一人于常熟共举应社，分治五经，其以治《尚书》见长。崇祯二年（1629 年），应社与江南诸文社合并成立复社，杨廷枢为社之中坚。 崇祯三年（1630 年），杨廷枢中解元，以文章气节负重名，为复社领袖之一。南明福王立后，授主事，因忤马士英、阮大铖罢归。弘光元年（1645 年），杨廷枢隐居邓尉山，联络抗清。于吴江芦墟泗洲寺被捕，题书血衣绝命词就义。时年 52 岁。编有《同文录》《古柏轩诗集》《全吴纪略》等。
201. /马世奇/ （1584 年—1644 年），字君常，号素修，直隶常州府无锡县人，明末政治人物，东林党人。马世奇幼年好学，有文名，天启四年（1624 年）举甲子科应天乡试，崇祯四年（1631 年）成进士，选为庶吉士，授翰林院编修。官至左庶子，清廉耿介，好扶掖后进；担任朝廷使者奉谕山东、湖广、江西诸藩时，世奇也是绝不接受贿赂馈赠。崇祯十五年，当周延儒再次复相时，他向马世奇询问时务要务，而马世奇则请他专注于蠲免拖欠赋税以苏民困，后来被周延儒实现。崇祯晚年，明廷陷入更严重的内忧外患之中，崇祯帝多次召问廷臣除寇之策，马世奇回答说：“闯、献二贼，除献易，除闯难。人心畏献而附闯，非附闯也，苦兵也。今欲收人心，惟敕督抚镇将严束部伍，使兵不虐民，民不苦兵，则乱可弭。”，上书受到崇祯帝的称赞。崇祯十七年三月十九日，京城被李自成攻破，马世奇回到家后叹息说“事不可为矣。”崇祯十七年（1644 年）李自成破北京，自缢死，二妾亦随死。赠礼部右侍郎，谥文忠。吴锺峦听说北京失陷，流涕说：“马君常必能死节”，果然如此。与龚廷祥、华允诚并称“锡山三忠”。清康熙十年，赐谥“文肃”，乾隆四十年，改谥“忠肃”。
202. /吴拭/ ，字去尘，居新安之上山。宗族多富人，去尘独好读书鼓琴，游名山水。仿易水法制墨，遇通人文士，倒囊相赠，富家翁厚价购之，辄大笑曰:“勿以孔方兄辱吾客卿也。 ”(寅恪检徐康《前尘梦影录.上》“虞山钱牧斋有蒙叟墨”条载牧斋门生歙人吴闻礼、闻诗兄弟，为牧斋制“为天下式”及“秋水阁”墨事。可供参考。）坐此益大困。耳聋头眩，为悍妇所逐，落魄游吴门。遇乱，死虞山舟中。毛子晋为收葬之。
203. /倪元璐/ （1594 年 1 月 7 日—1644 年 4 月 25 日），字玉汝，号鸿宝，浙江绍兴府上虞县人，军籍，明朝政治人物、书法家。与 /黄道周/ 、 /王铎/ 并称“明末书坛三株树”，又与 /王铎/ 、 /傅山/ 、 /黄道周/ 、 /张瑞图/ 并称“晚明五大家”。万历三十七年（1609 年）己酉科浙江乡试第六十六名举人，天启二年（1622 年）壬戌科二甲第二十名进士。子倪会鼎为其撰年谱。礼部观政，改庶吉士，倪元璐与马如蛟、黄道周等同出韩日缵门下。四年（1624 年）授翰林院编修，五年（1625 年）册封德藩，同年养病回籍。七年（1627 年）五月任江西乡试正考官。崇祯元年（1628 年）升翰林院侍讲，倪元璐请求毁去《三朝要典》，逐来宗道、杨景辰等阉党，并上书为东林党人辩护，又曾上书申救黄道周、刘宗周等人。升南京国子监司业，改右春坊右中允，四年（1631 年）升右谕德，充经筵讲官，五年（1632 年）倪元璐四次奏疏乞归，不准。曾说“吾平生不热爱官，不喜居要人牢笼之内”，七年（1634 年）升右庶子，八年（1635 年）改国子监祭酒，恢复祖制的贡士积分之法。其后被温体仁嫉妒，冠带闲住。崇祯十五年（1642 年）起为兵部右侍郎兼侍读学士，当其时正值清兵第六次入塞，邻近大乱，道路颇棘，倪元璐出金募壮士随行一路冲险北上。十六年（1643 年）抵达京师，崇祯帝得悉后，向其他人说“固知是吾倪讲官也”，即日召见面陈制敌机宜。当时，崇祯帝十分欣赏倪元璐，预备随时把他提拔为阁臣，而内阁大臣陈演恐怕他威胁自己，便进言说“天下不治，皆由于兵部和户部不合，今廷臣可任者，惟有倪元璐、冯元飚两人，假如元璐为户部尚书，元飚为兵部尚书，彼此合作，国家不日可治”，崇祯帝深以为然。同年五月，倪元璐擢户部尚书兼翰林院学士，充经筵讲官。任内倪元璐请求把征收三饷的官吏合三为一，以免越多官吏就越多机会作奸科，百姓得以稍缓。当时有崇明人沈廷扬向朝廷献计改漕运为海运，倪元璐把他的建议呈送崇祯帝，因而得以用湾船六船试行，一个月后，当倪元璐看见沈廷扬便惊讶说“我已经奏闻陛下，说你已经出发，你怎么还在这里？”沈廷扬则回复说“我已经去完回来，运送的物资亦已经抵达”，倪元璐大喜并上报崇祯帝，廷议今后海运和漕运相半而行，但后来未及实施就遭遇“甲申之变”。崇祯十七年（1644 年）正月，倪元璐上书请求让浙江乡绅团练乡兵，浙西由徐石麒、钱继登主持，浙东则推荐刘宗周、羌应甲主席；又在保甲中简练乡勇，实行古弓弩社法，崇祯帝赞同其言。同年二月，解任户部尚书，仍充经筵讲官。三月六日，李自成攻占宣府，从真定府绕道而出，倪元璐引用宋康王的故事，急请太子前往南京抚军，但未被崇祯帝接纳。三月十九日，李自成攻陷京师，倪元璐荡尽家产，募得数百死士，驰赴北京勤王。倪元璐入都时，强邀祝汤龄前往，但被婉拒。倪元璐得知崇祯帝自缢后，便“束带向阙，北谢天子，南谢太夫人”，又在桌子写下“南部尚可为。死，吾分也。毋紟棺，以志吾痛”，随后自缢而亡。南明弘光年间追赠少保、吏部尚书，谥文正。清朝改谥文贞，赐地七十亩，命有司春秋致祀。
204. /冯铨/ （1596 年—1672 年），字伯衡，又字振鹭，号鹿庵，顺天涿州（今河北涿州市）人，中国明清之际的贰臣、收藏家。明万历进士，授检讨。 天启五年（1625 年），谄事魏忠贤，以礼部侍郎兼东阁大学士入内阁，不久即晋尚书，加少保兼太子太保，次年因得罪崔呈秀而被罢免。崇祯初以谄事魏忠贤，赎徙为民。顺治元年（1644 年）降清，令以大学士原衔入内院佐理机务。次年，授内翰林弘文院大学士兼礼部尚书。顺治十三年（1656 年），加太保致仕，仍留备顾问。顺治十六年（1659 年），改设内阁，命以原衔兼中和殿大学士。康熙十一年（1672 年）卒于涿州。谥文敏。
205. /徐波/ （1590 年—1663 年），字元叹，苏州府吴县（今属江苏）人，明末清初遗民诗人，竟陵派重要成员，明诸生。谭友夏曾书其门为“落木庵”。著有《浪斋新旧诗》等诗文集，另有《谥箫堂》《染香庵》等集。《清史稿·文苑传》有其小传。其诗作长期散佚，2020 年整理出版的《落木庵诗集辑笺》收录其诗六百余首。徐波于万历四十七年结交竟陵派创始人钟惺，因茶诗传情结为忘年之交，其早期诗风获钟惺“似古人”之评。明亡后隐居吴县天池，构落木庵，以枯禅终。与钱谦益交好，钱氏在《有学集》中赠诗推重，有“江东留得一徐波”之句。诗歌创作继承竟陵派幽深孤峭风格，其“客来灯是主，叶落寺无邻”句被评凄清寒峭。
206. /顾凝远/ （约 1580—1655），字诞伯，号青霞，是晚明时期典型的文人画家，出身苏州仕宦世家，精研画理并自设诗瘦阁刊刻《画引》一书。
207. /瞿九思/ （1546 年—1617 年），字睿夫，号慕川，黄梅人（今湖北省黄冈市黄梅县），明代理学家。著有《乐章》、《万历武功录》、《孔庙礼乐考》五卷、《书经以俟录》六卷、《诗经以俟录》六卷、文集七十五卷。
208. /魏禧/ （1624—1681)，字冰叔，号裕斋、勺庭，江西宁都人。 明末清初历史人物，与侯朝宗方域、汪琬合称“明末清初散文三大家”， 与兄魏祥、弟魏礼并美，世称“三魏”，与彭士望、林时益、李腾蛟、邱维屏、彭任、曾灿等合称“易堂九子”，多次参加抗清斗争。 康熙十九年十一月十七日（1681 年 1 月 6 日），去世，时年五十七。魏禧论文主张经世致用，积理、练识，长于策论等以广大胸怀而谋天下之事的文体，同时对其它文体的创作有所心得，并且写出了煌煌百万字的作品。 文章多颂扬民族气节人事，表现出浓烈的民族意识。还善于评论古人的业迹，对古人的是非曲直、成败得失都有一定的见解，著有《魏叔子文集》22 卷，《诗集》8 卷，《日录》3 卷，《左传经世》10 卷，《兵谋》《兵法》各 1 卷，《兵迹》12 卷。 散文作品有《邱维屏传》和《大铁椎传》等。
209. /汪琬/ （1624 年—1691 年），字苕文，号钝翁，号尧峰、玉遮山樵，江南长洲县（今江苏省苏州市）人，曾结庐居于太湖尧峯，学者称尧峯先生。明末清初散文家、政治人物。清顺治十二年进士。康熙时举博学鸿词科，授翰林编修。与侯方域、魏禧合称“清初三大家”。天启四年（1624 年）生于官宦之家，曾参与复社事。顺治十二年（1655 年）中式乙未科会试，殿试位列第二甲第四十六名进士出身。历任户部主事、刑部郎中。康熙十八年（1679 年），召试博学鸿词科，授翰林院编修，预修《明史》，在馆六十余日。乞病归。晚年结庐于太湖之尧峰山，闭户撰述，不问世事。康熙二十九年（1691 年）卒。与侯方域、魏禧合称明末清初散文“三大家”，“然禧才纵横，未归于纯粹，方域体兼华藻，惟琬学术最深，轨辙复正。”其散文疏畅条达，论文要求明于辞义，合乎经旨，所谓“扬之欲其高，敛之欲其深”，论者以为其文风深受欧阳修的影响，而近于南宋诸家。计东认为“若其文章，溯宋而唐。明理卓绝，似李习之；简洁有气，似柳子厚”。康熙曾称赞他：“尝与近臣论本朝文学砥行之儒，首称数先生。”代表作有《陈处士墓表》、《尧峰山庄记》、《绮里诗选序》、《江天一传》、《书沈通明事》等。著有《钝翁类稿》，晚年自订为《尧峰文钞》。
210. /张潮/ （1650 年—1707 年），字山来，一字心斋，号仲子，自称三在道人，安徽省徽州府歙县人，清朝文学家、小说家、刻书家。张潮出身门阀。少年能文，与冒襄、孔云亭、陈维崧等名士有诗文往来，言论诙谐，观点精辟，处世潇洒，交友不拘，姑苏孝廉张为泉曰：“老子化胡，潮子化吾；我心斋兄，自化化人，自娱娱人。”1699 年夏，（康熙三十八年）张潮因政治原因被人告发下狱。但在‘清史稿’该年并无与此事有关的记录，因此张潮入狱的原因，难以详加探求。康熙二十四年（1685）江淮发生洪涝惨祸，张潮为其事写下‘苦雨行’，描写怵目惊心的惨象，诗中表达对满淸政策不当与天灾的愤懑，是一首珍贵的纪事诗。由于张潮有这些对淸政府的明显不满的内容与‘昭代丛书’中表现触犯封建礼敎的作品，张潮的《心斋聊复集》、《笔歌》、《奚囊寸锦》、《昭代丛书》四种，在乾隆四十六年十一月初六日，被选定两江总督萨载奏准禁缴的三十三种书中。故张潮遭到政治案件牵连而入狱可能与其言论不无关系。张潮不喜八股文，苦读不第，后补官，仅至翰林院孔目。张潮著作等身，著名的作品包括《幽梦影》、《虞初新志》、《花影词》、《心斋聊复集》、《奚囊寸锦》、《心斋诗集》、《饮中八仙令》等。文章风格简单明白、内容深长，广为众人接受，其著作重视“真”，张潮认为文章要有真情真意，无论四书五经或是小品散文都同样具有价值。
211. /杜文焕/ （？-1645 年）， 字弢武，陕西延安卫籍，明末清初昆山人。 都督杜桐之子，总兵杜松之侄。明末将领。 杜文焕由荫叙历延绥游击将军，累进参将、副总兵。明万历四十三年（1615 年），擢署都督佥事、宁夏总兵官。次年，镇延绥，屡败入犯蒙古诸部，以病归。天启元年（1621 年），杜文焕再镇延绥。加四川总兵，援成都平奢崇明叛建功。天启二年（1622 年），擢总理，统川贵湖广军，坐延绥失事罪戍边。天启七年（1627 年），起镇宁夏，援辽东分镇宁远，晋右提督，因病去职。崇祯元年（1628 年），录功荫指挥佥事。崇祯三年（1631 年），其署延绥镇总兵，兼督固原军镇压农民军，为提督兼统山陕军。崇祯五年（1633 年），杜文焕被劾下狱。崇祯十五年（1643 年），起原官，辞归。崇祯十七年（1645 年），加太子太保统兵入援。南明福王立，以原官佥书中府，提督京城巡捕营，进少保、少师兼太子太师。入清隐居昆山，同年去世。 杜文焕善骑射，精兵法，兼通《左氏春秋》，旁及诸子百家，诗工六朝、初唐诸体。著有《太霞洞集》《五岳志概》《餐霞漫笔》《六韬广义》《太霞集选》《八溪集》《弢武全集》等。
212. /郑芝龙/ （1595 年/1604 年 4 月 16 日—1661 年 11 月 24 日） ，初名国桂，小名一官，字曰甲，又字（一说号）飞皇（亦作黄、虹）。 天主教名尼古拉，福建南安石井镇人，祖籍河南固始，明末清初海商、武将。 郑芝龙早年闯荡澳门，学习葡萄牙语，并前往日本经商，娶日本女子田川松为妻，生郑成功。后随颜思齐等至台湾建立寮寨，屡败明朝官军。崇祯元年（1628 年）受明廷招抚，任海防游击，陆续平定李魁奇、杨六、杨七等海上势力，崇祯六年（1633 年）在金门料罗湾击败荷兰与刘香联合舰队，累升福建总兵、都督同知。明亡后，南明弘光政权封其为南安伯。弘光元年（1645 年，隆武元年，清顺治二年）拥立朱聿键，建立隆武政权，封太师、平虏侯（后累升平国公），排挤首辅黄道周，掌握军政大权。次年清军入闽，郑芝龙不听其子郑成功劝告而降清，被挟至北京，封同安侯，后因郑成功拒降而被削爵下狱，流放宁古塔。顺治十八年（1661 年）与四个儿子一起被杀。   郑芝龙移民开发台湾，建立海上贸易网络，规定商船需持郑氏令旗通行，年收入达千万金。他与其子郑成功继承发展壮大的郑氏海商集团雄踞海上，并在与荷兰东印度公司的博弈中胜出，成为 17 世纪全球市场中最活跃的海商力量之一。
213. /刘香/ （？－1635 年），又名刘香佬，广东省香港南丫岛人，为郑芝龙组“十八芝”武装海商集团成员之一，因拒绝降明遂与昔日拜把契兄弟郑芝龙于 1629 年（明崇祯二年）决裂，与郑芝龙代表的明朝、荷兰买办代表，刘香适为佛朗机(西班牙、葡萄牙)买办代表，在 1635 年（明崇祯八年）与郑芝虎在广东海上战斗时以渔网网住芝虎，在郑芝龙面前丢至海里，片刻后刘香也举枪自尽，成为最后一位被收服之海盗，为自 1625 年在台湾结义、曾经叱吒世界大航海时代风云的十八芝，谱上些许伤感的休止符。 *十八芝* 是明朝天启五年（1625 年）十二月初二，在台湾北港溪出海口，由郑芝龙与十七位华人海盗结拜形成的武装海盗集团 。其名源自江日升《台湾外纪》，因郑芝龙在颜思齐死后于十八日被推为首领，故选取十八位先锋，其余成员名讳均以“芝”字加神兽为序。该集团成立水师军后，曾击败明朝水师提督俞咨皐统领的福建、浙江水师及买办商人许心素。后因招安问题内部分裂，李魁奇、刘香等头目率部叛逃，并与郑芝龙发生冲突。
214. /郑成功/ （1624 年 8 月 27 日—1662 年 6 月 23 日） ，本名森，又名福松，字明俨，号大木。 福建泉州南安人，祖籍河南固始。 汉族，明末清初军事家，抗清名将，民族英雄。其父郑芝龙，其母名田川氏。因蒙隆武帝赐明朝国姓“朱”，赐名成功，并封忠孝伯，世称“郑赐姓”“郑国姓”“国姓爷”，又因蒙永历帝封延平王，称“郑延平”。 郑成功是弘光时监生，1645 年（清顺治二年，弘光元年）清军攻入江南，不久郑芝龙降清、田川氏在乱军中自尽。郑成功率领父亲旧部在中国东南沿海抗清，成为南明后期主要军事力量之一，一度由海路突袭、包围清江宁府（原明朝南京），但终遭清军击退，只能凭借海战优势固守泉州府的海岛厦门、金门。1661 年（清顺治十八年，永历十五年）率军横渡台湾海峡，翌年击败荷兰东印度公司在台湾大员（今台湾台南市境内）的驻军，收复台湾，开启郑氏在台湾的统治。以赤嵌城为东都，建立府县，编制军队，屯田垦荒，奖励移民， 推进了台湾经济的发展。 1662 年（康熙元年），郑成功在收复台湾四个月后，突然暴病而亡，年仅 38 岁。  子郑经嗣位。 初葬台南州仔尾，后迁葬于故乡南安的覆船山。 海峡两岸均立像树碑纪念。有《延平王集》行世。
215. /郑鸿逵/ （1613 年—1657 年），原名芝凤、芝彪，字曰渐，又字圣仪，号羽公。福建南安人，明平国公郑芝龙四弟，郑成功的叔父。 明朝将领。郑鸿逵于明崇祯三年中武举人，后又中崇祯十三年武进士，累官至登州副总兵。南明弘光朝建立后，加总兵官，驻镇江，以舟师扼守长江口，击高杰乱兵有功，封靖虏伯。弘光政权覆亡后，郑鸿逵引师南下。旋与郑芝龙拥立唐王于福州，封定国公。后因拥兵自重，避敌不前，郑鸿逵被削爵，不久因太子生，复爵，又晋漳国公，改定国公。隆武政权覆亡后，郑鸿逵与侄郑成功合兵抗清。永历四年（清顺治七年，1650 年），因纵放清军将领马得功，交出兵权，退居白沙，曾拒清廷诱降。清顺治十四年（南明永历十一年，1657 年），郑鸿逵卒于金门。
216. /范景文/ （1587 年 11 月 29 日-1644 年 4 月 25 日），字梦章，号质公，又号思仁，河北吴桥人。中国明代政治家、文学家。明万历三十七年（1609 年），中举，明万历四十一年（1613 年），进士。授东昌府推官。明万历四十七年（1619 年），入为吏部稽勋司主事，调验封司，转考功司。泰昌元年（1620 年），晋吏部文选司员外郎，升吏部验封司郎中，群贤进用。后托病辞官。天启五年（1625 年），起为吏部文选司郎中。次年，升礼部太常寺少卿，提督四夷馆，丁内忧归。崇祯二年（1629 年），任太常寺少卿，调任都察院右佥都御史，巡抚河南，京师戒严，率所部勤王。升兵部左侍郎，练兵通州。崇祯五年（1632 年），归乡为父守制。崇祯七年（1634 年），服除，任南京都察院右都御史，拜兵部尚书，参赞机务。崇祯十一年（1638 年），以救黄道周等触帝怒，削籍为民。崇祯十五年（1642 年），召复原官，道中转刑部尚书，旋改工部。崇祯十七年（1644 年），兼东阁大学士，入参机务，李自成入京师，投双塔寺旁古井而死，时年 58 岁。范景文文武全才，居官持正不阿，为世所称，国事多艰，殚精竭虑，厉兵秣马，带兵有度。其诗文方面颇有造诣，著作有纪事本末体史书《昭代武功编》10 卷，兵家类著述《战守全书》18 卷、《师律》16 卷，诗文集《文忠集》12 卷，文集《范文忠公文集》10 卷，文集《范文忠公文集》9 卷，稿本《范文忠公文稿》不分卷等。
217. /刘泽清/ （1603—1648 年），字鹤洲，一作雀洲，山东曹县人。刘源清之兄。明末清初将领，江北四镇之一（明末清初南明政权的淮安、扬州、庐州、泗州等四个重要军区。其主要领导为黄得功、刘良佐、高杰，以及刘泽清。）。官职从守备累迁总兵、左都督。崇祯八年（1635 年），他统制山东兵防漕运，镇压地方农民起义军。崇祯十六年（1643 年），他率师增援开封府，与起义军接战三日，随后拔营而去。李自成破京城后，他南遁江淮，到处焚掠，并与马士英、高杰等拥立福王（朱由）。南明弘光帝命他驻庐州（今安徽合肥），镇守淮北，封为东平伯。弘光元年（1645 年）清兵南下，扬州告急，命他前往增援，他却已先行投降清兵。后又谋反清，被杀。
218. /朱大典/ （1581 年—1646 年），字延之，号未孩，金华长山村人，明末抗清名臣。万历四十四年（1616 年）进士，初授章邱知县，立升至兵部右侍郎，总督漕运，巡抚凤阳。后遭弹劾，归故里。福王即位于南京，以原官任职，曾奉命抵御左良玉的叛军。南京沦陷后不久，清军进攻金华，大典督军抵御，城破，自焚死。
219. /左良玉/ （1599 年—1645 年），字昆山，山东临清人。明朝末年将领。 左良玉年少时早孤，虽不识字，但多智谋，善抚士卒。 初为辽东车右营都司。明崇祯元年（1628 年），率军援辽与后金军作战。不久奉调山西、河南等地镇压农民起义军，渐升至总兵。后在镇压农民军的战争中，不断扩大部队，日益骄横跋扈，拥兵自重。崇祯十三年（1640 年）春，以督师杨嗣昌推荐拜为平贼将军。统兵与陕西明军挫败张献忠军于玛瑙山，因功加太子少保。 崇祯十五年（1642 年），与李自成农民军战于河南朱仙镇等地，损失惨重，退兵至武昌，封为宁南伯。南明弘光政权建立后，晋封为侯，加太子太傅。 因其受知于东林党侯恂，权臣马士英、阮大铖担心东林党依靠左良玉、对己不利。后以“清君侧”为名进军南京，至九江，病重逝于军中。 其子左梦庚率所部降清。
220. /刘良佐/ （？-1667 年），字明辅，北直隶人（清代直隶省）。明末叛将。刘良佐初从李自成农民军，后降明，官至总兵，封广昌伯。清顺治二年（1645 年），清军南下，他率部十万降清，带兵俘虏弘光帝于芜湖，攻破江阴，大肆屠杀人民。清顺治五年（1648 年），以降功授世职二等精尼奇哈番，即二等“子”。后又转战至江西一带平息明军将领金声桓、王得仁军队，授散职。清顺治十八年（1661 年），授江南江安提督，加总官衔，寻政直隶提督，官至左都督。清康熙五年（1666 年），因病休官回乡，次年病故于左云。
221. /计六奇/ （1622 年-约 1687 年），字用宾，号天节子，别号九峰居士，无锡人，明末清初历史学家。 计六奇入清后，曾于顺治六年（1649 年）、顺治十一年（1654 年）两应乡试不第，从此放弃仕途，先后在无锡、苏州、江阴等地教书糊口，以教书认真而闻名乡里。后蓄意著述，除广泛搜集文字资料外，并访问故老，网罗遗闻佚事。自康熙五年（1666 年）起开始著述《明季北略》《明季南略》两书，缀草四载，誊次二年，至康熙十年（1671 年）始得告竣。计六奇大约卒于康熙二十六年（1687 年）。 计六奇所著《明季北略》《明季南略》两书系按编年次序系统记述明清鼎革史之作。《明季北略》二十四卷，记录了自努尔哈赤初起自清兵入关占领北京近五十年间的北方史事。《明季南略》十八卷，记述南明王朝二十余年的史事。两书收集宏富，叙事清晰，学术价值较高，是研究明末农民战争和明清之际民族斗争的重要历史资料。另著有《南京纪略》《粤滇纪闻》《金坛狱案》《辛丑纪闻》等。
222. /金声/ （1598 年 11 月 26 日—1645 年 11 月 25 日），字子骏，更字正希 ，小字三聘，号赤壁，南直隶徽州府休宁县瓯山人（今安徽省黄山市休宁县万安镇瓯山村），明末抗清义军首领。 金声负膂力，悦兵事，幼随父入籍湖广嘉鱼县，中崇祯元年（1628 年）进士，选庶吉士，始归休宁。己巳之变，金声与同官刘之纶荐僧申甫有奇才，擢山东道御史，参其军。然申甫兵未及练，而仓促对敌，全军覆没。言官交劾金声，崇祯帝嘉其敢于任事，仅令致仕。五年（1632 年），起山东道御史，与徐光启同修历法，未成。七年（1634 年）升山东佥事，未及赴任而母丧，丁内艰归。崇祯十六年（1643 年），以蓟辽总兵唐通荐，起金声翰林院修撰，未及入京而父丧，丁外艰归。清军攻陷南京，金声同门生江天一、推官温璜等率众在休宁起兵抗清，与宣城丘祖德、泾县尹民兴、贵池吴应箕、绩溪万曰吉等相照应，上表隆武帝，授右都御史兼兵部右侍郎。隆武元年（1645 年）八月，清军分三路围攻徽州府，金声等依凭丛山关险隘，固守绩溪，清兵久攻不克，后因文友黄澍出卖，失陷。拒降清，临刑前遥拜明孝陵后端坐饮刃。以好友熊开元请，赠金声礼部尚书，谥“文毅”，乾隆时赐通谥“忠节”。 金声著有《尚志堂录》《燕诒阁集》，门人辑有《金正希先生文集辑略》，嘉庆初出版官刻《金忠节先生文集》。
223. /熊开元/ （1598 或 1599-1676），湖广嘉鱼（今属湖北）人，祖籍金溪（今属江西）。字玄年，号鱼山，法名正志，号檗庵，一作蘖庵。郑敷教、徐枋师。明天启五年（1625 年）进士。授崇明知县，六年调吴江知县。崇祯四年（1631 年）授吏科给事中，疏请将王化贞正法，贬秩外调未任。十年起山西按察司照磨，历迁光禄寺监事、行人司副。十五年以劾首辅周延儒被廷杖下狱。十七年正月遣戍浙江杭州卫。南明福王立，赦居吴江，召授吏科给事中，未任。入福建抗清，唐王起为工科左给事中，擢太常寺卿、左佥都御史，进东阁大学士兼右副都御史，权理院事。隆武二年（1646 年）罢职，逃禅为僧。清顺治八年（1651 年）隐居苏州华山灵岩寺，为弘储嗣法弟子，因又号灵岩长老。曾主吴江华严寺、周庄永宁庵。葬于徽州黄山丞相原云谷监院。与葛芝等友。精内典，工书有文名。编次《戒法》，著有《华山纪胜集》《击筑馀音》《诸方语录》《檗庵别录》《鱼山剩稿》《鱼山疏稿》《壬癸罪状》《年谱》《示众语》等。
224. /叶廷琯/ （1791 年－1868 年），号调生、龙威遴隐，江苏苏州人，清代学者、篆刻家。精研印学，著有《吹网录》《鸥陂渔话》《闲涉印故》，篆刻风格苍劲。曾为李客山《归咏堂杂缀》作跋，记录其子叶道芬整理前人诗画论稿之事。同治七年卒，年七十余。叶廷琯以禀贡生候选训导，未显于仕途，毕生治学。汪日桢为其著作撰序，生平载于光绪本《苏州府志》。
225. /沈廷扬/ （1594 年－1647 年 7 月 2 日），字季明，号五梅，南直隶苏州府崇明（今属上海）人。少为诸生，慕忠义大节。崇祯中，以国子生为武英殿中书舍人，历官户部主事、郎中、兵部侍郎，好谈经济之学。辑《海运书》五卷以上。清军入关后，坚持抗清，曾造海舟试行，督舟师窥三吴，至鹿苑，遇风船坏，为清军俘杀，年仅五十三。
226. /卓尔康/ （1570 年－1644 年），字去病，号农山，浙江仁和人。明万历四十年（1612 年）中顺天乡试第七名举人，历任工部屯田司郎中、常州府检校、两淮盐运通判等职。初授祥符教谕，后任工部屯田司员外郎，因直言遭谗贬常州府检校，转大同府推官期间建言兵事。任两淮分司运判时因淮地赈灾直言罢归。早年考察黄淮水患著《河渠议》，撰《易学全书》五十卷（残本存台北中央图书馆）、《春秋辨义》三十八卷（收入《四库全书》）等。与徐孚远、高攀龙、钱谦益等东林党人交善，晚年关注辽东战事，明亡后悲愤而卒。
227. /许浩基/ ，字谷人，吴兴人，是近代著名的学者。有《文文山传信录》、《郑延平年谱》等。
228. /史可法/ （1602 年—1645 年），字宪之，号道邻，河南祥符（今河南省开封市）人，祖籍河南郑州市中牟县后史庄，明末政治家、军事家、抗清名将、民族英雄。 崇祯元年（1628 年）进士，任西安府推官。后转平各地叛乱。李自成攻占北京城后，崇祯皇帝自缢死，福王监国，授史可法为东阁大学士兼礼部尚书。及称帝，史可法因遭马士英等人排挤，自请出镇淮上，加太子太保，改兵部尚书、武英殿大学士。弘光元年（1645 年），清军大举南下。史可法由扬州至白洋河，部署诸镇抗敌军事。弘光朝廷大敌当前，犹内乱未已，总兵许定国诱杀高杰，率部投降清军。四月，大将左良玉以“清君侧”为名讨伐马士英，福王急召史可法入援，未至而良玉乱平。史可法奉命北返，闻盱眙降清、泗州城陷，遂奔扬州组织抵抗。城破，史可法自尽未死，为清军俘虏，不屈就义。 后人收史可法遗稿编为《史忠正公集》，清康熙间张纯修辑刻《史道邻先生遗稿》3 卷。1984 年，上海古籍出版社印行罗振常校补本《史可法集》。
229. /徐鼒/ （1810 年—1862 年），字彝舟，号亦才，江苏南京六合人，中国清代中后期史学家、经济学家。 清道光二十五年（1845 年），徐鼒中进士，曾参与镇压太平天国运动，历官翰林院检讨、实录馆协修官、福建福宁知府。其文集、著作为研究清史、南明史和清代经济、社会状况之重要文献，主要有《小腆纪年附考》二十卷、《小腆纪传》六十五卷、《务本论》两卷、《度支辑略》十卷、《未灰斋文集》八卷。《未灰斋诗文集》和《敝帚斋主人年谱》等。其中，《务本论》和《度支辑略》保存了许多清朝中后期国家财政经济方面的宝贵资料，是研究清代社会经济状况的重要文献。
230. /顾杲/ （1607-1645），字子方，号逋人，明常州府无锡（今江苏无锡）人，顾宪成从子。为人豪迈，好使酒骂座。吴应箕等为“留都防乱公揭”，讨阮大铖，杲列名于首。大铖得志，将捕之兴大狱。南都失守，事解。崇祯中，又为《号忠揭》，指国事逗留，触时忌不悔。杲散家财募士千人，取道江阴，乡人以为盗贼，集众御之，被杀。
231. /顾宪成/ （1550 年—1612 年），字叔时，号泾阳，世称泾阳先生或东林先生。南直隶无锡（今属江苏）人。明朝后期官员、思想家。顾宪成初学于张淇门下，后师事薛薛应旂。明神宗万历八年（1580 年）进士，授户部广东司主事。与魏允中、刘庭兰并称“三元”，言时政得失，无所隐蔽。万历十五年（1587 年），因上疏“分别小人，刺及时政”，被贬为湖广桂阳州判官。万历二十年（1592 年），擢吏部考功司主事。后因在立太子与推阁臣问题上与神宗及权臣抵牾，被革职归里，从事著述。后与高攀龙、顾允成、钱一本等重建东林书院，讲学其中，议论朝政。并创立东林学派，以“风声、雨声、读书声，声声入耳；家事、国事、天下事，事事关心”为座右铭。朝野士大夫多相应和，东林之名大著。及魏忠贤擅权，凡附东林者皆以“东林党”之名横加迫害，惨遭杀戮或禁锢，早已病逝的顾宪成也被追削官职。崇祯初获平反，追谥“端文”。顾宪成学宗程、朱，认为朱熹是继孔子之后集儒学大成之圣人，周敦颐创建理学之功不在孔孟之下，然其学不守门户之见，对陆、王之短长与朱熹之不足持公平态度。力排佛学之非，批评王守仁“无善无恶”之说是来自佛学禅宗。反对不学不虑的见成良知说，提倡“躬行”“重修”的修养功夫。强调治世，反对出世，要求讲学和结社自由，发出“外人所是，庙堂必以为非；外人所非，庙堂必以为是”和“天下之是非当自之天下”的呼声。其著作有《小心斋札记》、《顾端文公遗书》等。
232. /顾大章/ （1576～1625.10.19），字伯钦，号尘客，南直隶苏州府常熟县（今江苏省苏州市常熟市）人。万历三十五年（公元 1607 年）进士。天启元年刑部员外郎署山东司事。因刚正不阿，为魏忠贤阉党所忌恨，遭陷害，遂引疾归里。天启五年，起官任礼部郎中、陕西按察使。后阉党擅权，又遭陷害。与杨涟、左光斗、魏大中、袁化中、周朝瑞同时入狱。在刑部狱中，提笔作联曰：“故作风波翻世道，长留日月照人心。”后受酷刑而死。与同为阉党所害的魏大中、杨涟、左光斗、周朝瑞、袁化中并称“前六君子”。弟顾大韶，字仲恭；子顾麟生，字玉书。
233. /文秉/ （1609 年－1669 年），字荪符，号竹坞遗民，明代长洲（今江苏苏州）人。出身官宦世家，父文震孟为明代大学士，东林党成员，承荫为官生。崇祯十一年（1638 年）与黄宗羲等联名上书《留都防乱公揭》揭露阮大铖罪行。1644 年明亡后隐居竹坞不仕清朝，自号“竹坞遗民”，著有《烈皇小识》《先拨志始》《甲乙事案》《定陵注略》《先朝遗事》等。其中《烈皇小识》记录崇祯朝史事，主张改崇祯谥号为“烈宗正皇帝”，《先拨志始》分述万历至崇祯年间党争、梃击案等事件。
234. /侯恂/ （1590 年-1659 年），字太真，号若谷，河南商丘人，明朝官员，东林党人。 侯恂于明万历四十四年（1616 年），中进士，授行人。明熹宗即位后，为御史。明天启元年（1621 年），邹元标掌院事，倚侯恂为左右手。侯恂知人善用，明末大将左良玉、尤世威都曾得到他的提拔。贵州安邦彦反叛后，侯恂多次上疏方法策略。叙功准备升京卿，时魏忠贤擅权，剪除异己，侯恂被视为东林党魁，与父太常侍卿侯执蒲，弟翰林院编修侯恪，先后削籍罢官。明崇祯元年（1628 年），起用侯恂为广西道监察御史。己巳、庚午年间（1629 年-1630 年），侯恂由太仆寺少卿升兵部右侍郎。崇祯三年（1630 年），召侯恂升户部尚书，但被奸臣陷害下狱。崇祯十五年（1642 年），侯恂以镇压李自成农民起义军而释放出狱，起用为督师。兵败后，侯恂又被罢官，再次下狱。崇祯十七年（1644 年），农民军攻下北京，侯恂被从狱中放出。李自成等义军首领欲重用侯恂，但侯恂不拜。清兵入关后，侯恂逃亡江南。福王被立为南明皇帝后，欲捕杀侯恂。南明亡后，侯恂得以逃脱。清顺治三年（1646 年），侯恂归乡里，隐居南园。清顺治十六年（1659 年），侯恂去世，终年 70 岁。
235. /侯方域/ （1618 年—1655 年 1 月 20 日），字朝宗，早年号杂庸子，河南商丘人。明末清初文学家、 诗文作家。侯恂之子。明崇祯五年（1632 年），侯方域回乡应童子试，县、府、道皆第一。崇祯十二年（1639 年），入南雍，应江南乡试，举第三，以策语触讳黜。居乡期间，曾与同道徐作霖、吴伯裔等人结“雪苑社”以研习诗文。又与陈子龙、夏允彝等名士交游，积极参与复社社事活动。清顺治八年（1651 年），应河南乡试为副贡生。后归乡隐居，取室名为“壮悔堂”，寓壮年而悔之意。顺治十一年十二月（1654 年 1 月），侯方域因病去世，享年三十七岁。侯方域擅散文，在文论方面自成一家之言，提倡为文要学韩愈、欧阳修。认为作古文必由唐宋八家、《史记》《汉书》方可入古人境界。其著有《任源邃传》《徐作霖张渭传》等。现存文 100 余篇，涉序、书、奏议、传、记、论、策、墓志铭等多种文类，内容富赡。侯方域亦能诗，现存诗近 400 首，以甲申国变分前后两期，前期多感慨时事、忧民悯乱之作，如《禁旅十首》《闻乱八首》等，诗风雄浑慷慨，不乏苍凉之音；后期多书写亡国之痛、故国之思，如《过江秋咏八首》《春兴八首》等，诗风渐转深沉，或沉郁顿挫，或雄浑悲壮，老杜气象尽显。著有《壮悔堂文集》10 卷，《四忆堂诗集》6 卷，《补遗》1 卷。
236. /赵士春/ （1599－1675）字景之。江苏常熟人。明崇祯十年（1637）刘同升榜进士第三人。授翰林院编修。赵士春为赵用贤之孙。兵部尚书杨嗣昌“夺情”视事不久，竟被崇祯帝破格晋升为礼部尚书兼东阁大学士，参预机务，仍兼兵部事。当时何楷、黄道周、刘同升、赵士春、林兰友号“长安五谏”，先后上疏，均被罢官。赵士春被贬为广东布政司。后官复原职，终于左中允。
237. /赵用贤/ （1535 年 5 月 21 日 —1596 年 4 月 12 日 ），字汝师，号定宇，南直隶苏州府常熟县（今江苏省苏州市常熟市虞山街道）人，祖籍南直隶常州府江阴县（今江苏省无锡市江阴市），明朝中后期大臣、藏书家。 隆庆五年（1571 年）进士，选庶吉士，授检讨。万历五年（1577 年），首辅张居正父丧夺情，赵用贤上疏反对张居正不守父孝，削籍为民。万历十一年（1583 年）以原官起复，随即升为右春坊右赞善，历任司经局洗马、右春坊右庶子兼翰林院侍读、南京国子监祭酒、南京礼部右侍郎，万历十八年（1590 年）召还北京，任礼部右侍郎兼翰林院侍读学士，万历二十年（1592 年）进礼部左侍郎并教习庶吉士，次年改吏部左侍郎，旋移疾归。 万历二十四年（1594 年）三月，赵用贤去世，享年六十二岁。天启初年，追赠太子少保、礼部尚书，谥文毅。 赵用贤专修《大明会典》，纂《玉牒》。以经济自负，又崇阳明之学及李贽之论，性情刚烈。家富藏书 2000 余种，与其子赵琦美开常熟私家藏书风气之先。印刻《五经》《管子》《韩子》《玉海》等书，后人视为善本。诗文名于一时，王世贞曾将其与王行、石星、黎民表、朱多煃列为“续五子”，又列其为“末五子”之首。 赵用贤论诗提出“师心独运”，又云“声诗之道，其本在性情”，所作亦不再全袭复古之旧路。著作有《奏议》1 卷、《文集》30 卷、《诗》6 卷。另有《国朝典章》《三吴文献志》等。
238. /王应熊/ （1589 年-1647 年），字非熊，号春石，四川巴县人乐碛青溪里（今重庆市渝北区洛碛镇）人。极聪慧，少家贫，力学，四川按察使、《蜀中广记》作者曹学佺非常器重他，并亲自教学。万历四十年（1612 年）举人，万历四十一年（1613 年）进士。官至礼部尚书兼东阁大学士、兵部尚书兼文渊阁大学士，督川、湖、云、贵军务，卒赠太保、建极殿大学士，谥号“文恪”。王应熊博雅能文，尤工诗，著有《春石集》。
239. /屈大均/ （1630 年 10 月 10 日－1696 年 6 月 27 日），初名邵龙，又名邵隆，号非池，字骚余，又字翁山、介子，号莱圃，广东广州府番禺县（今广州市番禺区）人，广府名人。明末清初著名诗人、学者，与陈恭尹、梁佩兰并称“岭南三大家”，有“广东徐霞客”之称，代表作包括《广东新语》《翁山诗外》《皇明四朝成仁录》《翁山易外》等著作。屈大均早年随父归原籍番禺，恢复屈姓，更名大均；1648 年投奔陈邦彦参与抗清活动，失败后于 1650 年削发为僧，法名今种。北游期间遍历湖南、江西等地，后参与郑成功抗清。康熙十二年（1673 年）投军吴三桂反清，后辞归著述 。康熙二十二年（1683 年）台湾郑克塽降清后，屈大均归番禺专注于整理广东文献，摒弃传统“岭南”称谓而采用“广东”命名著作，编纂《广东文集》《广东文选》《广东新语》等作品 ，其中《广东新语》被潘耒评价为“考方舆，披志乘，验之以身经，征之以目见”，其诗学理论秉承儒家思想，主张以诗言道，强调诗歌需融合“丽”与“则”的美学标准，善用比兴手法追求诗画境界与中和朴素之美。晚年拒绝清廷博学鸿词科考试，存世诗歌 6700 余首、词 300 余首，顾炎武评其“弱冠诗名动九州” 。
240. /梁章钜/ （1775 年-1849 年），字闳中，又字茝林（邻），又号古瓦研斋，晚号退庵居士、退庵老人等。 祖籍福建福州府长乐县（今福建省福州市长乐区），生于福州府城。 其先祖于清初迁居福州市区。 清代学者、 诗文作家、 书法家、书画鉴藏家、 官员。 梁章钜于嘉庆七年（1802 年）中进士，升礼部主事。嘉庆二十一年（1816 年），考取军机章京。历任湖北荆州知府、江苏按察使等职。在江苏 7 年，四度代理巡抚。道光十一年（1831 年），江淮大水灾，逃难者沿江而下，日聚万人，梁章钜捐资劝募或派船护送，或开厂留养，自七月至十月，救济难民约 60 余万人。次年四月辞职，在福州黄巷造黄楼，日与诗文为缘。道光十五年（1835 年）五月，奉旨入京，授甘肃布政使。次年，升任广西巡抚，配合林则徐查禁鸦片。道光二十一年（1841 年）二月，英兵侵逼广州，梁章钜送运大炮 40 门，协助抗英。 道光二十二年（1842 年），因病辞官。归田后，专事著述。 后于道光二十九年（1849 年）病逝，年 75 岁。 梁章钜上疏主张重治鸦片囤贩之地，强调“行法必自官始”，并积极配合林则徐严禁鸦片，是坚定的抗英禁烟派人物，也是第一个向朝廷提出以“收香港为首务”的督抚，是一位政绩突出、深受百姓拥戴的官员。晚年从事诗文著作，一生共著诗文近 70 种，其在楹联创作研究方面的贡献颇丰，乃楹联学开山之祖。著有《浪迹丛谈》等。
241. /邵长蘅/ （1637 年-1704 年），一名衡，字子湘，号青门山人，武进（今江苏常州）人。诸生，因江南“奏销案”被罣误除名 ，后入太学，考授州同不就，以布衣终。著有《青门簏稿》《旅稿》《剩稿》，总题为《青门集》 ，另有《清史列传》行于世 。邵长蘅早年诗学唐人，后改学宋人，诗风由慷慨激越转向受王士禛神韵诗影响 。康熙十八年（1679 年）客游京师，被王泽弘延请至幕府，结交王士禛、施闰章、李天馥、宋荦、毛奇龄、陈维崧等名流。康熙三十一年（1692 年），应江苏巡抚宋荦之邀入其幕府，直至去世  。其间曾构筑青门草堂 。其诗学理论主张诗歌贵有“自得”，强调转益多师；古文理论注重溯源经史、重经博学。散文继承唐顺之、归有光传统，与侯方域、魏禧齐名，为王士祯、汪琬所称 。曾参与编纂《国朝三家文钞》并撰《侯方域魏禧传》。
242. /杨文骢/ （1596 年—1646 年），字龙友，号山子、雪斋、阿龙、鹤巢，贵州人，明代画家。流寓金陵（今南京）。万历四十七年（1619）举人，六次会试不中， 崇祯七年（1634）选为华亭县教谕，后迁青田、江宁、永嘉等知县。为御史詹兆恒参劾被夺官。杨文骢博学好古，善画山水。为“画中九友”之一。生于贵筑，独破天荒，所作台蕖等图，有宋人之骨力去其结，有元人之风雅去其佻，出入巨然、惠崇之间。杨文骢卓才绝艺,皆因他的诗、书、画三绝,还有精于骑射。杨文骢的诗作传世的有《洵美堂诗集》，刻于崇祯十五年，而 9 年前夏云鼎编选刊刻《崇祯八大家诗选》时，列杨文骢为一家，另外 7 人是董其昌、陈继儒、王思任、曹学佺、李明睿、谭元春、季孟莲，可见当时他的诗名之盛。
243. /曽化龙/ ，（1588-1650），字大云，号霖寰，明末清初·晋江县霞淮里（今丰泽区霞淮社区）人，生于明·万历十六年（1588 年）。清·顺治七年（1650 年，六月初一日）卒于家，年六十三。万历四十七年己未（1619 年）联捷中庄际昌榜进士。历任临川令，擢御史，宁国同知、南户部员外、兵部郎、督学广东、广西参议、江西副使，（江西）粮储道，兼巡视漕河、佥都御史巡抚登莱。与钱谦益交好。
244. /曾樱/ （1581 年-1651 年），字仲含，号二云，江西峡江人。明末政治人物。万历四十四年（1616 年）进士。历工部主事、郎中，常州知府，福建参政等职，崇祯十四年（1641 年）升右副都御史、巡抚登莱。后因失地下狱。隆武时起为工部尚书兼东阁大学士。小朝廷灭亡后，携家避难于海外中左所（今厦门），1651 年，清军来攻，自缢死难。《明史》卷 276 有传。
245. /张肯堂/ （？－1651 年），字载宁，号鲲渊、鲵渊。南直隶松江府华亭县（今上海市）人，明朝末年政治人物。天启五年（1625 年）进士。授河南浚县知县。崇祯七年（1634 年）擢御史。崇祯十五年（1642 年）迁大理寺丞，不久擢都察院右佥都御史，巡抚福建。清兵入关后追随南明隆武帝，隆武被清兵俘虏后，肯堂遁入舟山，随宗室鲁王朱以海，曾为大学士，永历五年（1651 年），清军破舟山，张肯堂自杀殉国。 /朱舜水/ 为其学生。
246. /熊文灿/ （1580 年-1640 年），字太蒙，号心开，明末大臣。贵州永宁卫军籍，四川泸州人。 明后期官吏。 熊文灿于 1606 年中举人，1607 年，其以第三甲第七十四名（总第 148 名进士），授湖广黄州（今湖北省黄岗市黄州区）推官，行取为礼部精膳司主事。1609 年，升本部仪制司员外郎。1620 年，再升祠祭司郎中。1628 年，起福建左布政使，三月，拜右佥都御史，巡抚其地。1633 年二月，擢其兵部右侍郎、右佥都御史，总督两广军务，兼巡抚广东。1637 年闰四月壬寅，以杨嗣昌荐，熊文灿被任命为“兵部尚书兼右副都御史，总理南京（南直隶）涧南、山（西）、陕（西）、（四）川、湖（广诸省）军务，驻那阳（湖北襄阳）讨贼。1639 年 8 月末，左良玉在追击张献忠时，遭受重创。由于这次失败，熊文灿被剥夺官职，受命等待其继任者杨嗣昌的到来。11 月，熊文灿被逮捕，并押送至北京受审。1640 年冬十月癸丑，其被判处死刑，斩首弃市。
247. /熊汝霖/ （1597 年－1648 年），字雨殷，浙江省绍兴府余姚县（今浙江省余姚市）人，南明首辅大臣，抗清志士，乃牧斋门人。崇祯四年（1631 年）进士。授同安知县，任内曾率兵渡海，在厦门击败荷兰殖民者。崇祯十四年（1641 年），升任户科给事中。后降为福建按察司照磨。与孙嘉绩举兵浙江抗清，迎鲁王朱以海于绍兴。弘光元年（1645 年），因军功擢升兵部尚书，授东阁大学士。鲁监国三年（1648 年），为拥有重兵的郑彩所杀。
248. /王道焜/ ，字昭平，或作少平，钱塘（今浙江杭州）人，明天启元年进士，崇祯年间任任南平知县、南雄同知。为官清正廉洁，曾整治会寇，百姓皆大加赞赏，辖区人民安定。庄烈帝时破格求贤，搜寻天下贤才，王道焜因远近闻名，待命任选职，但因为南京攻陷，接连杭州失守，自缢殉国。
249. /夏燮/ （1800 年-1875 年），又字季理，别号江上蹇叟、谢山居士，安徽当涂人。他出身于书香门第，自幼受家庭教育的熏陶，兄弟之间自相师友，学业日进。他除熟谙经书、音韵学之外，“兼深史学，留意时务”，成为一代史家。曾刊刻《明通鉴》一百卷。
250. /薛所蕴/ （？-1667）字子展，号行屋，河南孟县人。崇祯元年（1628 年）进士，累官国子监司业。入清后，累官礼部左侍郎。蕴工诗文，诗有《椁庵集》四卷，文有《澹友轩集》十六卷，《四库总目》传世。
251. /顾公燮/ （?—?），字丹午、又字丹武，号澹湖，又号担瓠。江苏吴县人。早年师从陆桂森、张九叶，乾隆年间为诸生。生性放旷，后来放弃科举事业，好摭拾稗野，以著述自娱。著有《丹午笔记》、《致穷奇书》、《消夏闲记摘抄》。
252. /陈之遴/ （1605 年-1666 年），字彦升，号素庵，浙江海宁盐官人。崇祯十年（1637 年），中进士，授翰林编修，迁太子中允。崇祯十一年（1638 年），因父坐失事入狱，被牵连革职，永不叙用。弘光元年（1645 年），陈之遴降清，授侍读学士，历迁至弘文院大学士，加少保，兼太子太保。顺治十三年（1656 年），因涉党争，以原官发往盛京居住，旋即召还。顺治十五年（1658 年），因以贿勾结内监罪，免死革职籍没，全家流徙尚阳堡。康熙五年（1666 年），死于戍所。陈之遴的诗多取材于明清之际的重大的政治事件，有较丰富的社会内容，也有一些感慨仕途坎坷的作品，如得罪后写的《感怀》二十首、《杂诗》十首、《秋日偶成》等。这些诗篇皆写得辞婉意深，颇有义山风韵。有《浮霎集》十二卷，为其亲自编集，所录诗作只占其作品十之一二。
253. /张世伟/ （1569 年—1641 年），字异度，南直隶吴县人。明末文人。隆庆三年（1569 年）出生，善写文章，为诸生时，已名满天下，得王世贞和王锡爵赏识，“每叹息以为国器”。万历四十年（1612 年），举顺天乡试，出同考官新城王象春之门。同年冬，给事中李奇珍诬劾王象春收受张世伟贿赂，王象春谪官，王象春罚停三科。荐贤良方正，不就。此后多次会试不第，于是绝意公车终老。崇祯十四年（1641 年）卒。崇祯十七年（1644 年），追赠翰林院待诏。著有《自广斋集》、《周史部纪事》等。娶徐氏，男子二人：长弇、次奕，弇早世，邕，其长子。与牧斋交好。
254. /许直/ （1601—1644），字若鲁，号柱石，扬州如皋人。崇祯癸酉科举人，甲戌科进士，先后出任义乌、惠来县令、吏部验封司主事、吏部考功员外郎诸职。许直一生，十分清贫，常以名节自砺。李自成入京师，自尽。赠太仆卿，谥忠节。清赐谥忠愍。
255. /田弘遇/ （16 世纪？—1643 年），陕西人，亦称广陵人，明末人物。曾任扬州千总，长女（或称其名田秀英）在崇祯帝做信王时入王府做妾。崇祯帝即位，女儿田氏封为贵妃，田弘遇官封左都督，窃弄威权，京城侧目，习称“ /田戚畹/ ”。 《明史》记，崇祯帝曾告诫他和袁贵妃的父亲袁祐“宜恪遵法度，为诸戚臣先。”其它典籍则记，袁祐相比田弘遇“声势相去远甚”。当时明朝内忧外患，崇祯帝郁郁不欢，田弘遇为崇祯帝稍解苦闷，往江南选美，携带千人，东南骚动。崇祯帝不好女色，陈圆圆进宫后被退回田府，收陈圆圆为歌妓，后赠予吴三桂，尽其拉拢之意。崇祯十五年（1642 年），田妃死，宠遇稍衰。田弘遇又欲送幼女（或称其名田淑英）入宫，次年田弘遇病死，再次年明亡，事情未成。1644 年，甲申之变，崇祯帝自缢于煤山。张岱《石匮书》有评：“国朝遇外戚，恩礼有数；虽极宠眷，而终不使任事莅民，故多所保全。高后创大业，以兵乱，外家无封者。永乐后本中山王女，以王勋世其家；而彭城、惠安（均为诚孝昭皇后兄）又各以军功封爵，余官止都督继世而已：不亦隆杀有体哉？迨后二张（张鹤龄、张延龄，孝康敬皇后弟）骄横，身就三木。而末叶李武清、周嘉定、田都督之富贵豪华，为欢无几，旋至灭亡。然而戚畹椒房，亦当知所自处矣！”
256. /周奎/ （?—?），字雲路，順天籍，南直隸人。崇祯帝皇后周氏的父親，早年以算命和行医为生。女儿在崇祯帝为信王的时候，被选为信王正妃。 崇祯帝登基后周氏立为皇后，周奎封为嘉定伯，賜第於蘇州葑門，家有女乐，陈圆圆一度是周家班成员。周奎性甚吝啬，崇祯十七年（1644 年），上懸令助餉，特遣司禮徐高加奎嘉定侯，多方动员之后，很不情愿地捐出一萬二千两银子。徐高曰：“老皇親如此鄙吝，大事去矣。廣蓄多產何益？”。北京陷落，周奎及全家都被大顺政府捉拿，在妻子、媳妇被迫自缢、长子被打死、自己和次子、侄子被严刑拷打几乎丧命之后，不得不交出七十萬巨款和全部家产。
257. /陆次云/ （生卒年不详），字云士，号北墅，浙江钱塘（今杭州）人，清代诗人。拔贡生，考授州判，曾举博学鸿儒未中，历任河南郏县、江苏江阴知县 。任江阴期间善理政事，雅集宾客，辑有《澄江集》 。早年以诗闻名，沈德潜评其诗“本真性情出之” 。康熙十八年（1679）应博学鸿词科试未中 。康熙十九年（1680）任郏县知县，期间拜谒三苏坟并撰《三苏先生墓铭》，离任时百姓送行。后任江苏江阴知县。一生著述涵盖史地、诗文等领域，撰有《八竑释史》《峒溪纤志》《北墅绪言》《澄江集》《玉山词》《圆圆传》等。《峒溪纤志》考辨西南少数民族风俗，其《志余》部分保留了珍贵的苗文记载。现存诗作《志感》《登岱》《咏史》等多寓怀古幽思与山川气象。
258. /张岱/ （1597 年 10 月 5 日－1689 年？），一名维城，字宗子，又字石公，号陶庵、陶庵老人、蝶庵、古剑老人、古剑陶庵、古剑陶庵老人、古剑蝶庵老人， 晚年号六休居士，山阴（今浙江省绍兴市）人，明清之际史学家、文学家。张岱出身仕宦家庭，早年患有痰疾而长住外祖父陶允嘉家养病，因聪颖善对而被舅父陶崇道称为“今之江淹”，提出过“若以有诗句之画作画，画不能佳；以有诗意之诗为诗，诗必不妙”等观点；于天启年间和崇祯初年悠游自在，创作了许多诗文；于崇祯八年（1635 年）参加乡试，因不第而未入仕；明亡后，避兵灾于剡中，于兵灾结束后隐居四明山中，坚守贫困，潜心著述，著有《陶庵梦忆》和《石匮书》等；康熙四年（1665 年）撰写《自为墓志铭》，向死而生；后约于康熙二十八年（1689 年）与世长辞，享年约九十三岁，逝后被安葬于山阴项里。史学上，张岱与谈迁、万斯同、查继佐并称“浙东四大史家”；文学创作上，张岱以小品文见长，以“小品圣手”名世。
259. /申绍芳/ （1597 年—？），字维烈，号清门，南直隶苏州府长洲县人，民籍，明朝政治人物。萬曆四十三年（1615 年）乙卯科應天鄉試第八名舉人，四十四年（1616 年）丙辰科三甲第二百七名進士。吏部觀政，授應天府教授，天啟元年（1621 年）升南京國子監助教，二年（1622 年）升南京禮部祠祭司主事，五年（1625 年）升郎中，六年（1626 年）調南京吏部考功司郎中，崇禎元年（1628 年）三月出為山東按察司副使，三年（1630 年）升福建布政使司右參政，五年（1632 年）升福建按察使，六年（1633 年）升福建右布政使，升戶部左侍郎。弘光年間起復原職，與錢謙益受僧大悲之獄牽連，二人疏辯後免罪。曾祖申士章；祖父申時行，吏部尚書；伯父申用懋，兵部尚書；父申用嘉，廣西布政使司右參政。兄申繼揆，弟申縯芳、申緒芳、申繹芳、申紀成、申繩芳、申纘功、申綋祚。
260. /李日华/ （1565 年—1635 年），字君实，号九疑，又号竹懒、痴居士，浙江嘉兴府嘉兴县人。晚明官员，书画家、鉴赏家。李日华生于明世宗嘉靖四十四年（1565 年），幼时聪敏，其父“口授以《大学》，率能成诵”，万历十九年（1591 年），李日华参加辛卯科浙江乡试，为文放纵不羁，考官郝敬赏识其才，破格录取，且称：“天下那得如此好秀才。”万历二十年（1592 年），李日华联捷三甲二十二名进士，通政司观政，任江西九江府推官，署新昌县事，二十六年考察，二十八年贬任汝州判官，升西华知县，三十二年丁内艰。四十四年起升南礼部仪制司主事，天启四年（1624 年）升尚宝司丞，崇祯元年（1628 年）官至太仆寺少卿，差往蓟辽抚赏将士，事竣还里，遂不复出。归隐后，以著述、鉴藏自娱。《明史·文苑传》称其“恬澹和易，与物无忤。”，崇祯八年（1635 年）卒。能书善画，精鉴藏，世称“博雅君子”。擅绘画，绘《宿迁水溢图》轴。又有《恬致堂集》、《檇李丛谈》、《书画想象录》、《紫桃轩杂缀》、《味水轩日记》、《六砚斋笔记》、《梅墟先生别录》、《恬致堂诗话》等书，钱谦益在《恬致堂集》作《序》称：“文章者，天地英淑之气与人之灵心结习而成者也。与山水近，与市朝远；与异石古木哀吟清唳近，与尘壒远；与钟鼎彝器法书名画近，与时俗玩好远。故风流儒雅、博物好古之人，文章往往殊邈于世，其结习使然也。”。后人称李日华有“两多”，著作多、别号多。曾祖李衍，登仕郎。祖李惠。父李应筠，封文林郎推官。前母钱氏，封孺人；母吴氏，封孺人。具庆下。子肇隆、肇亨。从兄李在公，同科进士。
261. /张昱/ （约公元 1330 年前后在世），字光弼，号一笑居士，晚号可闲老人，庐陵（今江西吉安）人。中国元代诗人，终年八十三岁。张昱少事虞集，得其诗法。 元至正年间，江浙行省左丞杨完者以他参谋军府事，迁左右司员外郎，行枢密院判官。杨完者死后，张昱弃官而去。 张士诚占据苏州，以礼请其出山，坚辞不就，借题蕉叶以明志。与周伯温、杨维桢交游密切。 张士诚败亡后，明太祖朱元璋召至京师，悯其老，曰“可闲矣”，厚赐遣还，乃自号可闲老人。后归老于西湖山水间，留居西湖寿安坊，贫无以葺庐。 曾于酒间对瞿佑言：“我死，埋骨湖上，题曰诗人张员外墓，足矣。” 张昱时逢元明动荡之际，以诗酒自娱，其诗作风苍莽雄肆，有沉郁悲凉之概。 七古《过歌风台》是其得意之作。著有《张光弼诗集》（又题为《可闲老人集》或《庐陵集》）2卷（别本作 7 卷或 4 卷）。《元诗选》初集选入他的诗 195 首。
262. /阮葵生/ （1727 年—1789 年），字宝成，号吾山，江苏山阳县（今淮安）人。阮学浩之子，生于清世宗雍正五年（1727 年），天资早慧，乾隆十七年（1752 年）中举，乾隆二十六年（1761 年）恩科，不中，另以“明通榜”入选中书，以内阁中书入值军机处，乾隆三十八年(1773 年)，入馆编纂《西域图志》、《西域同文志》，官至刑部侍郎，久居京师，交游多天下名士，“耿直不面谀人，人有过而面斥，退而相忘”，“熟精法律，屡决大狱”，为“刑名总汇熟谙之员”，办案主张“成见不设，定见不移，不恃聪察以矜明柱，不务宽纵以博虚誉”。乾隆帝二次在西苑召见他：“汝父儒臣，能文章，汝复长于政事，当益勉之！”因祀祭天坛坠马受伤，乾隆帝闻之，特谕“此后乘轿勿骑马”。乾隆五十四年（1789 年）中风卒。著作有《茶余客话》30 卷、《七录斋诗集》、《秋谳志略》。有子阮钟瓂、阮钟瑗。
263. /孙原湘/ （1760 年—1829 年），字子潇，号心青，江苏昭文县（今属常熟市）人。清代政治人物、学者，进士出身。嘉庆十年（1805 年）登乙丑科进士， 授翰林院庶吉士，充武英殿协修官。乞假归里，未再出仕。孙原湘工骈文、散文，兼善书画。与王昙、舒位齐名。着有《天真阁集》。
264. /陈瑚/ （1613 年—1675 年），字言夏，号确庵、无闷道人、顽潭主人、七十二潭渔父。南直隸太仓州人，明末清初學者。生于万历四十一年（1613 年），少承家学，贯通五经，十五岁与陆世仪等交，论学相辩驳。 崇祯十五年（1642 年）中式壬午科應天鄉試举人。清康熙八年（1669 年），朝廷诏举隐逸，陈瑚為知州上報姓名，力辭不就。康熙十四年（1675 年）卒，年六十三岁。门人私谥其为“安道先生”。 巡抚汤斌將陈瑚故居改建成安道书院。著有《条教》、《条议》、《开江书》、《筑堤书》、《治纲》、《荒政全书》、《圣学入门书》、《讲学全规》等書。
265. /董潮/ （1729 年—1764 年），字晓沧，号东亭，又号臞仙。江苏省常州府阳湖县（今属常州市）人，清朝政治人物、翰林、诗人、词人、书画家、骈文家、史学家。董潮少年时孤贫，由祖母海盐陈氏抚养成人，之后入赘并占籍浙江嘉兴府海盐县。性情孝顺，读书慷慨有志节，善作诗文，擅书法，尤其精工骈体文。乾隆二十一年（1756 年）浙江乡试举人。乾隆二十六年（1761 年）乾隆帝允准朝廷大臣请求，在会试未录取的备卷中挑四十人为中书、学正的预备人选。董潮此时入选，补授内阁中书，充《通鉴辑览》纂修官。董潮取材渊博丰富、体裁严谨，有良史的素质。乾隆二十八年（1763 年）癸未科殿试，中第二甲第十三名进士。选翰林院庶吉士。乾隆二十九年（1764 年）董潮请假归乡，受聘参与修纂常州城附郭武进、阳湖两县志书，未及完成而卒，年三十六。董潮平时与赵翼交游，跟朱琰互相砥砺诗文。诗风近温庭筠、李商隐、王士祯，与夏銮、朱琰、朱方蔼、李旦华、陆以谦等人称为“嘉禾八子”，在京师曾作〈红豆树歌〉，时人称其“红豆诗人”。绘画师法黄公望，书法学习《灵飞经》，词作风格绮丽。著作有：《东亭诗选》二卷、《东皋杂钞》三卷、《漱花集诗余》一卷、《红豆诗人集》十九卷、《附集》一卷等。
266. /郑钦谕/ ，字叁山，，自号初晓道人，吴县人。性孝友，冲和乐易，与之处者，如坐春风中。先代习带下医，因世其业。四方造请，餽遗所入，辄以济人。凡饲饥絮寒，埋胔掩骼，不可胜数。家有杏圃，花竹交错，日与高人逸士往来。年七十六卒。
267. /徐复祚/ （1560 年—1630 年？），原名笃儒，字阳初，号暮竹，别署破悭道人、洛诵生、休休生等，晚号三家村老。常熟（今属江苏）人，明代戏曲家。生于贵族之家，博学能文，一生布衣。 受内伯张凤翼影响，好词曲创作。撰有传奇六种：《霄光记》（一名《宵光剑》）、《红梨记》、《投梭记》、《题塔记》（已佚）、《雪樵记》（已佚）、《祝发记》（已佚）。杂剧三种：《一文钱》，《梧桐雨》（已佚）、《闹中牟》（已佚）。另著有《三家村老委谈》（又称《花当阁丛谈》）三十六卷、曲选《南北词广韵选》。
268. /林古度/ （1580 年—1666 年），字茂之，号那子，别号乳山道士。福建福清人。万历八年（1580 年），寓居江宁。万历三十一年（1603 年），屠隆与名士宴集福州乌石山邻霄台，古度奋袖击鼓，以《挝鼓行》诗受知屠隆，与曹学佺友善。又与钟惺、谭元春交游。明亡后以遗民自居，时人称“东南硕魁”。晚年家产殆尽，双眼失明。康熙五年（1666 年）卒，得年八十七岁。有《林茂之诗选》二卷，今存。父 /林章/ ，字初文。
269. /曹学佺/ （1575 年 1 月 26 日—1646 年），字能始，号尊生，又号雁泽、石仓居士、西峰居士，福建布政司福州府侯官县洪塘乡人，明末政治人物、藏书家，东林党成员。明亡殉国。在家休养期间，曹学佺精心经营石仓园，藏书万余卷，并邀请许多文人来讨论文学，还针对海盗、水利、修桥等问题给予朝廷很多建议，不少都得到采纳。崇祯十七年（1644 年），崇祯帝在北京自杀，清兵入关，他投水自尽，但被家人救起。次年，唐王朱聿键定都福州，建立南明隆武政权，曹学佺被再度起用，封为太常寺卿，进礼部尚书，加封加太子太保，与大学士黄道周共同参与国策制定。隆武二年（清顺治三年，1646 年），他力主隆武帝亲征，以收复明朝失地；自己也捐银万两作为军饷。但隆武帝在军事上遭遇失败，清军于当年进入福建，郑芝龙降清，隆武帝在逃亡汀州的途中被俘，绝食而死。九月十七日，清军攻陷福州，次日，曹学佺香汤沐浴，整顿衣冠，在西峰里家中自缢殉国，死前留下绝命联：“生前单管笔，死后一条绳。”另有说法称他是在鼓山涌泉寺自缢的。曹学佺死后，其家被清兵所抄，家人也遭逮捕，藏书被清军抢光。曹学佺毕生好学，对文学、诗词、地理、天文、禅理、音律、诸子百家等都有研究，尤其工于诗词，写景抒情诗是他的特长。他的私人藏书量达到上万卷。 在文学方面，他与徐𤊹、谢肇淛等人在诗文上颇有建树，并带动了自明朝中期以来沉寂的闽中文坛，被认为是明末福建文苑的复兴者。他与李贽、焦竑等学者都有交往，这两人对他的思想影响很大。同时他也接受了许多佛教思想。他将佛教的出世解脱和儒家的入世精神统一起来，因而其思想开阔，虽然在官场多年，但功名之心并不太深，内心追求幽静。他的诗文著作被收录进一百卷的《石仓诗文集》，在清初，《石仓诗文集》被清政府视为禁书，以致失传。曹学佺一生著作颇丰，写有《周易可说》七卷，《书传会衷》十卷，《诗经质疑》六卷，《春秋阐义》十二卷，《春秋义略》三卷，《蜀中人物记》六卷，《一统名胜志》一百九十八卷，《蜀汉地理补》二卷，《蜀郡县古今通释》四卷，《蜀中风土记》四卷，《方物记》十二卷，《蜀画记》四卷，《蜀中神仙记》十卷，《蜀中高僧记》十卷，《石仓诗文集》一百卷，《石仓十二代诗选》八百八十八卷，《蜀中诗话》四卷，另外还有《宋诗选》四十九卷，所有作品共计 1329 卷。
270. /黄翼圣/ （1596 年~1659 年），字子羽，号摄六、莲蕊居士，明末常熟（今属江苏）人。崇祯中，以诸生应聘，官四川新都知县、安吉州知州。 晚年建藏书楼为“莲蕊楼”，以藏所购古铜器、瓷器及宋雕板古书，搜访把玩，爱不释手。尤以藏有宋嘉祐年间的缕本书为镇库之宝。藏有宋本《参寥子诗集》、《林和靖诗》等。藏书印有“有明黄翼收藏”、“黄子习读书记”、“印溪黄子习氏藏书记”等。明亡后，以遗老自居，杜门不出，潜心于佛教。在四川新都知县任上，曾于县堂供斋饭僧，摆设饭匙及筷子，以供养僧众。明亡后杜门不出，与朱明镐、吴伟业及僧人苍雪等唱和。卒后，所有藏书及古器物，均流如他人。著作《黄摄六诗选》2 卷，《莲蕊居士诗选》，《跃影斋诗集》。
271. /顾在观/ ，字观生，华亭人。居金陵。晚号东篱子。观生为杨文总所引，入马士英幕。尝言阮大铖不可用，士英不从。大铖欲起钩党之狱，观生复使士英子銮泣谏，赖以稍止。南都亡，归守二顷，复以逋赋，遂弃产遁。居金陵衡阳寺以终。
272. /沈士柱/ （？—1659 年），字昆銅，號惕庵。蕪湖人。父沈希韶是明朝御史。明末復社成員，反對閹黨，明亡後隱居蕪湖，仍秘密從事反清活動，順治十四年（1657 年）被捕，順治十六年（1659 年）在南京處斬，其一妻二妾皆殉。黃宗羲有《哭沈昆銅》詩。
273. /万泰/ （1598 年—1657 年），字履安，晚号悔庵，浙江宁波卫（今宁波市）人（今属宁波市海曙区）人，祖籍河南定远（今安徽），明末清初学者。少师事刘宗周，是刘宗周弟子，与黄宗羲同学。崇祯九年（1636 年）中乡试。曾参加文昌社，也是复社干将，以激扬名节自任而闻名当时，反对阉党专权。阮大铖擅权时，参与署名《留都防乱揭》，弹劾阮大铖，士林称快。明朝时官至户部主事。学术上创立明末清初浙东学派甬上支派。北京城破，崇祯帝自缢，明亡，清兵南下。离乡远避至榆林，后来回到乡里，参与反清复明的军事斗争。晚年游历杭州、苏南、广州等地，在江西时因病逝世。出生明朝锦衣卫世家，曾祖万表，都督同知、漕运总兵官。祖父万达甫，父万邦孚。万泰有子八人，学术上各有所成，对后世影响极大，人称“万氏八虎”。“八虎”中又以万斯选、万斯大、万斯同学术成就最高。代表著作有：《续骚堂集》、《万履安行卷》、《寒松斋集》、《明州唱和集》、《怀剡诗》等。
274. /杨维垣/ （？—1645 年），字斗枢，彭城卫籍山东文登县（今属威海市）人，明朝政治人物。万历三十四年（1506 年）丙午科順天鄉試第五十九名舉人，四十四年（1616 年）丙辰科三甲一百六十二名进士，户部觀政，四十五年授行人司行人，天啓元年（1621 年）选授云南道监察御史。天启间，力排东林党人。毅宗即位，身先弹劾阉党。升太常寺卿。崇祯元年（1628 年），入魏忠賢逆案，謫戍淮安府。弘光元年（1645 年），起为通政使。清军陷南京时，全家死节。曾祖杨鸾，户部主事；祖楊君璽，两淮運使；父楊從俭，廪生；本生父楊從書。
275. /蔡奕琛/ （1597 年—1654 年），字韫先，晚号是庵居士，浙江德清人，明朝政治人物，进士出身。生于万历二十五年丁酉。万历四十三年（1615 年）举乙卯科浙江乡试第十三名，万历四十四年（1616 年）联捷丙辰科进士。工部观政，四十六年授工部都水司主事，四十八年调吏部稽勋司主事，本年调验封司，本年十月调考功司，十二月调文选司，天启元年（1621 年）二月升本司员外郎，本年养病。崇祯元年（1628 年）起验封司郎中，养病，三年除原职，调文选司，四年升太常寺少卿、提督四夷馆，六年升顺天府府尹，七年升大理寺卿。历任刑部侍郎。丁忧在家时，行贿大学士薛国观。崇祯十三年（1640 年）薛国观纳贿事发，他因此被逮捕入狱。蔡奕琛讦攻复社人士张溥、张采遥握朝政、结党乱政，说自己行贿罪因张溥而起。南明建立，弘光帝命他为吏部右侍郎。弘光元年（1645 年）兼东阁大学士，不久晋升礼部尚书兼文渊阁大学士。五月，清朝军队攻陷南京，蔡奕琛与王铎、钱谦益一起迎降。曾祖蔡永祥，鸿胪寺丞。祖父蔡绍宗，太学生。父蔡演传，丁酉文魁。子蔡启僔，清康熙九年（1670 年）庚戌科状元。孙蔡升元，康熙二十一年（1682 年）壬戌科状元。升元从弟蔡彬，辛酉浙省解元。
276. /王铎/ （1592 年—1652 年 4 月 28 日），字觉斯，一字觉之，号嵩樵、十樵、石樵、痴庵、东皋长、痴庵道人、烟潭渔叟、雪塘渔隐、痴仙道人、兰台外史、雪山道人、二室山人、白雪道人、云岩漫士等，生于河南孟津县（今河南孟津），籍平阳府洪洞县（今山西省洪洞县），世称“王孟津”，明末清初官员，进士出身，书画家。王铎幼时家境贫寒，“不能一日两粥”，母亲陈氏曾将陪嫁的“钏珥链柎鬻之市，以供朝夕”。聪颖慧敏，十八岁就学于山西蒲州河东书院，明天启二年（1622 年）成进士，任翰林院庶吉士、编修、少詹事，累擢礼部尚书。南明弘光朝任东阁大学士、次辅。顺治二年（1645）五月，清军攻占南京后，降清。顺治六年（1649 年），授礼部左侍郎，充《太宗文皇帝实录》副总裁，官至弘文院大学士，授礼部尚书。顺治八年（1651 年），晋少保兼太子太保。顺治九年（1652 年），三月十八日病逝于孟津，赐祭葬，谥文安。“赠太保。荫一子为中书舍人”（据《清实录顺治朝实录》）。葬于偃师县城东山化乡石家庄村南。明万历三十八年（1610 年）庚戌科探花钱谦益作《故宫保大学士孟津王公墓志铭》，明天启二年（1622 年）壬戌科同榜进士张镜心为其作《王文安公神道碑铭》。《清史稿》卷七十九有传。写书法主张“一日临帖，一日应请索”，非常专注于书法上。书风倾向“刚强”。王铎博学好古，能作诗、写文章，兼能绘画，开创一代书风。其书法笔力雄健，长于布白，楷、行、隶、草，无不精妙。姜绍书《无声诗史》称其“行草书宗山阴父子（王羲之、王献之），正书出锺元常，虽模范锺王，亦能自出胸臆”，学米芾几可乱真。马宗霍在《书林藻鉴》卷十二中评其书法“纵而能敛，故不极势而势不尽”。有《琅华馆帖》、《拟山园法帖》，诸体悉备，以草书功力最深，林散之称其草书为“自唐怀素后第一人”。有“神笔王铎”之誉。明时与董其昌齐名，有“南董北王”之称。著有《拟山园诗集》、文集《拟山园选集》。
277. /史惇/ （？—？），字子有，南直隶金坛县人。明末政治人物。崇祯十五年（1642 年）科举特科状元，由于皇帝求才心切，特加试一次（正常应于 1643 年会试）。史惇以举人身份进考，一举得魁。授户部山东司主事，调员外郎中，不久，任江西九江府知府。着有《恸余杂记》。
278. /严嵩/ （1480 年 3 月 3 日—1567 年 5 月 29 日），字惟中，号介溪，又号勉庵，江西分宜人，祖籍福建邵武，明代嘉靖年间大臣，官至内阁首辅、谨身殿大学士、少傅兼太子太师，少师、华盖殿大学士、谨身殿大学士。孝宗弘治十八年（1505 年）进士，改翰林院庶吉士，授翰林院编修，旋病休归里。严嵩读书八载，诗文峻洁，声名始著。武宗正德十一年（1516 年），还朝复官。世宗嘉靖七年（1528 年），奉命祭告显陵，归而极言祥瑞，世宗喜。几年内先后迁其为吏部右侍郎，进南京礼部尚书，两年后改任吏部尚书。嘉靖十五年（1536 年），以贺万寿节至京师。时值廷议重修《宋史》，遂留京以礼部尚书兼翰林院学士衔主持其事。他善伺帝意，以醮祀青词，取得宠信，加为太子太保。二十一年（1542 年），拜武英殿大学士。入直文渊阁，仍掌礼部事。后解部事，专直西苑；累进吏部尚书，谨身殿大学士、少傅兼太子太师，少师、华盖殿大学士。严嵩一意媚上，窃权罔利，专擅国政近二十年。士大夫侧目屏息，不肖者奔走其门，行贿者络绎不绝。严嵩戕害他人以成已私，并大力排除异已。他还吞没军饷，废弛边防，招权纳贿，肆行贪污，激化了当时的社会矛盾。晚年，以事激怒世宗，为世宗所疏远，被抄家去职，两年后而殁。著有《钤山堂集》40 卷。
279. /赵之龙/ （生卒年不详），凤阳府虹县（今安徽省泗县）人，明朝第 10 代忻城伯，弘光元年（1645 年），与明朝一众勋臣在南京投降清朝。崇祯时，以忻城伯镇南京。福王立，与拥戴，干政。豫亲王师至，与魏国公徐允爵，保国公朱国弼，隆平侯张拱日，临淮侯李祖述，怀宁侯孙维城，灵壁侯汤国祚，安远侯柳祚昌，永昌侯徐宏爵，定远侯邓文囿，项城伯常应俊，大兴伯邹存义，宁晋伯刘允极，南和伯方一元，东宁伯焦梦熊，安城伯张国才，洛中伯黄九鼎，成安伯郭祚永，驸马齐赞元，大学士王铎，尚书钱谦益，侍郎朱之臣、梁雲构、李绰等迎降。之龙授世职三等阿思哈尼哈番，允爵等皆置勿用。铎等诣京师。先是北都降者多授原官，御史卢传言南都新人不得与旧臣比。铎至，命以尚书管弘文院学士，累擢至礼部尚书，卒，諡文安。谦益语在文苑传。
280. /姜曰广/ （1584 年—1649 年 2 月 29 日），字居之，号燕及，晚号浠湖老人，江西新建浠湖里（今丰城市同田乡候塘村）人，明末政治人物，进士出身。崇祯九年（1636 年）累官至吏部右侍郎，后因事获罪而被贬为南京太常寺卿，遂引疾归乡。崇祯十五年（1642 年）升任詹事。崇祯十七年（1644 年）以詹事掌南京翰林院事，期间曾经与史可法上书请求让皇太子朱慈烺前往南京监国，但意见未被崇祯帝采纳。同年，李自成攻陷北京，崇祯帝于煤山自缢而亡，南京议论立帝，姜曰广等主张立潞王，结果福王为帝，仍为礼部尚书兼东阁大学士，与史可法、高弘图并称“南中三贤相”。内阁首辅马士英虽与姜曰广同年，但两人素来不和，本想诬陷姜曰广。然而因姜曰广有声望，无人敢响应马士英。后得知宗室朱统𨰥品行恶劣，便想到可以用职官加以利诱，使其打击姜曰广。遂指使朱统𨰥上疏诬告弹劾姜曰广任用东林党郑三俊、吴甡、房可壮、孙晋等人，把持朝政，以刘士祯为通政使，阻遏章奏，以王重为文选，扶植私人；命令杨廷麟放走狱中的凶悍盗贼，联同江河大侠与水陆奸官窥视南京，阴谋迁都或另立新君；包庇曾投靠李自成的臣子；收受贿赂；姑息养奸等五大罪状。后又遭马、阮党人佥事陆朗、副使黄耳鼎等人上疏弹劾其结党欺君、把持朝政、无人臣礼，遂弃官回南昌。隆武四年（1648 年）金声桓邀姜曰广起义，并授其太子太保、吏部尚书兼兵部尚书、中极殿大学士等官衔，御赐尚方宝剑，可以根据实际情况或临时变化，先斩后奏，清廷得知后，派征南大将军谭泰率兵攻打南昌，次年，正月十九，城破，金声桓投水死，姜曰广亦投水自尽，一说于仁臣之心牌坊下上吊自尽。著有《石井山房文集》、《皇华集》、《石井山房语录》、《过江七事》等。其中《过江七事》专记南明弘光帝政权的七件大事，目分“计迎立”、“正纠参”、“禁缉事”、“护总宪”、“裁镇将”、“防左镇”、“持逆案”。以往误认为《过江七事》为明末四公子之一的陈贞慧所作，但顾诚在其所著《南明史》明白指出《过江七事》应为姜曰广所作。
281. /高弘图/ （1583 年—1645 年），初字惟怀，改字研文，一字子犹，号硁斋，山东莱州府胶州（今胶县）灶籍，济南府利津县人。明末政治人物。 安宗时官至内阁首辅。高弘图生于万历十一年（1583 年），万历三十七年（1609 年）己酉科山东乡试第八名举人，万历三十八年（1610 年）成进士。授中书舍人。后来升任陕西道御史，为官正直，不附权贵。天启初年，陈时政八患，又推荐起用邹元标、赵南星等东林党人，并转任巡按陕西御使。在任期间，捕诛奸民，澄清吏治，惟后来高弘图因“题荐属吏”的公事上与赵南星意见相左，于是便以疾辞职。阉党以为高弘图和赵南星等东林党人有隙，加上高弘图为人中立不依附东林党、齐楚浙党等，于是魏忠贤便重新起用高弘图为原来的官职。期间高弘图曾经上书要求加强京营训练，整顿戎政，但后来因忤魏忠贤而被罢职。崇祯帝即位后，起用为太仆寺少卿，随后因病辞职，后来又历任左佥都御史、左副都御史、工部右侍郎等，但后来因得罪太监张彝宪而激怒崇祯帝，因而被削籍罢官，此后家居十余年不再当官。在清兵入塞时期，曾经捐家产以助守胶州城。崇祯十六年（1643 年），因守城之功而重新被崇祯帝起用为南京兵部右侍郎、户部尚书。次年，李自成破北京，威宗自缢殉国，期间高弘图曾积极协助时任南京兵部尚书史可法领兵北上勤王之事，但终不果。南明时，弘光帝委任高弘图为礼部尚书兼文渊阁大学士，期间曾经尝试调解马士英和东林党人的关系，但最终失败。又曾经倡议迁都凤阳，北伐山东，但不为接纳。后来为马士英、阮大铖所排斥，是年十月，弘图四疏乞休获准。流寓会稽（今浙江绍兴）。弘图在内阁时，马士英尚畏之，不敢放肆，一旦去职，遂无忌惮。清军攻陷山东，弘图流寓吴门，渡江入浙东。弘光元年（清顺治二年，1645 年），清军破杭州，携一幼孙逃入一野寺中，绝食九日，卒于会稽之竹园。与姜曰广、史可法并称“南中三贤相”。有《太古堂集》。
282. /陈子壮/ （1596 年—1647 年），字集生，号秋涛。广东南海县沙贝村（今广州白云区金沙街道沙贝社区）人。明末及南明政治人物。永历时官东阁大学士兼兵部尚书，谋求收复广州，兵败殉国。陈子壮出生广州九曜坊之杲日堂故宅，四岁能文、七岁能诗，万历四十三年（1615 年）乙卯科广东乡试第八名举人，四十七年己未（1619 年）成一甲第三名进士（探花），授翰林院编修。魏忠贤欲延为己用，被陈婉拒，魏忠贤大怒：“何物陈子壮，竟敢逆我意！”天启四年（1624 年），自翰林院去浙江主持乡试，策论〈历代宦官之祸〉，为魏党所忌，遂罢职，定居盐仓街。崇祯元年（1628 年）起复原职，升官左春坊左谕德，丁忧，起升少詹事，五年纂修玉牒，六年升礼部右侍郎、兼侍读学士。后因朱姓案下狱，不久罢归乡里。崇祯十年（1637 年）在广州白云山辟云淙书院，次年修禊南园，与其弟陈子升及黎遂球、区怀瑞、曾道唯等 12 人修复南园诗社，世称南园十二子。后在禺山书院授徒讲学。弘光时，为礼部尚书。隆武二年（1646 年），广州城陷，陈子壮与弟陈子升捐资募兵，在南海九江举旗誓师，永历帝授以东阁大学士兼兵部尚书。陈邦彦同陈子壮密谋攻取省城，同广州城内的原明朝广州卫指挥使杨可观、杨景晔秘密联系，“暗用桂字印票，号召多人”为内应，不料事泄，张贴檄文的家僮被清军捕获。后兵败被俘至广州，佟养甲下令将陈子壮“寸磔于教场”，与陈邦彦、张家玉合称为“南明三忠”。谥号文忠。
283. /林时对/ （1615 年—1705 年），字殿飏，号茧庵、茧翁，浙江宁波府鄞县人。明末政治人物。崇祯十二年（1639 年）己卯科浙江乡试举人，崇祯十三年（1640 年）联捷庚辰科进士，授行人司行人，乞假归。鲁王监国，召为兵科给事中，累迁至右副都御史。时总兵王之仁请塞东钱湖，力持不可。马、阮在方国安军中，疏请诛之，诸镇积怒，国安纠为东林遗孽，遂归。明亡后，杜门不出，以著述自娱，有《诗史》、《荷插丛谈》。年逾八十，同辈凋落殆尽，悒悒无可与语，乃令从人舁肩舆行坊巷中，一日至湖上圣功寺侧，有歌伶演剧，驻舆听之，目已花不辨场上所演何曲，但见冕旒踉跄而前者，问曰：“谁也？”或曰：“此流贼破京师也。”即狂号自投舆下，晕绝良久，观者大裓，伶人为之罢剧，时去甲申已四十年矣。及卒，遗命柳棺布衣，不许以状请志墓之文，得年九十一。
284. /陈于鼎/ （1600 年 1 月 2 日—1661 年 6 月 6 日），字尔新，号实菴，又号南山逸史，直隶宜兴人，明朝政治人物，进士出身。万历二十八年（1600 年）生，十一岁童子试考上秀才。后漳州参将郑芝龙聘为家塾教师，教其子郑成功。天启元年（1612 年）辛酉科应天乡试第四名举人，为《春秋》经魁。崇祯元年（1628 年）登戊辰科进士，选翰林院庶吉士，授编修，崇祯六年（1633 年）开始戏剧创作。弘光时，官左春坊左庶子掌院事。降清后，任弘文馆编修，因替苏州人申氏作保借旗债，受累革职。南归后，定居镇江。顺治十六年（1659 年）郑成功兵临镇江，陈于鼎与知府戴可进等计议迎降。郑成功兵败后，清廷查办“通海案”，顺治十八年（1661 年）陈于鼎被检举入狱，解押往北京处决。临刑时说：“明末惟李定国、郑某水陆两大战差可人意。吾得附其骥尾，死何恨哉。”
285. /李定国/ （1621 年 7 月 29 日—1662 年 8 月 10 日），字鸿远，又字宁宇、霖宇、一纯、大绶，陕西延安府（现属陕西省榆林市）人，南明晋王，抗清将领。李定国是明末民变势力之一大西将领，张献忠义子，封为安西将军。大西大顺三年末（1647 年初）张献忠战死后，与孙可望等率大西军余部南逃至云南称安西王。后与一众大西将领一同归顺南明，成为永历朝廷重要的抗清将领。永历六年（1652 年），入广西，克桂林，乘胜北上，连克永州、衡州，“两蹶名王，天下震动”，令清廷一度准备放弃吞并中国南方七省。因功封西宁王。但遭孙可望嫉忌，退入广西，再屯云南。永历十年（1656 年），密迎永历帝入滇，封晋王。后孙可望降清，并向清朝献上了“滇黔地图”使西南防务机密尽失，清军大举攻黔。他转战不利，退入缅甸继续抗清。永历十六年（1662 年），永历帝被杀，他忧愤至极，一个多月后病亡。
286. /朱师辙/ （1879 年 4 月 14 日—1969 年），字少滨。祖籍苏州，出生于安徽省黟县。祖父朱骏声、父朱孔彰皆晚清学者。朱师辙曾撰写《清史稿》列传 100 多篇。后执教于北平辅仁大学、中国大学。与陈寅恪、冼玉清等好友，陈寅恪有《寄怀杭州朱少滨》诗。1969 年在杭州逝世。著有《黄山樵唱》、《清史述闻》、《商君书解诂》、《和清真词》。
287. /沈明抡/ ，字伯叙，精春秋，得安成闻喜之传，与同里徐汧、李模、郑敷教友善，从游甚众。崇祯癸酉以恩贡中顺天副榜。乙酉乱后，授徒自给。三十余年卒。
288. /徐树丕/ ，字武子，号活埋庵道人，又号墙东居士、石农、墙东野老，江苏长洲（今吴县）人，明末清初诸生（秀才）。他工诗，善隶书。著作有《识小录》、《中兴纲目》、《杜诗执鞭录》、《埋庵集》等。徐树丕为明末诸生，其笔记《识小录》是一部综合性文人笔记，成书于明清鼎革之际，内容包含考据类条目。 姚希孟曾将女儿嫁予徐树丕。明亡后，徐树丕隐居不出，康熙年间卒。
289. /李清/ （1602 年－1683 年），字心水，号映碧，南直隶扬州府兴化县（今江苏省泰州市兴化市）人。天启年间中举，明崇祯四年（1631 年）进士，授宁波府推官，历任刑科、吏科、工科给事中，南明弘光时官至大理寺左寺丞。早年任宁波府推官期间多平反冤案，判词注重证据梳理与法理阐述。崇祯十一年任刑科给事中时奏请追谥前朝忠谏之臣，后因忤旨降职。弘光政权期间屡陈抗清方略未果。清军南下后隐居兴化枣园三十八年，拒绝清廷征召。  晚年潜心著述，撰有《南渡录》《三垣笔记》《折狱新语》等史学及司法文献，记录明代司法制度与南明史事。每逢崇祯帝忌日必行哭祭，终未仕清。
290. /邓之诚/ （1887 年 11 月 29 日—1960 年 1 月 6 日），字文如，号明斋，又号五石斋，祖籍江苏江宁，生于四川成都。中国历史学家。邓之诚自幼酷爱读书，尤喜文史。先后就读于成都外国语专门学校法文科、云南两级师范学堂。1917 年任教育部国史编纂处民国史纂辑。 1921 年起，专任北京大学史学系教授，又先后兼任北平师范大学、北平大学女子文理学院和燕京大学史学教授。1930 年任燕京大学历史系教授并兼任北平师范大学和辅仁大学史学教授，1941 年冬，太平洋战争爆发，燕京大学被封闭，与洪煨莲等同被日本军逮捕入狱,翌年获释。1946 年燕京大学复校，仍回校任教。1952 年院系调整以后，并入北京大学历史系。专任明清史研究导师，并为中国科学院哲学社会科学部历史考古专门委员。1960 年 1 月 6 日逝世，终年 73 岁。邓之诚学识渊博，除治史讲史外，对金石、书画、陶瓷、玺印、版本、校勘、目录等，都有很深的造诣。著作有《清诗纪事初编》等。
291. /卢世㴶/ （1588～1653），明代诗人。字德水，号紫房、南村病叟、杜亭亭长，祖籍河北涞水，徙居德州（今属山东）。天启五年（1625）进士，官户部主事，告终养归，起转礼部，改监察御史。清初徵至京师，谢病归。有《杜诗胥钞》、《余论》、《尊水园集略》等。生平见杨钟羲《雪桥诗话》。
292. 凌駉（1612—1645）原名云翔，字龙翰，歙县沙溪（今属安徽）人，崇祯十六年（1643）进士，福王时授监察御史，巡抚河南，守归德，清兵渡黄河南下，城破自缢死。
293. /蒋良骐/ （1723—1790 年），清朝史学家，字千之，号赢川（一作漯川），广西全州人。乾隆十六年（1751 年）进士，历任翰林院编修、国史馆纂修官，官至通政使。嘉庆《全州志》载其“才思宏富，倚马千言，为两粤文人之冠”  。蒋良骐出身进士世家，家族有“一门四进士，三代三翰林”之称，其中祖父蒋肇、父蒋林为康熙朝进士。早年师从陈黄中，乾隆三十年（1765 年）任国史馆纂修期间，以《清实录》为基础，参酌红本等官修文献编成《东华录》32 卷，因国史馆位于东华门内得名。为与光绪年间王先谦的《东华录》续录区别，史家亦称“蒋氏《东华录》”或《蒋东华》。该书保留清初六朝原始史料，部分内容未被实录修订本收录  。其出生地经考证为全州县才湾镇，墓葬于才湾镇纱帽岭并由女婿蒋锡璃捐葬。现存《东华录》1980 年由中华书局再版 ，《清史稿》未为其立传。
294. /陈之龙/ （？－1660 年），字云亢，明末清初宜春北外厢（今江西宜春市区秀江街一带）人。明天启元年（1621 年）中举，历任常德司理、乾州知州、西安同知。著有《水月山房集》一卷。崇祯十六年（1643 年）投降李自成大顺政权，授宁夏节度使。后任三边监军道，监军榆林、宁夏、甘肃三镇。清降清后任右佥都御史巡抚凤阳。顺治五年（1648 年）凤阳巡抚任内擒获黄毓祺 ，并奏报其与钱谦益等交通，黄毓祺死于狱 。同年因江西镇将金声桓叛，攻陷无为州巢县等处，被劾不能御寇，纵兵淫掠，得旨降二级调用。后因未受清廷重用遭夺职归乡，顺治十七年（1660 年）病逝。
295. /马国柱/ （？-1664 年），辽阳（今属辽宁省）人，隶汉军正白旗。清初官吏。马国柱天聪年间，初以诸生值文馆。天聪八年（1634 年），中式为举人。崇德三年（1638 年），任都察院理事官。顺治元年（1644 年），从入官，授左佥都御史。又以右副都御史巡抚山西。顺治二年（1645 年），镇压李自成农民起义军，擢兼兵部侍郎，总督宣。顺治四年（1647 年），加兵部尚书，总督江南、江西、河南。次年，江西总兵金声桓反清，败之。又击败李成栋于赣州。顺治六年（1649 年），招降南明鲁王部将吴凯等。顺治七年（1650 年），加太子少保。顺治十一年（1654 年），败南明将领张张名振于崇明，加太子太保。是年致仕。康熙三年（1664 年），马国柱去世。
296. /金声桓/ （？—1649 年），字虎臣（又作虎夫、虎符），辽东人（一说陕西榆林人），明末清初武将。金声桓初为世袭军户，先后隶黄龙、左良玉等将领。左良玉死后，金声桓随其子左梦庚降清，任江西总兵，驻守南昌，攻拔吉安及赣州，逼杀杨廷麟，以功改提督江西军务总兵官。南明永历二年（1648 年），金声桓因封赏太薄，江西巡抚章于天、巡按董学成又胁迫勒索其钱财，金声桓与部将 /王得仁/ 在江西南昌反正归明，并邀姜曰广起义，擒杀江西巡抚章于天、巡按董学成等人，派王得仁攻克九江，后力攻赣州，久攻不下。后听说清军围攻南昌，从赣州撤兵返回南昌。金声桓出兵与战，无法冲破包围。永历三年（1649 年），南昌城中粮尽，杀人而食，他下令打开东城门放百姓出逃觅食，清军亦解一面之围，容百姓逃离。金声桓的部下见此情景，争相出逃，眼见城将陷，金声桓投帅府荷花池而死。
297. /查继佐/ （1601 年 8 月 1 日－1676 年 3 月 4 日），初名继佑，入清更名省，或隐名为左尹。初字三秀，后字不省、友三。号非人氏、伊璜、敬修、与斋、舆斋、东山钓史。学者称东山先生。浙江海宁人。明末清初史学家、文学家。 查继佐出身于书香门第，自幼勤奋读书，稍长后善于诗文，声名鹊起，20 岁起在私塾任教。崇祯六年（1633 年），中试为举人。大明北都沦陷后，参加抗清斗争，曾任鲁监国的兵部职方主事。抗清失败后返回故里隐居，后又讲学于杭州敬修堂。康熙十五年（1676 年），去世。 查继佐一生勤于著书，其著作有六七十种之多，其中史学著作占有重要位置，《罪惟录》一书尤为重要，是一部纪传体明史巨著。他还撰写了多部南明史著作，如纲目体史书《鲁春秋》，专记鲁王监国始末，兼及福王、唐王、桂王政权史事；传记体史书《国寿录》，记载明末浙江地区抗清的史事；《东山国语》，记载南明抗清殉节诸人传略，分区编排，以地系人。其与张岱、谈迁、万斯同合称为“浙东四大史家”。
298. /吴胜兆/ （？—1647 年），明朝辽东人。明末清初军事人物。早年是吴三桂的副官。后来是李成栋麾下，任参将。招降杨廷枢的学生戴之俊与周谦指挥的太湖叛军。与江宁巡抚土国宝不合，南京总督军务洪承畴命吴胜兆于顺治三年七月初八日移镇松江。土国宝和洪承畴对吴胜兆开始起疑，吴胜兆接受夏宝谟的邀请，去舟山谋叛。吴胜兆通过戴之俊暗中与陈子龙取得联系。顺治四年（1647 年）四月十五日吴胜兆策划叛清投明。吴胜兆反清事败被杀，清廷搜得夏完淳所书谢表，洪承畴下令通缉夏完淳。
299. /梁维枢/ （1587 年—1662 年），字慎可，号西韩生，京师真定府真定县（今河北省石家庄市正定县）人，清朝政治人物。梁梦龙之孙、梁志之子。 崇祯年间，担任内阁撰文中书舍人，工部主事。入清后，担任营缮司郎中、山东按察司佥事 、武德道。著有《玉剑尊闻》、《性谱日笺》、《内阁小识》、《群玉直誉》。有子梁清远、梁清恭、梁清传、梁清尚、梁清芳、梁清烈、梁清泰。
300. /梁清远/ （1606 年—1683 年），字迩之、葵石、无垢，号瘿冠道人、雕丘、祓园，京师真定府真定县（今河北省石家庄市正定县）人，清朝政治人物。 总角时，赵南星见而器重之；十六岁补诸生，为学使左光斗所赏拔。崇祯十五年（1642 年），举顺天乡试。清顺治三年（1646 年）登进士，授刑部主事。次年任稽勋司主事，后升文选司员外郎、考工司郎中，调文选司郎中、太常寺少卿提督四译馆。顺治十一年（1654 年），任大理寺卿，改兵部督补右侍郎。顺治十三年（1656 年），任户部右侍郎督理钱法局，同年改吏部左侍郎。性好观书，四十余年，未尝一日释卷。晚年以病归里。梁梦龙之曾孙。同辈兄弟梁清标、梁清宽，均科甲折桂，同列九卿。著有《稷园集》九卷、《史记》四卷、《文集》四卷、《词》一卷、《雕邱杂录》十八集等。
301. /梁化凤/ （1621—1671） 字翀天，又字岐山，号沣源。西安府长安（今陕西西安）人。清代将领。 顺治三年（1646 年），武进士。顺治四年（1647 年），任山西高山卫守备。顺治五年（1648 年），从讨姜瓖，克阳和城，擢大同掌印都司。顺治六年（1649 年），攻大同，克浑源，战左卫，身中三矢而力战，超加都督佥事。顺治十二年（1655 年），擢浙江宁波副将，败明将张名振于高桥。顺治十三年（1656 年），任苏松总兵。 顺治十三年（1656 年），郑成功率兵攻江宁，遂率兵赴援，解江宁围。顺治十七年（1660 年），擢苏松提督，加太子太保、左都督。明年，任江南提督，反对徙沿海居民于内地，疏称“沿海设兵，赋拟弃之地以养之。”康熙十年（1671 年），梁化凤卒。
302. /赵宗建/ （1824—1900），字次侯，一作次公、次山，号非昔居士，江苏常熟人，清末藏书家。自称宋代宗室后裔，咸丰六年（1856 年）修缮祖宅并建藏书楼"旧山楼"，收藏司马光《资治通鉴》手稿、朱熹《大学章句》草稿、徐霞客游记手稿、钱曾手写藏书目录、钱谦益日记及信稿等珍本，宋元刻本 64 种，以脉望馆抄本《古今杂剧》最著。赵宗建少时孤苦好学，屡试不第，以太常博士就试于京兆，独居野寺不与人往。战后广收江南散佚典籍，编纂《旧山楼书目》著录 558 种，其子补录 147 种。藏书印有"非昔元赏""旧山楼秘匧"等数十枚，卒后藏书多归盛宣怀、莫有芝、丁丙丁乙。与翁同龢、杨沂孙等人交游，旧山楼常为文人雅集之地。 著有《旧山楼诗录》《非昔居士日记》《旧山楼藏书记》，张瑛、邵渊耀曾撰《旧山楼记》详载其藏书。
303. /叶绍袁/ （1589 年-1648 年），初名宝生，后改名绍袁，字仲韶，号粟庵，又号天寥道人。自号桐华流衲，又号木拂。江苏吴江（今苏州吴江）人。中国明末文学家。 叶绍袁自幼被送至袁黄处抚养。明天启五年（1625 年）举进士，选为南京武学教授，迁国子监助教。崇祯元年（1628 年）十月，擢虞衡司主事，后因不耐吏职，以母老乞归，居于汾湖之滨，绝意仕进。弘光元年（1644 年），清军攻入吴江，叶绍袁遂入杭州皋亭山，遁入空门。清顺治五年（1648 年），卒于平湖孝廉冯兼山的耘庐别墅。叶绍袁自幼聪慧，有藻思，工诗词，著有《午梦堂集》一书。另有《叶天寥自撰年谱》《年谱续纂》《叶天寥年谱别记》《湖隐外史》等著述。
     1) *沈宜修* （1590 年—1635 年），字宛君，南直隶吴江（今属江苏苏州）人。沈璟侄女。中国明代词人。沈宜修生于书香世家，幼擅文翰，好吟咏。嫁与同邑 /叶绍袁/ 为妻。绍袁以工部主事辞归后，夫妇偕隐汾湖，与子女以诗词自娱。在小鸾、纨纨及二子相继早亡后，哀伤过度，不久去世。沈宜修有词集《鹂吹》2 卷，存词 190 首，主要有感怀、闺情、咏物、送别、节序、悼亡几类，喜好效仿易安词，擅长用典，语言尖新，有林下风致。在众多词中，尤以书写闺情的词作最佳。著有《梅花诗》1 卷、《香雪吟》1 卷、《鹂吹》2 卷附 1 卷，并辑有《伊人思》1 卷。
304. /孙之獬/ （约 1591 年—1647 年 7 月 23 日），字龙拂，号毅叟，山东淄川县（今淄博市博山区白塔镇大庄村）人，明末清初官员，同进士出身。 孙之獬是明清鼎革之际一位充满争议的人物。明崇祯初年，身在翰苑的孙之獬力争禁毁《三朝要典》，被归为阉党，削籍返乡。清军入关后，他主动剃发，投靠清廷，官至礼部左侍郎、翰林院侍讲学士，自请前往江西招抚，不久又因事夺官。顺治四年（1647 年），孙之獬在家乡被山东谢迁抗清民军折磨、肢解而死。然而，清廷最终因其已经削籍，没有下达任何旌表与抚恤。
305. /濮仲谦/ （1582—清初），原名澄，字仲谦，明末清初雕刻家，金陵竹刻创始人。其竹刻技艺以"大璞不斫"著称，主张顺应竹材天然形态施以简约刀法，追求自然意趣，张岱赞其"技艺之巧，夺天工焉"。濮仲谦浅刻技法融合阴文线刻与极浅浅浮雕，线条细如毫发，能在竹面呈现书画笔墨韵味，代表作品有竹雕竹枝笔筒、《松树形壶》等。其风格与"嘉定三朱"形成对比，创立"金陵派"，清代潘西凤继承其技艺，被郑板桥称为"仲谦后一人" 。濮氏技法在清后期广泛应用于扇骨、竹杖等文房器物，传世真迹罕见，南京博物院藏"会昌九老图竹香筒"为其风格印证。
306. /土国宝/ （？—1648 年），山西大同县人。明末清初军事人物，曾任总兵。早年为太湖水盗，为洪承畴所招降，任总兵。降清后，以原官录用，顺治二年，随豫亲王多铎平定江宁，击杀福山副总鲁之屿。明代总漕田仰据守崇明，兵犯福山，遭国宝亲自率中军副将曹虎等击败。顺治四年（1647 年）四月十六日，清提督吴胜兆据松江府抗清，事败被杀。土国宝下令搜捕参与人士，一日要俘杀百余人，半月方止，“兜捕之后，凡能咀嚼者一人不留”。顺治四年八月，以布政衔管江南按察司事。顺治五年（1648 年），官至江宁巡抚。左营游击杨国海是土国宝的外甥，贩卖私盐及硝磺，每个月馈送国宝银三百两，故民间有“土埋金，谢土好”之歌谣。后因徇庇贪污等不法事，被勒令革职严讯。国宝闻讯，畏罪自杀。
307. /龚明之/ （约 1091 年—1182 年），字希仲（一作熙仲），号五休居士，中国南宋苏州昆山（今属江苏）人。约生于北宋哲宗元祐六年（1091 年），出身苏州士族，以孝行闻名，受宣教郎。宣和二年（1120 年）入国子监。绍兴二十年乡贡，绍兴三十年（1160 年）进士，授高州文学，时已八十二岁。官至宣教郎。“生平不摘人短，不作貌言，每自谓平日受用，唯一“诚”字”。淳熙五年（1178 年）致仕，晚年在太仓南郊黄姑村筑“黄姑别墅”，啜饮歌吟于其间。南宋孝宗淳熙九年（1182 年）卒。著有《中吴纪闻》。有子龚昱。
308. /邵弥/ （1597 年—1642 年），原名高，字僧弥，号瓜畴，又号长斋，灌园叟，青门隐人，芬陀居士。长州（今江苏苏州人）。万历二十五年（1597 年）生。性格孤僻，善长书法，草书学米芾、米友仁，楷书学锺繇，又长于绘画，能画水仙兰竹，与 /董其昌/ 、 /王时敏/ 、 /王鉴/ 、 /李流芳/ 、 /杨文骢/ 、 /张学曾/ 、 /程嘉燧/ 、 /卞文瑜/ 合称画中九友。中年得消渴症，查书自医，效果不佳。性情迂癖不谐俗。崇祯十五年（1642 年）卒。有《划开众皴图》、《贻鹤寄书图》等传世。
309. /郑元勋/ （1603 年—1644 年），字超宗，号惠东。直隶扬州府江都县（今江苏省扬州市）人，明朝末年政治人物、诗文作家。 郑元勋出身于晚明时期寓居扬州的盐商望族，世居徽州府歙县岩寺附近的长龄村。祖父郑景濂因旧产为族豪暴占，1576 年到扬州经营盐业，父亲郑之彦成为盐商领袖。到郑元勋这一代四兄弟竞相修筑园林（郑元嗣嘉树园、郑元勋影园、郑元化休园、郑侠如五亩园和王氏园）。天启四年（1624 年）举人。崇祯二年（1629 年）参加复社。崇祯十六年（1643 年）登进士。崇祯十七年（1644 年），授兵部职方司主事，请假归乡。李自成破北京，郑元勋麻衣哭于圣庙。六月，军阀高杰南下依附福王朝廷，奉命在扬州驻扎。由于高杰军队好劫掠，扬州士民拒绝其入城。郑元勋劝和，引起公愤，为众人所杀，死年四十二岁。
310. /盛斯唐/ ，字集陶，明朝安徽桐城人，进士盛世翼之孙。清初寓居金陵十庙西门（今南京），居所残破荒芜，常与林古度、钱谦益以诗文唱和。晚年双目失明，谢绝访客独居至终。
311. /季振宜/ （1630 年—1673 年），字诜兮，号沧苇，江南扬州府泰兴县季家市（今靖江市季市镇）人。明末清初官员、豪富，与山西平阳亢氏并称“北亢南季”。 季振宜生于明崇祯三年（1630 年）。季家为名门望族，曾祖父季缙为山东乐安县县丞，祖父季三卿是贡生，为河南祥符县知县，父亲季寓庸是天启二年（1622 年）进士，迁居泰兴县城，建嘉树园，革职归里后经营盐业致富。收藏国宝级名画《富春山居图》之《无用师卷》。其兄季开生（1627—1659），字天中，号冠月，顺治六年（1649）中进士。清顺治三年（1646）季振宜 17 岁中举，顺治四年（1647 年），18 岁中进士，授浙江兰溪县知县，后历任刑部主事、户部郎中，官至广西道御史。擅长行书，工诗文，喜藏书，又精鉴别，贮书于“静思堂”和“辛夷馆”。季振宜是清初著名藏书家，藏书之富，冠于江南，宋元名刻甚富；钱谦益的曾孙钱曾死后，其书尽归振宜，后撰成《季沧苇藏书目》，该书搜集唐诗 1859 位作者的 42931 首诗，康熙时编《全唐诗》即以此为底本。康熙四十四年（1705 年）五月下诏彭定求、沈三曾等 10 人修《全唐诗》，至次年十月，《全唐诗》在短短一年多时间内编成，这主要是利用了季振宜编《唐诗》和胡震亨编《唐音统签》的成果，在这之前，季振宜与钱谦益整理唐诗七百十七卷，始于康熙三年（1664 年），迄于康熙十二年（1673 年），历时十年。著有《静思堂集》等。
312. /黄洪宪/ （1541 年 10 月 3 日—1600 年 9 月 15 日），字懋忠，号葵旸、葵阳，自号碧山学士，中军都督府嘉兴中左千户所（今浙江嘉兴市）人，祖籍江西新淦，明朝政治人物，以解元中式隆庆辛未进士。官至詹事府少詹事。隆庆元年（1567 年）浙江乡试第一名。隆庆五年（1571 年）辛未科联捷会试第二名，殿试二甲第十三名进士，万历元年（1573 年）五月授翰林院编修。四年六月参与纂修《大明会典》，六年丁忧归。九年复除原官，十年九月与工科右给事中王敬民一起出使朝鲜，十二年五月管理诰敕，十三年二月充经筵讲官，五月与兵部主事蔡文范主考福建乡试，十二月升侍读，十五年升右春坊右庶子兼侍读，充日讲官，十六年主考顺天府乡试，十七年八月升詹事府少詹事兼翰林院侍读学士，掌院事，照旧经筵日讲，养病回籍，二十一年二月考察拾遗，令在籍听勘。万历二十八年（1600 年）八月卒，年六十岁。四十五年子黄承玄请恤去世的母亲沈氏，及并祭其父，神宗赐予祭葬。黄洪宪善写文章，“其于文特精制艺，神圣工巧”。文章写成，人们争购为奇宝。万历十六年（1588 年）黄洪宪主考顺天乡试，因取王锡爵之子王衡为榜首，又取中申时行之婿李鸿、蓟辽总督张国彦之孙张毓塘，受到礼部郎中高桂、刑部主事饶伸等人弹劾，之后工科给事中李汝华、吏科给事中史孟麟等人亦上章弹劾黄洪宪监试舞弊。张居正二子张敬修与张懋修相继在会试中中式，得到过黄洪宪的教导，也在这一科场案被人提起。著作有《朝鲜国纪》、《玉堂日钞》三卷、《碧山学士集》二十一卷、《别集》四卷、《周易集说》四卷、《学诗多识》、《读礼日钞》、《四书石床随笔》、《性理要删》六卷、《春秋左传释附》二十七卷、《资治历朝纪政纲目》七十四卷、《銮坡制草》五卷、《蒙庄独契》、《辅轩录》四卷、《箕子实纪》、《离骚解》等，曾纂修《嘉兴府志遗稿》（续解）、《秀水县志》十卷。 *黄媛介* 即其族女也。
313. /刘湘客/ （?—?），陕西富平人。明末诸生，何刚以荐举为职方主事，未及行而北京陷。隆武时任御史，永历时改授翰林院编修。永历二年（1648 年）依附李元胤，与 /金堡/ 、 /袁彭年/ 、 /丁时魁/ 、 /蒙正发/ 号称南明五虎，是为“虎皮”。著有《行在阳秋》，专记永历朝事。
314. /金堡/ （1614 年—1680 年 9 月 11 日） ，字道隐，号卫公，浙江仁和县（今属杭州市）人，明末、南明政治人物，崇祯庚辰进士。 永历时官兵科给事中，为陈邦傅等排挤，下狱遣戍。清军陷桂林后，削发为僧，法名今释，字澹归，号性因。明崇祯九年（1636 年）丙子科第五十二名举人，崇祯十三年（1640 年）登庚辰科进士，都察院观政，官山东临清州知州。明永历二年（1648 年）授官兵科给事中。号称“五虎”之一，以直言敢谏，被称为虎牙。在《驳何吾驺疏》中痛斥何吾驺、黄士俊：“黄士俊在佟虏坐中见先臣子壮极刑，四十三年状元及第，而不早死真不幸耳。后与吾驺携手同来，为国贼乎？……若叩头养甲，满口老爷，则吾驺之礼义逊让也。臣为太祖高皇帝而骂之，何体面之有？”永历四年（1650 年）陈邦傅、马吉翔一同指控金堡为“北人间谍”，遭到锦衣卫的严刑拷打，腿部残废，被黜戍清浪卫（今贵州省岑巩县境内），因瞿式耜连上七疏营救，留居桂林。清兵攻陷桂林，金堡即削发为僧，法名今释，字澹归，号性因。清顺治九年（明永历六年，1652 年）至广州，投奔海幢寺的高僧天然禅师。后曾为尚可喜树碑立传《平南王元功垂范》。墓塔在广东仁化丹霞半山中，云雾可嘉。工诗，著有《遍行堂集》、《岭海焚余》、《千山剩人禅师语录》、《丹霞澹归禅师语录》等。《晚晴簃诗汇》收其诗作。
315. /顾梦游/ （1599－1660），明末清初诗人，字与治，江宁（今江苏南京）人。明副使顾英玉曾孙，少负神童名，八岁作《荷花赋》。崇祯十五年（1642）岁贡生，入清后拒仕，以遗民终老。平生任侠好义，喜交结四方名士贤豪，为明末复社重要成员，亦是金陵遗民群体的中心人物。工古文辞，善行草书，著有《茂绿轩集》。明末时期，因肺病绝意科举，倡秦淮诗社，宗尚竞陵诗风，并乐于为友人于奕正、苏桓、宋珏等料理后事、整理遗稿。顺治初因函可私撰南明史案牵连入狱，面无惧色后获释。晚年闭门隐居，陷田产纠纷贫困潦倒，得丹徒知县张晋资助解困，作《寄丹徒张康侯明府》致谢。其去世后，好友施闰章整理刊刻其诗集为《顾与治诗集》。顾梦游画像由曾鲸以“墨骨”技法绘制，背景山水由张大风补缀，现藏南京博物院；故宫博物院亦收藏有其《行书自书诗》等书法作品。诗作《腊八日水草庵即事》借节日景象寄寓遗民哀思。
     1) 曾祖 /顾瑮/ ，字英玉，进士，官按察司副使。顾瑮从兄 /顾璘/ （1476 年—1545 年），字华玉，号东桥，直隶苏州府吴县（今江苏省苏州市）人，应天府上元县（在今江苏省南京市）匠籍。明朝政治人物，弘治丙辰进士，嘉靖朝官至南京刑部尚书。
316. /金渐皋/ ，字梦蜚，号怡安，顺治九年进士，官汉阳知县。祖父 /金明时/ （？—？），字戬檀，号鲵桓，浙江湖州府德清县人，民籍，明朝政治人物。
317. /函可/ （1612 年—1660 年），俗姓韩，俗名宗騋，字犹龙，法名函可，法字祖心，法号剩人（故亦称之剩和尚），广东博罗人，明末曹洞宗诗僧，也是清初函可案的主角。 函可原名韩宗騋，为明朝南京礼部尚书韩日缵之子。崇祯九年（1636 年）父亲病逝北京，二十九岁的函可因而到江西庐山出家，拜曹洞宗第三十二代名僧道独禅师为师，法名函可。崇祯十二年（1639 年）道独为函可剃度，并立函可为传衣钵之第二法嗣。顺治四年（1647 年）函可于南京被逻卒搜出“逆书”《再变记》，记载顺治二年（1645 年）至顺治三年（1646 年）的事变。后定罪流放沈阳，为清朝流放东北的第一人，因而亦有“清代第一宗文字狱”之说。次年春，函可抵达沈阳，到戍所仍吟咏不辍，并与同样被流放的人共同筹组“冰天诗社”，堪称东北文人结社风气的滥觞。顺治十七年（1660 年）卒于沈阳，享年四十九岁。著有《千山诗集》二十卷（补遗一卷）【顾梦游为之序】等。
     1) /韩日缵/ （1578 年—1636 年），字绪仲，号若海，广东惠州府博罗县人，明朝政治人物，同进士出身。万历二十五年丁酉科广东乡试第三名举人，三十五年（1607 年）登丁未科会试第十名，三甲七十五名进士，授翰林院检讨，耻与魏忠贤为伍，以“德业声施在天下”累官至南京礼部尚书。卒赠太子太保，谥文恪。著有《韩文恪公集》等。
318. /张伯鲸/ （1590 年—1645 年），字瀚伯，别号绳海，直隶扬州府江都县民籍。明朝政治人物。庚寅年生。万历四十年（1612 年）壬子科应天府乡试第三十三名举人，万历四十四年（1616 年）丙辰科会试一百二十九名，三甲五十七名进士。知浙江会稽、归安、鄞三县。天启中，大计，调补卢氏。崇祯二年稍迁户部主事，出督延、宁二镇军储。大盗起延绥，擢榆林兵备佥事，辖榆林中路，击破贺思贤，擒金翅鹏、一座城等逆贼，败套寇于长乐堡。崇祯六年擢陕西右参政，仍视兵备事。七年春，巡抚陈奇瑜迁总督，遂擢伯鲸右佥都御史代之任延绥巡抚。明年，以拾遗论罢。寻论延绥功，诏起用，荫子锦衣千户。十年，即家起为户部侍郎，驻池州，专理兵食。又明年，熊文灿抚事败，杨嗣昌自出督师，移伯鲸襄阳。熊文灿被逮下狱，言剿饷不至者六十余万，伯鲸坐贬秩。十五年召拜兵部左侍郎，明年，尚书冯元飇在告，伯鲸摄部事。寻以足病乞休。又明年，京城陷，微服遁还归扬州。清兵至扬州，与史可法固守，城破自经死。
319. /程正揆/ （1604 年—1676 年），初名正葵，字端伯（端白），号鞠陵，别号清谿道人、青谿老人、青谿旧史，湖广孝感（今湖北省）人，明末清初画家、书法家，政治人物。与“清初四僧”之一的髡残并称“二谿”，又与顾大申、方亨咸并称为“鼎足”。太仆寺卿程学博曾孙。万历三十二年（1604 年）出生。明天启四年（1624 年）中举人，崇祯四年（1631 年），登进士，大理寺观政，考选入翰林，授翰林院编修，累任行人司正、尚宝司卿。后因得罪辅臣而调外任。遂举家迁往南京，住秦淮河青谿之上。崇祯十五年（1642 年），官为行人司正，后升尚宝司卿，直至右庶子翰林院侍读，又加司空学士经延日讲官。明亡清兴后，改名正揆，归附清朝，为光禄寺寺丞，后曾官至工部右侍郎。顺治十一年，改光禄寺少卿、任山西乡试考官。同年任大理寺丞。次年，改太仆寺卿、工部右侍郎。顺治十三年（1656 年），受御史张自德的弹劾，下部院察议。翌年被革职，时年五十四岁。回家之后，倾力诗文书画创作。康熙十五年丙辰（1676 年）卒，年七十三。平生所作诗文题跋，卒后由其子程大皋辑为《青溪遗稿》。程正揆的著作有《青溪遗稿》《读书偶然录》《沧州纪事》等。《青溪遗稿》是程正揆去世后，其长子程大皋将他平生所做诗文、题跋、像赞、墓志铭等文学作品搜集整理而成，共二十八卷（五册），1693 年（康熙三十二年）刻板行世。
320. /邢昉/ （1590 年—1653 年），字孟贞，一字石湖。江苏高淳人。曾祖邢符，祖邢尚宾，父邢一淳，科场俱不得意。明末诸生，屡试不中，第六次参加乡试，主考官称其文笔太狂﹐愤而作《太狂篇》，从此绝意仕途。与方文友好，两人有诗往来。崇祯十年丁丑（1637 年），应杨文骢之请赴华亭幕府。崇祯十三年庚辰（1640 年），邢昉、方文等人于金陵结社。崇祯十四年辛巳（1641 年），方文赴庐州投靠蔡如蘅，邢昉有诗相送。崇祯十六年癸未（1643 年），邢昉旅居宣城。崇祯十七年甲申（1644 年）八月，母赵孺人逝。邢昉是明代著名诗人，终身布衣，为诗清真古澹，以《故宫燕》最著名，王士禛在《渔洋诗话》独推邢昉“韦、柳门庭人”及“布衣诗人第一”。吴敬梓曾拜访其石臼湖畔故居，谒邢昉墓。著有《宛游草》、《石臼集》。
321. /施起元/ （约 1605 年—约 1673 年），字君贞，一字虹涧，福建福清人，清初政治人物。顺治六年（1649 年）中式己丑科三甲第三十一名进士。擢广东布政司右参议，分守岭东道。
322. /许友/ （约 1620 年—1663 年，其生卒年说法各异），原名采，曾名宰。父许豸，因闽音宰与豸同，有忌者称许友改名宰犯家讳，以不孝责之，遂更名友，字有介，又更名为眉，字介寿、介眉，号瓯香，福建侯官（今福州市）人。明崇祯间举孝廉，以诸生终，入清不仕。许友工书善画，诗尤孤旷。钱谦益尝录其诗于《吾炙集》中。王士禛、朱彝尊亦称赏之。著有《米友堂诗集》，《清史列传》行于世。许友资性颖异，疏旷不羁，自命晋人。日娱山水，与僧仆为友。精于草书，善画枯木竹石，诗尤孤旷高迥，时有“三绝”之誉。许友早年家境宽裕，生活奢靡。顾景星《白茅堂集·许有介诗集序》云：“崇祯时，闽以僻境宴安，风俗华侈。有介家给既足，娈童舞女，诗酒谈䜩，无虚日。任侠结纳，轻视一切。……长不满六尺，肥白如匏，谈笑风发，酒酣操楮，笔墨饱腾。或为诗词，或画枯木竹石，奕奕有致，比之襄阳、眉山。顾胸中常郁促不平，若圈鹿絷鹤，怦怦怫怫不乐生者，则不善世故也。然而风流自胜。”周亮工《书许有介自用印章后》中描写道：“君大腹，无一茎须，望之类乳媪，面横而肥，不似文人。……君既负盛名，闽士多造之，恒不报谒，亦不省来者为谁。以故，人多憾之。即与君昵者，亦退多后言。君但自放于酒，一切弗问也。”入清后，许友大隐隐于市，愈发孤高，心无牵挂，时常游山水，访旧友，组诗社，作书画，怡情养性，不问世事。从父亲许豸那继承来的石林别墅，在明末毁于战火，经许友精心修整，增置亭台，又恢复生机。许友在园中标明诸名胜，大书刻于石壁，还写了《石林自记》，并以松涛阵阵而易名为“涛园”。又建“箬茧室”，长丈余，读书其中，并作《箬茧读书图》，题诗记其事。于园中栽种松竹梅菊等，邀诗友社集其中，吟诗作赋，留下了许多吟咏山林之作。清顺治五年（1648 年），许友与时任福建按察使的周亮工订交，常于米友堂内谈诗论画，交情甚笃。周亮工有诗《与有介》：“戊子之夏相与友，至今郁郁未成还。乱里真难此一日，人生能得几十年。江南移家欲更去，茅屋分人懒自全。老夫终亦欲归尔，恋君酒美不须钱。”又有“疏狂独爱许瓯香”句，可见赏爱之深。清顺治十二年（1655），周亮工被劾。1658 年，周亮工被逮入京，受诛连者千余人，其中百余人遭逮入京赴质，许友亦在其列。直至 1960 年 6 月，许友才无恙返乡。但经此冤屈，家道衰落，穷困窘迫，许友于《与周减斋先生书》中道尽辛酸：“抵家但余满面风尘。故乡城郭，已非向之翼然𫄧絙者。今则叠叠凌齿，兼以飓风之后，坊观庐舍，颓委殆尽。家人面如尘土，恸哭伤心，告诉债主凌辱、伍伯索饷，真如刀锯刻刻受也。近来朋友亲戚已绝往来，酒茗聚谈，竟若瑶池王母之宴，安可得耶？寒家之屋，前后左右已分数姓。友所自居者，仅此屋十之一，主人反为客矣。每常见炊烟相乱，鸡犬声闻，一屋竞成一村，嗟乎亦异哉！”此后，许友变得愤世嫉俗，画风诗风都有了明显转变，改画枯木寒鸦，并作《学哑》、《学聩》、《学瞽》、《学担粪》、《学死》等诗，以泄胸中不平之气。1663 年 10 月，许友抑郁病终，年四十余。著有《米友堂集》。
323. /徐延寿/ （1614—1662），名陵，字存永，一字无量，号延寿，闽县（今福州市区）人，诗人 /徐火勃/ 次子。绮岁才藻丽逸，善诗能文，钱谦益称之；将移家湖南，道扬州，与王士稹定交。家富藏书，埒曹学佺、谢肇淛，乱后并田园尽失之。著有《尺木堂集》，钱谦益为其作序。明诸生，明亡不仕，与 /许友/ 、 /陈浚/ 号称“闽中三才子”，名冠一时。有《尺木集》。其“红雨楼”藏书闻名四方。其父卒后，承父志，读父所遗留藏书，益加购藏。家有书楼名“鳌峰”，至延寿时，改称“鳌峰书舍”，牙签四周。藏书之富，当地无人可比。明末清兵入关，其藏书散失，大部分归于郑杰，郑氏因得徐氏“红雨楼”的部分藏书，录其题跋，辑有《红雨楼题跋》，所作《红雨楼题跋·序》，对福建自明嘉靖以后的藏书之事、藏家之长，皆有精到论述。并曾应同乡中牟知县吴彦芳采辑史料，编纂《中牟县志》。
324. /陈镒/ ，元人，字伯铢，丽水人。尝官松阳教授。后筑室午溪上，遂以“午溪”名其集。卷首题“前进士曲阜孔旸编选，前进士青田刘基校正”。有黄溍、张翥、孙炎及旸、基五人《序》。牧斋与毛子晋尺牍所谓“蕴生诗自佳，非午溪辈可比”即指镒也。
325. /房可壮/ （1579 年—1653 年），字象薇，改字阳初，号蔚居，改号海客，山东青州府益都县（今青州市）人，明末清初政治人物，同进士出身。明按察使房如式季子。万历三十一年（1603 年）癸卯科山东乡试第四十八名举人，万历三十二年（1604 年）联捷甲辰科三甲进士，吏部观政，三十四年授中书舍人，三十四年丙午、三十七年己酉两次典试顺天府。三十九年丁忧归。四十三年起补原职，四十六年考选，泰昌元年选授广西道御史，天启元年两淮巡盐，四年京畿道刷卷，以忤魏忠贤被逮入诏狱，几死。崇祯初，起山西道御史，掌河南道印。以争枚卜镌秩，崇祯二年（1629 年）补南京吏部考功司主事，三年升郎中，四年升尚宝司少卿，累升尚宝司卿、太仆寺少卿，居左太夫人忧，哀毁逾礼。晋光禄寺卿，再晋都察院副都御史。廷推枚卜，复为柄臣中伤削籍归。清兵入关后立即降清，顺治二年（1645 年）授大理寺卿，同年改刑部左侍郎，因事降为右侍郎；顺治五年（1648 年）再升左侍郎。顺治八年（1651 年）加太子太保。顺治九年（1652 年）升任左都御史，以老病乞休，次年去世，年七十五，赠少保。谥安恪。著作有《偕园诗草》、《侍御疏稿》等著作传世。
326. /王鳌永/ （1588 年—1644 年），字克巩，号蘅皋，又号涧溯，山东淄川罗村镇窎桥村人。天启四年（1624 年）甲子科山东乡试举人，天启五年（1625 年）联捷进士，曾任湖北宜城县令。累官通州巡抚。李自成陷京师，鳌永被拷索输银后释放。降清后官户部侍郞兼工部侍郞，招抚山东、河南。清兵占领北京后，派王鳌永至青州（益都），任山东总督，招抚明朝残余势力。李自成裨将赵应元占领青州，鳌永骂不绝口，被肢解而死，史称青州之变。死后清廷赠赠户部尚书，授其子樛骑都尉世职，隶镶蓝旗汉军。
327. /佟国器/ （？—？），字思远，号汇白，辽阳人，是中国清朝官员，满洲人，佟佳氏。顺治二年（1645 年）授浙江嘉湖兵备道，次年，担任福建左布政使晋按察使，顺治十年（1653 年）担任福建巡抚，顺治十二年（1655 年）调南赣巡抚，顺治十五年（1658 年）任浙江巡抚。佟国器订旧增新完成了明朝末年佟卜年初定的《佟佳氏宗谱》。妻钱氏，牧斋同族，牧斋尺牍称其“老姊丈”。
328. /佟卜年/ （？—1625 年），字八百，号观澜，定辽中卫（今属辽宁省辽阳）人，明末政治人物。顺天乡试举人，万历四十四年（1616 年）进士，历南皮县、河间县知县，勤俭廉洁，爱惜人才，天启初，迁四川夔州府同知，未至，经熊廷弼荐为登莱监军佥事，被诬私通建州（后金），被捕入狱而死。曾作《幽愤录》，以抒胸隐。另据学者研究，天启元年（1621 年），因为辽东战事吃紧，明廷重新启用熊廷弼为辽东经略。在熊廷弼的保举下，佟卜年出任登莱监军道，以招抚辽人。辽东连年征战，汉人佟养真、佟养性投靠了努尔哈赤；而佟卜年与佟养真、佟养性系同姓，故而在明廷激烈的党争中，熊廷弼的政敌将佟卜年当作通敌的把柄，用以攻击熊廷弼。结果佟卜年被解职，于次年（1622 年）入狱。后经审判，虽未查实佟卜年有“通逆”的证据，但佟卜年依然身陷囹圄。天启五年（1625 年），熊廷弼因丢失广宁城而被传首九边，不久佟卜年亦死。子 /佟国器/ ，清朝官至福建与南赣巡抚。
329. /张存仁/ （？—1652 年），字完真，清朝初年辽东广宁人。张存仁本来是明朝宁远副将，守大凌河城。崇祯四年（1631 年），投降皇太极军。后来隶属于汉军镶蓝旗，官至都察院承政，多次上书议论军国政事。顺治元年（1644 年），从清军入关，历任浙江总督、闽浙总督，兵部尚书兼右副都御史。直隶、山东、河南总督兼领海防。进封一等精奇尼哈番兼拖沙喇哈番（云骑尉）世职。先后率军征讨山西、下江南，击破明朝鲁王朱以海部属，擒杀马士英。上书建议清朝朝廷从速开科取士，减免赋税以安民心。顺治九年去世，谥号忠勤。
330. /李永芳/ （1583 年—1634 年），明朝辽东铁岭（今属辽宁）人。李永芳原籍铁岭，一说是李成梁之孙。原为明朝抚顺游击，万历四十六年（1618 年），因后金兵攻陷抚顺，李永芳投降努尔哈赤，授三等副将，娶努尔哈赤孙女、阿巴泰之女为妻，是第一位降清的明朝将领。及后于萨尔浒之战中献计以“凭尔几路来，我只一路去”，努尔哈赤采用此计，便决定以集中兵力、逐个击破，以多战少来打败明军。曾随兵征讨朝鲜。天命六年（1621 年），以功授三等总兵官。崇祯七年卒。有子九人，知名者有次子李率泰、三子刚阿泰、五子巴颜。李永芳之女嫁阿巴泰孙辅国公翁古。孙女为康熙帝之安嫔，李侍尧是他后人，他也是首个剃发的高级汉人官员。李永芳和李思忠是隔旗同族。
331. /熊廷弼/ （1569 年—1625 年），字飞百，一字非伯，亦作非白，号芝冈，湖广江夏（今湖北省武汉市江夏区）人，明朝后期名臣。熊廷弼于万历二十六年（1598 年）中进士，万历三十六年（1608 年）巡按辽东，万历三十九年（1611 年）提督南直隶学政，两年后因卷入党争而罢官回籍。万历四十七年（1619 年），明军在萨尔浒之战中被后金击溃，熊廷弼被起用为兵部右侍郎兼都察院右佥都御史，代杨镐经略辽东，任上斩逃将，造军器，修城堡，派兵扼守各要塞，互为应援，召集流民，安定人心，守备大固，使后金军不敢轻进。明熹宗即位后，他因不进兵而为言官所劾，请求辞职，获得批准。天启元年（1621 年），后金攻破沈阳、辽阳，熊廷弼再次临危受命，进兵部尚书兼右副都御史，仍任辽东经略，提出“三方布置”之策，但与主战的辽东巡抚王化贞不和，终致兵败溃退，广宁（今辽宁北镇）失守，熊廷弼随之下狱，又卷入党争，于天启五年（1625 年）被斩，享年五十七岁。崇祯时获昭雪，谥号襄愍。熊廷弼遗著有《熊襄愍公集》《辽中书牍》等，今人整理为《熊廷弼集》。
332. /沈惟炳/ （1581 年—1648 年），字斗仲，别号炎洲，湖广德安府孝感县人。明末清初政治人物。万历三十四年（1606 年）丙午科举人，四十四年（1616 年）丙辰科进士。授直隶香河县知县，任内修《香河县志》。天启二年（1622 年）转刑科给事中，上疏劾魏忠贤，废立枷之法。以序转吏科右给事。天启甲子（1624 年）冬，又以争掌垣魏大中、选郎夏嘉遇等不应降级。疏入，忠贤怒，夜半下中旨降一级，调外任。明年（1626 年），御史梁梦环弹劾惟炳，党邪害正，削籍，夺诰命。崇祯改元，起补刑科右给事中，八月改工科左给事中，十一月升吏科都给事中。崇祯二年（1629 年）四月，升任太常寺少卿。十五年（1642 年），自工部右侍郎转左。调吏部左侍郎。三月为通政使。崇祯十七年（1644 年），任吏部左侍郎。李自成破京师，被执。李自成败走后，降清，仍任吏部左侍郎，掌部事。屡乞骸骨不允。顺治二年（1645 年），得谢归家。五年戊子（1648 年）九月卒。有子沈宜、沈寅、沈宽。
333. /俞安期/ （约明神宗万历年间在世），初名策，字公临，后改今名，字羡长，江苏吴江人，徙居宜兴，晚年定居南京。明代山人代表人物，终身未仕，工诗文书法，编纂有《唐类函》四十卷，另著有《翏翏集》四十卷及《启隽类函》《诗隽类函》等典籍。早年以长律一百五十韵投赠王世贞得名，万历二十六年（1598）后长期居南京，参与金陵社文人集会，与王世贞、吴国伦、汪道昆等后七子派成员交往密切。作为出版家，曾校刻《唐类函》并编纂地方文献。晚年与于若瀛、臧懋循交游，诗作多涉山水行旅题材，存有《过洞庭湖》《沅江杂述二首》等作品。
334. /龚开/ （1222 年～1307 年 ），宋末元初画家，字圣予（一作圣与），号翠岩，晚号龟城叟、岩叟，人称龚高士。 淮阴（今属江苏省淮安市）人。景定年间曾任两淮制置司监当官，曾为赵葵、李庭芝幕僚，与陆秀夫共事。宋亡后，以遗民身份往来于杭州、苏州一带，后隐居于苏州。他是一位诗文书画都擅长的文人画家，山水画师法米芾、米友仁，人物、鞍马则学曹霸，亦能画梅、菊等花卉。喜欢用水墨画鬼魅及钟馗，“怪怪奇奇，自成一家”。其画作《骏骨图》（亦称《瘦马图》）以瘦马形象寄托情怀。他还创作了《宋江三十六人赞并序》，为《水浒传》的成书提供了重要参考。从现存作品看，其特点是用笔粗重、墨色淋漓，造形比较夸张，画上多题诗及跋语。抒情寓意，寄托遗老的怀抱。著作有《桑海遗录》等。
335. /钱陆灿/ （1612 年—1698 年），字湘灵，号圆沙。江南常熟人。明末清初学者。钱泮的玄孙。自幼亡父，随祖母和母亲度日，勤奋苦读。顺治十四年（1657 年）丁酉科举人，教授常州、金陵之间，从游者甚众，主纂《常熟县志》。又通佛法，为蘗庵禅师入室弟子，自号石人。节录钱谦益《列朝诗集》书成《列朝诗集小传》。晚年居虞山，老屋三楹。钱陆灿于顺治十四年（1657 年）中举人，时江南科场案发，虽复试过关，但会试报罢。顺治十八年（1661 年），以奏销案牵连除名，既而复还。后坐馆于金陵、常州。晚年归里教授，弟子著录数百人。康熙三十三年（1694 年），钱陆灿与徐乾学、王日藻、秦松龄、周金然等人为老年会。钱陆灿为听社十七子之一，在文学主张不为虞山派所缚，别调独弹，论诗提倡儒家温柔敦厚诗教说，强调从自然中获得诗思灵机。其诗骨力雄厚，诗格苍老，著有《调运斋诗》12 卷，《和陶诗》1 卷等，批点有《楚辞》10 卷、《庄子南华真经》4 卷等。
336. /李因笃/ （1631 年—1692 年），字子德，一字孔德，号天生，陕西富平薛镇韩家村人，明末清初学者、诗人。李因笃生于明崇祯四年（1631 年），三岁丧父，不久李自成率军占领关中，随寡母田氏投外祖父就读。自幼博闻强记，遍读经史，人称神童。早年拒不出仕，自称中南山人。曾参加扛清活动，当整个国家陷入乱世时，李因笃决定前往塞上寻找勇士，希望能够召集志同道合的人一起消灭贼寇，为国家报效。然而，他的号召没有得到任何人的回应。李因笃长期寄居陈上年家担任塾师，“其投契之深，有同骨肉”。康熙二年，顾炎武与李因笃在山西代州结识。康熙五年，屈大均亦寄居陈上年家中，由李因笃撮合，娶王壮献之女为妻室。康熙六年（1667 年）九月，陈上年离职而去，李因笃携家归秦。精通《十三经注疏》，长律得杜甫家法，曹秋岳（曹溶）贻上叹曰：“数百年无此作矣。”著《诗说》，顾炎武称：“毛，郑有嗣音矣。”康熙七年（1668 年），顾炎武因莱州黄培诗案入狱，得李因笃等营救出狱。康熙九年（1670 年），李因笃东出潼关，走河南、再下扬州，南游湘、鄂、楚等地，结交各地学者。康熙十八年（1679 年），由内阁学士李天馥推荐博学鸿词，列一等。授检讨，以母老辞退。地方官吏奉旨催促，因笃不从，以死抗拒，后在母亲的规劝下，秋季入京。奉命编修《明史》。因受到顾炎武的批评，再度辞归。与周至县李二曲、眉县李柏合称“关中三李”，“生平与李二曲交最密，天生宗朱子，二曲讲良知。”晚年抱病卧床，助王鸿绪修改《明史稿》。康熙三十一年（1692 年）壬申十一月二十二日卒，年六十二。著有《受祺堂诗集》。其先世为盐商，父李映林“以文补邑诸生”，为明末冯从吾门生。
337. /王士禛/ （1634 年 9 月 17 日—1711 年 6 月 26 日），小名豫孙，字贻上，号阮亭，别号渔洋山人，斋号蚕尾山房，人称王渔洋、新城尚书，山东新城（今山东桓台）人， 清代政治人物、文人，进士出身，康熙年间官至刑部尚书。工诗文，勤著述，著作有《渔洋山人精华录》、《池北偶谈》等五百余种。卒谥文简。王士禛的“禛”字，在他死后，于雍正时因避讳 ( 雍正汉名为胤禛 )，被人改称王士正。乾隆帝复赐名士祯，并追谥文简。
338. /马逢知/ （？-1660），原名马进宝，山西隰州人，明末清初将领，入《逆臣传》。初隶汉军镶白旗，后改隶正蓝旗。顺治二年（1645 年）于九江降清，获授总兵衔，招抚明军官员张亮等。顺治三年随端重亲王博洛攻克金华并驻守，六年升任金华总兵，八年获骑都尉世职。顺治八年率清军于舟山大败鲁王部将阮进、张名振。十三年迁苏松常镇提督，十四年奉诏改名 。顺治十六年因失城被解职。户科孙光祀劾其江宁战役不援、崇明战后代敌请降，刘之源等奏报。礼科成肇毅指其通海害民，十七年会审认定其纵放海敌柳卯、收受郑成功部银两及私通书信。经尼满复审，以"阴相比附""潜谋往来"定罪，同年伏诛。
339. /韩逢禧/ （1576—1655 后），字朝延，号古洲、半山老人，明代苏州人。 /韩世能/ 长子，其父为晚明著名收藏家，韩逢禧以父荫入仕，天启元年（1621）任雷州知府，后成为韩氏书画收藏的主要继承者。自韩世能、韩逢禧父子以来，韩氏家族以书画收藏名世。韩逢禧继承的藏品包括曹弗兴《兵符图》、顾恺之《洛神图》等名迹，好友张丑将其收藏编为《南阳法书表》及《南阳名画表》，收录于《清河书画舫》。上海博物馆藏韩世能《临黄庭经》后附其题跋，记载韩家藏品在明末动荡中散佚的经过。韩逢禧曾在项元汴《奇石菖蒲》作品上题诗。董其昌以《行穰帖》与韩逢禧交换《江山小景图》，该画原为韩世能旧藏，后因质押被董其昌所得。
340. /杭世骏/ （1696 年—1773 年），字大宗，号堇浦，浙江仁和县（今杭州市）人。清朝学者。康熙三十五年（1696 年）出生。勤奋好学，藏书数万卷，与同乡梁诗正、孙灏、严在昌等人有往来。雍正二年（1724 年）举人。乾隆元年（1736 年）举博学鸿词科，授翰林院编修，充武英殿纂修。后入三礼馆，纂修《三礼义疏》，用功颇多，主要负责《礼记》中〈学记〉、〈乐记〉、〈丧大记〉与〈 玉藻〉诸篇。乾隆八年因《时务策》主张“意见不可先设，轸域不可太分，满洲才贤号多，较之汉人，仅什之三四，天下巡抚尚满汉参半，总督则汉人无一焉，何内满而外汉也？三江两浙天下人才渊薮，边隅之士间出者无几。今则果于用边省之人，不计其才，不计其操履，不计其资俸。而十年不调者，皆江浙之人，岂非意见轸域？”乾隆帝闻知大怒，几欲处以极刑，因刑部尚书徐本极力求情，称“是狂生，当其为诸生时，放言高论久矣”，免死罢归。杭世骏在馆期间于《礼记义疏》的修纂用功颇多，在离开“三礼馆”后更倾心于《礼记》一经的搜讨和编纂，晚年撰成《续礼记集说》一百卷。乾隆三十年（1765 年），乾隆帝南巡，杭世骏前往接驾。乾隆帝问他：性情改了没？杭世骏回答：“臣老矣，不能改也。”乾隆三十七年（1772 年）去世，另一说乾隆三十八年（1773 年）乾隆帝再度南巡，惊讶杭世骏竟没死，当晚杭世骏去世。工书法，善写梅竹，诗与厉鹗齐名。晚年曾主讲广东粤秀书院、扬州安定书院。长于史学及小学，曾校勘《十三经》、《二十四史》。著有《道古堂集》、《两浙经籍志》、《经籍志》、《榕城诗话》、《词科掌录》、《石经考异》、《订讹类编》等。
341. /卢之颐/ （1599－1664），字子繇，号晋公，钱塘（今浙江杭州）人，明清之际医学家。出身医学世家，其父卢复为晚明名医。毕生精研医理，著有《本草乘雅半偈》《痎疟论疏》《学古诊则》等典籍，倡导医易互参，对疟疾理论与本草学发展有重要贡献。幼承家学，青年时即精于方药。遵父命耗时十八年编撰《本草乘雅》，选药 355 种分四目解析，原稿毁于兵火后凭记忆重撰为《本草乘雅半偈》。中年因劳致盲仍坚持口授医论，完成《摩索金匮》等著作。学术上承袭《内经》与张仲景学说，融合《周易》阐释医理，首开钱塘医派讲学之风，其创立的侣山堂书院为学派奠定基础，直接影响张志聪等后世医家。所著《痎疟论疏》被列为明清开创性医学专著。
342. /文震孟/ （1574 年—1636 年），原名文从鼎，字文起，号湛持，南直隶苏州府长洲县人，祖籍湖广衡州府衡山县，明末政治人物、书法家，状元。 书画家文徵明曾孙，篆刻家文彭孙，文震孟生于万历二年（1574 年），其风貌秀伟，剑眉插鬓，与弟文震亨二人，被邻里誉为“双林”。万历二十二年（1594 年），文震孟弱冠之年即以《春秋》举应天乡试第四十二名，此后十上春宫。天启二年（1622 年），中式壬戌科第一名进士（状元），授翰林院修撰。为官刚正不阿，直指皇帝诸事不理，犹如“傀儡登场”，忤逆魏忠贤，遭到廷杖，镌级被逐。崇祯帝即位，任日讲官、少詹事，秉直言政，崇祯三年（1630 年）文震孟进讲《鲁论》“君使臣以礼”一章，反复规讽，崇祯即降旨将入狱的刑部尚书乔允升、侍郎胡世赏释放。又一次，文震孟进讲《五子之歌》，崇祯帝翘起二郎腿，讲至“为人上者，奈何不敬”时，文震孟注视崇祯帝的腿，皇帝连忙把腿放下。崇祯八年（1635 年）六月，特擢礼部左侍郎兼东阁大学士，参预机务。与首辅温体仁不和，责文震孟“徇私挠乱”，于十一月初七日夺官，崇祯九年（1636 年）逝世。朱由崧在南京称帝，追谥文肃。
343. /严栻/ ，明末清初官吏。字子张，号虞仲，晚年自号髻珠头陀，江苏常熟人。严讷孙。娶文震孟女为妻。崇祯七年（1634 年）进士。仕为职方，官至兵部职方司员外郎。有文武才略，能诗，工篆刻，善画山水。崇祯七年（1634 年）中式甲戌科二甲进士，礼部观政。八年授河南信阳州知州，被给事中史可敬弹劾，九年降调。崇祯十七年（1644 年），抚臣祁彪佳推荐复任兵部职方司主事，母忧未任。同年，南明弘光朝廷成立后，担任兵部职方司员外郎。顺治二年（1645 年）六月于常熟起兵抗清，被推为义军领袖，组织乡兵抵抗，最终失败。后隐居不仕，专注佛学。七十九岁无疾而终。
344. /堵胤锡/ ，（1601 年—1649 年），又写允锡，又名锡君，原名灵授，字仲缄，一字牧子，号牧游。 今宜兴市屺亭镇前亭村人。清军入关后，任大明兵部尚书，封光化伯。在湖南、江西、贵州、广东、广西等地进行抗清活动，遭瞿式耜、李元胤的猜忌。堵胤锡等人主张联合大顺军和大西军，何腾蛟、瞿式耜则排斥农民军。瞿式耜同党的丁时魁、金堡等上疏劾奏他在湖南“丧师失地之罪”。永历三年（1649 年）十一月与忠贞营的淮侯刘国昌出兵，是月二十六日，至浔州（今广西桂平），二十七日吐血病卒，三军恸哭，如丧父母。昭宗皇帝痛悼不已，辍朝五日，谕祭九坛，赠上柱国、中极殿大学士，太傅兼太子太师、浔国公，谥文襄，后改谥忠肃。葬屺山西南麓（今属屺亭镇胜天村）。
345. /姚志卓/ ，字子求，长兴人（一说仁和人）。乙酉年（1645 年）闰六月，姚志卓与参将方元章起兵，以钱塘人张起芬为将攻破余杭。 后组织义军参加抗清活动，受封为仁武伯。兵败后潜伏于清统治区，曾赴广西、贵州与永历朝廷建立联系。顺治九年（1652 年）冬，得钱谦益资助支持其联络永历朝廷。次年赴贵州安龙行营，受到永历帝召见慰劳，被遣返东南招集义兵。乙未年（1655 年）冬，随张名振、张煌言水师至镇江，合兵攻打崇明，阵亡。
346. /路振飞/ （1590 年-1655 年），字见白，号皓月，明末著名的抗清人士之一。 崇祯帝殉国后，路振飞曾致书南京兵部尚书史可法，谓“伦序当在福王，宜早定社稷主”。弘光帝被俘后，唐王朱聿键（即南明隆武帝）自立于福州，先后封路振飞为左都御史、太子太保、文渊阁大学士兼吏部尚书等职。官爵累至左柱国、光禄大夫、太子太师、吏部尚书兼兵部尚书、武英殿大学士。后卒于粤中，谥文贞。有子路泽溥、路泽淳、路泽浓。
     1) /路泽溥/ （？—？），字苏生，或称长公、安卿，明末清初直隶曲周人。路振飞长子。明末曾官中书舍人。明亡后不仕，偕其弟路泽浓隐居于太湖东山三十年，从事抗清活动。与顾炎武是至交。顺治十二年（1655 年）顾炎武因杀奴下狱。 路泽溥与松江兵备使者有旧，代为说项，炎武一案才得以移交松江府审理，最后以“杀有罪奴”的罪名结案，顾炎武得以出狱。
347. /侯性/ ，字若孩，又称月鹭，邑人侯执介之养子。执介妻，田通政珍女。田无子，少育性为子。及长状貌魁梧，脑后有异骨，人目之，为封侯相。为人豪放博达，补博士弟子，铮铮诸生间。尤善骑射，自负有文武才，明末从军于南，累功拜爵。后弃官养母，隐于吴之洞庭山，母终遂葬焉。性在吴与故明之逋臣遗老，如钱尚书谦益、杜将军弘玮、姜给事埰辈，共相引重，称“遗民寓公”。殁于吴，其子北还，徙鄢陵，今亦泯然矣。（见诸《商丘县志》（清康熙四十四年））。又，王夫之《永历实录》云：性家世豪贵，骄纵不法。补弟子员，粗通制义举业，习骑射，好纳响马贼，为无赖行，邑令梁以樟以法钤束之，性拳击以樟仆地，不数日死。性亡命走，从十余骑，劫商旅于河北，得资数万，用赂内臣王化民，恂、恪复为之地，窜军功籍，以白衣径授镇守广东西宁参将。上即位于肇庆，性依附拥戴，丁魁楚庇之，擢御营都督同知。从上入武冈，谄事傅作霖，援马吉翔例，封商邱伯。上自武冈奔靖州，性与车驾相失。先由新宁至柳，于右江劫行旅，得金帛数万。上至柳，服御皆匮，性以其所劫献慈圣、慈宁两宫，上及中宫充服御，三宫大喜，加性太子太师、左都督，掌中军都督府事，从上自南宁至肇庆。性素畜无赖健儿，将百人，沿两江东至三水，劫掠仕宦商贾，多得金资。以豪侈与戚畹王维恭及马吉翔、李元胤日夕征歌纵酒，颇干预国政，引荐文吏。给事中金堡论劾之。书奏，不省。性黠慧，通文墨，堡所上章奏，性皆译解示吉翔，文稍深僻者则曲释之，指为诽讪两官。以是慈圣恨堡，必欲杀之。性往往以珍异进奉内庭，尤为宫禁所喜。其母奉佛，自剃为尼，敕赐号静慧大师。紫袈裟，金钵盂，出入以朱棒前驱，入宫禁，称说外事。慈圣信之，往往辄强上行。国事之坏，性实阴持之也。梧州陷，性降于清。
348. /蔡士英/ （？—1675 年），字伯彦，号魁吾。汉军正白旗人。世居辽东锦州，崇德七年（1642 年），随祖大寿降郑亲王济尔哈朗。授征山东、福建，授佥都御史，顺治六年（1649 年）总管八旗红衣大炮，顺治九年（1652 年）为江西巡抚。顺治十二年（1655 年）担任漕运总督，加兵部尚书，“抗言力陈”海禁之弊，“多所振刷，厘革挽输，天庚迄无亏额。”。顺治十三年（1656 年）钱谦益赴淮安访蔡士英，“必与复明运动相涉”。康熙六年，捐资重修三官庙。康熙十四年（1675 年）尚在世。谥襄敏。有子蔡毓荣。1998 年在山东新泰敖山发现蔡士英的“三通碑记”。


[^1]: 泛指正室旁的别室，或简陋的房舍。
